### ISSUE TITLE
global tracking of application and window state

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#10]
As of right now, **chunkwm** does not track any state at all.
It simply delegates events to the plugins that subscribe to these.

Because **chunkwm** does not track state, a plugin is not able to directly subscribe to `window events`, and the plugin developer must listen to `application events` and manage the state manually. This involves tracking `already running`, `launched` and `terminated` applications.

For each of these applications, window notifications must be set up using the observer, 
and the `kAXUIElementDestroyedNotification` must be registered per window. 
This is quite frankly, not a pleasent experience...

As of now, the API I have provided for dealing with this is pretty usable, at least from my (biased) point of view.

I have more or less implemented a system that does the above in `src/plugins/tiling`.
This system could potentially be refactored and managed by **chunkwm** instead.
I haven't given it enough thought to be sure if this is a good thing to do or not, and
 so opinions here are welcome. 

If applications and windows were tracked by **chunkwm**, a plugin could simply subscribe to the following events, and would receive a pointer to a macos_window struct:

```
chunkwm_export_window_focused

chunkwm_export_window_created
chunkwm_export_window_destroyed

chunkwm_export_window_moved
chunkwm_export_window_resized

chunkwm_export_window_minimized
chunkwm_export_window_deminimized

chunkwm_export_window_title_changed
```

The `macos_window` struct contains basic information about the window and a pointer to the `macos_application` it belongs to. A `macos_application` also contains only basic information, to avoid the stupid problem that **Kwm** has. As these values are not being mutated, it is safe for multiple threads to be reading the data.

The memory would be managed by **chunkwm** and a plugin should not free or otherwise modify it in any way. **chunkwm** can theoretically free this memory at any time, and so if a plugin wants to store the data, it must create a local copy.

My approach so far with **chunkwm** is more or less just writing user-code (plugin) first. Figuring out something that I want to do, and how I want the API to be. Then implementing a local version of the API, and finally refactoring code. This also involves moving code that obviously belongs in the `common` category.

**Comment by choco** [comment]
I would probably lean towards chunkwm tracking these things but the correct solution would probably show itself if we come up to a good solution for having multiple plugins cooperating and interacting between them. But I haven't given enough though to come up with a solution I'd recommend.

**Comment by koekeishiya** [comment]
I've implemented the above on a separate [branch](https://github.com/koekeishiya/chunkwm/tree/state) for testing purposes. So far it would seem like an ok decision to make..
