### ISSUE TITLE
Stuck on startup

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#104]
Updated to last version, converted my configuration but for some reason chunkwm just hangs.
Here's my config:
```
#!/bin/zsh

# Plugins dir
chunkc core::plugin_dir ~/Projects/chunkwm/plugins
chunkc core::hotload 1

# Tiling Conf
chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top      60
chunkc set global_desktop_offset_bottom   60
chunkc set global_desktop_offset_left     60
chunkc set global_desktop_offset_right    60
chunkc set global_desktop_offset_gap      15
# desktop 3 layout
chunkc set 3_desktop_tree    ~/.social.chkwm

chunkc set desktop_padding_step_size    10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                  1
chunkc set bsp_optimal_ratio           1.618
chunkc set bsp_split_mode            optimal
chunkc set bsp_split_ratio               0.5

chunkc set window_focus_cycle            all
chunkc set mouse_follows_focus             1
chunkc set window_float_next               0
chunkc set window_float_center             1
chunkc set window_region_locked            1

# Border conf
chunkc set focused_border_color   0xFFDD5A45
chunkc set focused_border_width            4
chunkc set focused_border_radius           4

# Plugins to load
chunkc core::load ffm.so
chunkc core::load border.so
chunkc core::load tiling.so

# Tiling rules
chunkc tiling::rule --owner "^Tweetbot$"        --state float   --except "Main Window"
chunkc tiling::rule --owner "^Xcode$"           --state float
chunkc tiling::rule --owner "^Photoshop CC$"    --state float
chunkc tiling::rule --owner "^Fantastical 2$"   --state float
chunkc tiling::rule --owner "^Fantastical$"     --state float
chunkc tiling::rule --owner "^App Store$"       --state float
chunkc tiling::rule --owner "^The Unarchiver$"  --state float
chunkc tiling::rule --owner "^CleanMyMac 3$"    --state float
chunkc tiling::rule --owner "^Spotify$"         --state float
echo "HERE"
chunkc tiling::rule --owner "^Airmail$"         --state float
echo "NOT HERE"
chunkc tiling::rule --owner "^LeagueClientUx$"  --state float
chunkc tiling::rule --owner "^Finder$"          --name "Trash"  --state float
chunkc tiling::rule --owner "^Finder$"          --name "Copy"   --state float
```

You'll see that the first echo message gets printed, but the second one won't. It seems to be based on the amount of rules I try to set, more then the HERE message and chunkwm hangs. I'm sorry for not providing better help in debugging this, but don't have lots of time.

**Comment by koekeishiya** [comment]
You need to escape the quotes in rules. Not sure why that would cause it to hang though.

On Jul 2, 2017 9:46 PM, Enrico Ghirardi <notifications@github.com> wrote:

Updated to last version, converted my configuration but for some reason chunkwm just hangs.
Here's my config:

#!/bin/zsh

# Plugins dir
chunkc core::plugin_dir ~/Projects/chunkwm/plugins
chunkc core::hotload 1

# Tiling Conf
chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top      60
chunkc set global_desktop_offset_bottom   60
chunkc set global_desktop_offset_left     60
chunkc set global_desktop_offset_right    60
chunkc set global_desktop_offset_gap      15
# desktop 3 layout
chunkc set 3_desktop_tree    ~/.social.chkwm

chunkc set desktop_padding_step_size    10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                  1
chunkc set bsp_optimal_ratio           1.618
chunkc set bsp_split_mode            optimal
chunkc set bsp_split_ratio               0.5

chunkc set window_focus_cycle            all
chunkc set mouse_follows_focus             1
chunkc set window_float_next               0
chunkc set window_float_center             1
chunkc set window_region_locked            1

# Border conf
chunkc set focused_border_color   0xFFDD5A45
chunkc set focused_border_width            4
chunkc set focused_border_radius           4

# Plugins to load
chunkc core::load ffm.so
chunkc core::load border.so
chunkc core::load tiling.so

# Tiling rules
chunkc tiling::rule --owner "^Tweetbot$"        --state float   --except "Main Window"
chunkc tiling::rule --owner "^Xcode$"           --state float
chunkc tiling::rule --owner "^Photoshop CC$"    --state float
chunkc tiling::rule --owner "^Fantastical 2$"   --state float
chunkc tiling::rule --owner "^Fantastical$"     --state float
chunkc tiling::rule --owner "^App Store$"       --state float
chunkc tiling::rule --owner "^The Unarchiver$"  --state float
chunkc tiling::rule --owner "^CleanMyMac 3$"    --state float
chunkc tiling::rule --owner "^Spotify$"         --state float
echo "HERE"
chunkc tiling::rule --owner "^Airmail$"         --state float
echo "NOT HERE"
chunkc tiling::rule --owner "^LeagueClientUx$"  --state float
chunkc tiling::rule --owner "^Finder$"          --name "Trash"  --state float
chunkc tiling::rule --owner "^Finder$"          --name "Copy"   --state float


You'll see that the first echo message gets printed, but the second one won't. It seems to be based on the amount of rules I try to set, more then the HERE message and chunkwm hangs. I'm sorry for not providing better help in debugging this, but don't have lots of time.

**Comment by choco** [comment]
> You need to escape the quotes in rules.
I'm pretty sure this isn't needed, but anyway escaping doesn't change anything.

It hangs on the `connect` call in `chunkc` while executing the config file.

**Comment by choco** [comment]
Rising the backlog limit of the `listen` call in `common/ipc/daemon`  fixes this for me, but it is obviously not ideal.

**Comment by koekeishiya** [comment]
> I'm pretty sure this isn't needed, but anyway escaping doesn't change anything.

This is needed if the argument contains a space.

chunkc tiling::rule --owner "System Preferences" is parsed as:
-arg1: --owner
-arg2: System
-arg3: Preferences

I've tested and confirmed this.

> It hangs on the connect call in chunkc while executing the config file.
Rising the backlog limit of the listen call in common/ipc/daemon fixes this for me, but it is obviously not ideal.

This should only be necessary if any of the connections do not end properly for some reason. Thus, the backlog is filled.

**Comment by choco** [comment]
> This is needed if the argument contains a space.
chunkc tiling::rule --owner "System Preferences" is parsed as:
-arg1: --owner
-arg2: System
-arg3: Preferences
I've tested and confirmed this.

You're absolutely right, i wonder how this has never bit me ahah

Anyway the issue is that the load request for the border plugin is never completed.
https://github.com/koekeishiya/chunkwm/blob/master/src/common/border/border.mm#L112 the `dispatch_sync` never returns. As I understand this tries to execute the event on the main thread queue but the main thread queue isn't getting consumed so it never returns.

**Comment by koekeishiya** [comment]
> Anyway the issue is that the load request for the border plugin is never completed.
https://github.com/koekeishiya/chunkwm/blob/master/src/common/border/border.mm#L112 the dispatch_sync never returns. As I understand this tries to execute the event on the main thread queue but the main thread queue isn't getting consumed so it never returns.

Ye I just figured this out as well. 

The problem is that the system call executing the config file is ran from the main thread.
The borderwindowcreate call then tries to run synch on the main thread as well, which causes a block.

The border calls should in theory be safe to run asynch on the main queue.
