### ISSUE TITLE
Emacs not tiling

### ISSUE THREAD

**Issue by peel** [koekeishiya/chunkwm#105]
First of all, kudos for the grate progress.
After getting the latest versions I'm stumbling upon an issue that was faced with KWM previously - Emacs not tiling. 
It seems like the window is discovered properly - hence the border.
The logs don't really suggest anything though.

```
40755:Emacs activated
328:iTerm2 deactivated
chunkwm-tiling command: (5) 'window --swap east'
chunkwm-tiling recv: 'window --swap east'
1:desktop   1421:0:invalid window:Emacs
```

Do you have any suggestions?

**Comment by koekeishiya** [comment]
What's the output of `chunkc query window details 1421`?

**Comment by peel** [comment]
Looking good:
```
id: 1421
level: 0
name: osx.nix
owner: Emacs
role: AXTextField
subrole: AXStandardWindow
movable: 1
resizable: 1
```

**Comment by koekeishiya** [comment]
The main-role is AXTextField for some reason. You can add a rule for emacs that forces it to tile. See window rules section in the chunkwm-tiling readme.

On Jul 3, 2017 1:03 PM, Piotr Limanowski <notifications@github.com> wrote:

Looking good:

id: 1421
level: 0
name: osx.nix
owner: Emacs
role: AXTextField
subrole: AXStandardWindow
movable: 1
resizable: 1

**Comment by peel** [comment]
Actually I did, hence the following config:
```
#!/bin/bash
chunkc core::plugin_dir /run/current-system/sw/lib/chunkwm/plugins
chunkc core::hotload 1
# Config for chunkwm-border plugin
chunkc set focused_border_color          0xffc0b18b
chunkc set focused_border_width 4
chunkc set focused_border_radius 0
chunkc set focused_border_skip_floating  0

# Config for chunkwm-ffm plugin
# Nothing to configure
# Config for chunkwm-tiling plugin
chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                monocle
chunkc set 5_desktop_mode                float

chunkc set 1_desktop_tree                ~/.chunkwm_layouts/dev_1

chunkc set global_desktop_offset_top     25
chunkc set global_desktop_offset_bottom  15
chunkc set global_desktop_offset_left    15
chunkc set global_desktop_offset_right   15
chunkc set global_desktop_offset_gap     15

chunkc set 1_desktop_offset_top          25
chunkc set 1_desktop_offset_bottom       15
chunkc set 1_desktop_offset_left         15
chunkc set 1_desktop_offset_right        15
chunkc set 1_desktop_offset_gap          15

chunkc set 3_desktop_offset_top          15
chunkc set 3_desktop_offset_bottom       15
chunkc set 3_desktop_offset_left         15
chunkc set 3_desktop_offset_right        15

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.66

chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           1
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1
chunkc core::load tiling.so
chunkc core::load ffm.so
chunkc core::load border.so
chunkc tiling::rule --owner Emacs --state tile
```

**Comment by koekeishiya** [comment]
It appears that the rule has not been applied to the window atleast.

The log `1:desktop   1421:0:invalid window:Emacs` is only printed for windows that fail the `IsWindowValid` check. `--state tile` automatically makes it pass this check.

Not sure why the rule would fail though.

**Comment by koekeishiya** [comment]
I think the problem could be related to when rules are applied.

Try the following:

Quit chunkwm
Quit Emacs
Start chunkwm first,
then start Emacs.

Does it tile now?

**Comment by peel** [comment]
I still get the same behaviour. Upgraded to v0.2.5.
Did try the procedure you mentioned. 
Noticed this in the `chunkwm.err`:
```
chunkwm-tiling: window rule - no filter specified, ignored..
```
The rule is:
```
chunkc tiling::rule --owner Emacs --state tile
```
to shave the yak, did try:
```
chunkc tiling::rule --owner \"Emacs \" --state tile
```
with the same effect.

Also for completeness here's 
`chunkwm.out`:
```
carbon: process details
Name: chunkwm
PID: 35262
PSN: 1319234 0
Policy: 2
Background: 1
Finder:<unknown> is not destructible, ignore!
Plugin Details
API Version 5
FileName 'plugin.cpp'
PluginName 'Tiling'
PluginVersion '0.2.2'
1:desktop   54:0:iTerm2:1. tmux  /Users/peel (tmux)
chunkwm: plugin 'tiling.so' loaded!
Plugin 'Tiling' subscribed to 'chunkwm_export_application_launched'
Plugin 'Tiling' subscribed to 'chunkwm_export_application_terminated'
Plugin 'Tiling' subscribed to 'chunkwm_export_application_hidden'
Plugin 'Tiling' subscribed to 'chunkwm_export_application_unhidden'
Plugin 'Tiling' subscribed to 'chunkwm_export_application_activated'
Plugin 'Tiling' subscribed to 'chunkwm_export_window_created'
Plugin 'Tiling' subscribed to 'chunkwm_export_window_destroyed'
Plugin 'Tiling' subscribed to 'chunkwm_export_window_minimized'
Plugin 'Tiling' subscribed to 'chunkwm_export_window_deminimized'
Plugin 'Tiling' subscribed to 'chunkwm_export_window_focused'
Plugin 'Tiling' subscribed to 'chunkwm_export_window_moved'
Plugin 'Tiling' subscribed to 'chunkwm_export_window_resized'
Plugin 'Tiling' subscribed to 'chunkwm_export_window_title_changed'
Plugin 'Tiling' subscribed to 'chunkwm_export_space_changed'
Plugin 'Tiling' subscribed to 'chunkwm_export_display_changed'
Plugin Details
API Version 5
FileName 'plugin.cpp'
PluginName 'Focus Follows Mouse'
PluginVersion '0.1.0'
chunkwm: plugin 'ffm.so' loaded!
Plugin Details
API Version 5
FileName 'plugin.cpp'
PluginName 'Border'
PluginVersion '0.2.2'
chunkwm: plugin 'border.so' loaded!
Plugin 'Border' subscribed to 'chunkwm_export_application_activated'
Plugin 'Border' subscribed to 'chunkwm_export_application_deactivated'
Plugin 'Border' subscribed to 'chunkwm_export_window_focused'
Plugin 'Border' subscribed to 'chunkwm_export_window_destroyed'
Plugin 'Border' subscribed to 'chunkwm_export_window_moved'
Plugin 'Border' subscribed to 'chunkwm_export_window_resized'
Plugin 'Border' subscribed to 'chunkwm_export_window_minimized'
Plugin 'Border' subscribed to 'chunkwm_export_space_changed'
chunkwm-tiling command: (5) 'rule --owner Emacs --state tile'
chunkwm-tiling recv: 'rule --owner Emacs --state tile'
chunkwm: config file finished executing
carbon: process details
Name: Emacs
PID: 35349
PSN: 1323331 0
Policy: 0
Background: 0
35349:Emacs launched
OBSERVER ERROR (Emacs): The function cannot complete because messaging has failed in some way.
35349:Emacs successfully registered window notifications
Emacs:<unknown> is not destructible, igno
```

**Comment by peel** [comment]
Can't reopen though.

**Comment by koekeishiya** [comment]
Hm, not sure what the problem could be. If it tiles with *kwm*, it should also tile with *chunkwm* granted granted that the above requirement is met.

Regarding the rule, `chunkc tiling::rule --owner Emacs --state tile` should work fine. Escaped quotes are only needed when the value contains a whitespace.

**Comment by peel** [comment]
Uh, I was in the middle of editing the comment.
I was yak-shaving for a trailing whitespace, hence the doublequotes.

My yak shaving lead to me following rule for Emacs that works:
```
chunkc tiling::rule --owner "Emacs.*" --state tile
```

**Comment by jonathanwilner** [comment]
This tiling rule definitely catches Emacs, but at least using the
"Emacs-Mac" version from  Mitsuharu Yamamoto, I wind up with also
seeing 3-5 other what I would call "phantom" windows also getting
tiled and thus taking up space.

If I don't tile Emacs and just choose to pkill -HUP chunkwm after
Emacs launches, I wind up with everything working properly.

Any ideas or suggestions appreciated!

Herschel

**Comment by koekeishiya** [comment]
You can investigate this by outputting the windows and information about them: 

query list of windows on focused desktop: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#query-list-of-windows-on-focused-desktop

query window information: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#query-window-information

**Comment by lego** [comment]
I found the same behavior occurred with iTerm2 when you changed the preferences to remove the title bar (Preferences > Profiles > Window > Style, "No title bar"), yet tiling seemed to work fine with KWM. Mind you they tile fine with `chunkc tiling::rule --owner "iTerm2.*" --state tile`.

```bash
$ chunkc tiling::query --window 856353 # Window with a title bar
id: 856353
level: 0
name: 1. chunkwm (chunkwm)
owner: iTerm2
role: AXWindow
subrole: AXStandardWindow
movable: 1
resizable: 1
```
```bash
$ chunkc tiling::query --window 856381 # Window without a title bar
id: 856381
level: 0
name: joey@pollen: ~ (zsh)
owner: iTerm2
role: AXWindow
subrole: AXDialog
movable: 1
resizable: 1
```

**Comment by crisidev** [comment]
For me iterm2 borderless works out of the box, without special treatments. Are you running the latest version of iterm2?

**Comment by slifin** [comment]
If I hover the mouse over emacs it doesn't raise the application like my other apps, and if I do emacs . the title of emacs is now the working folder not emacs which causes it to not tile because 

```
chunkc tiling::rule --owner "Emacs.*" --state tile
```
What is it about emacs that makes it non standard?

**Comment by x-ji** [comment]
I'd also just like to chime in that replacing `emacs-plus` with `emacs-mac` seems to solve these issues.
