### ISSUE TITLE
Chunkc

### ISSUE THREAD

**Issue by illusaen** [koekeishiya/chunkwm#106]
Hello,

I keep getting chunkc connection failed when I try to install. Any ideas on a fix?

Thanks!

**Comment by synthetiv** [comment]
Not sure if this is your problem, but there have been some major structural changes just recently, so if you've previously compiled from source, you'll need to recompile everything (chunkc, chunkwm, and any plugins you use) and update your .chunkwmrc to use the new command format (see https://github.com/koekeishiya/chunkwm/blob/master/examples/chunkwmrc).

I was getting the same error this morning until I realized I'd forgotten to recompile chunkc.

**Comment by koekeishiya** [comment]
Make sure that `lsof -i :3920` is not taken.

Clean all binaries (chunkwm, plugins, chunkc) and follow the install instructions again from the start.
This includes removing said binaries from `/usr/local/bin` as well, if you followed the manual instructions.

as *synthetiv* said, there was recently a rather large structural change regarding the messaging system.
