### ISSUE TITLE
Unable to get tiling or border highlighting after installing using source

### ISSUE THREAD

**Issue by hxeaven** [koekeishiya/chunkwm#107]
Now this could be because of my inexperience using any of your tiling window managers, but after following your instructions for installing form source and using your .chunkwmrc sample file, I am not getting any interaction.

Should I just try using the macports installation? Or is my problem due to having to setup everything in the same rc file?

For example, should I be changing these lines.
```
chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                monocle
chunkc set 5_desktop_mode                float

chunkc set 1_desktop_tree                ~/.chunkwm_layouts/dev_1
```

EDIT: Solution was to overwrite old files in /usr/local/bin that I had not removed when I tried installing chunkwm a month previous.

**Comment by koekeishiya** [comment]
The default config should work fine and is just a copy of my own personal config.
Did you remember to make the *.chunkwmrc* file executable?

The config file is just a bash script, so it is necessary to `chmod +x ~/.chunkwmrc`

**Comment by hxeaven** [comment]
Yeah I did that. I even put an echo command in it to see if it would output to the chunkwm.out file. I have .chunkwmrc in my home directory (copy of sample), .chunkwm_plugins with the shared object files from the plugins. I have the chunkwm and chunkc in /usr/local/bin. They are both in my path and can run them from terminal. I'm opening iTerm and Safari and not getting any highlighting or tiling.

**Comment by hxeaven** [comment]
I have also installed khd, and that works because I am able to open an application using:
```
# open terminal, blazingly fast compared to iTerm/Hyper
cmd - return : open -na /Applications/iTerm.app
```

**Comment by hxeaven** [comment]
Should I be getting this error?
```
❯❯❯ chunkwm
chunkwm: failed to initialize daemon! abort..
```

**Comment by hxeaven** [comment]
I think I figured it out. I must have had some previous files that I didn't remove when I originally tried to get it working. Have it working now. Now to figure out how to get it setup properly. Thanks for chunkwm!
