### ISSUE TITLE
MPV window is not recognized if it appears after chunkwm starts

### ISSUE THREAD

**Issue by jakibaki** [koekeishiya/chunkwm#108]
It works properly if chunkwm is started (or restarted) when MPV is already on screen but if you start it while chunkwm is running it doesn't get recognized by chunkm (no tiling, no focus on mouse over...).

**Comment by koekeishiya** [comment]
Can you post the log-output.

How do you start mpv ?

I use mpv a lot and it works fine for me. Installed using MacPorts.

**Comment by jakibaki** [comment]
iTerm2:mpv (zsh):132 window title changed
    iTerm2:jakibaki@iThink: ~ (zsh):132 window title changed
    carbon: process details
    Name: mpv
    PID: 1216
    PSN: 225335 0
    Policy: 2 
    Background: 1
    iTerm2:mpv https://www.twitch.tv/gamesdonequick (zsh):132 window title changed
    iTerm2:mpv https://www.twitch.tv/gamesdonequick (mpv):132 window title changed
    iTerm2:1. chunkwm (chunkwm):119 window focused
    iTerm2:mpv https://www.twitch.tv/gamesdonequick (mpv):132 window destroyed
    1:desktop   119:0:iTerm2:1. chunkwm (chunkwm)
    1:desktop   99:0:invalid window:Google Chrome:
    1:desktop   100:0:Google Chrome:MPV window is not recognized if it appears after chunkwm starts · 
    Issue #108 · koekeishiya/chunkwm
    339:iTerm2 deactivated
    339:iTerm2 activated

I installed mpv from homebrew. The window doesn't seem to be recognized at all (everything in the log that mentions it just comes from iTerm and nothing was added to the log after mpv started).

It works if I start the packaged version from finder but not if I start it from the terminal (which seems to be the only way to start streams).

**Comment by dominiklohmann** [comment]
I think the issue here is that livestreamer (assuming you use it) spawns mpv as a child process instead of launching the mpv app package.

**Comment by jakibaki** [comment]
I'm not using livestreamer (mpv uses youtube-dl as a backend for streams) so I just start it directly from the terminal.

Chunkwm picks the window from other applications up just fine if they are started from the terminal (for example running '/Applications/Maps.app/Contents/MacOS/Maps' from the terminal works just fine) so it seems to be an mpv-specific problem.

**Comment by koekeishiya** [comment]
Well as seen in the log. mpv is launched as a background process as a daemon. Processes with these flags set are ignored by chunkwm because in 99.99% cases they are not apps we can interact with.

you can most likely alias mpv -> open -na /Applications/mpv.app to have the bundle launch from iterm when you pass a url to be opened using youtubd-dl extension

**Comment by jakibaki** [comment]
If I use your way it starts properly but doesn't take command-line arguments (with --args).

For some reason it works perfectly fine when I start it with the absolute application path (/Applications/mpv.app/Contents/MacOS/mpv args) but not if I symlink mpv from the package to /usr/local/bin/ so I can solve my problem by using an alias instead of a symlink.

Thank you for the quick help!

I'm not sure if I should close this issue now because while my problem itself has been resolved the underlying issue of chunkwm not picking up some windows correctly is still present (but apparently hard to solve while only few applications are affected by this).

**Comment by koekeishiya** [comment]
I've only encountered this issue with mpv. I had this issue while working on *kwm* at some point, and that was the reason for the `kwmc whitelist <..>` option that was added.

The reason for this problem is that processes on macOS have various policy classes.
https://github.com/koekeishiya/chunkwm/blob/master/src/common/misc/carbon.h#L6

Current settings:
https://github.com/koekeishiya/chunkwm/blob/master/src/core/callback.cpp#L157
https://github.com/koekeishiya/chunkwm/blob/548bff61aee2a8dd13d1e8b5c81bea5afb73d18d/src/core/state.cpp#L344
https://github.com/koekeishiya/chunkwm/blob/5bf6ef42b47ae02d086597b0a42eb5de4ca005bd/src/plugins/tiling/plugin.cpp#L1468

**Comment by darvelo** [comment]
Even though chunkwm doesn't pick up the mpv window, if I use `launchd` to `unload` and then `load` chunkwm, it'll pick up the existing mpv window it didn't pick up before.

**Comment by koekeishiya** [comment]
I'll be closing this for now. If this happens for multiple applications in the future, I will consider the ability to specify the `process policy` in the config file.

**Comment by ilevantis** [comment]
I may have another example of this behaviour. 

I previously had Numi reliably tiling with `kwmc whitelist Numi` but `chunkc tiling::rule --owner Numi --state tile` does not seem to tile Numi properly.

**Comment by wfrx** [comment]
I have the same issue with multiple applications:
- ~~mupdf~~ (works now, see below)
- qutebrowser
The app windows are not recognized, but if I restart chunkwm while they are still open, everything starts working as expected.

I had the issue with mpv and calibre, but fixed that by aliasing to the binary within /Applications/*.app. 
This workaround does not work for qutebrowser, I have an alias set but it still only works after restarting chunkwm. 
~~For mupdf, this is not applicable as there is no *.app.~~ While typing this I got the idea to create a Mupdf.app inside applications and move the mupdf-gl binary into it, which apparently fixed the issue.
So now there's only qutebrowser left that's not working properly.

**Comment by koekeishiya** [comment]
So yeah, turns out we do need some filtering going on, but it is less strict than it used to be.
