### ISSUE TITLE
Is XQuartz a requirement? 

### ISSUE THREAD

**Issue by knightjp** [koekeishiya/chunkwm#109]
I noticed that in the installation instructions, Mac Ports is used. I know that as a part of the requirement for the installation of MacPorts, XQuartz is needed.. 

If I choose to install via Homebrew, is XQuartz a requirement for Chunkwm?

**Comment by jakibaki** [comment]
It works perfectly fine without XQuartz for me.

**Comment by knightjp** [comment]
@jakibaki How did you install it? Did you use Mac Ports?

**Comment by koekeishiya** [comment]
There are no requirements except for the native macOS frameworks.
