### ISSUE TITLE
Readme needs work

### ISSUE THREAD

**Issue by Waynekosimoto** [koekeishiya/chunkwm#111]
The instructions are extremely vague if you've never used window tiling software. It's not clear how you control it, it's not clear how you launch it, it's not clear anywhere in terms of usage. I've managed to figure out how to do all of this but everything should be in the readme regardless. I'm still not sure how I would set my F13-19 keys for actions, the only thing I found was a diagram for all the keys but i've tried setting the numbers, combinations and I'm not sure how I actually set them.

**Comment by koekeishiya** [comment]
> The instructions are extremely vague if you've never used window tiling software.

This is true, but the readme is not supposed to be a guide. Just simple instructions to getting started.

> it's not clear how you launch it

It is launched just like any other binary file. If you are referring to the *launchd* service, you can google that or use the *man* pages provided with macOS. Open a terminal: `man launchd`, `man launchctl`

> It's not clear how you control it,

It's controlled through messages sent to its dedicated socket. Use *chunkc* to write messages on *chunkwm's* socket. See configuration section of the readme.

> I'm still not sure how I would set my F13-19 keys for actions

*chunkwm* does not handle any keyboard input.

**Comment by Waynekosimoto** [comment]
I wasn't asking those questions, except for the last one, I'm pointing out the flaws in the readme but, since you say that it isn't a guide where could I find one?

**Comment by Waynekosimoto** [comment]
Thanks for the additions it's made it much easier.
