### ISSUE TITLE
Spacemacs / Emacs not able to tile

### ISSUE THREAD

**Issue by natsumi** [koekeishiya/chunkwm#113]
The Spacemacs window can't seem to be tiled.  It ends up acting like a floating window.

I'm seeing this in the logs:

carbon: process details
Name: Emacs
PID: 13935
PSN: 446573 0
Policy: 0
Background: 0
13935:Emacs launched
OBSERVER ERROR (Emacs): The function cannot complete because messaging has failed in some way.
OBSERVER ERROR (Emacs): The function cannot complete because messaging has failed in some way.
OBSERVER ERROR (Emacs): The function cannot complete because messaging has failed in some way.
OBSERVER ERROR (Emacs): The function cannot complete because messaging has failed in some way.
OBSERVER E
RROR (Emacs): The function cannot complete because messaging has failed in some way.
OBSERVER ERROR (Emacs): The function cannot complete because messaging has failed in some way.
OBSERVER ERROR (Emacs): The function cannot complete because messaging has failed in some way.
13935:Emacs successfully registered window notifications
13935:Emacs activated

**Comment by koekeishiya** [comment]
See #105

**Comment by natsumi** [comment]
@koekeishiya thanks.  that worked perfect.
