### ISSUE TITLE
Add an option to lower chunkwm output

### ISSUE THREAD

**Issue by crisidev** [koekeishiya/chunkwm#119]
When running as a daemon via plist file, every action is recorded on /tmp/chunkwm.out.

Can we add an option to only print important messages there and not every user action? 

This could be useful in the plist file.

**Comment by koekeishiya** [comment]
Can I assume that the `with-logging` option provided in the brew formulae is good enough ?

**Comment by crisidev** [comment]
Yes, it think so! You can close this one.
