### ISSUE TITLE
how to load plugins

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#12]
I've been thinking quite a bit about how I want plugins to be loaded.

So far, the most basic approach would be to have a `~/.chunkwmrc` or something that specifies which plugins to load, e.g:
```
load_plugin "/path/to/plugin"
load_plugin "/path/to/plugin"
load_plugin "/path/to/plugin"
```
Doing this would require manual editing of the config file to load new plugins, and would require some form of `ReloadPlugin` command, if a plugin was rebuilt or otherwise modified. To do this, without having to set up a daemon, we could register  for `SIGUSR1` and have that signal be our reload config command. The reload would probably check the file and reload the listed plugins, as well as unload any plugin that is no longer in the file, but is currently active.

Downside to the above approach is that we will not be able to reload a single plugin, without losing the state of all other plugins simultaneously. This can be fixed by only reloading a plugin if the `last_modified` flag has changed from when it was originally loaded.

The more sophisticated method (in my opinion) would be to specify an environment variable (or launch argument ?), say `CHUNKWM_PLUGIN_DIR=/path/to/plugins`. This directory would be monitored for changes to `.so` files, and unload / load plugins as they are modified (hotloading plugins). 

This would require no user interaction when changes are made to plugins. When you want to load a new plugin, simply throw it into the directory. If you are developing a plugin and want to see the changes in action, simply recompile and it will reload automatically.

Personally, I prefer doing hotloading.

I do realize that automatically loading code (even though we verify the plugin structure) can be a potential security risk, if not handled properly by the user. I guess this is more of a question for people that do not feel comfortable with that approach.

Thoughts and suggestions ?

**Comment by chrishoage** [comment]
What about a mix of both? 

`zplug` allows plugins to be "hot loaded", but then you can also go and edit your `zshrc`. 

If you'd like to test out a plugin with out reloading the while `chunkwmrc` file you can hot load a plugin, if you like the plugin you can go and edit `chunkwmrc` to include that plugin, then next time `chunkwm` loads it will include that plugin. 

Something like 

`chunkwmc load /path/to/plugin`

then 

`chunkwmc unload /path/to/plugin` 

There could even be something like you suggested with `CHUNKWM_PLUGIN_DIR` where it would look for plugins. 

`chunkwmc unload myplugin` 

Just my two cents.

**Comment by koekeishiya** [comment]
> What about a mix of both?

I suppose **chunkwm** could start a daemon for configuration purposes.
The config would be a bash script that is executed upon launch.
Hotloading through directory-watcher could be enabled there for users that want to do so.

Theoretical config sample, assuming **chunkwm** listens on port `5432`:
```
export CHUNKC_SOCKET=5432
export CHUNKWM_PLUGIN_DIR=~/.chunkwm_plugins

# enable hotloading through directory-watcher.
# requires CHUNKWM_PLUGIN_DIR to be set.
# this option is disabled by default.
chunkc hotloader on

# if plugin dir is set, it will search that directory.
# if a plugin dir is not set, absolute path is necessary.
chunkc load tiling.so
chunkc load border.so
chunkc load ffm.so
```

To unload or load a plugin manually after **chunkwm** has already started:
```
CHUNKC_SOCKET=5432 chunkc unload tiling.so
CHUNKC_SOCKET=5432 chunkc load tiling.so
```

This sounds like a good solution to me.

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/chunkwm/blob/master/examples/chunkwmrc
