### ISSUE TITLE
[new feature]Is it possible to launch application in the current desktop even though another window of the application has been opened on another desktop?

### ISSUE THREAD

**Issue by Michael-Jing** [koekeishiya/chunkwm#123]
I want a feature like this:
I am using a web browser viewing some kind of tutorial, and then I would like to bring up something else, a terminal to practice, or a text editor to write some notes.  This is the natural behavior if the second app is not opened before, but if the second app  is opened on another screen, then Mac will switch to the desktop where the app resides or just doing nothing depending on mission control settings. 

A simple solution maybe checking the desktop and window tree, and send the app needed to current desktop.

**Comment by koekeishiya** [comment]
Not sure if  this is possible to do properly. Needs investigation.

**Comment by nuynait** [comment]
Check out `group windows by application` in mission control setting. Now it focus to application but not the specific window. That prevent switch to other spaces when open an app. 

What I usually do is I open application using `Alfred` by typing its name and press `enter`. After that I hit `cmd+N` naturally to open a new window. 

In that case I think is already enough to solve this `to launch application in the current desktop even though another window of the application has been opened on another desktop` issue

**Comment by Michael-Jing** [comment]
Thanks, `cmd + N` works for me.

**Comment by koekeishiya** [comment]
I think the workaround provided by nuynait is the best solution here.
