### ISSUE TITLE
[plugin|tiling] window dimensions desync on active desktop upon launch

### ISSUE THREAD

**Issue by crisidev** [koekeishiya/chunkwm#125]
Sometimes, with more than one borderless Iterm2 window in the same desktop, chunwm acts in a weird way: If I move the mouse to another Iterm window, the mouse start moving autonomously between 2 of the windows and after ~ 1 second, it returns to the window where the focus started.

Example:
```
-----------------------
|          |          |
|     1    |          |
|          |          |
------------    3     |
|          |          |
|     2    |          |
|          |          |
------------------------
```
* Mouse focus on 3
* Move mouse to 2
* Mouse fucus moves quickly between 1 and 2
* Mouse focus returns to 3

I need to restart chunkwm to resolve the issue.

I am using ffm, tiling and border plugins.

**Comment by dominiklohmann** [comment]
Do you happen to have iTerms own Focus Follows Mouse enabled? To check, search for "mouse" in advanced settings. Kwm had all sorts of weird behaviour when using its ffm together with iTerms ffm.

**Comment by crisidev** [comment]
Nope, iterm's ffm is disabled as I had problems with kwm. This is something different I think..

**Comment by koekeishiya** [comment]
This is an issue where dimensions sometime go out of sync for whatever reason. 
I have not tried to figure out why this happens yet.

If you do `chunkc tiling::desktop --rotate 90` or some other command that causes the affected windows to resize, the problem should go away.

**Comment by crisidev** [comment]
Ok, cool. I'll try it as a workaround. Let's keep the issue open for future reference and in case a fix is found.

**Comment by koekeishiya** [comment]
The easiest way while still preserving your arrangement is to just toggle offsets on and off:
`chunkc tiling::desktop --toggle offset`

**Comment by crisidev** [comment]
Also optimize desktop works quite well as temporary fix.

**Comment by crisidev** [comment]
I cannot reproduce the problem anymore.. maybe some of the changes you pushed fixed it?

**Comment by koekeishiya** [comment]
doubt it. the issue is kinda random.

**Comment by koekeishiya** [comment]
The reason this issue exists is that we call `CreateWindowTree()` in our *plugin init* function.
By doing this, we resize windows on the active space BEFORE *chunkwm* has hooked our plugin into the event system. Thus, we do not receive updated positions and size for the windows from the events that we ourselves created, that we rely on.

This is what causes the desync to happen.

Possible solutions:

1. *chunkwm* should notify the specific plugin through the event system when that plugin has been hooked into the system. We can then call the *CreateWindowTree* when we receive that event shortly after the init call has succeede.

2. the tiling plugin knows which windows are on the space and thus know the windows that are out of sync. we can manually call *AXLibGetWindowPosition/Size()* for these windows.
