### ISSUE TITLE
chunkwmrc help

### ISSUE THREAD

**Issue by knightjp** [koekeishiya/chunkwm#126]
I was quite happy with my kwmrc settings. But on chunkwm, I am not able to get the same look and feel. I am guessing that I need help in editing the settings. 
I have dual monitor setup on my system. One of the monitors tiles the windows. The other one does not. On KWM, I was able to get tiling windows on both monitors and a multiple number of workspaces. But on this I can't... Can someone explain... 
Here is my kwmrc for reference... 
[kwmrc.pdf](https://github.com/koekeishiya/chunkwm/files/1133826/kwmrc.pdf)

**Comment by dominiklohmann** [comment]
Monitor issue: You need to restart chunkwm after (dis-)connecting monitors. This was not necessary with Kwm.

As for your settings, please just paste them here in a codeblock instead of uploading as a pdf file.

**Comment by knightjp** [comment]
Kwm settings: 

`/*
This is a sample config for Kwm

The following statements can be used to set Kwms internal directory structure.

    This is the root folder for Kwms files, the only thing this actually
    specifies is the location of the 'init' script which Kwm runs upon startup.
    Defaults to $HOME/.kwm

        kwm_home /path/to/.kwm

    This is the root folder in which all files included using 'include' must reside.
    Defaults to $HOME/.kwm

        kwm_include /path/to/.kwm/include

    This is the folder in which all bsp-layouts managed by 'tree load' and 'tree save'
    is loaded from / saved to. Defaults to $HOME/.kwm/layouts

        kwm_layouts /path/to/.kwm/layouts

Commands prefixed with 'kwmc' will call
local functions corresponding to the
kwmc syntax.

To run an external program or command,
use the prefix 'exec' followed by command.
e.g 'exec mvim' would open macvim

Read file and execute commands as
if they were written inside kwmrc.

include filename

e.g: window-rules in a separate file called 'rules'
    include rules
*/

# Set default values for screen padding
kwmc config padding 1 1 1 1 

# Set default values for container gaps
kwmc config gap 1 1

# Default tiling mode for Kwm (bsp | monocle | float)
kwmc config tiling bsp

# Automatically float windows that fail to resize
kwmc config float-non-resizable on

# Automatically resize the window to its container
kwmc config lock-to-container off

# Set focus-follows-mouse-mode to autoraise
kwmc config focus-follows-mouse on

/*
    Focus-follows-mouse is temporarily disabled when
    a floating window has focus
*/
kwmc config standby-on-float on

# Center window when made floating
kwmc config center-on-float on

/*
    The mouse will automatically move to the center
    of the focused window
*/
kwmc config mouse-follows-focus on

/*
    Allows a window to be moved by dragging,
    when a modifier key and left-click is held down.

    Allows a window to be resized by dragging
    when a modifier key and right-click is held down.
*/
kwmc config mouse-drag on

# The modifier keys to be held down to initiate mouse-drag
kwmc config mouse-drag mod shift+ctrl

# Allow window focus to wrap-around
kwmc config cycle-focus on

/*
Override default settings for space 1 on screen 0
   kwmc config space 0 1 mode monocle
   kwmc config space 0 1 padding 100 100 100 100
   kwmc config space 0 1 gap 40 40
*/

/*
Override default settings for screen 1
   kwmc config display 1 mode bsp
   kwmc config display 1 padding 100 100 100 100
   kwmc config display 1 gap 40 40
*/

# Set default container split-ratio
kwmc config optimal-ratio 1.6

# New splits become the left leaf-node
kwmc config spawn left

/*
    Add custom tiling rules for applications that
    does not get tiled by Kwm by default.
    This is because some applications do not have the
    AXWindowRole and AXStandardWindowSubRole
*/
kwmc rule owner="iTerm2" properties={role="AXDialog"}

/*
The following commands create rules that
blacklists an application from Kwms tiling

    kwmc rule owner="Steam" properties={float="true"}
    kwmc rule owner="Photoshop" properties={float="true"}
*/

/*
The following command creates a rule that
captures an application to the given screen,
if the screen exists.

   kwmc rule owner="iTunes" properties={display="1"}
*/

# Enable border for focused window
kwmc config border focused off
kwmc config border focused size 2
kwmc config border focused color 0xFFBDD322
kwmc config border focused radius 6

# Enable border for marked window
kwmc config border marked off
kwmc config border marked size 2
kwmc config border marked color 0xFFCC5577
kwmc config border marked radius 6
`

**Comment by knightjp** [comment]
`/*
This is a sample config for Kwm

The following statements can be used to set Kwms internal directory structure.

    This is the root folder for Kwms files, the only thing this actually
    specifies is the location of the 'init' script which Kwm runs upon startup.
    Defaults to $HOME/.kwm

        kwm_home /path/to/.kwm

    This is the root folder in which all files included using 'include' must reside.
    Defaults to $HOME/.kwm

        kwm_include /path/to/.kwm/include

    This is the folder in which all bsp-layouts managed by 'tree load' and 'tree save'
    is loaded from / saved to. Defaults to $HOME/.kwm/layouts

        kwm_layouts /path/to/.kwm/layouts

Commands prefixed with 'kwmc' will call
local functions corresponding to the
kwmc syntax.

To run an external program or command,
use the prefix 'exec' followed by command.
e.g 'exec mvim' would open macvim

Read file and execute commands as
if they were written inside kwmrc.

include filename

e.g: window-rules in a separate file called 'rules'
    include rules
*/

# Set default values for screen padding
kwmc config padding 1 1 1 1 

# Set default values for container gaps
kwmc config gap 1 1

# Default tiling mode for Kwm (bsp | monocle | float)
kwmc config tiling bsp

# Automatically float windows that fail to resize
kwmc config float-non-resizable on

# Automatically resize the window to its container
kwmc config lock-to-container off

# Set focus-follows-mouse-mode to autoraise
kwmc config focus-follows-mouse on

/*
    Focus-follows-mouse is temporarily disabled when
    a floating window has focus
*/
kwmc config standby-on-float on

# Center window when made floating
kwmc config center-on-float on

/*
    The mouse will automatically move to the center
    of the focused window
*/
kwmc config mouse-follows-focus on

/*
    Allows a window to be moved by dragging,
    when a modifier key and left-click is held down.

    Allows a window to be resized by dragging
    when a modifier key and right-click is held down.
*/
kwmc config mouse-drag on

# The modifier keys to be held down to initiate mouse-drag
kwmc config mouse-drag mod shift+ctrl

# Allow window focus to wrap-around
kwmc config cycle-focus on

/*
Override default settings for space 1 on screen 0
   kwmc config space 0 1 mode monocle
   kwmc config space 0 1 padding 100 100 100 100
   kwmc config space 0 1 gap 40 40
*/

/*
Override default settings for screen 1
   kwmc config display 1 mode bsp
   kwmc config display 1 padding 100 100 100 100
   kwmc config display 1 gap 40 40
*/

# Set default container split-ratio
kwmc config optimal-ratio 1.6

# New splits become the left leaf-node
kwmc config spawn left

/*
    Add custom tiling rules for applications that
    does not get tiled by Kwm by default.
    This is because some applications do not have the
    AXWindowRole and AXStandardWindowSubRole
*/
kwmc rule owner="iTerm2" properties={role="AXDialog"}

/*
The following commands create rules that
blacklists an application from Kwms tiling

    kwmc rule owner="Steam" properties={float="true"}
    kwmc rule owner="Photoshop" properties={float="true"}
*/

/*
The following command creates a rule that
captures an application to the given screen,
if the screen exists.

   kwmc rule owner="iTunes" properties={display="1"}
*/

# Enable border for focused window
kwmc config border focused off
kwmc config border focused size 2
kwmc config border focused color 0xFFBDD322
kwmc config border focused radius 6

# Enable border for marked window
kwmc config border marked off
kwmc config border marked size 2
kwmc config border marked color 0xFFCC5577
kwmc config border marked radius 6
`

**Comment by koekeishiya** [comment]
@knightjp 

You need to use triple \` to create a code paragraph. Single \` only works on one-liners.

\```
code here
\```

Regarding the issue at hand, you probably want to customize the settings and not run the default *chunkwm* config, as it is a copy of my own personal one.

In particular, https://github.com/koekeishiya/chunkwm/blob/master/examples/chunkwmrc#L23 makes desktop 5 float. If desktop 5 is on your secondary monitor, that is probably why.

Otherwise, as @dominiklohmann said, you need to restart *chunkwm* (the tiling plugin) if you have disconnected a monitor and reconnected it. Hoping to start work on live monitor changes soon.

**Comment by knightjp** [comment]
@koekeishiya why does chunkwm have many setting for different desktops? Why not just the one 
`chunkc set global_desktop_mode           bsp`..? 

To be honest, this wasn't the only issue for me. I also noticed that some of the standard Mac OS keyboard shortcuts like "Cmd+Shilft-H" didn't take me to the Home folder like it usually does. There were other that weren't working as well.

**Comment by koekeishiya** [comment]
> @koekeishiya why does chunkwm have many setting for different desktops? Why not just the one
chunkc set global_desktop_mode bsp..?

I don't want bsp-tiling on all desktops, so I override the setting for a few specific ones.
You need to figure out what you want and configure it so. Nothing in the config file is necessary, and so you need to spend some time to make it work the way you want.

> To be honest, this wasn't the only issue for me. I also noticed that some of the standard Mac OS keyboard shortcuts like "Cmd+Shilft-H" didn't take me to the Home folder like it usually does. There were other that weren't working as well.

Same as above. I assume you copied the *.khdrc* file that came with brew. This is just my keybindings, and you need to edit this to suit your needs. Remove what you don't use etc.

**Comment by knightjp** [comment]
What I want is actually the same settings as what I have on KWM. So I guess I need to spend some time and figure out the chunkwmrc file properly. Thank you.

**Comment by knightjp** [comment]
`chunkc set preselect_border_color        0xffffff00
chunkc set preselect_border_width        none
chunkc set preselect_border_radius       none`

How do I remove the focused window borders?

**Comment by koekeishiya** [comment]
Just don't load the border  plugin.

remove or comment the `chunkc core::load border.so` line at the bottom of the config

**Comment by crisidev** [comment]
Remove the border plugin from your configuration. 

Remove the line
```
chunkc core::load border.so
```

**Comment by koekeishiya** [comment]
@knightjp 

> Since I'm just an ordinary user. Do you think that chunkwm is ready for someone like me to use?

I just want to make clear that the current complexity is intended. My tools are meant for (mainly developers) and power users, thus the reason for the amount of configurability that is there.

I very much understand that this is a lot to take in for regular users that are interested in trying this sort of a setup. Ideally, there would be a user-guide like the one *i3* provides, but I'm not very good at, nor do I really have the time to write a proper guide.

**Comment by knightjp** [comment]
@koekeishiya Thank you for the assistance. I have actually gotten chunkwm running exactly the way that I want it. 
To be honest I am rather impressed with the performance. Window movements are extremely snappy. 
Although it took a bit of doing for me to get it right, I would say that this is a worthy successor to kwm.
