### ISSUE TITLE
Focus 'bounces' when switching between monitors

### ISSUE THREAD

**Issue by synthetiv** [koekeishiya/chunkwm#129]
I've been using chunkwm for a couple weeks now, and all of a sudden, with version 0.2.12, it's started behaving inconsistently when changing focus between my two monitors. When I issue `chunkc tiling::monitor -f prev`|`next`|`1`|`2`, or `chunkc tiling::window --focus west`|`east` to switch focus to another monitor (I have `window_focus_cycle` set to `all`), focus will often switch to the other monitor/window for only an instant, and then switch right back to the previously focused monitor/window. This doesn't happen every time, but I'd say it happens at least 50% of the time.

Changing focus between windows on the same desktop works fine, and using the mouse to click on a window on the monitor that isn't currently focused also works fine.

Background: I don't use the ffm plugin, and I have `mouse_follows_focus` set to `0`. I use different `desktop_offset_*` settings for my two monitors, but changing them so they're the same doesn't seem to make a difference. I was also trying out the new tiling rules for forcing certain apps to other desktops when I first noticed this issue, but commenting out those rules and restarting chunkwm hasn't helped.

I'm pasting a snippet from `chunkwm.out` below. Here I tried twice to switch focus to Atom on monitor 2, but iTerm2 re-focused again on its own. I've had this happen when trying to switch between Chrome and HipChat too, so it's not just an issue with these apps.

```
chunkwm-tiling command: (7) 'monitor -f next'
chunkwm-tiling recv: 'monitor -f next'
2:desktop   224361:0:Atom:.chunkwmrc — ~
2:desktop   221375:0:HipChat:HipChat
Atom:.chunkwmrc — ~:224361 window focused
1:desktop   203128:0:iTerm2:Python
1:desktop   162639:0:invalid window:Google Chrome:
1:desktop   162640:0:Google Chrome:New Issue · koekeishiya/chunkwm
1:desktop   224764:0:invalid window:System Preferences:Security & Privacy
Atom:.chunkwmrc — ~:224361 window focused
1:desktop   203128:0:iTerm2:Python
1:desktop   162639:0:invalid window:Google Chrome:
1:desktop   162640:0:Google Chrome:New Issue · koekeishiya/chunkwm
1:desktop   224764:0:invalid window:System Preferences:Security & Privacy
Finder:<unknown> is not destructible, ignore!
1:desktop   203128:0:iTerm2:Python
1:desktop   162639:0:invalid window:Google Chrome:
1:desktop   162640:0:Google Chrome:New Issue · koekeishiya/chunkwm
1:desktop   224764:0:invalid window:System Preferences:Security & Privacy
30744:Atom activated
1:desktop   203128:0:iTerm2:Python
1:desktop   162639:0:invalid window:Google Chrome:
1:desktop   162640:0:Google Chrome:New Issue · koekeishiya/chunkwm
1:desktop   224764:0:invalid window:System Preferences:Security & Privacy
291:iTerm2 deactivated
iTerm2:Python:203128 window focused
iTerm2:Python:203128 window focused
Finder:<unknown> is not destructible, ignore!
1:desktop   203128:0:iTerm2:Python
1:desktop   162639:0:invalid window:Google Chrome:
1:desktop   162640:0:Google Chrome:New Issue · koekeishiya/chunkwm
1:desktop   224764:0:invalid window:System Preferences:Security & Privacy
291:iTerm2 activated
30744:Atom deactivated
chunkwm-tiling command: (7) 'monitor -f next'
chunkwm-tiling recv: 'monitor -f next'
2:desktop   224361:0:Atom:.chunkwmrc — ~
2:desktop   221375:0:HipChat:HipChat
Atom:.chunkwmrc — ~:224361 window focused
1:desktop   203128:0:iTerm2:Python
1:desktop   162639:0:invalid window:Google Chrome:
1:desktop   162640:0:Google Chrome:New Issue · koekeishiya/chunkwm
1:desktop   224764:0:invalid window:System Preferences:Security & Privacy
Atom:.chunkwmrc — ~:224361 window focused
1:desktop   203128:0:iTerm2:Python
1:desktop   162639:0:invalid window:Google Chrome:
1:desktop   162640:0:Google Chrome:New Issue · koekeishiya/chunkwm
1:desktop   224764:0:invalid window:System Preferences:Security & Privacy
30744:Atom activated
1:desktop   203128:0:iTerm2:Python
1:desktop   162639:0:invalid window:Google Chrome:
1:desktop   162640:0:Google Chrome:New Issue · koekeishiya/chunkwm
1:desktop   224764:0:invalid window:System Preferences:Security & Privacy
291:iTerm2 deactivated
Finder:<unknown> is not destructible, ignore!
1:desktop   203128:0:iTerm2:Python
1:desktop   162639:0:invalid window:Google Chrome:
1:desktop   162640:0:Google Chrome:New Issue · koekeishiya/chunkwm
1:desktop   224764:0:invalid window:System Preferences:Security & Privacy
iTerm2:Python:203128 window focused
iTerm2:Python:203128 window focused
Finder:<unknown> is not destructible, ignore!
1:desktop   203128:0:iTerm2:Python
1:desktop   162639:0:invalid window:Google Chrome:
1:desktop   162640:0:Google Chrome:New Issue · koekeishiya/chunkwm
1:desktop   224764:0:invalid window:System Preferences:Security & Privacy
291:iTerm2 activated
30744:Atom deactivated
```

I've since rebuilt version 0.2.11, and that's working fine again for me.

**Comment by synthetiv** [comment]
Also, I don't use iTerm2's own ffm functionality, and it doesn't seem to matter which monitor or app the mouse cursor is on.

**Comment by knightjp** [comment]
I have dual monitors setup on my machine. I notice that some windows bounce in between monitors as well. This and the flickering windows is my only current gripe with chunkwm.

**Comment by knightjp** [comment]
As @koekeishiya mentioned in my thread... Disable `window_region_locked`. 
I tried it and it totally solved my problem. I assume that the standard window animations of Mac OS are the main cause of the bouncing, etc.. 
For instance, when I click send on Mail, the window slides upwards like it is flying off. But chunkwm locks the window in place and so it starts bouncing.

**Comment by synthetiv** [comment]
Seemed worth a shot, so I just tried that, but no dice. Anyway, this isn't really an issue of the windows _themselves_ bouncing, but rather of focus bouncing between the monitors. The word "bounce" mostly came to mind because it feels kind of like an event might be double-triggering and needs to be "debounced." But I'm not at all sure that's actually the problem.

**Comment by synthetiv** [comment]
FWIW, I just checked and it looks like this issue was introduced in commit fe3d67e.

**Comment by koekeishiya** [comment]
This is a different issue than #130 

Thos is caused by the change made to the tiling plugin.cpp in this commit: fe3d67eaca24a2007eeae2edc0fe660d3e8acf15

the change in question greatly improves the behaviour when sending a window to a different desktop / monitor. it appears to have a sideeffect regarding focusing with multiple monitors. i dont have access to external monitors at my current location so i cannot investigate the internal window, space and monitor structure of macos at this time.

**Comment by synthetiv** [comment]
Interesting. Glad to know what that commit is all about. I don't really use spaces, so the prior behavior has been fine for me and I'll just stick with that for now. Thank you!

**Comment by koekeishiya** [comment]
Could you test the latest master and see if it solvs the issue? As I mentioned, I can not test this myself, but I believe this should fix the issue, if my memory regarding the structure is correct.

**Comment by synthetiv** [comment]
Amazing. Yep, it looks like you've fixed it. Thank you again!
