### ISSUE TITLE
thoughts on BSP window move vs. swap

### ISSUE THREAD

**Issue by cprice404** [koekeishiya/chunkwm#13]
I wanted to throw out a suggestion for a user experience topic.  I'm using kwm and very very happy with it compared to everything else I've tried on osx, and very much looking forward to seeing where chunkwm goes.

One thing that is taking just a little getting used to for me is the distinction between the window 'move' and 'swap' actions.  I've been using i3 on linux for the last 5 years or so, and that WM somehow seems to have managed to combine those two actions into a single one.

So, e.g., if I have two vertical columns of window on my display, and I have one window in the left column and two windows in the right column, on i3 I could trigger the 'move left' action on one of the windows in the right column, and it would move it into the tree on the left side.  So then I'd have two windows in the left column and just one in the right column.

If I had only one window in each column, and did a 'move left' on the one in the right column, then it'd swap them.

In kwm I can achieve the latter scenario by doing a 'swap', but to achieve the former, I need to do one 'swap' and one 'move'.

This is not the end of the world, certainly :)  And may be more akin to how other BSP WMs work (as opposed to how i3 works).  Still much happier with kwm than anything else I've used, but I just thought I'd throw this out as food for thought!

Thanks for the awesome program!

**Comment by koekeishiya** [comment]
> One thing that is taking just a little getting used to for me is the distinction between the window 'move' and 'swap' actions. I've been using i3 on linux for the last 5 years or so, and that WM somehow seems to have managed to combine those two actions into a single one.

So in Kwm, the `swap` exclusively means to swap windows without modifying the layout,
whereas `move` actually modifies the window layout. I have personally not used `i3`, but I see people comparing **Kwm** to it, a lot. I used to use `bspwm` and `awesomewm` back on linux, and based my design around that.

You can sort of merge these two using a script I wrote, [here](https://github.com/koekeishiya/dotfiles/blob/master/kwm/scripts/move_window.sh). You may have to edit the path to `kwmc` and so on for the script to work.

You call the script with a direction as its argument, so if you are using **Khd**:
```
alt - h  : /path/to/scripts/move_window.sh west
alt - j   : /path/to/scripts/move_window.sh south
alt - k  : /path/to/scripts/move_window.sh north
alt - l   : /path/to/scripts/move_window.sh east
```

I'm not sure if this is what you're looking for, but hey, maybe it helps.

Feel free to open issues regarding behaviour, functionality that you think would help improve productivity, or features in **Kwm** that you think may not be important / could be removed.

I implement things that I personally like (and think are worthwhile) for the most part, and so the opinion of others are greatly valued.

Considering most people seem to be comparing **Kwm** to **i3**, I should probably take a closer look at how it works.

**Comment by matthewdias** [comment]
honestly i3 is very different from kwm in philosophy and usage. still probably something to be gained by checking it out tho. its popular for a reason after all.

**Comment by cprice404** [comment]
Cool, thanks for the script, I'll check it out!

**Comment by chris-kahn** [comment]
Highly recommend taking the time to get familiar with i3. It manages windows a little differently than bspwm / kwm, but it's super flexible and easy to use out of the box. Especially take a look at stacking and tabs, which is like monocle nodes but two different ways to display the title bars.

**Comment by chrishoage** [comment]
I would say `kwm` is closer to `bspwm`, as `i3` isn't truly a BSP window manager.

**Comment by koekeishiya** [comment]
> Especially take a look at stacking and tabs, which is like monocle nodes but two different ways to display the title bars.

I looked into these wben monocle nodes was implemented, however we are very limited by MacOS in how we can manipulate windows. Reordering titlebars is something we just cannot do.

I'm still running El Capitan, so I'm not sure if there are any APIs that let us utilize the new Sierra window-grouping system.

> I would say kwm is closer to bspwm, as i3 isn't truly a BSP window manager.

Honestly, I would really hope that is the case, as I basically based the development around what I remembered liking in **bspwm** with my own tweaks that I thought felt better on Mac.

I'm likely to continue this approach for **chunkwm**, but we'll see. Having the tiling code be isolated as a plugin should also make it more feasible for users to custumize behaviour as well.

**Comment by koekeishiya** [comment]
I've decided that the `swap` command is going to stay as is, it is probably my most used type of command. Rearranging windows without modifying the layout is huge for me.

With that said, I don't see any reason why the `move` command would not have the behaviour of the script i referenced above.

If a `move` command is issued, and the affected windows have the same parent, it feels natural to perform a `swap` operation. If they have different parents, we perform the `move` operation, altering the layout. I think this is a more sane implementation.

**Comment by koekeishiya** [comment]
I'm satisfied with how this works for now. Closing.
