### ISSUE TITLE
Flickering windows. 

### ISSUE THREAD

**Issue by knightjp** [koekeishiya/chunkwm#130]
There is this odd flickering of windows that happens at random. So far it has happened to me twice within the span of the past 30 minutes and always when I click send on an email I just composed in "Mail" 
I wish that I could attach a video to give you an idea of what I'm talking about.

**Comment by synthetiv** [comment]
This doesn't sound exactly like #129, but possibly related?

**Comment by knightjp** [comment]
Possibly. I installed chunkwm using brew and its version 0.2.12

**Comment by knightjp** [comment]
The windows tend to flicker when I am closing them.

**Comment by koekeishiya** [comment]
Probably same as in kwm. Disable `window_region_locked`

**Comment by knightjp** [comment]
@koekeishiya Yes.. I figured that it might be the issue.

**Comment by choco** [comment]
Maybe it'd be possible to mitigate this issue by buffering window resizes if we try to resize a win more then a threshold in an arbitrary amount of time...

**Comment by knightjp** [comment]
@choco I believe that the standard window animations of Mac OS are probably the issue. As mentioned in issue #129 , I notice the window start bouncing when compose and send a letter in the Mail app. The animation for sending a letter is the window basically flying upwards and closing. So with  the `window_region_locked` in the on position, we basically have an issue where the window is trying to fly off and the lock wants it kept in place. 
Perhaps switching off the window animations is needed. Or a way to unlock the windows for the animations to do their thing and switching it back on.
