### ISSUE TITLE
updating chunkwm

### ISSUE THREAD

**Issue by knightjp** [koekeishiya/chunkwm#132]
Which is the best way to make sure that we are updated to the latest commits? 
I am assuming rebuilding from source.

**Comment by crisidev** [comment]
You can use the brew formula and install the HEAD version.

```
brew uninstall chunkwm
brew install --HEAD --with-ffm chunkwm
```

This builds and installs the latest commit.

To update and rebuild the head version after first install:
```
brew upgrade chunkwm
```

**Comment by knightjp** [comment]
@crisidev thanks for the instructions.

**Comment by knightjp** [comment]
I got this error after using `brew upgrade chunkwm`

The error is `Error: crisidev/chunkwm/chunkwm HEAD-2424ef1 already installed`

**Comment by crisidev** [comment]
Mmmm maybe you cannot upgrade an HEAD formula. I think you need to uninstall and reinstall it every time. I honestly suggest you to use the stable release. I will keep it updated.

**Comment by koekeishiya** [comment]
2424ef1 is the latest commit.

**Comment by dominiklohmann** [comment]
> Mmmm maybe you cannot upgrade an HEAD formula. 

That is indeed the case, but you can use `brew reinstall chunkwm --HEAD --with-ffm` if yiou want to have a single command.

**Comment by knightjp** [comment]
Thanks everyone.. it is pretty sorted.
