### ISSUE TITLE
Add option to reload chunkwm configuration

### ISSUE THREAD

**Issue by crisidev** [koekeishiya/chunkwm#137]
Would it be possible to add a command line argument to reload chunkwm configuration like it is done in khd with
```
khd -e reload
```
?

**Comment by koekeishiya** [comment]
I assume you want this to also unload -> load all plugins listed in the .chunkwmrc?

**Comment by crisidev** [comment]
Correct.

**Comment by koekeishiya** [comment]
I suppose this could be added, although you could just have 

```
#usual part of config file
chunkc core::plugin dir ..
chunkc core::hotload ..

# do this for all plugins you use
chunkc core::unload tiling.so

# usual part of config file
....
```
and just do `sh ~/.chunkwmrc` when you want to reload.

**Comment by crisidev** [comment]
Ah, right.. it makes sense. I'll try this soon.

**Comment by crisidev** [comment]
It works pretty well for me. The issue can be closed if you don't want to implement an internal option for this.
