### ISSUE TITLE
[plugin|transparency] Add an option to make the focused window opaque

### ISSUE THREAD

**Issue by joshuap** [koekeishiya/chunkwm#139]
I took a stab at this myself tonight but didn't get too far; the approach I was thinking of was:

On `chunkwm_export_window_focused` event:

1. Reset transparency of all windows to `0.98f`
2. Set transparency of current window to `1.00f`

I accomplished 2., but I'm not sure how to build a list of all the windows for 1. (my c++ is so rusty it's nonexistent, and I'm not familiar with the macOS apis yet). I'm also worried about performance of 1.

Another idea I had was to set transparency to `1.00f` on the `chunkwm_export_window_focused` event and back to `0.98f` when the window loses focus, however [there is no event](https://github.com/koekeishiya/chunkwm/blob/master/src/api/plugin_export.h#L30) for when a window is "unfocused".

Does anyone have an opinion of how this would be best implemented? Thanks!

**Comment by koekeishiya** [comment]
Hm interesting idea

**Comment by choco** [comment]
A really cool implementation of a similar concept https://hazeover.com

**Comment by koekeishiya** [comment]
Not idea if this is what **hazeover** is doing, but a similar effect can be achieved by drawing a black (with %transparency) fullscreen rectangle, make it ignore mouse-clicks (so they fall through to the underlaying app) and make sure it is always ordered behind the frontmost window.

I'll take a lookt at this transparent windows approach later. Maybe I'll actually use the transparency then, as it is just "for show" and not really productive to have it on the window I'm working in.

**Comment by koekeishiya** [comment]
@joshuap I've added this to the tiling plugin as a config option (testing locally). This is actually amazing, nice idea.

**Comment by koekeishiya** [comment]
Make sure to update the **chwm-sa** before using this.
Added a different API to allow for animated fading.

Fading is handled by **chunkwm-tiling**

related cvars:
```
# enable fading of windows that are not in focus
chunkc set window_fade_inactive 1
# the target alpha value for faded windows
chunkc set window_fade_alpha 0.75
# the amount of time in seconds the fade should last
chunkc set window_fade_duration 0.5
```

**Comment by joshuap** [comment]
Thanks @koekeishiya, you rock! I'll give this a try later today.

**Comment by jonathanwilner** [comment]
Tested + works (on High Sierra), extremely cool! Thanks, @koekeishiya !

**Comment by joshuap** [comment]
Works here too. Great work; this is a fav feature from my Linux setup (I use [compton](https://github.com/chjj/compton) to achieve the same effect there). If anyone is feeling ambitious, blurring the background behind transparent windows (which iTerm2 supports, so it appears possible) is also a super nice effect.

**Comment by koekeishiya** [comment]
@joshuap I might be able to add blur as well. Will give it a try soon.

**Comment by koekeishiya** [comment]
There are APIs that seemingly let us add blur, but I have no idea what the names of valid *backingdrops* are.

Get the following err: `Unable to create backdrop for window b8cd.  Unknown backdrop type specified.`

**Comment by dominiklohmann** [comment]
I don't think you'd be able to get good blur performance without using vibrancy effects from NSVisualEffectView. Using CGS BackgroundBlur with a big enough blur radius to get a good effect will be about as performant as what iTerm2 uses, which means lag on a maxed out 2017 15" MBP.

**Comment by koekeishiya** [comment]
@dominiklohmann I noticed that as well. We probably want to be using:

```
CGSWindowBackdropCreateWithLevel(CGWindowId wid, CFStringRef materialName, CGWindowLevel level, CGRect frame);
CGSWindowBackdropActivate(CGSWindowBackdropRef backdrop);
```
and we can then force the window to draw as a "key window" IIRC.

No idea what to pass for *materialName* though. I've tried some combinations that I figure might make sense, but no success so far.

I probably wont spend more time on this for quite some time.

**Comment by jonathanwilner** [comment]
I began to notice 75 % + CPU utilization when I enabled window fading. I didn't see this a few days ago, but when running the build from the last two changes to the tiling plugin. Not 100 % sure - anyone else seeing this?

**Comment by jonathanwilner** [comment]
@koekeishiya - I am definitely still seeing the 75 % + CPU. Would you consider reopening the ticket?

**Comment by koekeishiya** [comment]
Are you sure this is not caused by some other system change?

I'm having the same CPU usage now as I did before. There has not been any changes to the code that should impact this either.

What's the performance like if you checkout and compile ddd837b03b08d867810d2d35658e834892d6ade4

**Comment by jonathanwilner** [comment]
Forgive my ignorance, I'm running from HEAD - you're suggesting to roll back? 

Jonathan

On Tue 18 Jul 2017 at 16:34, Åsmund Vikane <notifications@github.com> wrote:

Are you sure this is not caused by some other system change?

I'm having the same CPU usage now as I did before. There has not been any changes to the code that should impact this either.

What's the performance like if you checkout and compile ddd837b

**Comment by koekeishiya** [comment]
yeah. see if you can reproduce the problem on an earlier commit.

On Jul 20, 2017 7:28 PM, jonathanwilner <notifications@github.com> wrote:
Forgive my ignorance, I'm running from HEAD - you're suggesting to roll back?

Jonathan

On Tue 18 Jul 2017 at 16:34, Åsmund Vikane <notifications@github.com> wrote:

Are you sure this is not caused by some other system change?

I'm having the same CPU usage now as I did before. There has not been any changes to the code that should impact this either.

What's the performance like if you checkout and compile ddd837b

**Comment by jonathanwilner** [comment]
I believe I figured it out. If I launch chunkwm without chwm-sa's bin/inject running, I get the 100 % CPU problem. As soon as I manually launch bin/inject, performance returns to normal.

**Comment by waynehoover** [comment]
Is it possible to change the color of the opacity of the window? This would be like what hazeover does, so instead of decreasing opacity of a window, put a black opacity over inactive windows. Maybe even the color could be customized. Thoughts?
