### ISSUE TITLE
Multi monitor issue - Window shifting in between monitors

### ISSUE THREAD

**Issue by knightjp** [koekeishiya/chunkwm#141]
![screen shot 2017-07-13 at 7 18 16 pm](https://user-images.githubusercontent.com/14360736/28176458-8aa5d3c0-6808-11e7-80e5-7848492f60a1.png)
This is a rather strange issue that has happened to me for the first time. I was trying the change the wallpaper on my computer and the setup for both monitors appeared on one screen. 

Also a scenario that happened earlier. I opened a video and moved the window over to monitor 1. Then after opening another app window on monitor 1 the video window just moved back to monitor one. 
I hope that my explanation is clear enough.. I do apologize for any confusion.

**Comment by knightjp** [comment]
I have dual monitor setup on my computer. The windows still keep on shuffling in between them at random. If I have safari on one monitor, the moment I open a new tab, it moves suddenly to other one. And then there is the issue above. I am not quite sure what is happening.

**Comment by koekeishiya** [comment]
Does this happen if you restart chunkwm *after* the external monitor has been connected?

If yes, can you post your *.chunkwmrc*, and try to identify step by step instructions on how I can reproduce this. If there is an issue, this will help me a lot when trying to identify the problem and provde a fix. 

I've had no troubles with multiple monitors except for the live connect / disconnection part, that has yet to be implemented.

**Comment by knightjp** [comment]
My computer isn't a laptop. It is desktop... a Mac mini with dual monitors. So there really is no disconnecting or connecting of monitors at all. Sorry if I gave you the impression it was. 

```#!/bin/bash

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc plugin_dir /usr/local/opt/chunkwm/share/chunkwm_plugins
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm_plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1

#
# NOTE: The following are config variables for the chunkwm-tiling plugin
#

chunkc set global_desktop_mode           bsp

chunkc set 1_desktop_tree                ~/.chunkwm_layouts/dev_1

chunkc set global_desktop_offset_top     2
chunkc set global_desktop_offset_bottom  2
chunkc set global_desktop_offset_left    2
chunkc set global_desktop_offset_right   2
chunkc set global_desktop_offset_gap     2

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

#chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.6

chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           1
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          0

chunkc set preselect_border_color        0xffffff00
chunkc set preselect_border_width        4
chunkc set preselect_border_radius       4

# signal dock to make windows topmost when floated
# requires chwm-sa (https://github.com/koekeishiya/chwm-sa)
chunkc set window_float_topmost          0

#
# NOTE: The following are config variables for the chunkwm-border plugin
#

chunkc set focused_border_color          0xffffdb00
chunkc set focused_border_width          4
chunkc set focused_border_radius         4
chunkc set focused_border_skip_floating  0

#
# NOTE: specify plugins to load when chunkwm starts.
#

chunkc core::load tiling.so
chunkc core::load ffm.so
chunkc core::load border.so

chunkc tiling::rule --owner \"System Preferences\" --state tile
chunkc tiling::rule --owner Finder --name Copy --state float

#
# NOTE: if chunkc plugin_dir is not set, the absolutepath is necessary.
#

# chunkc core::load ~/.chunkwm_plugins/tiling.so
# chunkc core::load ~/.chunkwm_plugins/ffm.so
# chunkc core::load ~/.chunkwm_plugins/border.so```

**Comment by koekeishiya** [comment]
Hmm I still haven't been able to reproduce this, sadly. I'm going to close this for now, but please do let me know if this is still happening in the latest version. Thanks!
