### ISSUE TITLE
window --focus prev doesn't cycle in monocle layout

### ISSUE THREAD

**Issue by carymrobbins** [koekeishiya/chunkwm#142]
In conjunction with khd, If I switch to the monocle layout -

```
ctrl + alt - s : chunkc tiling::desktop --layout monocle
```

Using `window --focus next` will properly cycle back to the beginning of the windows; however, `prev` won't; it'll stop at the "first" window and successive calls to `prev` don't seem to do anything.

```
alt - j : chunkc tiling::window --focus prev
alt - k : chunkc tiling::window --focus next
```

**Comment by dominiklohmann** [comment]
I believe this is your issue: It only cycles if you set `window_focus_cycle` to `monitor` (as opposed to `all`), see previous discussion at https://github.com/koekeishiya/chunkwm/issues/15#issuecomment-302876509

> > Also, I just noticed that `chunkc config window_focus_cycle all` does not behave like `chunkc config window_focus_cycle monitor` if there's only a single monitor. There's no wraparound with all.
> 
> This is because the all option works fundamentally different from the monitor option, but will take a look at possible solutions for this. Currently, the all option does not wrap last monitor -> first monitor and first monitor -> last monitor either.

**Comment by koekeishiya** [comment]
I'm able to reproduce. Weird bug..

**Comment by carymrobbins** [comment]
@koekeishiya - FWIW, I'm about 85% sure that I had this same problem with kwm.
