### ISSUE TITLE
Mouse support - How to use

### ISSUE THREAD

**Issue by natsumi** [koekeishiya/chunkwm#146]
fn + left mouse / right mouse functions don't seem to work for me.

I'll using alt + left mouse to try to swap 2 windows and it causes one of the windwos to minimize.  alt + right click doesn't seem to allow resizing of the bsp region either.

Is there some option that needs to be turned on for this to work?  I have ffm disabled.

Thanks.

**Comment by koekeishiya** [comment]
> I'll using alt + left mouse to try to swap 2 windows and it causes one of the windwos to minimize. alt + right click doesn't seem to allow resizing of the bsp region either.

The modifier is `fn`. It only works on *bsp-desktops*.

Hold *fn*, left click **inside** a window and drag the mouse on top of some other window.
Hold *fn*, right click **inside the focused window** and drag the mouse

**Comment by natsumi** [comment]
@koekeishiya thanks for the info.  I didn't have a fn key but managed to resolve things with #150

**Comment by kirkegaard** [comment]
Is there anyway to change the resize (right click) event to something else? Could i change it to something like fn + shift + left click?

**Comment by koekeishiya** [comment]
It is currently not possible to interchange left and right mouse buttons. 
The reason for this is that they are two different event type, and both have a "special" case in their callback.

```
       case kCGEventLeftMouseDown:
        {
            CGEventFlags Flags = CGEventGetFlags(Event);
            if(((Flags & MouseModifier) == MouseModifier) &&
               (ResizeState.Mode == Drag_Mode_None))
            {
                LeftMouseDown();
                return NULL;
            }
        } break;
        case kCGEventLeftMouseDragged: { LeftMouseDragged(); } break;
        case kCGEventLeftMouseUp: { LeftMouseUp(); } break;
        case kCGEventRightMouseDown:
        {
            CGEventFlags Flags = CGEventGetFlags(Event);
            if(((Flags & MouseModifier) == MouseModifier) &&
               (ResizeState.Mode == Drag_Mode_None))
            {
                RightMouseDown();
                return NULL;
            }
        } break;
        case kCGEventRightMouseDragged: { RightMouseDragged(); } break;
        case kCGEventRightMouseUp: { RightMouseUp(); } break;
```

The only reason I see this happening is that we require the actions to be bound, using two cvars:
`chunkc set window_mouse_move fn left_mouse`
`chunkc set window_mouse_resize fn shift left_mouse`

In our callback above, we have to combine left + right events of a category:
```
case kCGEventLeftMouseDown:
case kCGEventRightMouseDown:
{
    // match flags and button with cvars
} break;
```

In addition, the handlers must be combined to single functions and switch based on click-type.

**Comment by cormacrelf** [comment]
I am extremely confused by this also. It seems to be great at hiding windows, but nothing else.

I have no function keys, so I have:

```
```
