### ISSUE TITLE
Enabling FFM

### ISSUE THREAD

**Issue by Serubin** [koekeishiya/chunkwm#149]
I've been looking around but I have not yet found my answer:
How do you enable focus follows mouse?

Thanks

**Comment by jakibaki** [comment]
You just need to load the ffm plugin 

    chunkc core::load ffm.so

and it should work.

**Comment by Serubin** [comment]
This doesn't act how focus_follows_mouse acts in kwm, I have to click to focus the window.

**Comment by koekeishiya** [comment]
Did you install the *ffm* plugin?

By default, *brew* and *port* only install **chunkwm-tiling**, and **chunkwm-border**, as stated in the README.

**Comment by Serubin** [comment]
That would do it. Apologies.
