### ISSUE TITLE
[plugins|ffm] crash if `mouse_modifier` isn't set in the configuration

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#152]
As per title.

**Comment by koekeishiya** [comment]
Hm what, I'm unable to reproduce ??

**Comment by koekeishiya** [comment]
God damnit, yeah..

**Comment by koekeishiya** [comment]
For some reason I thought passing a null pointer would be valid, but I was actually thinking of the \0 char. Bad dereference. The reason I didn't get the crash is that I load the tiling plugin before the ffm one, and tiling set a default value for that cvar.

**Comment by choco** [comment]
Yeah I know, just didn't bother to submit a pullrequest for a one line fix, sorry XD hopefully i'll be able to help more next month....

**Comment by koekeishiya** [comment]
No worries, solid bug reports help a lot as well :)
