### ISSUE TITLE
[plugin|tiling] follow to other desktop as specified in rule

### ISSUE THREAD

**Issue by marcjoha** [koekeishiya/chunkwm#154]
I have this rule

`chunkc tiling::rule --owner Spotify --desktop 3`

When it triggers I'd also like to "follow along" to that desktop, and not just have the app open in the background. Perhaps add a new flag `--desktop-and-follow` or similar?

**Comment by koekeishiya** [comment]
There is no API for us to programmatically switch active desktop.

**Comment by marcjoha** [comment]
Oh bummer
