### ISSUE TITLE
Connection failed after brew install

### ISSUE THREAD

**Issue by slifin** [koekeishiya/chunkwm#155]
I was using kwm, then compiled this from source, then noticed a lot of bugs and stopped chunkwm and went back to kwm, now I'm testing chunkwm using the brew package this time

```bash 
chunkc tiling::window --focus west
chunkc: connection failed!
```

I saw in one of the other issues the suggestion of checking port 3920, looks like chunkwm is listening there, when I turn off chunkwm via brew services it disappears from the port so I'm assume that's correct behaviour

**Comment by koekeishiya** [comment]
You probably have an out of date `chunkc`. Make sure you remove all artifacts before installing.

`which chunkc`
`which chunkwm`

**Comment by slifin** [comment]
Thank you this was the problem
