### ISSUE TITLE
Disable focus-follows-mouse

### ISSUE THREAD

**Issue by ShadauxCat** [koekeishiya/chunkwm#157]
How do I do this? Surely there's a way. Passing my mouse over a window and having it steal focus from a floating window (and thus requiring me to go down to the dock to show it again, only for it to lose focus yet again when I try to move my mouse back to it) is extremely annoying. Holding a button every time I move my mouse is also extremely annoying and not something I want to try to get used to. Also, when my mouse is in a window and I move it to another monitor, whatever window takes over its space steals focus because my mouse is suddenly in it. I just want to turn this feature off.

**Comment by ShadauxCat** [comment]
Also there seems to be a bug with this on portrait monitors, too. The windows at the bottom segment of the screen (below the maximum height of my primary landscape monitor) want to take focus even when my mouse is in windows above them.

**Comment by chrishoage** [comment]
Do not load the focus follows mouse plugin

**Comment by ShadauxCat** [comment]
ohhh. Is that what the ffm plugin is? I didn't put that together. I had no idea what 'ffm' stood for, I just thought it was necessary. XD Thank you.

**Comment by chrishoage** [comment]
yes, `ffm` is shorthand for `focus-follows-mouse` 

glad to help!

**Comment by jamesjlyons** [comment]
You can always set a KHD command to load/unload plugins too. Here's what I've been using in my khdrc file:

    # disable/enable ffm
    cmd + ctrl + alt + shift - m : chunkc core::load ffm.so
    cmd + ctrl + alt - m : chunkc core::unload ffm.so
