### ISSUE TITLE
Window movement via mouse

### ISSUE THREAD

**Issue by pardom** [koekeishiya/chunkwm#159]
I've seen other window managers which allow windows to be repositioned via mouse rather than keyboard. I'm not sure I'd use the feature personally, but I'm curious if I were to write it, could it be a plugin or would it need to be more tightly integrated?

**Comment by ultrahumanite** [comment]
A feature like this would be great. I might only use it occasionally but I know quite a few people who'd see chunkwm as way more approachable if they could at least fall back on the mouse to reposition and perhaps even resize the windows.

**Comment by chrishoage** [comment]
If this were to be implemented it would be nice if it worked based on the traditional mouse resizing functionality built into OS X. 

I have no idea how feasible it is, but being able to resize one window and have the rest of the windows adjust their container in response would be a pretty seamless user experience.

**Comment by koekeishiya** [comment]
It is already possible to swap and resize windows using the mouse, but only for bsp-desktops.

During resize we're creating borders that outline the new positions. I experimented with live resize but disabled it because the AX API is slow as hell.

**Comment by koekeishiya** [comment]
I'm gonna close this. Feel free to reopen if you think there is still work to be done regarding this.

**Comment by ricelid** [comment]
Is there a way to configure which mouse button does which action?
