### ISSUE TITLE
Send window to desktop and switch desktop not working.

### ISSUE THREAD

**Issue by colonelk1** [koekeishiya/chunkwm#161]
Hey koekeishiya, really appreciate all the work you put into these window managers. 

I'm using your dotfiles, and when I try to "send window to desktop and switch desktop", it doesn't work. 

I have "automatically rearrange spaces based on most recent use" turned OFF, "when switching.." on, "group windows by application" OFF, and "displays have .." ON.

Any recommendations?

**Comment by colonelk1** [comment]
Another question, sorry. I installed chunkwm, etc. via homebrew, does this not come with chunkwm FFM? How do I go about installing plugins? Thank you!

**Comment by jakibaki** [comment]
The config assumes certain keyboard-shortcuts for switching the workspace and just sends that.

    khd -p "cmd + alt - 1"

You can change the "cmd + alt - 1" part to whatever keyboard-shortcut you have for switching workspaces

FFM is the Focus follows mouse plugin.

It just activates windows when you have your mouse over them without you having to click anything.

If you want to use that just run

    brew install --with-ffm chunkwm

to install chunkwm with the ffm plugin (see [this](https://github.com/crisidev/homebrew-chunkwm) readme from the homebrew package)

**Comment by colonelk1** [comment]
Thank you very much! Works after changing my settings.
