### ISSUE TITLE
XQuartz X11 windows are not being recognised at all

### ISSUE THREAD

**Issue by jakibaki** [koekeishiya/chunkwm#163]
Chunkwm completely ignores XQuartz windows (no tiling, no border, no moving to other spaces...)

**Comment by chrishoage** [comment]
I'm not sure the Accessibility API can not recognize XQuarz windows, so chunkwm probably will never be able to manage them. 

koekeishiya will know for sure though.

**Comment by dominiklohmann** [comment]
I believe partial support for this could be added, but it looks like it requires a lot of work. Here's how ShiftIt interacts with X11 windows for example: https://github.com/fikovnik/ShiftIt/blob/master/ShiftIt/X11WindowDriver.m

**Comment by koekeishiya** [comment]
It is possible to move and resize windows as ShiftIt does it, however there is no way to get notified about changes to XQuartz windows (to my knowledge), and so this is not something that I'll target in *chunkwm*.
