### ISSUE TITLE
Float on per app basis?

### ISSUE THREAD

**Issue by sealevelcain** [koekeishiya/chunkwm#164]
Hello,

Apologies if this has been brought up before but I was unable to find anything. 

Is there a way to configure chunkwm to always float certain apps/windows (e.g. system preferences)? If so how would I go about that?

Thanks

**Comment by dominiklohmann** [comment]
```
chunkc tiling::rule --owner \"System Preferences\" --state float
```

**Comment by koekeishiya** [comment]
You can use the rules system as stated above.

**Comment by L3rchal** [comment]
Is there way to set for floating windows to display always in the center?

**Comment by dominiklohmann** [comment]
There's `chunkc config window_float_center 1`, but since commit 53a02e this does only apply to user-initiated float, so this wouldn't work for windows floated because of tiling rules.
