### ISSUE TITLE
Window (app) without dock icon not recognised

### ISSUE THREAD

**Issue by L3rchal** [koekeishiya/chunkwm#165]
For image preview I use macfeh. I found annoying when app opens every time icon in dock like normal application (I wanted behaviour like terminal application). So I disable it via editing Info.plist :
```xml
	<key>LSUIElement</key>
	<true/>
```
I added this to Info.plist. However after opening image, *chunwm* ignores opened window.
This is definitely not critical issue, I just found it strange.

**Comment by koekeishiya** [comment]
Same as #108
