### ISSUE TITLE
Gradient/image based borders?

### ISSUE THREAD

**Issue by sealevelcain** [koekeishiya/chunkwm#168]
Is it possible to use gradients or tiling images for borders instead of solid colours?

**Comment by chrishoage** [comment]
nope

**Comment by sealevelcain** [comment]
Oh well.

**Comment by sealevelcain** [comment]
Bumping to ask if there is any way to set border colour on a per app basis?

**Comment by koekeishiya** [comment]
Not by default, but it is fairly trivial for anyone to modify the border plugin to do so, or create a separate plugin that listens for *application_activated* event and automates a `chunkc border::color <color>` command.

**Comment by sealevelcain** [comment]
Thanks for the reply. I'm very new to this and thus have no idea what I'm doing, so to avoid breaking anything I'll leave it for now. It's good to know it's possible though. Thanks!

**Comment by sealevelcain** [comment]
Just out of curiosity... when modifying the border plugin, is that referring to border.so? and if so how does one go about modifying that? (Complete noob, sorry for all of the questions)

**Comment by koekeishiya** [comment]
> Just out of curiosity... when modifying the border plugin, is that referring to border.so? and if so how does one go about modifying that? (Complete noob, sorry for all of the questions)

You'd have to edit the [source code](https://github.com/koekeishiya/chunkwm/tree/master/src/plugins/border) to do what you want, and recompile.

**Comment by sealevelcain** [comment]
Awesome, thanks.
