### ISSUE TITLE
[plugin|tiling] mouse follows focus triggers when closing "Help" menu bar entry

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/chunkwm#169]
Regardless of the application open or the amount of open windows, if I close the "Help" menu bar entry (e.g. by moving the mouse over another entry), mouse follows focus triggers and the cursor gets sent to the middle of the window. This does not happen with any other menu bar entries.

The only thing that appears in stdout when doing this is the following:
```
Safari:New Issue · koekeishiya/chunkwm:50 window focused
```

Edit: Changed ffm -> mff.

**Comment by dominiklohmann** [comment]
This does not happen when opening and closing the Help item with `cmd + shift - /`. However, if either opening or closing is done using the mouse mouse follows focus triggers.

Really not sure what is causing this, although it is likely an issue with the search field since that's the only difference between Help and other menu bar items.

**Comment by koekeishiya** [comment]
As noted by the above print you posted, we are getting a *window focused* event from macOS when the *Help item* closes. God knows why, as we do not get a *window focused* event when the *Help item* is opened..

I don't really have any idea of what to do about this.

**Comment by koekeishiya** [comment]
This actually seems related to  #75.
Regression on my part during a refactor when previously removing caching of focused window id.

**Comment by dominiklohmann** [comment]
That fixed it. Thanks! 👍
