### ISSUE TITLE
Disable iTerm Visor window tiling

### ISSUE THREAD

**Issue by Jarvvski** [koekeishiya/chunkwm#181]
Hi there @koekeishiya 

Long time user of your previous Kwm.

Great work so far. Chunkwm seems to be running really stable.

I notice however that iTerm's visor window has issues with Chunkwm, similar to how it was reported here: https://github.com/koekeishiya/kwm/issues/299

`kwmc rule owner="iTerm2Visor" properties={role="AXDialog";float=true}`

This seemed to be the solution, and worked well.

Is there any way I can get the same to work in Chunkwm? Currently the visor looks like this:

![](https://i.imgur.com/H9TNhGG.png)

When it should look like:

![](https://i.imgur.com/O7wjcAU.png)

As you can see the issues are;

- it tiles the background window
- increases the window size of new visor window to standard tile size

**Comment by koekeishiya** [comment]
See #176 and window rules section in the chunkwm-tiling readme.

if you need more specific help, let me know.

**Comment by Jarvvski** [comment]
Fantastic, thank you.

This system for rules seem much simpler than Kwm's. Good work!

Sadly, there doesn't seem to be a real way to differentiate a normal iTerm window from an iTermVisor window:

![](https://i.imgur.com/fnclhru.png)
*the visor being `36505`*

But thankfully my visor is nearly always in tmux mode so filtering by name works for the time being!

**Comment by Jarvvski** [comment]
Another thing I've noticed with another application I use, is it possible to check for values **not** equaling that something for a given rule?

For example:

`chunkc tiling::rule --owner Finder --name ! "" --state float`

Meaning, a rule for any window owned by Finder but whose name is not `""`

**Comment by dominiklohmann** [comment]
You can use `--except` for that

**Comment by Jarvvski** [comment]
Thanks @dominiklohmann, I didn't see that line

However, this doesn't seem to work when the name is empty:

![](https://i.imgur.com/KGwAFQb.png)

`chunkc tiling::rule --owner newton --except "" --state float`

**Comment by dominiklohmann** [comment]
Does it work if you use this instead?

```
chunkc tiling::rule --owner newton --except \"\" --state float
```

**Comment by dominiklohmann** [comment]
Also if I recall correctly `--name` works with anything that works with `std::regex`, so this should also work:

```
chunkc tiling::rule --owner newton --name \"^(?![\s\S])\" --state float
```

That regex is a negative lookahead for any character, so it only matches an empty string.

**Comment by koekeishiya** [comment]
filter type is also mentioned in the tiling readme. the supported syntax is POSIX Extended Regular Expression

**Comment by dominiklohmann** [comment]
> POSIX Extended Regular Expression

So no (negative) lookahead, so cut that idea. This leaves the `--except` option for that afaik.

**Comment by koekeishiya** [comment]
`chunkc tiling::rule --owner Finder --name .+ --state float`

Applies to window that has a non-empty name, iirc

**Comment by koekeishiya** [comment]
Ok so screw my last post, the rule worked. I just failed at testing...

float all finder windows that does have a name.  `.` matches any character except the null character, and the `+` tells us to match the previous atom 1 or more times, thus ignoring empty windows.
`chunkc tiling::rule --owner Finder --name ".+" --state float` 

if you want the rule to ONLY apply to windows with empty title:
`chunkc tiling::rule --owner Finder --except ".+" --state float

https://www.gnu.org/software/findutils/manual/html_node/find_html/posix_002dextended-regular-expression-syntax.html

**Comment by Jarvvski** [comment]
Perfect @koekeishiya 

That works great, thank you for all your hard work!

**Comment by koekeishiya** [comment]
Great, closing this issue then.

**Comment by asselinpaul** [comment]
I solved this by setting turning off the "terminal may set tab/window title" option in my 'Slide Down' profiles' preferences in iTerm.

Then I set the following in my .chunkwmrc (my shell is zsh):
`chunkc tiling::rule --owner iTerm2 --name "^zsh" --state float`

This works because my drop-down has name `zsh` whereas my default profile has names that are set by the window/tab (which usually start with my username).

**Comment by Jarvvski** [comment]
@asselinpaul even better, the window gets it's name from the profile. So simply having a the visor profile called `hotkey` in profiles>general>name allows us to filter for it.

Turning off the "terminal may set tab/window title" for that profile, then:

`chunkc tiling::rule --owner iTerm2 --name "{name_of_profile}" --state float`

**Comment by asselinpaul** [comment]
@Jarvvski even better, thank you

**Comment by Kryan90** [comment]
@karbecker In case you are still having this issue, I found a solution.

Keys Tab > create a dedicated hotkey window... > configure existing profile > check Floating window

**Comment by Jarvvski** [comment]
@Kryan90 this is the best method I've found:

`chunkc tiling::rule --owner iTerm2 --name \"Hotkey Window\" --state float`

Then in iTerm2 prefs: 'your hotkey profile' > terminal tab > uncheck both terminal may report/set window/tab title

The name of your profile is what you use in the chunkrc config

**Comment by ccarlile** [comment]
This was driving me nuts, until I found the setting in iTerm2: Appearance > Window and Tab Titles > check "Show Profile Name". This might be your problem @karbecker unless you figured it out already 😄
