### ISSUE TITLE
Change monitor order?

### ISSUE THREAD

**Issue by jessemillar** [koekeishiya/chunkwm#183]
It seems that chunkwm wants/expects monitors to be laid out in a `1, 2, 3` order with `1` being my MacBook's built-in monitor and `2` and `3` being external. This is fine except I have my monitors arranged so an external monitor is on each side of my MacBook in a `2, 1, 3` order which makes setting my `window_focus_cycle` to `all` slightly confusing. Is there any way to change the order of my monitors in chunkwm's logic so it can cycle focus on my setup "properly"?

**Comment by koekeishiya** [comment]
I currently have no idea how hard that would be. Right now use the arrangement returned to us directly by the macOS APIs. As far as I know, this is the same ordering that shows up in *display preferences*, where you can make some other monitor your main monitor and so on.

**Comment by jessemillar** [comment]
Ah. I hadn't even thought of changing my main monitor. I set my main monitor to my leftmost one and now all works as expected. Thanks!

**Comment by lhanson** [comment]
This also worked for me, thanks!
