### ISSUE TITLE
[plugin|tiling] Inconsistent behaviour of --adjust-window-edge east|south

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/chunkwm#184]
In a layout with three windows like shown below, `--adjust-window-edge east`  moves the container border in the wrong direction for the bottom left window.

Demonstration screencast:
![window-edge-east-bug](https://user-images.githubusercontent.com/4488655/28962106-dde63b6c-7904-11e7-8703-1a7f05d559c5.gif)

This also happens for `south` when the whole thing is rotated by 90°, but never for `west` or `north`.

**Comment by dominiklohmann** [comment]
Now it's broken for west and north if you rotate the whole thing by 180° / 270°.

**Comment by koekeishiya** [comment]
Ugh, I wonder if this problem also exists in Kwm. It uses the same logic.
