### ISSUE TITLE
Error Installing 

### ISSUE THREAD

**Issue by phlind** [koekeishiya/chunkwm#186]
Hi, when I try to install chunkwm, I get the following error:

> MacBook-Air:local philipp$ brew install chunkwm
> ==> Installing chunkwm from crisidev/chunkwm
> ==> Using the sandbox
> ==> Downloading https://github.com/koekeishiya/chunkwm/archive/v0.2.28.tar.gz
> Already downloaded: /Users/philipp/Library/Caches/Homebrew/chunkwm-0.2.28.tar.gz
> ==> make install
> ==> make
> ==> make install
> Last 15 lines from /Users/philipp/Library/Logs/Homebrew/chunkwm/03.make:
> 2017-08-06 14:46:13 +0200
> 
> make
> install
> 
> rm -f ./../../../plugins/tiling.so
> mkdir -p ./../../../plugins
> clang++ plugin.mm -O2 -std=c++11 -Wall -Wno-deprecated -Wno-writable-strings -o ../../../plugins/tiling.so -shared -fPIC -framework Carbon -framework Cocoa -framework ApplicationServices
> In file included from plugin.mm:35:
> ./../../common/border/border.mm:76:51: error: use of undeclared identifier 'NSWindowStyleMaskBorderless'
>                                        styleMask: NSWindowStyleMaskBorderless
>                                                   ^
> 1 error generated.
> make: *** [../../../plugins/tiling.so] Error 1

Can someone help me, please?
Thanks

**Comment by crisidev** [comment]
Which version of macosx are you using?

**Comment by koekeishiya** [comment]
See #93

**Comment by Sorombo** [comment]
Hi, I'm also having a problem installing kwm. I get the following error:

> Last 15 lines from /Users/Sorombo/Library/Logs/Homebrew/chunkwm/01.make:
2017-08-07 23:41:06 -0300
>
>make
>install
>
>rm -rf ./bin
>mkdir -p ./bin
>clang++ src/core/chunkwm.mm -O2 -std=c++11 -Wall -Wno-deprecated -o bin/chunkwm >-rdynamic -ldl -lpthread -framework Carbon -framework Cocoa
>ld: can't open output file for writing: bin/chunkwm, errno=2 for architecture x86_64
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>make: *** [bin/chunkwm] Error 1

Any help would be much appreciated. Thanks.

**Comment by koekeishiya** [comment]
@phlind 

Should be fixed at master now. If you install from brew, you need to specify the head option `brew install --HEAD chunkwm`

@Sorombo 

The linker fails to write the file to disk for some reason. No idea why that would be happening, but it is not an issue with chunkwm in general. I would suggest trying to do an uninstall with brew, and potentially also look in */usr/local/bin* for *chunkc* and / or *chunkwm*. Reboot the system and try to install through brew again.
