### ISSUE TITLE
Closing the active window

### ISSUE THREAD

**Issue by carymrobbins** [koekeishiya/chunkwm#187]
Is there a way to close the active window? This should be identical to clicking the red x button in the top-left of the window. Simply simulating `cmd+w` isn't really enough since different apps deal with this differently; however, they all pretty much interpret the red x button the same way.

**Comment by koekeishiya** [comment]
I can add the ability to invoke the *AXCloseButton* action, that the red x activates. This will only work for windows that define this *AXCloseButton*.

e.g: this works on my borderless-firefox theme, but it does not work on my borderless terminal application.

**Comment by dominiklohmann** [comment]
This should do the trick as well:
```
ctrl - w : osascript -e 'tell application (path to frontmost application as text) to close front window'
```

**Comment by carymrobbins** [comment]
That'd be great, thanks!

**Comment by koekeishiya** [comment]
`chunkc tiling::window --close` @ master

**Comment by carymrobbins** [comment]
@koekeishiya - Works great, thanks!

@dominiklohmann - I tried the `osascript` approach but it doesn't seem to work properly for some applications (IntelliJ windows being one of them). The new `chunkc` feature, however, seems to work well so far.

**Comment by simonsmith** [comment]
@koekeishiya I'm having a problem where closing the window means I lose the ability to interact with the existing windows until I click on them. In fact I can't seem to use the keyboard at all.

 I'm using the modes in khd. I've tried this, but no joy:

```
switcher - w            :   chunkc tiling::window --close;\
                            khd -e "mode activate default"
```

Any thoughts?

**Comment by xiamaz** [comment]
I am using an xquartz application, where the chunkc feature does not seem to work. The application does not expose an window menu, although normal window controls are available.

The application is zimwiki installed via macports.

**Comment by dominiklohmann** [comment]
I don't think X11/XQuartz windows are supported in any way since they do not expose anything to the Accessibility API.
