### ISSUE TITLE
[plugin|tiling] chunkwm reads subrole of minimzed windows as AXDialog on launch

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/chunkwm#188]
To reproduce:
- Stop chunkwm
- Minimize a window with role `AXWindow` and subrole `AXStandardWindow`
- Start chunkwm
- Window now has subrole `AXDialog` and is treated as floating

Not sure why this happens. ~~Window appears in logs as deminimized (2x) and immediately after as focused (2x), which is no different from what gets logged if a window gets minimized while chunkwm is running and then deminimized.~~

**Comment by koekeishiya** [comment]
I'm able to reproduce the `AXDialog` -> *floating* issue.

>  Window appears in logs as deminimized (2x) and immediately after as focused (2x), which is no different from what gets logged if a window gets minimized while chunkwm is running and then deminimized.

I'm unable to reproduce this. I only get a single deminimized and focused event.

**Comment by dominiklohmann** [comment]
> I'm unable to reproduce this. I only get a single deminimized and focused event.

Tested some more, was apparently on High Sierra when I tested this. Will post that part in #80.
