### ISSUE TITLE
[plugin|tiling] query if window is floating

### ISSUE THREAD

**Issue by szymonkaliski** [koekeishiya/chunkwm#189]
Is it possible to know if window is currently floating from `chunkc`?

**Comment by koekeishiya** [comment]
By window, do you mean any arbitrary window or the focused window only ?

As of now, the answer to both is no, but the latter is fairly trivial to implement.
For the former, a command syntax change is most likely necessary for it to make sense.

**Comment by szymonkaliski** [comment]
Yeah, just currently focused one would work for me :)

**Comment by koekeishiya** [comment]
`chunkc tiling::query --window float` -> `1` or `0`  @ master
