### ISSUE TITLE
separation of interactive window and focused window

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#19]
Not really sure where I'm going with this, but rambling ensues.

A major part of interaction with **Kwm** was locked around only being able to perform window operations on the focused window. To operate on some other window, it had to be given focus, and then it could be resized, moved around and so on.

I am experimenting with having the so called `insertion_point`, or rather `interactive_point` be somewhat separate from the `focused window`. By this I mean that the `focused window` is tracked separately so that we can always retrieve what we think is the focused window if necessary.

This is the feature that will take the place of **Kwm**'s `mark window` behaviour.

The `insertion_point` starts out by being equal to the `focused_window`. When an application is activated, or the focus is changed, we check if the new active window is tiled in our bsp-tree. If it is tiled, this becomes our new `insertion_point`. The `insertion_point` can be modified using `chunkc window -i <west | east | north | south | focus>`. The interesting part here is that the `insertion_point` is relative to itself.

e.g: If you have three vertical columns, and the right column is given focus, this is now our `insertion_point`. I want to open a new terminal window in the left column, but I don't want to have to manually move my focus there first. I can set the proper `insertion_point` by doing `chunkc window -i west -i west` (move insertion point west twice, either as a single command or hitting the bind twice)  before spawning a terminal.

Maybe I'd rather want to displace the middle column into a small horizontal split with my currently focused window. I could simply do `chunkc window -i west -r 0.35 -w east`.

The `insertion_point` would work for all (?) `window <flag>` commands.

**Comment by matthewdias** [comment]
would also be cool to have a "main" insertion point that all new windows spawned in. maybe with a command to set the insertion point and/or focus based on pre-ordered index in the tree?

**Comment by Amar1729** [comment]
This is really similar to the ["preselection" offered by bspwm](https://github.com/baskerville/bspwm/blob/master/doc/bspwm.1.asciidoc#commands) which is really helpful in controlling a space when spawning a new window. Right now in kwm it's sometimes a bit of guesswork as to where a new window will spawn, and then re-inserting it at the desired location.

**Comment by chrishoage** [comment]
> Right now in kwm it's sometimes a bit of guesswork as to where a new window will spawn, and then re-inserting it at the desired location.

I _think_ that was the original goal of "marked" windows however. You could mark a window and the next spawn would be split at the marked window.
