### ISSUE TITLE
Borders not properly displayed in multimonitor

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/chunkwm#194]
Hi,

chunkwm have some difficulties to set the borders appropriately on my setup.

Here are some screenshots:

## My 3 monitors setup
![2017-08-18_10-19-36](https://user-images.githubusercontent.com/5844226/29451263-48674ee2-8402-11e7-918a-ba8b2f556eae.png)
Note that I have a vertical display.
### The details
![2017-08-18_10-47-53](https://user-images.githubusercontent.com/5844226/29451378-be7480b4-8402-11e7-81d2-5c030e0f9e78.png)

## First example: Screenshot of the main (top) monitor while hovering a full screen application on the internal (bottom) monitor.
![2017-08-18_10-19-20](https://user-images.githubusercontent.com/5844226/29451298-70f13986-8402-11e7-8769-7215c2c5ff57.png)
The border is displayed on the top screen :(

## Second example: hovering the bottom item window on my left monitor
![2017-08-18_10-18-32](https://user-images.githubusercontent.com/5844226/29451403-dd7bb568-8402-11e7-87c0-0c2ecad9d68f.png)

## Third example: Hovering the top iterm window.
![2017-08-18_10-18-49](https://user-images.githubusercontent.com/5844226/29451506-3ca18630-8403-11e7-9734-55a5f3004c9a.png)

The border is not properly displayed. There is a small gap between the window and iterm. Note that is not a bug related to iterm. I have it on all windows.

## Configuration files

I use `chukwm version 0.2.30` installed with `brew`.

My configuration file, you will notice that I use a rather big bottom margin on my main screen:

```
#!/bin/bash

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir ~/.chunkwm_plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1

#
# NOTE: the following are config variables for the chunkwm-tiling plugin.
#

chunkc set global_desktop_mode           bsp
#chunkc set 2_desktop_mode                monocle
#chunkc set 5_desktop_mode                float

#chunkc set 1_desktop_tree                ~/.chunkwm_layouts/dev_1

chunkc set global_desktop_offset_top     10
chunkc set global_desktop_offset_bottom  10
chunkc set global_desktop_offset_left    10
chunkc set global_desktop_offset_right   10
chunkc set global_desktop_offset_gap     5

chunkc set 16_desktop_offset_top     20
chunkc set 16_desktop_offset_bottom  600
chunkc set 16_desktop_offset_left    10
chunkc set 16_desktop_offset_right   200
chunkc set 16_desktop_offset_gap     15

chunkc set 17_desktop_offset_top     20
chunkc set 17_desktop_offset_bottom  600
chunkc set 17_desktop_offset_left    10
chunkc set 17_desktop_offset_right   200
chunkc set 17_desktop_offset_gap     15

chunkc set 18_desktop_offset_top     20
chunkc set 18_desktop_offset_bottom  600
chunkc set 18_desktop_offset_left    10
chunkc set 18_desktop_offset_right   200
chunkc set 18_desktop_offset_gap     15

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           0
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#
# chunkc set mouse_modifier              \"cmd shift\"
chunkc set mouse_modifier                fn

chunkc set preselect_border_color        0xff00ff00
chunkc set preselect_border_width        1
chunkc set preselect_border_radius       0

#
# NOTE: these settings require chwm-sa.
#       (https://github.com/koekeishiya/chwm-sa)
#

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.5

#
# NOTE: the following are config variables for the chunkwm-border plugin.
#

chunkc set focused_border_color          0x99FF0000
chunkc set focused_border_width          4
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  0

#
# NOTE: specify plugins to load when chunkwm starts.
#       if chunkc plugin_dir is not set, the absolutepath is necessary.
#

chunkc core::load tiling.so
chunkc core::load ffm.so
chunkc core::load border.so

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#

chunkc tiling::rule --owner \"System Preferences\" --subrole AXStandardWindow --state tile
chunkc tiling::rule --owner \"iTerm2\" --subrole AXStandardWindow --state tile
chunkc tiling::rule --owner Finder --name Copy --state float

```

Thanks for your help and great work !

**Comment by crisidev** [comment]
This happens to me when when I connect a monitor and do not fully restart chunkwm.

Have you tried 

```brew services stop chunkwm && brew services start chunkwm```

?

**Comment by koekeishiya** [comment]
We have to invert the y-coordinates between the position returned by the accessiblity API, and the actual monitor dimensions. The values we use have to correspond with the monitor that is currently flagged as the "Main" monitor. When you connect or disconnect a monitor, this arrangement might change depending on your macOS display arrangement settings.

Because of the above, I suspect that this issue is because of a (premature) optimization I did here: https://github.com/koekeishiya/chunkwm/blob/master/src/common/border/border.mm#L70

Can one of you remove the *static* specifier from line *#70* and *#71* and see if that fixes it ?

**Comment by mickaelperrin** [comment]
@crisidev of course, I have mapped a shortcut in khd to run the restart of the service :)

@koekeishiya I will have a look at it. I need to check the compilation process. I also noticed that removing the specific configuration for the spaces of my main monitor fixed the issue. But of course, this is not what I want ;)

**Comment by koekeishiya** [comment]
@mickaelperrin 

If the compilation process seems tedious, you could fork the repository, perform edits and push to your remote. Then edit the homebrew formula to point to your master, and use the *--HEAD* option.

**Comment by mickaelperrin** [comment]
So, as you requested, here is the change I did:
```
diff --git a/src/common/border/border.mm b/src/common/border/border.mm
index df375ce..4f67447 100644
--- a/src/common/border/border.mm
+++ b/src/common/border/border.mm
@@ -67,8 +67,8 @@ - (void)drawRect:(NSRect)Rect
 static int
 InvertY(int Y, int Height)
 {
-    static NSScreen *MainScreen = [NSScreen mainScreen];
-    static NSRect Rect = [MainScreen frame];
+    NSScreen *MainScreen = [NSScreen mainScreen];
+    NSRect Rect = [MainScreen frame];
     int InvertedY = Rect.size.height - (Y + Height);
     return InvertedY;
 }
```

I recompiled the whole stuff with:
```
#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR
make install
cp bin/chunkwm /usr/local/bin
cp examples/com.koekeishiya.chunkwm.plist ~/Library/LaunchAgents
cd ${DIR}/src/chunkc
make
cp bin/chunkc /usr/local/bin

cd ${DIR}/src/plugins/tiling
make install
cp ../../../plugins/tiling.so ~/.chunkwm_plugins

cd ${DIR}/src/plugins/border
make install
cp ../../../plugins/border.so ~/.chunkwm_plugins

cd ${DIR}/src/plugins/ffm
make install
cp ../../../plugins/ffm.so ~/.chunkwm_plugins

launchctl load -w ~/Library/LaunchAgents/com.koekeishiya.chunkwm.plist
pkill chunkwm
```
Issue 1 seems to be resolved, but not 2 & 3.

**Comment by mickaelperrin** [comment]
I `pkill`the application, as you can see at the end of my script. Do you mean, this is maybe not sufficient to *completely* restart chunkwm ?

I just tried with:
```
launchctl unload -w ~/Library/LaunchAgents/com.koekeishiya.chunkwm.plist
launchctl load -w ~/Library/LaunchAgents/com.koekeishiya.chunkwm.plist
```

And didn't see any differences, issues are still here.

I just tried again to remove my specific stuff for spaces configuration, and the problem is still here.

**Comment by koekeishiya** [comment]
Can no longer reproduce on my setup with 1 external monitor. Hopefully this fixes it as I'm literally out of ideas.

**Comment by koekeishiya** [comment]
Let me know if this did not solve the problem, and I will reopen the issue.

**Comment by mickaelperrin** [comment]
@koekeishiya Back at home and finally did a test, it looks like it works great now ! Awesome job ! Thanks
