### ISSUE TITLE
No more tiling without specific rule

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/chunkwm#195]
Hi,

I have noticed since a few days that the tiling doesn't work anymore by default.

It works only for windows explicitly marked as "to tile" in the configuration file with: `chunkc tiling::rule --owner \"Chrome\" --subrole AXStandardWindow --state tile`.

Has something changed?

Thx,

--
[My ~/.chunkwmrc](https://gist.github.com/mickaelperrin/bc754ee2c4626e283eaada109d3302bd)
`chunkwm 0.2.30`

**Comment by koekeishiya** [comment]
There has not been any changes regarding this. I don't see how that problem could even occur :/

**Comment by koekeishiya** [comment]
The only change that is even remotely connected would be the fix for:  https://github.com/koekeishiya/chunkwm/issues/188  (6days ago)

I suspect something else is the cause though.

**Comment by mickaelperrin** [comment]
In order to test your proposal, I switched to a compiled version, and it works.

A problem with the brew version or with my setup maybe?

**Comment by splintah** [comment]
Same problem here... I can't get version 0.2.30 to work, nor can I get it to work by installing with `brew install --HEAD chunkwm`. I also tried compiling it myself with same results.
