### ISSUE TITLE
[plugin|tiling] reapply window rules upon title-change

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#198]
@ilevantis

> An issue I have with KWM that would be great to fix in ChunkWM is with trying to specify behaviours of particular firefox windows.

> When firefox spawns a new window its initial title will just be 'Firefox' and very soon after it changes to the actual title e.g. 'DownThemAll!'. Could there be a way to allow rechecking a window title and applying new rules a set amount of time after a window spawns?

> i.e. For firefox windows, set new window to float on spawn, wait 1.5 seconds, then apply new window title rule.

We may want to just re-apply rules for a specific window when the title of that window changes. Not sure if this has any drawbacks that we should be aware of.

-----------------

Extracted from #15 

There does not seem to be any immediate drawbacks to this, and should probably be implemented.

**Comment by natsumi** [comment]
I believe this happens with Google Chrome whenever you open the Developer Tools.  Been looking for a fix for this.

**Comment by koekeishiya** [comment]
Implemented on master.

Tested using following rules:
```
chunkc tiling::rule --owner Firefox --name GitHub --state float
chunkc tiling::rule --owner Firefox --except GitHub --state tile
```
Open firefox (should tile by default). Navigate to https://github.com. Window will now be made floating. Open a new tab, window will tile again.
