### ISSUE TITLE
[plugin|tiling] Safari Status Bar tiles with rule to always tile Safari

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/chunkwm#202]
Rule:
```
chunkc tiling::rule --owner Safari --state tile
```

Steps to reproduce:
- Enable `Menu Bar > View > Show Status Bar`
- Move mouse over any link, the link preview (showing the target) will tile

**Comment by koekeishiya** [comment]
Can't really fix this. Rewrite the rule to also filter on roles to avoid this.

On Aug 23, 2017 11:39 PM, Dominik Lohmann <notifications@github.com> wrote:

Rule:

chunkc tiling::rule --owner Safari --state tile


Steps to reproduce:

  *   Enable Menu Bar > View > Show Status Bar
  *   Move mouse over any link, the link preview (showing the target) will tile

**Comment by dominiklohmann** [comment]
```
chunkc tiling::rule --owner Safari --subrole AXStandardWindow --state tile
```

That worked.

Thanks!
