### ISSUE TITLE
Confusing focus behavior

### ISSUE THREAD

**Issue by issmirnov** [koekeishiya/chunkwm#203]
I have three monitors set up side by side, running 10.12.5 at the moment. I've noticed some odd mouse following focus behavior.

Setup: I have chrome open on the middle monitor (2), workspace 1, as well as the right monitor (3), workspace 1. I have a non chrome app on the second workspace on monitor 2. I use `ctrl + alt + right` to cycle the spaces on monitor 2 by one, so I now move from chrome to my other app. Mouse stays on monitor (2). So far so good

The problem: When I repeat `ctrl + alt + right` and cycle to a third space on monitor 2 (which is empty) my mouse jumps to the chrome window that's still sitting on monitor (3). 

I've tried changing the `window_focus_cycle ` setting but it doesn't appear to have an effect.

I have `chunkc core::load ffm.so` included in my `chunkwmrc`

Any thoughts?

**Comment by koekeishiya** [comment]
Probably same problem as #153 

Bascially, macOS does a lot of stupid things to try and act smart, and so far it doesn't look like something we can actually override.

**Comment by issmirnov** [comment]
Understood, subscribed to the other issue.
