### ISSUE TITLE
new release not working compare to June version

### ISSUE THREAD

**Issue by wxmtech** [koekeishiya/chunkwm#205]
I compiled commands and config the files around June, chunkwm is working very well with khd.
I installed the newest tap via homebrew, with the original config files, it said connection failed.
Then I just cloned the repository and compiled the commands and move to /usr/local/bin, still same errors, connection failed when loading tilingrc.
I rolled back to the june compiled ones with same config files, it is working, I really don't know the reason behind that.

**Comment by dominiklohmann** [comment]
The default plugin directory changed with the 0.2.30 release.

Assuming a default homebrew installation, change it to
```
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
```

**Comment by koekeishiya** [comment]
If your previous version was around *June*, there has been structural changes since.

I merged https://github.com/koekeishiya/chunkwm/pull/100 first of July.

**Comment by wxmtech** [comment]
Thank you @dominiklohmann @koekeishiya , checked the new syntax, there's a bit difference on the config files as well as khd, did some modifications, it is working now, thanks for your help.
