### ISSUE TITLE
Can I disable "focus on hover"?

### ISSUE THREAD

**Issue by sunqingyao** [koekeishiya/chunkwm#208]
Say I have two windows: A and B. When I move the mouse from A to B (not that I didn't click B; just hover on it), B would be focused automatically.

How can I change this behavior? I want A to stay focused when I hover the mouse on B

**Comment by dominiklohmann** [comment]
Edit your `.chunkwmrc` and remove this line:

```
chunkc core::load ffm.so
```

ffm is short for focus-follows-mouse, which is a plugin you may opt not to run.

**Comment by sunqingyao** [comment]
Ah thank you! Please consider making the document a little bit clearer about this :)

**Comment by Alok** [comment]
+1 to ^. I had no idea what FFM was.
