### ISSUE TITLE
neofetch incorrectly report the WM to be kwm instead of chunkwm

### ISSUE THREAD

**Issue by sunqingyao** [koekeishiya/chunkwm#209]
While this might be a bug of `neofetch`, I think you should take a look

![screen shot 2017-08-30 at 21 24 28](https://user-images.githubusercontent.com/13443062/29874575-c9060ef0-8dc9-11e7-9e6c-21ebc1f5cbfd.png)

**Comment by dominiklohmann** [comment]
See https://github.com/dylanaraps/neofetch/pull/785 – I noticed this a while back and fixed it, submitted a PR and it got merged, but there has not been a new release yet. It should work just fine if you install from master.

**Comment by sunqingyao** [comment]
@dominiklohmann That's great, thanks for your timely response!
