### ISSUE TITLE
images

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#21]
<img width="800" alt="screen shot 2017-02-24 at 18 25 37" src="https://cloud.githubusercontent.com/assets/6175959/23313599/acf600e2-fabe-11e6-889f-3b0ff20db510.png">

**Comment by piotryordanov** [comment]
What's the color scheme used in vim? :D

**Comment by koekeishiya** [comment]
@piotryordanov 

I made my own theme, which can be found here: https://github.com/koekeishiya/dotfiles/blob/master/nvim/colors/koe.new.vim

Terminal colors are defined here: https://github.com/koekeishiya/dotfiles/blob/master/kitty/kitty.conf#L140

**Comment by piotryordanov** [comment]
Nice, thx! What terminal are you using? Can the kitty theme be used on iterm, or will I need to convert it to an iterm theme?

Thx :)

**Comment by koekeishiya** [comment]
The terminal I use is kitty: https://github.com/koekeishiya/kitty, forked from https://github.com/kovidgoyal/kitty

You probably have to take the color hex-codes and place them in your iTerm profile color-section manually.

**Comment by gerd2002** [comment]
Is it possible to remove the window bar in any program or just in kitty?

**Comment by dominiklohmann** [comment]
> Is it possible to remove the window bar in any program or just in kitty?

See issue #253.

**Comment by janniks** [comment]
What are you using for the top and bottom bar in the first screenshot?

Music and menu bar, etc.

**Comment by koekeishiya** [comment]
@janniks 

https://github.com/koekeishiya/Statusbar

**Comment by piclemx** [comment]
@koekeishiya how can I got the same look that your first image in this issue?

**Comment by koekeishiya** [comment]
I use https://github.com/koekeishiya/Statusbar to create the top and bottom menubar. The macOS Menubar and Dock are both set to autohide (in System Preferences).

The terminal I use is https://github.com/kovidgoyal/kitty which is really fast, and quite customizable.
There is an option there to hide the titlebar, which I use. Terminal colors are defined here: https://github.com/koekeishiya/dotfiles/blob/master/kitty/kitty.conf#L147

The editor is neovim, using my custom theme that can be found here: https://github.com/koekeishiya/dotfiles/blob/master/nvim/colors/koe.new.vim

**Comment by georgenica** [comment]
@koekeishiya I see no mention of the gorgeous font, what font is it?

**Comment by nakrule** [comment]
I'm trying to copy your Vim colorsheme, but even after tweaking the .vim to use the color from your terminal dot file, it look far different from your screenshot. Any idea ?
