### ISSUE TITLE
chunkwm-border blocking Grab (macOS's native screenshot taker)

### ISSUE THREAD

**Issue by sunqingyao** [koekeishiya/chunkwm#210]
This is the screenshot taken by <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>3</kbd>

![screen shot 2017-08-30 at 21 31 31](https://user-images.githubusercontent.com/13443062/29874861-9bfc0792-8dca-11e7-9c24-ea2a4efd6978.png)

and this is the screenshot taken by <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>4</kbd> followed by <kbd>space</kbd>

![screen shot 2017-08-30 at 21 31 21](https://user-images.githubusercontent.com/13443062/29874920-cf7bb6d0-8dca-11e7-8a86-73c430dd44be.png)

As you can see, when I try to take a screenshot for a single window, only its border is captured.

**Comment by dominiklohmann** [comment]
Duplicate of #98.

Add this to your `.khdrc` file:
```
cmd + shift - 4 -> : chunkc border::clear
```

**Comment by sunqingyao** [comment]
My bad, I should have searched through the issues before opening a new one!
