### ISSUE TITLE
[plugin|tiling] move windows through dock extension instead of AX API (optional)

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#212]
The AX API for moving windows is slow as ****. See #211 

We can use *chwm-sa* to call *CGSMoveWindow* instead, which is a lot more responsive and (seemingly) uses less resources.

By using this API, the move operation we perform (in the case of #211) behaves exactly the same as when dragging a window by its titlebar.

**Comment by crisidev** [comment]
Does this require a full chwm-sa reinstall? I mean all the codesigning + disabling system protection part.

**Comment by koekeishiya** [comment]
Yeah, had to update chwm-sa. It is only used by mouse-drag as of now though

**Comment by dominiklohmann** [comment]
There also is a `CGSSetWindowShape `, could this possibly be used to resize windows smoothly (and move them at the same time)?

```objc
CGS_EXTERN CGError CGSSetWindowShape(const CGSConnectionID cid,
    CGSWindowID wid, const CGSCoord xOffset, const CGSCoord yOffset,
    const CGSRegionObj shape);

// Create CGSRegionObj from CGRect
CG_EXTERN CGError CGSNewRegionWithRect(const CGRect *rect, CGSRegionObj *outRegion);
```

**Comment by koekeishiya** [comment]
*CGSSetWindowShape* doesn't appear to do anything, sadly.

**Comment by dominiklohmann** [comment]
Ah too bad. Was just looking through the symbols in Skylight.framework and this sounded interesting.

**Comment by dominiklohmann** [comment]
There's also `WSShapeWindow` and `WSShapeWindowWithRect`, but I haven't yet dug into the functions with the WS Prefix (Window Server?) enough to find their signature. Have you experimented with any of these functions?

**Comment by koekeishiya** [comment]
There is also `CGSShapeWindow` but I'm apparently not passing it the correct parameters.

I know so far that it takes. `CGSShapeWindow(CGSConnectionID cid, CGSBackingStore bs, ???)`

I tried calling it as follows: `CGSShapeWindow(cid, 2, region, wid)`. Although it does not crash, noting happens. 

I haven't seen any of the `WS` functions before.

**Comment by dominiklohmann** [comment]
The WS and SLS functions are in `Skylight.framework`, which is what Dock seems to use.

```
nm -gU /System/Library/PrivateFrameworks/SkyLight.framework/SkyLight
```

**Comment by koekeishiya** [comment]
A lot of the *CGS* functions seem to just call the corresponding *SLS* function.
When I triggered a crash in the `CGShapeWindow` function I mentioned above, the trace showed a call to `SLSShapeWindow`

**Comment by choco** [comment]
I was curious so I tried and indeed it is possible to use the two functions above to resize a window, but this is probably a dead end. The backing window is resized, but NSThemeFrame which is basically the view that performs the window drawing, doesn't resize, making it practically useless, and by giving a quick look there nothing that we can do.
What I'm saying is that Cocoa takes care of creating the window and a resize in the upper level leads to a CGSShapeWindow call, but modifying a window backing under it's nose from the window server side isn't supported. That the same problem as the spaces API, they are used by the Dock which also has its internal structure, modifying shit from the window server isn't automatically updated in the app.
