### ISSUE TITLE
Brew Services Interaction Not Working

### ISSUE THREAD

**Issue by Eymantia** [koekeishiya/chunkwm#215]
Whenever I attempt to run 'brew services start/stop/restart/update chunkwm' it returns this: 

https://pastebin.com/X10jDqst

Last time this worked was around 08/30/2017, first noticed 08/31/17.

Screenshot: http://prntscr.com/gfnx5o

**Comment by crisidev** [comment]
You have local modification in the brew tap. Please uninstall chunkwm, untap crisidev/homebrew-chunkwm, tap it again and reinstall. the issue will go away.

**Comment by Eymantia** [comment]
Followed instructions, no longer receiving errors. However, chunkwm is no longer functioning as a tiling window manager. I can start it, and nothing out of the ordinary is returned, but there is no border on windows (I didn't set width to 0), and no tiling is occurring.

Screenshot: http://prntscr.com/gfwjii

**Comment by crisidev** [comment]
So, recent changes on the formula modified the plugin directory. Check if the plugin directory from your config file matches with the one installed by brew. This should be the problem you are experiencing.

**Comment by dominiklohmann** [comment]
The change of plugin directory is on me... the original directory was not allowed as per Homebrew guidelines, so I changed it. I assumed that to be fine since chunkwm is still not labeled stable and it is certainly better to change now instead of later on. 

The example `.chunkwmrc` file that ships with the current Homebrew install should contain the proper plugin directory path, you need to change it accordingly. With a default Homebrew installation, this should do the trick:
```
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
```

**Comment by koekeishiya** [comment]
> I assumed that to be fine since chunkwm is still not labeled stable and it is certainly better to change now instead of later on.

Just to add to this; While chunkwm is rather stable in terms of usage, I don't consider the design final and I want to be able to do breaking changes in the future if necessary, which is why I keep it in the alpha stage.

**Comment by Eymantia** [comment]
> The example .chunkwmrc file that ships with the current Homebrew install should contain the proper plugin directory path, you need to change it accordingly.

How does one go about changing this?

**Comment by dominiklohmann** [comment]
> How does one go about changing this?
Edit `~/.chunkwmrc`, find the line that defines the `plugin_dir` and change it to the line in my above post. Save the file, then restart chunkwm using `brew services restart chunkwm`.

**Comment by Eymantia** [comment]
Okay, it worked. Thanks so much!
