### ISSUE TITLE
random resizing

### ISSUE THREAD

**Issue by Alok** [koekeishiya/chunkwm#216]
I often have 2 windows open, and sometimes  one is suddenly resized to half its current height. Hiding the window and showing it again doesn't always help.

**Comment by koekeishiya** [comment]
What's the output of: `chunkc tiling::query --desktop windows` when this happens?

Knowing which applications are running at the time also helps, as some of them create "invisible" windows for whatever reason, which show up in the APIs and mess with us (Steam is an example of this).

**Comment by Alok** [comment]
looks like invisible windows. when i hit the 'media next' button (f9 for me), spotify seems to create an invisible window.
