### ISSUE TITLE
Tiling: option to let windows from same application share same region

### ISSUE THREAD

**Issue by kvcrawford** [koekeishiya/chunkwm#219]

**Comment by dominiklohmann** [comment]
Do you mean monocle subtrees? As in BSP tree nodes that can hold multiple windows in a subtree (and display one at a time), similar to a monocle space?

See https://github.com/koekeishiya/chunkwm/issues/2#issuecomment-280854480
> Monocle-subtrees for binary space partitioned spaces is not something that is going to be implemented.

**Comment by kvcrawford** [comment]
Yes, I believe that's what I mean. Disappointing that it's a "won't implement." Is there some complexity that makes implementation difficult?

FWIW I'm mostly concerned with windows of the  same application. I often think of separate windows as separate "workspaces" (e.g. projects in a code editor, topics of research in a web browser, etc.), and I can quickly cycle through them with native ``cmd+` ``.

**Comment by koekeishiya** [comment]
The idea itself is interesting,  but I find the actual usability to be poor on macOS. If we could have a stacked mode the way *i3*  does it, it would be done. See test implementation in *kwm* for reference.

As for complexity; Getting windows to tile in the same region is fine. Finding a good way to interact with both the new and existing system that makes sense, is user friendly and unambigious, is hard.
Failing the latter made me barely use the feature in *kwm*.

I probably will not be implementing this, but that should't stop other people from trying.

**Comment by kvcrawford** [comment]
Yeah, if you think of it as a monocle subtree in a pure sense, then that is indeed a difficult problem to solve for—though it would be powerful.

But I think it could be kept very simple and still solve for my use-case

```
# Stack windows of the same applications in the same region
chunkc set stack_same_application_windows true

# Or only apply to specific applications
chunkc tiling::rule --owner \"Sublime Text\" --stack-windows true
```

I personally wouldn't want the windows at the bottom of the stack peeking up at the top. I just `` cmd+` `` to cycle through them.

**Comment by srob650** [comment]
+1 for this request, and if you felt we needed to differentiate between a stacked tile and a single tile you could alter the border slightly for stacked tiles.

**Comment by dominiklohmann** [comment]
> alter the border slightly for stacked tiles

I'm all for monocle-subtrees iff they are implemented better (as in consistent with focus commands) than Kwms, but I think the tiling plugin should stay separate from the border plugin.

**Comment by koekeishiya** [comment]
As quoted by dominiklohmann above; my opinion on this has not changed. This will most likely not be implemented upstream.

**Comment by koekeishiya** [comment]
Decided that this is not happening upstream, sorry!
