### ISSUE TITLE
[plugin|tiling] mouse-drag - interchange left and right button

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#220]
Extracted from [here](https://github.com/koekeishiya/chunkwm/issues/146#issuecomment-327150388)

---------

It is currently not possible to interchange left and right mouse buttons. 
The reason for this is that they are two separate event types, and both have a "special" case in their callback.

```
       case kCGEventLeftMouseDown:
        {
            CGEventFlags Flags = CGEventGetFlags(Event);
            if(((Flags & MouseModifier) == MouseModifier) &&
               (ResizeState.Mode == Drag_Mode_None))
            {
                LeftMouseDown();
                return NULL;
            }
        } break;
        case kCGEventLeftMouseDragged: { LeftMouseDragged(); } break;
        case kCGEventLeftMouseUp: { LeftMouseUp(); } break;
        case kCGEventRightMouseDown:
        {
            CGEventFlags Flags = CGEventGetFlags(Event);
            if(((Flags & MouseModifier) == MouseModifier) &&
               (ResizeState.Mode == Drag_Mode_None))
            {
                RightMouseDown();
                return NULL;
            }
        } break;
        case kCGEventRightMouseDragged: { RightMouseDragged(); } break;
        case kCGEventRightMouseUp: { RightMouseUp(); } break;
```

The only way I see this happening is that we require the actions to be bound, using two cvars:
`chunkc set window_mouse_move fn left_mouse`
`chunkc set window_mouse_resize fn shift left_mouse`

In our callback above, we have to combine left + right events of each category:
```
case kCGEventLeftMouseDown:
case kCGEventRightMouseDown:
{
    // match flags and button with cvars
} break;
```

In addition, the handlers must be combined to single functions and switch based on event-type (*window_mouse_move* and *window_mouse_resize)*.

**Comment by koekeishiya** [comment]
implemented on master.

set binding for moving windows with the mouse:
`chunkc set mouse_move_window \"shift 1\"`

set binding for resizing windows with the mouse:
`chunkc set mouse_resize_window \"ctrl shift 1\"`

to disable the action, use *none*

`chunkc set mouse_move_window "none"

**Comment by koekeishiya** [comment]
docs in tiling README: https://github.com/koekeishiya/chunkwm/tree/master/src/plugins/tiling#set-binding-to-use-for-moving-windows-with-the-mouse

**Comment by kirkegaard** [comment]
Thank you so much for this!! <3

**Comment by koekeishiya** [comment]
Uh, that would be because the default binding for *mouse_move_window* is `fn 1`, so that probably overrides your *mouse_resize_window* if you don't explicitly unbind it. I should probably figure out a way to handle that scenario.
