### ISSUE TITLE
Respect XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by OJFord** [koekeishiya/chunkwm#222]
Are you open to having chunkwm respect [the XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), at least as far as the `.chunkwmrc` configuration file?

This would mean that if the environment variable `XDG_CONFIG_HOME` is set, the files would be located at `$XDG_CONFIG_HOME/chunkwm/.chunkwmrc` (by which point, due to having its own namespace, many tools name it simply 'config').

The specification also says that the fallback (when the env var does not exist) is `$HOME/.config/chunkwm/` - but I'm not so bothered about that, nor do I expect other `XDG_CONFIG_HOME` users would be.

**Comment by koekeishiya** [comment]
I probably will not make any changes here. There are so many "standard" variations of where the config should go that I will not even try to support all these methods. The "standard" on macOS as far as I can tell would be something like  `~/Library/Application Support/chunkwm/config`

You can always edit the .plist or launch script to use the  `--config` argument to specify the location as requested in #96

**Comment by koekeishiya** [comment]
Closing this for now.
