### ISSUE TITLE
[plugin|ffm] Exceptions for FFM

### ISSUE THREAD

**Issue by CarlosEvo** [koekeishiya/chunkwm#226]
I hope there is an implementation for setting rules for FFM, because ffm messes with certain Apps like [PopClip](http://pilotmoon.com/popclip/).

In the PopClip case, the text selection is rendered unusable once chunkwm puts focus on PopClip, which is supposed to process the text.

I don't think the functionality is implemented or documented. I would really appreciate it if the function could be implemented or if anyone can tell me how to set the rules. Thank you!

**Comment by koekeishiya** [comment]
Fixed on master. Tested using trial version of popclip.
