### ISSUE TITLE
Tiling not working on Desktop 2

### ISSUE THREAD

**Issue by evanrlong** [koekeishiya/chunkwm#227]
For some reason, tiling of applications is not working for me exclusively on Desktop 2 of my main laptop monitor.  All applications scale as if they are the only app on the page and they stack on top of each other instead of tiling next to each other properly.  Tiling works well on every other desktop except Desktop 2.  I have tried deleting and recreating my desktops and restarting chunkwm/my computer but the issue keeps occurring.  If you need any other diagnostic info, let me know and I will provide it.

![chunkwm_desktop_bug](https://user-images.githubusercontent.com/3453944/30516853-a5cdbbae-9b07-11e7-9a8c-07bd07b0bf3b.gif)

**Comment by koekeishiya** [comment]
Remove line #22 (https://github.com/koekeishiya/chunkwm/blob/master/examples/chunkwmrc#L22) in your config file. Probably want to check the other settings as well.

**Comment by evanrlong** [comment]
Thanks that did the trick!  The help for the chunkwm novice is appreciated and the window manager is amazing so far.
