### ISSUE TITLE
Automatically add padding for the Dock

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#23]
If the Dock does not have auto-hide enabled, we try to detect the orientation and size and automatically add padding in the appropriate direction.

**Comment by dominiklohmann** [comment]
> TODO(koekeishiya): is the Dock only ever visible on the primary display when autohide is disabled?

If the dock is set to the left side, it only appears on the leftmost monitor.

If the dock is set to the right side, it only appears on the rightmost monitor.

If the dock is set to the bottom side, it appears on the active monitor.

**Comment by koekeishiya** [comment]
> If the dock is set to the bottom side, it appears on the active monitor.

What would be the expected behaviour at this point. Apply the Dock padding to all monitors?

**Comment by dominiklohmann** [comment]
> If the dock is set to the bottom side, it appears on the active monitor.

Correction: it appears on what is set as the main monitor in display preferences. It's only the active monitor when autohide is enabled. Sorry for the confusion.

**Comment by koekeishiya** [comment]
> it appears on what is set as the main monitor in display preferences. It's only the active monitor when autohide is enabled. Sorry for the confusion.

I seem to be able to get the Dock to move to any monitor I want without having the autohide option enabled, but not completely sure how / why it happens yet.

On MacOS Sierra (10.12.3)
