### ISSUE TITLE
[plugin|tiling] Query display enhancements

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/chunkwm#230]
I'm currently rewriting my config files to be independent of my setup (2 monitors at home, 1 monitor otherwise), and I've run into an issue where I want to query my active display count.

As a workaround, I am using `system_profiler SPDisplaysDataType | grep "Online: Yes" | wc -l | xargs`, which works just fine, but is notably slow.

There are two solutions to my problem:

1. Query display id from desktop id
```
chunkc tiling::query --display for-desktop id
```
2. Query display count
```
chunkc tiling::query --display count
```

I think both of these have their use case and would like to see them implemented.

**Comment by crisidev** [comment]
I am doing the same as you do. I have a python script which handles chunkwm +skhd configuration depending where I am and how many monitor I have. This script triggers the rebuild of configs based on jinja templates.

The display counter part is the same trick you use and it is pretty slow as well on my machine..

**Comment by koekeishiya** [comment]
You can query the number of active displays using: `chunkc tiling::query --monitor count`
Getting the monitor for a desktop might happen at a later time.

**Comment by koekeishiya** [comment]
See my latest comment https://github.com/koekeishiya/chunkwm/pull/171
Does that sound reasonable regarding the above request?

**Comment by dominiklohmann** [comment]
Yes, that sounds reasonable. Didn't even see the PR. Feel free to close this.
