### ISSUE TITLE
Multiple accessibility requests

### ISSUE THREAD

**Issue by issmirnov** [koekeishiya/chunkwm#231]
After each `brew upgrade` flow, I get multiple accessibility requests. I'm not running `brew services restart chunkwm` manually, so IMO this dialog should only pop up once.

Not a huge deal, but wanted to flag anyway. Even after giving consent, the other 3-4 dialogs still stay up until you close all of them out.

For those looking for a quick workaround, you can code-sign the binary and avoid the prompts entirely.

**Comment by dominiklohmann** [comment]
This is actually explained in the brew formula caveats. 

```
This has to be done after every update to chunkwm, unless you codesign the
binary with self-signed certificate before restarting
  Create code signing certificate named "chunkwm-cert" using Keychain Access.app
  codesign -fs "chunkwm-cert" /usr/local/opt/chunkwm/bin/chunkwm
```

There is no way around the codesigning requirement, and once chunkwm is running as a brew service, it will restart until it has the permissions required, which is why you're getting multiple requests.

I have this in my .zshrc/.bashrc for easy upgrades:
```bash
function upgrade-chunkwm() {
    brew reinstall --HEAD chunkwm
    codesign -fs "chunkwm-cert" $(brew --prefix chunkwm)/bin/chunkwm
    brew services restart chunkwm
}
```

**Comment by issmirnov** [comment]
>  it will restart until it has the permissions required, which is why you're getting multiple requests.

I figured it was something like this. It's not a huge dealbreaker by any stretch (I love the i3-wm feel this gives OSX) but if it's a simple fix would be cool to see this. I don't know the optimal approach, but something like a 60 second backoff on restarts would be good. If I as a user grant permissions to chunkwm, it's fair to expect that the user will manually run `brew services start chunkwm` to get it going.

Thanks for the alias! I'm a huge fan of automation, so will happily use that.

**Comment by dominiklohmann** [comment]
> I don't know the optimal approach, but something like a 60 second backoff on restarts would be good

I wouldn't consider this optimal because it has downsides if chunkwm crashes within that time limit, but you can do this.

Run `brew edit chunkwm` and add this to both launchd files.
```plist
<key>ThrottleInterval</key>
<integer>60</integer>
```

After that reinstall with your edited formula and launchd will have a 60 second throttle on keep-alive.

**Comment by issmirnov** [comment]
Great, that works. Thanks!
