### ISSUE TITLE
focus west/north/... is slow, about 1 second to switch

### ISSUE THREAD

**Issue by jwkvam** [koekeishiya/chunkwm#232]
I'm using skhd with chunkwm. I am using essentially the default configs for both. In particular these binds:
```
alt - h : chunkc tiling::window --focus west
alt - j : chunkc tiling::window --focus south
alt - k : chunkc tiling::window --focus north
alt - l : chunkc tiling::window --focus east
```
I'm using the stable versions for each from homebrew, 0.2.32 chunkwm and 0.0.8 for skhd. It's built with all plugins, but I disabled loading `ffm.so`. Any ideas on how I can further debug?

**Comment by koekeishiya** [comment]
what shell are you using? echo $SHELL

**Comment by jwkvam** [comment]
I'm using fish from homebrew v2.6.0. Is there a way to run chunkwm through another shell?

**Comment by koekeishiya** [comment]
the issue is with skhd, not chunkwm. you can make skhd use bash or some other shell by overriding the $SHELL environment variable for skhd upon launch.

**Comment by jwkvam** [comment]
Thanks that fixed it and thanks for the quick response!

**Comment by ricelid** [comment]
Hi, how do I control the environment variables when skhd is started by "brew services"?

**Comment by ricelid** [comment]
I guess you need to edit this file?
https://github.com/koekeishiya/homebrew-formulae/blob/master/skhd.rb

Would you be open to making that change? If so, should I open an issue against skhd?

**Comment by dominiklohmann** [comment]
Just run `brew edit skhd` before installing and change this 

```plist
<key>EnvironmentVariables</key>
<dict>
    <key>PATH</key>
    <string>#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
</dict>
```

to

```plist
<key>EnvironmentVariables</key>
<dict>
    <key>PATH</key>
    <string>#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    <key>SHELL</key>
    <string>/bin/bash</string>
</dict>
```

**Comment by Kryan90** [comment]
Had the same issue using zsh

How to fix:
brew services stop skhd
edit /usr/local/Cellar/skhd/0.0.10/homebrew.mxcl.skhd.plist, add the SHELL key
```
<key>EnvironmentVariables</key>
<dict>
    <key>PATH</key>
    <string>#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    <key>SHELL</key>
    <string>/bin/bash</string>
</dict>
```
brew services start skhd

**Comment by ccwanggl** [comment]
> Had the same issue using zsh
> 
> How to fix:
> brew services stop skhd
> edit /usr/local/Cellar/skhd/0.0.10/homebrew.mxcl.skhd.plist, add the SHELL key
> 
> ```
> <key>EnvironmentVariables</key>
> <dict>
>     <key>PATH</key>
>     <string>#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
>     <key>SHELL</key>
>     <string>/bin/bash</string>
> </dict>
> ```
> brew services start skhd

make sense for me, thank you very much!!
