### ISSUE TITLE
[plugin|tiling] chunkc tiling::monitor --focus next|prev has no option to wrap

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/chunkwm#234]
Used upgrading to High Sierra as an excuse to upgrade to chunkwm, great work on this. Seems superior to kwm

I've looked though the docs of chunkwm many times and can't seem to figure this out. In kwm I was have to issue a monitor focus prev/next command and it would wrap around if it was the last/first monitor and focus _something_. 

In chunkwm `chunkc tiling::monitor --focus next` does not seem to wrap. I have to try both next/prev till I find the direction I need to go in. 

Is there an option to allow wrapping that I missed? 

This is the only issue i've found so far, which is a really great sign. 

Thanks a bunch!

**Comment by chrishoage** [comment]
Ah, just noticed this is tied to `window_focus_cycle`. 

Would you consider splitting these into to settings?

`window_focus_cycle` and `monitor_focus_cycle` (or `display`, whatever fits other settings)

I personally dislike focus to wrap between monitors, but do like having focus wrap when focusing an entire monitor. 

This is a pretty small deal, so feel free to close if this is out of scope

**Comment by koekeishiya** [comment]
I think this makes sense, but there are bigger issues that should probably be resolved first (#153)

**Comment by koekeishiya** [comment]
I have no idea how to even fix the referenced issue, as it is forced behaviour by macOS.
Figured I'd at least implement this. I have not tested this personally, but it should work.

`chunkc set monitor_focus_cycle 1 | 0`

**Comment by braham-snyder** [comment]
FWIW: I can confirm `monitor_focus_cycle` permits focus commands to cycle/wrap over monitors

**Comment by chrishoage** [comment]
I too confirm this works. Please feel free to close at your discretion
