### ISSUE TITLE
homebrew log permission / service hangs at start

### ISSUE THREAD

**Issue by kidpixo** [koekeishiya/chunkwm#238]
First thing first: thanks @koekeishiya for you wonderful work!

I installed chunkwm via homebrew ( the normal release and also the HEAD) and I got the `chunkc: connection failed!` . 

After debugging the typical stuff ( ~./chinkwmrc not executable , hand wokr on plist  etc etc) I discovered the problem was I had no permission to write in the log folder defined in the homebrew formula `/usr/local/var/log/chunkwm/`.

This is typical because I have a machine from work and they enforce to have an user with "Administrative" (~ sudoer but not exactly the same) and a "Normal" user (not sudoer).

The "Administrative" one install stuff and give some privileges to the "Normal" to run stuff in ` /usr/local/bin/` (standard homebrew root), but not to write in the ``/usr/local/var/log/`. 

This crashes the chunkwm service to start and stop log files to be written! An option would be to write in standard log directory (`/var/log` or `~/Library/Logs/`) or use `/tmp/`.

I know this is more related to [crisidev/homebrew-chunkwm](https://github.com/crisidev/homebrew-chunkwm), but could be a useful reference here.

**Comment by kidpixo** [comment]
Totally agree, it was just to help people like me :-D

**Comment by koekeishiya** [comment]
Seems like this was resolved in the homebrew-repo. Closing.
