### ISSUE TITLE
Chunkc not found

### ISSUE THREAD

**Issue by nihal127** [koekeishiya/chunkwm#239]
When I type anything into my terminal (Hyper.app if it helps), I always get `zsh: command not found: chunkc`. I have also tried with `bash` but it still doesn't work

**Comment by dominiklohmann** [comment]
1. Check if the installation via Homebrew succeeded
```bash
ls $(brew --prefix)/bin/chunk*
```

2. Check your `$PATH`: it should contain the directory that `chunkc` and `chunkwm` are in (usually `/usr/local/bin`)
```bash
echo $PATH
```

**Comment by nihal127** [comment]
I tried step one and nothing came up however tiling still occurs. I get the error for any input but don't have anything like `launchctl debug ...`. The error still occurs when I run `env -i zsh --no-rcs` / `env -i bash --noprofile --norc`.

**Comment by dominiklohmann** [comment]
Run `brew link --force chunkwm` if step one returned nothing.

**Comment by koekeishiya** [comment]
Is this still an issue or can it be closed?
