### ISSUE TITLE
universal "picture in picture"

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#24]
The picture in picture mode added in Sierra for videos playing through iTunes or Safari would be a neat feature to have for any kind of application.

With the scripting addition that extends the dock  to modify window layers, we should be able to replicate this kind of a feature. We should be able to make a certain window appear on all spaces, as well as have it appear as topmost. We could then offer ways to specify which corner it should appear in, as well as the size.

**Comment by koekeishiya** [comment]
This is sort of now possible with the following setting enabled in *.chunkwmrc*:

`chunkc set window_float_topmost 1`

Focus the window in question, and hit a bind that runs the command:
`chunkc tiling::window --toggle sticky`

The window will now be shown on all desktops, and be topmost.
You can then resize the window using `chunkc tiling::window --warp-floating pip-right`.

By combining the above two commands, you can have a window "enter pip mode" with a single bind:
```
alt -s : chunkc tiling::window -t sticky; chunkc tiling::window -W pip-right
```

**Comment by natsumi** [comment]
@koekeishiya that seems like a very useful tip.  Any thoughts on adding "cookbook" style usage tips to the Wiki?

**Comment by koekeishiya** [comment]
Will probably do that at some point. No ETA just yet though.

If you have tips you want to share, feel free to create an *issue* and I'll label it.
