### ISSUE TITLE
[plugin|tiling] Consider matching kwm for mouse follows focus behavior

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/chunkwm#242]
https://github.com/koekeishiya/chunkwm/issues/15#issuecomment-305706631

This is my own preferences leaking though, but this change in behavior is quite difficult for me to get used to. I often switch between using the keyboard and trackpad (mouse) quite a bit, and this change causes friction in how I use the mouse input. 

Consider this case: 

I have 4 windows all of the same application open. When I close one window with my mouse and start to drag the mouse over to the other side of the screen the mouse snaps to center of the next window. This interrupts where I was trying to go with my mouse and  causes me to have to try again. 

Due to this behavior uninterrupted mouse movement is not possible when closing windows with the mouse. 

I would like matching the behavior in kwm to be considered: _Only_ triggering mff when a chunkwm focus command is what caused the focus change. There are lots of things that cause focus to change in macOS (closing a window being a big one) and having _any_ of those focus events cause mff to trigger is kinda frustrating. 

I'm open to suggestion for other ideas, however I feel like the simplest and easiest thing to implement would be to only trigger mff when chunkwm issues a focus command. 

There could even be a command that cycles focus between windows of the same application similar to  ```cmd + ` ```. This would allow focus to be given to the window though chunkwm and trigger mff. 

`alt + tab` is quite a bit tricker, maybe it would be possible to offer a command that cycled though applications in a similar way - just with no UI. 

If you are dead set on how mff is implemented in chunkwm please feel free to close this issue. 

(This is fairly low priority, while it is annoying I will survive. If you decide that the behavior should be addressed please chuck this at the bottom of the pile)

Thanks!

**Comment by koekeishiya** [comment]
I don't really have any opinions on this. I have no problems with ffm only triggering on focus commands issued by chunkwm. 

I think this is a discussion that has to be between users of chunkwm, as seen in the comment thread you referenced, different people expect / want different things.

Doubt implementing something like *cmd + `* or *cmd + tab* is going to happen. I'd rather create a proper fuzzy-searchable window switcher that works across desktops in that case.

**Comment by crisidev** [comment]
I tend to agree with @chrishoage on the mff behavior. Some time the focus is set by other things and chunkwm's behaviour is not consistent.

Regarding ```cmd + ```` or ```cmd + tab```, I agree with @koekeishiya. A fuzzy window switcher would be awesome.

**Comment by chrishoage** [comment]
> Doubt implementing something like cmd + ` or cmd + tab is going to happen. I'd rather create a proper fuzzy-searchable window switcher that works across desktops in that case.

Sure, this was just a suggestion to emulate the current behavior and what I perceived a way to match the desired behavior for the change. 

If chunkwm could somehow tell the difference between a mouse close window event and a keyboard one that would work too. However that seems difficult to implement correctly, which lead me to the suggestion that only `chunkwm` issued focus command trigger mff.

**Comment by chrishoage** [comment]
I've been having trouble with MFF triggering when FFM causes a focus change. 

Since there hasn't been much discussion and you seemed amenable to changing the behavior of MFF maybe we should just move forward with it. 

The original reason for the change was to support MFF during ```cmd + ` ``` and `cmd + tab`. In my experience this can cause problems with applications that show system alerts.

**Comment by choco** [comment]
Personally I’m a fan of the current behaviour, and if there are any issue it would be better to approach them rather then move back to kwm behaviour.

**Comment by chrishoage** [comment]
I don't think the issue can be solved. 

Here is the case:

A application opens a system level alert dialog. This dialog is not able to be focused in the same way other windows can be focused. Due to the way tiling works this dialog will usually appear below other windows. So the only way to address this dialog is to move your mouse to where the dialog is behind the application window then alt tab to bring that dialog to the foreground. 

MFF gets in the way of this. See this video here: https://www.dropbox.com/s/vegvpxwakkshndy/cmdtab.mov?dl=0

(note: the video is a bit dated because chrome no longer opens alerts via the system alert dialog any more, but I have experienced this frustration with other applications)

If this is a super contentious issue maybe make it a setting (though I don't think we need _more_ settings. MFF should only be triggered by chunkwm focus requests)

**Comment by choco** [comment]
That seems an issue with `standby-on-float ` not getting triggered with alerts, not sure it is fixable but it's worth taking a look.

**Comment by chrishoage** [comment]
I don't think it's fixable because these alerts are not reported to chunkwm/kwm. There is no good way to target them with extra rules. 

There was a long thread in kwm about this very issue. 

There is further behavior issue where sometimes a FFM will trigger a MFF, which is probably a bug, but all of this goes way if only chunkwm issued focus commands trigger a MFF

Can you make the case for keeping `cmd + ` ``` and `cmd + tab` for trigger MFF. I don't see the value in it, maybe I'm missing a use case for it.

**Comment by chrishoage** [comment]
@koekeishiya Can we revert this change? 

Sometimes mouse follows focus is triggered when Mission control is open and it snaps to the wrong place. 

I feel that this behavior causes way more problems than it solves.

**Comment by koekeishiya** [comment]
I'll think about what to do about this; maybe make it a config option or something

**Comment by chrishoage** [comment]
It is much appricated. In theory having MFF trigger on any focus event should work fine, there are just tons of little edge cases that are difficult to account for.

**Comment by koekeishiya** [comment]
Changed config setting for mouse-follows-focus on master.

New:
```
chunkc set mouse_follows_focus <none | intrinsic | all>

none: disable mouse-follows-focus
intrinsic: only trigger from chunkwm commands (focus, swap, warp)
all: triggers from system-wide focus-change notifications (pre-commit behaviour)
```

**Comment by chrishoage** [comment]
@koekeishiya You rock, this works great. Thank you very very much!
