### ISSUE TITLE
Chrome becomes unresponsive when border plugin is disabled

### ISSUE THREAD

**Issue by ellipticaldoor** [koekeishiya/chunkwm#244]
I  commented the line

```
chunkc core::load border.so
```

Now the border plugin is deactivated but chrome behaves unresponsive, for example if you click the **watch** button in a github repo and hover the mouse over the options it looks like there is some delay.

**Comment by chrishoage** [comment]
I can no repo this issue for what its worth. 

Chrome seems responsive with and with out the border plugin enabled.

**Comment by ellipticaldoor** [comment]
well, for me introduces a lot of lag.
uhm, I don't care to leave it but when I disable borders like this
```
chunkc set preselect_border_width        0
chunkc set focused_border_width          0
```
it still appears a border of 1px

**Comment by chrishoage** [comment]
Well some more information would be helpful 

1. Does it happen with other applications
2. Does it happen when the window is floating
3. Does it happen when the window is floating and the setting for disabling borders when floating is enabled
4. What other browser interactions have a delay? Is it only things on web pages? Or does the chrome browser also have lag. 

I'm not doubting you experience what you're experiencing , simply saying this is not as trivial to reproduce as turning on the boarder and using chrome - as that works as expected for me

**Comment by ellipticaldoor** [comment]
It's random, sometimes happens and sometimes not... sorry for being so vague.

1. no
2. yes
3. yes
4. it's everything, even opening a new tab

**Comment by koekeishiya** [comment]
> well, for me introduces a lot of lag.
uhm, I don't care to leave it but when I disable borders like this

> chunkc set preselect_border_width        0
chunkc set focused_border_width          0

> it still appears a border of 1px

It's not technically possible to create a window with 0 width, which is what you are encountering here.
What you can do instead, is simply set the color to be transparent:
```
chunkc set focused_border_color 0x00000000
``` 
I would advice you to keep the preselect border color, if you utilize the manual insertion point logic, but ultimately that is your decision to make.

As for the actual issue you are experiencing. If you disable focus follows mouse (ffm.so) in your config file, does the problem still occur ?

**Comment by ellipticaldoor** [comment]
I don't know why but I'm not experiencing this bug any more, I hace ffm.so enabled

**Comment by koekeishiya** [comment]
Closing this. Feel free to reopen if you start experience the bug. I suppose this could be related to #247
