### ISSUE TITLE
[plugin|tiling] Desktop in bad state - no windows are being tiled

### ISSUE THREAD

**Issue by magicmark** [koekeishiya/chunkwm#245]
I think I've gotten myself into a bad state, where no windows are tiling.

Oddly, it *only* happens in one mission control "Desktop". If I try a different desktop, it works fine. This issue persists through chunkwm and khd restarts.

(Recording: https://imgur.com/0UCE8u2)

Happens with any window, not just iterm.

(Config is here: https://i.fluffy.cc/1tdPH0QlG0ScWSc7sWcHkBnk9XPFzzVW.html)

Any thoughts? Thanks!

**Comment by dominiklohmann** [comment]
From your config:
```
chunkc set 2_desktop_mode                monocle
```

Your second desktop is in monocle mode, which makes every window on the desktop use all available space. Focus commands simply cycle through windows in monocle mode.

**Comment by magicmark** [comment]
Derp, my fault for blindingly copying and pasting from the example config.

Thanks!
