### ISSUE TITLE
Failed to initialize daemon

### ISSUE THREAD

**Issue by crouse0** [koekeishiya/chunkwm#246]
Getting this message when trying to manually start the service.

### chunkwm: failed to initialize daemon! abort..
* * *
The service was working fine for several months until this morning where i noticed my windows were not being managed.  I reinstalled and now it will not start.  Any advice would be great.

**Comment by crisidev** [comment]
What is the output of 
```ps aux |grep chunkwm```

and the output of 
```brew services list```

?

**Comment by crouse0** [comment]
Resolved. 
$ brew services restart chunkwm # command will run without error, but does nothing
$ brew services restart crisisdev/chunkwm/chunkwm # this will restart the correct service

**Comment by Couto** [comment]
I'm having the same problem, however I'm using multiple user accounts on a laptop, where at least two of them use chunkwm.

When I run `ps aux |grep chunkwm` I get

```
couto             9638   0.0  0.4  2551008  32196   ??  S     1:13AM   0:00.50 /Users/couto/.homebrew/opt/chunkwm/bin/chunkwm
personal         11941   0.0  0.0  2432804   1972 s004  S+    1:18AM   0:00.00 grep chunkwm
```

Notice that I'm running this command on the `personal` account as you can see from the grep command in the ps results.

Also both accounts (couto and personal) have their homebrew folders in their home directory respectively, which means each user is calling a different chunkwm binary.

Do you have any ideas on how to fix this? I can try to provide more info if you wish to.

Could there be a conflict between accounts?

**Comment by koekeishiya** [comment]
I have not tried running it from multiple accounts, but yes I do believe that is the problem.
When you start chunkwm it tries to listen (locally) on port 3920. If some other instance of chunkwm is running on the computer, this port will already be taken and the new instance will fail to start.

**Comment by Couto** [comment]
@koekeishiya I'm still a bit newbie but is there a way to change the port? I'm trying to find info about but I'm not having much luck :(
