### ISSUE TITLE
How I can disable focusing on an app when I hover it with the mouse?

### ISSUE THREAD

**Issue by ellipticaldoor** [koekeishiya/chunkwm#248]
Float mode is really hard to use when the focus is following the mouse, can this be disabled?

**Comment by dominiklohmann** [comment]
In your `.chunkwmrc`, remove the line that loads the focus follows mouse plugin (`ffm.so`):
```
chunkc core::load ffm.so
```

**Comment by ellipticaldoor** [comment]
It worked :)

**Comment by ellipticaldoor** [comment]
How I can disable it only for float mode?

**Comment by dominiklohmann** [comment]
There is no such functionality. The closest thing you can use currently is to temporarily load and unload `ffm.so` or to hold down the mouse modifier key (default: <kbd>fn</kbd>) to temporarily disable focus follows mouse.

The focus follows mouse plugin is very simple and consists only of a single source file, which you can find here: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/ffm/plugin.cpp

**Comment by ellipticaldoor** [comment]
If I want to enable it only when fn is pressed how it can be?

**Comment by dominiklohmann** [comment]
https://github.com/koekeishiya/chunkwm/blob/719d31bc27905904055645e83b58360a05d35fe1/src/plugins/ffm/plugin.cpp#L122-L130

Negating the condition in that if statement checking the modifier should do it.

**Comment by ellipticaldoor** [comment]
so I should recompile the plugin?

**Comment by dominiklohmann** [comment]
Yes, and then copy the new `ffm.so` file into your plugin directory.

**Comment by ellipticaldoor** [comment]
okay thanks!

do you think that this feature can be added in a more elegant way in the settings?
maybe it's useful for someone more?

I can try to add it but I don't know objetive-c

thanks a lot for your help

**Comment by dominiklohmann** [comment]
Honestly, I don't really see the use case for having `ffm` only while a modifier key is held down. It's not any faster than clicking, and `ffm` is all about being faster and not having to click or press a key.

Maybe @koekeishiya thinks differently about this and makes it an option, I don't know. After all this is a really simple addition.

**Comment by ellipticaldoor** [comment]
Yes, but maybe adding more options makes the config more confusing.

An option to just enable it in some modes would be better I think

**Comment by ellipticaldoor** [comment]
Okay, I fixed it with bettertouchtool

![image](https://user-images.githubusercontent.com/3449006/31202728-b274f536-a95b-11e7-9762-9993b7e31aaf.png)

when I switch to bsp it loads ffm.so and when I change to monocle or float it's unloaded.
