### ISSUE TITLE
Missing command

### ISSUE THREAD

**Issue by jagajaga** [koekeishiya/chunkwm#249]
Hello! I can't find any command to make current window the main one in my tree of windows (make it the biggest). Am I missing something?

**Comment by koekeishiya** [comment]
This is not a thing yet, but it probably should be.

**Comment by koekeishiya** [comment]
implemented on master.

`chunkc tiling::window --focus biggest`
`chunkc tiling::window --swap biggest`
`chunkc tiling::window --warp biggest`

**Comment by jagajaga** [comment]
Thank you.
