### ISSUE TITLE
RC files not loaded when starting chunkwm via plist

### ISSUE THREAD

**Issue by sunjon** [koekeishiya/chunkwm#25]
Version: 0.0.10

When starting the wm via a plist (based on the template from kwm), the .chunkwmrc and .chunkwmtilingrc are not read/processed.

After sourcing them manually, windows get tiled by the tiling plugin, but some default margin/padding is applied, and not what is configured in the .chunkwmtilingrc.

**Comment by deathbeam** [comment]
I managed to get chunkwm working from .plist using this file (that I based on kwm example too):

~/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>homebrew.mxcl.chunkwm</string>
    <key>ProgramArguments</key>
    <array>
      <string>/bin/chunkwm</string>
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/chunkwm.out</string>
    <key>StandardErrorPath</key>
    <string>/tmp/chunkwm.err</string>
    <key>Debug</key>
    <true/>
    <key>EnvironmentVariables</key>
    <dict>
      <key>HOME</key>
      <string>/Users/Tomas/</string>
    </dict>
    <key>Sockets</key>
    <dict>
      <key>Listeners</key>
      <dict>
        <key>SockServiceName</key>
        <string>3020</string>
        <key>SockType</key>
        <string>dgram</string>
        <key>SockFamily</key>
        <string>IPv4</string>
      </dict>
    </dict>
  </dict>
</plist>
```

You need to change `HOME` there to your owm home folder and also `/bin/chunkwm` to correct patch to your `chunkwm` executable, but after that, it should work.

**Comment by koekeishiya** [comment]
This will all be sorted out when the first alpha goes live, should be soon ™
