### ISSUE TITLE
Border color is reset when focus changes between monitors

### ISSUE THREAD

**Issue by synthetiv** [koekeishiya/chunkwm#251]
Hi there,

I've been dealing with some confusing behavior for a few months now, and just finally realized what's going on: whenever focus changes from a window on one monitor to a window on another monitor, the border color reverts to the value given in the `focused_border_color` cvar, instead of retaining the last value set with the `chunkc border::color` command.

I'll try to explain why this has been bothering me: my default `focused_border_color` in .chunkwmrc is `0x00000000`, and I use two modes in khd: a default mode that mostly lets keypresses through normally, and another that lets me change window focus, size, etc. When the default mode is activated, khd issues `chunkwm border::color 0x00000000` to make the border invisible, and when the second mode is activated, it issues `chunkwm border::color 0xddff55aa` for a bright pink; that's how I distinguish between the two modes.

Until I made the changes to the border plugin given below, if I entered the second khd mode and switched to another monitor, the border color would be reset to `0x00000000`, which made it seem as though I'm in the first/default mode. I tried changing my border color cvar to that bright pink, but then if I was in khd's default mode and (god forbid :)) I used the _mouse_ to switch to an app on another monitor, then the border color would be set to bright pink, even though I was still in the default mode.

Anyway, FWIW, I hacked at the border plugin a little bit, and storing the most recent color in a static variable seems to work just fine for my purposes; I'm no C++ expert and I'm not intimately familiar with this code, so I bet this could be handled more elegantly, but this is working for me for now.

``` diff
diff --git a/src/plugins/border/plugin.mm b/src/plugins/border/plugin.mm
index bbf6325..2dc00b1 100644
--- a/src/plugins/border/plugin.mm
+++ b/src/plugins/border/plugin.mm
@@ -26,6 +26,7 @@ internal border_window *Border;
 internal bool SkipFloating;
 internal bool DrawBorder;
 internal chunkwm_api API;
+internal unsigned BorderColor;

 internal AXUIElementRef
 GetFocusedWindow()
@@ -49,10 +50,10 @@ GetFocusedWindow()
 internal void
 CreateBorder(int X, int Y, int W, int H)
 {
-    unsigned Color = CVarUnsignedValue("focused_border_color");
+    if(!BorderColor) BorderColor = CVarUnsignedValue("focused_border_color");
     int Width = CVarIntegerValue("focused_border_width");
     int Radius = CVarIntegerValue("focused_border_radius");
-    Border = CreateBorderWindow(X, Y, W, H, Width, Radius, Color, false);
+    Border = CreateBorderWindow(X, Y, W, H, Width, Radius, BorderColor, false);
 }

 internal inline void
@@ -295,6 +296,7 @@ CommandHandler(void *Data)
             unsigned Color = TokenToUnsigned(Token);
             if(Border)
             {
+                BorderColor = Color;
                 UpdateBorderWindowColor(Border, Color);
             }
         }
```

**Comment by koekeishiya** [comment]
This is intended behaviour, although I can see how that would be annoying in your scenario.
You can do the following from *khd* to fix it:
```
<some mode on_enter>: chunkc set focused_border_color 0xff775759;\
                      chunkc border::color 0xff775759
 ```

**Comment by synthetiv** [comment]
Oh hey, that makes sense. I guess I didn't realize you could set that cvar again after startup. Thank you!
