### ISSUE TITLE
[plugin|border] border from previously focused window shown after transition to empty desktop

### ISSUE THREAD

**Issue by bwasti** [koekeishiya/chunkwm#252]
<img width="1920" alt="screen shot 2017-10-10 at 10 21 17 am" src="https://user-images.githubusercontent.com/4842908/31400598-07993e62-ada5-11e7-9ab8-8896185223d0.png">
Here's a screenshot (the border is the purplish square)

repro steps:

- enable border and tiling plugins
- have two desktops, one empty of windows
- starting on the desktop with a window, focus on that window
- switch desktops

**Comment by koekeishiya** [comment]
Are you sure you are running the latest version ? It is not possible for this bug to happen in the current version, as the border window is restricted to the space it was created on.

**Comment by koekeishiya** [comment]
Closing this as I don't see it as a problem in the latest version.

Make sure you remove all old artifacts of chunkwm, chunkc and the plugins; Reinstall and the problem should be gone.
