### ISSUE TITLE
[plugin|tiling] Windows may resize while on an inactive desktop, breaking window_region_lock

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/chunkwm#255]
See title. I've noticed this with Safari, which I had open with a single tab on one desktop. I then ran `brew home ...` on another desktop, which opened another Safari tab (triggering a resize) before activating Safari and switching back to the desktop Safari was on.

Suggested solution: Also do all the necessary checks for `window_region_lock` when switching to another desktop.

**Comment by koekeishiya** [comment]
Unless I'm mistaken, this is a duplicate of #86

**Comment by dominiklohmann** [comment]
Didn't see #86 before, gonna close this then.
