### ISSUE TITLE
Multi-Monitor Window Cycling Issue

### ISSUE THREAD

**Issue by jessemillar** [koekeishiya/chunkwm#256]
With the current release of `chunkwm`, it seems that properly cycling focus between windows on different monitors and sending windows to specific monitors by index depends on the monitor arrangement in System Preferences.

My workstation setup is two external monitors and a MacBook Pro with a Retina display. More details can be given if pertinent.

The following screenshot shows the only System Preferences configuration I've found so far that allows `chunkwm` to function as expected. My MacBook is the center display.

![screen shot 2017-09-14 at 4 41 43 pm](https://user-images.githubusercontent.com/4627837/30457098-c77aa1a6-996b-11e7-914b-fe20a017332e.png)

The above arrangement isn't ideal for me because my desk mandates having my MacBook beneath my two monitors. The below System Preferences arrangement is preferred but causes `chunkwm` to not cycle window focus correctly or send windows to specified desktops as expected. On occasion, attempting to send a window to a specific desktop causes the window in question to disappear (seems to happen more often when sending to desktop `3`).

![screen shot 2017-09-14 at 4 41 12 pm](https://user-images.githubusercontent.com/4627837/30457202-1fe49f40-996c-11e7-93a3-0744598b9d2a.png)

Here are links to my current [`chunkwm` configuration](https://github.com/jessemillar/dotfiles/blob/4704458b0d396afb19cf8bf52b77d4632cd76870/.chunkwmrc) and my [`khd` configuration](https://github.com/jessemillar/dotfiles/blob/4704458b0d396afb19cf8bf52b77d4632cd76870/.khdrc) with the relevant `khd` lines being `25-29` and `81-97`.

**Comment by koekeishiya** [comment]
Probably a bug, but do not have 3 monitors to investigate with.

**Comment by koekeishiya** [comment]
So I have investigated this behaviour using 3monitors, with your display arrangement as mentioned (the 2 above, 1 below) and I can reproduce the behaviour 100% of the time with *mpv*.

The funny thing is that there is no issue in the code what so ever for this window.
Checking the source, destination and transformed coordinates, they are all calculated properly as expected, however when we try to move the window through the accessibility API it simply does not move even close to the position that we tell it to; same goes for its size.

This is not really a bug in chunkwm, but with how these applications interact with the AX API.
I'm not sure what we can do about this.. if anything.

**Comment by koekeishiya** [comment]
I believe this should be solved on the latest master.

**Comment by koekeishiya** [comment]
I've tested the second arrangement you've listed and it works just fine for me now in the latest release. Closing this.

**Comment by jessemillar** [comment]
@koekeishiya Awesome! I'm away from my workstation this week, but I'll test soon and report any issues I still have. You rock!
