### ISSUE TITLE
[Question] Workflow, layouts

### ISSUE THREAD

**Issue by snwflake** [koekeishiya/chunkwm#258]
Finally took some time to properly configure both skhd and chunkwm. Love 'em!

How would I go about setting up layouts though? `~/.chunkwm_layouts/foo`
I couldn't find any documentation about it and therefore I'm not even sure that's what I'm looking for.
I want to be able to have a predefined layout which I can call from within skhd.

E.g.
```
&---------&--------&
|         | iterm  |
| firefox &--------& 
|         |  foo   |
&---------&--------&
```

Is that somehow possible?

Another question: Let's say my only open/visible app is iterm. It turns fullscreen because I don't use offset. I can now set the tiling to float, which is almost what I want in that situation; but the window is too small. I tried increasing the region size in all  directions:
```
ctrl + cmd - 0x5C : chunkc tiling::window --use-temporary-ratio 0.1 --adjust-window-edge west;\
                    chunkc tiling::window --use-temporary-ratio 0.1 --adjust-window-edge south;\
                    chunkc tiling::window --use-temporary-ratio 0.1 --adjust-window-edge north;\
                    chunkc tiling::window --use-temporary-ratio 0.1 --adjust-window-edge east
```
That doesn't seem to do anything. My guess here is that `float` doesn't have a region to be expanded?

**Comment by koekeishiya** [comment]
@snwflake 

> How would I go about setting up layouts though? ~/.chunkwm_layouts/foo
I couldn't find any documentation about it and therefore I'm not even sure that's what I'm looking for.
I want to be able to have a predefined layout which I can call from within skhd.

You would have to create a bsp-space that has the layout you want. Then issue the command `chunkc tiling::desktop --serialize /full/path/to/output/file` (you can edit and create layout files manually as well, but the format is not described anywhere, opening the layout files in a text-editor after saving one to file should give you an idea of how they are constructed though.)

This will store the current bsp-layout for later use, and you can apply it to any arbitrary space using the following command: `chunkc tiling::desktop --deserialize /full/path/to/file`

Note that the serialization system CANNOT save the position of the open applications within the layout. You just have to experiment with the system and see if you can make use of it.

See https://github.com/koekeishiya/chunkwm/issues/44, https://github.com/koekeishiya/chunkwm/issues/190 for history / info about the system.

> That doesn't seem to do anything. My guess here is that float doesn't have a region to be expanded?

That is true. There is currently no way to do relative-resize of a floating window using keyboard shortcuts. There are a couple of pre-made dimensions that can be applied though, see: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#warp-floating-window

**Comment by snwflake** [comment]
Did the trick 👍 
/close
