### ISSUE TITLE
Chunkwm crashes, can only be fixed with reboot

### ISSUE THREAD

**Issue by CarlosEvo** [koekeishiya/chunkwm#259]
I am on macOS 10.13, and sometimes chunkwm daemon (as brew/launchctl service) crashes.

After starting `chunkwm` from the terminal, I got the following message and the program exits:

```
chunkwm: recv signal 11, printing stack trace
0   chunkwm                             0x0000000104173fc8 _Z13SignalHandleri + 36
1   libsystem_platform.dylib            0x00007fff5a7f8f5a _sigtramp + 26
2   ???                                 0x0000000000000400 0x0 + 1024
3   tiling.so                           0x0000000106c4ebea _ZL15ApplyWindowRuleP12macos_windowP11window_rule + 487
4   tiling.so                           0x0000000106c49937 _Z13AddWindowRuleP11window_rule + 143
5   tiling.so                           0x0000000106c48e15 _Z15CommandCallbackiPKcS0_ + 401
6   tiling.so                           0x0000000106c50be5 _Z10PluginMainPKcPv + 2018
7   chunkwm                             0x000000010417390c _Z14DaemonCallbackPKci + 279
8   chunkwm                             0x000000010416effc _ZL16HandleConnectionPv + 99
9   libsystem_pthread.dylib             0x00007fff5a8026c1 _pthread_body + 340
10  libsystem_pthread.dylib             0x00007fff5a80256d _pthread_body + 0
11  libsystem_pthread.dylib             0x00007fff5a801c5d thread_start + 13
```

The only fix so far is to restart.

**Comment by koekeishiya** [comment]
Not exactly sure how we'd get a nullpointer dereference there..
Seems to be caused by trying to apply a newly added window rules to the existing windows.

I think this is a bad design decision and rules should only be applied to windows that are created AFTER chunkwm has been started, or AFTER said rules have been added.

**Comment by koekeishiya** [comment]
Re-added support for newly window rules to apply to existing windows, on master. Fixed it the proper way that it should have worked from the beginning.
