### ISSUE TITLE
Chunkc: Connection failed

### ISSUE THREAD

**Issue by z3t0** [koekeishiya/chunkwm#26]
Hi,

I am having some issues figuring out how to build and run this project.

So far I have the binaries built for chunkc and chunkwm, and am using the sample config. However I am getting an error about chunkc: connection failed from the sample config being run from chunkwm. I  have also tried running it from the terminal.

It seems to be I'm making some sort of trivial error... Would appreciate any support

**Comment by maxkatzmann** [comment]
Hi z3t0,

I had the very same issues as you have and reached out to koekeishiya on reddit. His explanation
helped me getting chunkwm to work:

Uh, so the first thing to do is to compile chunkwm, chunkc and the plugins.
chunkc has to be in your path, I personally symlink the binary from its build-directory directly to /usr/local/bin/chunkc
chunkwm tries to run ~/.chunkwmrc (just a bash script), and in this file you can specify where it should look for plugins.
The example .chunkwmrc (in github repo) uses the directory ~/.chunkwm_plugins
This is just a symlink to the <chunkwm project>/plugins directory (default build path for plugins).
The tiling plugin tries to run its config from ~/.chunkwmtilingrc (this is also just a bash script)

Thanks to koekeishiya!

My two cents to this:

Make sure you do not forget to compile the plugins.

Using symlinks did not work for me. Therefore I added the location of the compiled chunkc file to my PATH variable. Additionally, I changed the _plugin_dir_ in the .chunkwmrc file to the path of the plugins in the build directory which for me was ~/chunkwm/plugins

I hope this helps.

**Comment by koekeishiya** [comment]
The above instructions should be sufficient, if not, wait for the first official alpha to be ready, and instructions will be provided.
