### ISSUE TITLE
ffm.so: mouse focus doesn't leave floating window

### ISSUE THREAD

**Issue by bsuh** [koekeishiya/chunkwm#260]
in tiling mode, i'll toggle float on a window and then when the mouse moves into the floating window, it focuses, but once a floating window is focused, focus will not follow mouse to any other window.

**Comment by koekeishiya** [comment]
Intended behaviour to prevent smaller (always floating) popup windows and so on from being harder to interact with, when ffm.so is enabled.

If you don't care for that, you can comment line. 210 (https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/ffm/plugin.cpp#L210) and recompile the ffm plugin.

**Comment by bsuh** [comment]
I turned off ffm, but I miss it. My ideal workflow would be ffm does not focus floating windows. The way I use floating windows is keep occasionally needed windows in the bg with some part of them visible slightly so I can focus them when needed. Unfortunately with ffm, I tend to accidentally focus them a lot.

How would I go about doing this? It seems the easiest way would be to move FocusWindow function to tiling plugin, modify the function to ignore floating windows, use API.broadcast from ffm plugin to signal tiling plugin to call FocusWindow. It's hacky, but if I'm reading correctly, the information whether a window is floating is only available within the tiling plugin.
