### ISSUE TITLE
tiling::rule state float ignored after hiding/showing again the app

### ISSUE THREAD

**Issue by zifeo** [koekeishiya/chunkwm#261]
I have a few tiling rules enforcing some apps (via owner) to stay in floating mode. However after hiding the app, reactivating it ignores the rules and the app is again tiled.

Version : head brewed on High Sierra.

**Comment by koekeishiya** [comment]
Thanks for reporting this. Fixed on master.

**Comment by zifeo** [comment]
Thanks, works fine!
