### ISSUE TITLE
floating window after cmd+h (hide) and reveal changes to full screen window

### ISSUE THREAD

**Issue by wxmtech** [koekeishiya/chunkwm#263]
When a floating window hides and then reveal, it somehow changes to the bsp mode, but minimize and reveal keeps the window in floating mode. Is this a feature or something else?

**Comment by koekeishiya** [comment]
Same as #261

**Comment by wxmtech** [comment]
Thank you, I did the search first and did not find anything so I leaved a issue here, definitely solved.
