### ISSUE TITLE
chunkwm crashed by NULL pointer dereferecence

### ISSUE THREAD

**Issue by NTT123** [koekeishiya/chunkwm#266]
Here is my stack trace
![Imgur](https://i.imgur.com/FNV8VRy.png)

window is a `NULL` pointer!

![Imgur](https://i.imgur.com/vq2Fvnk.png)
Look into `BeginFloatingWindow` function, it seems be the case that `GetWindowByID` or `GetFocuedWindow` is return `NULL` pointer.

So my suggestion is to check if window is `NULL` at line `20`  in the above picture. Or we also want to check `NULL` pointer at the `AXLibHasFlags` function to prevent possibly other crashes.

**Comment by koekeishiya** [comment]
I'd rather try to figure out why the function would return null in the first place - figuring out what the actual problem is, instead of simply guarding for null and call that a fix.

**Comment by koekeishiya** [comment]
So I've identifier why this happens, and the correct fix is to isolate this specific function.
Sorry for taking so long regarding this.
