### ISSUE TITLE
chunkwm doesn't actually move windows

### ISSUE THREAD

**Issue by lobachevzky** [koekeishiya/chunkwm#268]
I'm unclear if additional commands are required but when I run `chunkwm` on the command line, I get a running print out of the activity of my various windows, but nothing gets moved or resized as one would expect with a window tiling manager. 

I installed the program using
```
brew tap crisidev/homebrew-chunkwm
brew install chunkwm
```

Part of the print outs that looks a little ominous is 
```
chunkwm: plugin '/Users/ethan/.chunkwm_plugins/border.so' not found..
chunkwm: plugin '/Users/ethan/.chunkwm_plugins/tiling.so' not found..
chunkwm: plugin '/Users/ethan/.chunkwm_plugins/ffm.so' not found..
chunkwm: plugin 'tiling' is not loaded
chunkwm: plugin 'tiling' is not loaded
chunkwm: plugin 'tiling' is not loaded
chunkwm: config file finished executing
hotloader: '/Users/ethan/.chunkwm_plugins' is not a valid path!
```

Thanks for this utility and thanks for your help with it.

**Comment by dominiklohmann** [comment]
From `brew info chunkwm`:

> **==> Caveats**
> 
> [...]
> 
> NOTE: plugins folder has been moved to /usr/local/opt/chunkwm/share/chunkwm/plugins

Recent versions of the default `.chunkwmrc` file have been updated to this new path, but if your config file is old you will have to change the path yourself, like this:

```
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
```

Note that if your Homebrew installation uses a custom prefix path, the plugin directory may be changed. `brew info chunkwm` will always show you the correct path for your setup.

**Comment by lobachevzky** [comment]
Ok. Thanks. That did it. Actually, I ran `brew info chunkwm`, copied in the default .chunkwmrc and ran `brew service start chunkwm`.
