### ISSUE TITLE
Can't build plugins for Sierra

### ISSUE THREAD

**Issue by crisidev** [koekeishiya/chunkwm#27]
Hello, I have problems building all the plugins on Sierra.

Both `make` and `make install` returns a linker error at the end:
```
ld: can't open output file for writing: ../../../plugins/tiling.so, errno=2 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../../../plugins/tiling.so] Error 1
```

Not sure if I am missing something, but both xcode and its command line util are installed.

**Comment by koekeishiya** [comment]
Uh, you probably have to create the `<project>/plugins` directory, as the build script does not actually make sure that the desired build path has already been set up.

**Comment by crisidev** [comment]
Yep, you are right, thanks.

I think should be good to put that in the documentation. Thanks in the meantime.
