### ISSUE TITLE
Emacs syntax error screen jump issue

### ISSUE THREAD

**Issue by cmatzenbach** [koekeishiya/chunkwm#270]
Anytime I encounter a syntax error in emacs, the program ends up "jumping" within chunkwm and is reduced to half it's tiled area.  See the quick screen recording below.  This happens every time I run into a syntax error, and the window stays in the reduced size until the error is corrected.  It seems a small message box indicating the syntax error appears over the buffer in emacs, perhaps that is what is causing it?  When the app is fullscreen, as in my demo, it's not unreadable, but when it's splitting the screen with another app, this jump makes everything unreadable (and is also extremely annoying, unless you never make any mistakes :) )

For what it's worth, I'm using the spacemacs distribution and the latest version of chunkwm.  I have tested this in i3 on my other laptop and the issue does not occur.

Screen recording: https://drive.google.com/open?id=0BwV-DO25BNYkSmlPOGdTVTRwRG8

**Comment by dominiklohmann** [comment]
If you manage to run `chunkc tiling::query --desktop windows` while the invisible error window is open that chunkwm tries to tile you might get the necessary info to create a tiling rule that floats the invisible error window.

**Comment by natsumi** [comment]
this is the rule i use to have emacs tile correctly along with the floating tooltips

chunkc tiling::rule --owner Emacs --except "^$" --state tile

**Comment by koekeishiya** [comment]
Closing this. I have enabled the wiki and it should be open for everyone to edit. Particularly something like https://github.com/koekeishiya/chunkwm/wiki/Useful-tips-and-workarounds could be nice for the community to edit / add to instead of having all this information be buried in issues.
