### ISSUE TITLE
High Sierra, Open a tab for XCode will resize window

### ISSUE THREAD

**Issue by nuynait** [koekeishiya/chunkwm#272]
In macOS High Sierra, if I open a new tab in XCode, it will resize the window. I tried Safari, Finder, they works fine. Currently I found only XCode is affected.

**Comment by dominiklohmann** [comment]
Duplicate of #235

**Comment by nuynait** [comment]
Sorry, I did search before creating the issue, but didn't find that issue post. Closed due to duplication.
