### ISSUE TITLE
Cannot use ffm with chrome extensions

### ISSUE THREAD

**Issue by bsuh** [koekeishiya/chunkwm#273]
With ffm enabled, when you click on a chrome extension icon to open a menu and mouse over the menu. It focuses on the menu and then that somehow closes the menu.

**Comment by koekeishiya** [comment]
Is this still an issue in the latest release? 

I don't really use Chrome, and I've only tested this on the UBlock extension. That seems to work fine.

**Comment by Amar1729** [comment]
Not an issue for me, I'm able to interact with Chrome extension menus.

**Comment by koekeishiya** [comment]
I do believe it should've been fixed some time ago, so I'll take it the fix did work. Thanks for confirming. Closing this.
