### ISSUE TITLE
dragging windows causes flicker

### ISSUE THREAD

**Issue by Alok** [koekeishiya/chunkwm#274]
Say I have two chrome windows open. Trying to drag a tab from one window to another causes horrible flicker, possibly `chunkwm` trying to resize it while I'm still dragging it.

**Comment by HeathNaylor** [comment]
Yea, I have found that chunck is a bit aggressive with things like this as well.

**Comment by chrishoage** [comment]
Reported in kwm, marked as can't fix https://github.com/koekeishiya/kwm/issues/396

There isn't much that can be done in this situation.

**Comment by neverfox** [comment]
@blahsd Thanks for that tip. However, I get some weird behavior when dragging tabs in either case. The literal tab at the top disappears such that you cannot drag it back in. You have to open a new tab with a hot key to get the tabs to reappear. This doesn't happen if Chrome is running on a floating desktop. Also with the locked value set at 0, when I drag the tab out of a Chrome window, it seems to end up in floating mode and if you want it to end up in the bsp layout you have to toggle float mode off. I guess that's to be expected?

**Comment by koekeishiya** [comment]
Firefox also works fine. This is a Chrome thing and I know of no way to solve it.
