### ISSUE TITLE
switching monitor is only effective when there are windows in the monitor

### ISSUE THREAD

**Issue by xieyuheng** [koekeishiya/chunkwm#275]
switching monitor is only effective when there are windows in the monitor
I have the following binding in my ~/.skhdrc

```
cmd - 1 : chunkc tiling::monitor -f 1
cmd - 2 : chunkc tiling::monitor -f 2
```

if you can not reproduce this problem,
I will supply my full config files.

**Comment by dominiklohmann** [comment]
This has been discussed a lot in previous issues regarding multi-monitor behaviour. There is no way we know to focus the desktop on a given monitor programmatically.

**Comment by xieyuheng** [comment]
thanks @dominiklohmann 
sad to know
closing it
