### ISSUE TITLE
focused_border_skip_floating draws border while desktop float mode is on.

### ISSUE THREAD

**Issue by hankerboy** [koekeishiya/chunkwm#276]
**OS**: Mac OS 10.13
**Installation method**: Homebrew tap
**chunkwm version**: 0.2.33
**Detailed description of the issue**
When I float window manually chunkwm doesn't draw border, but it draws borders around the windows on floating desktop.
![image](https://user-images.githubusercontent.com/31503345/32831307-f009a3d8-ca08-11e7-8ba3-583efe9be20a.png)
<img width="752" alt="screen shot 2017-11-15 at 1 28 51 pm" src="https://user-images.githubusercontent.com/31503345/32831320-fb34df16-ca08-11e7-8305-dae9f2593c8e.png">

[chukwm config](https://pastebin.com/W1Vc8aKj)

**Comment by koekeishiya** [comment]
implemented on master.
