### ISSUE TITLE
setting padding based on screen resolution

### ISSUE THREAD

**Issue by asselinpaul** [koekeishiya/chunkwm#277]
Looking for an easy solution to this problem:

**Problem:** 
I plug my laptop into a 27in Dell monitor (laptop screen usually closed).
The padding that looks good on my 27in monitor is too big when I use my laptop's 13in screen. I want the padding to change based on which monitor I'm using.

Is this feasible?

**Comment by dominiklohmann** [comment]
The `.chunkwmrc` file is just a bash script, which means you can use shell commands and bash built-in if/else-statements.

You can get your current monitor resolution like this: 
```bash
system_profiler SPDisplaysDataType | grep Resolution
```

So yeah, this is feasible, but you still have to piece the bits together here.

**Comment by asselinpaul** [comment]
@dominiklohmann that is exactly what I was looking for. Thank you!
