### ISSUE TITLE
Add border to unfocused windows

### ISSUE THREAD

**Issue by JodusNodus** [koekeishiya/chunkwm#280]
Is it possible to allow adding a border to the unfocused windows?

**Comment by dominiklohmann** [comment]
See https://github.com/koekeishiya/chunkwm/issues/15#issuecomment-281208937

> > Add borders also for inactive windows, just for consistency (and when your inspiration was bspwm, it does have them)
> 
> This is something I will give an attempt at some point down the road, but I think this is going to be tricky to get working properly. This can be implemented as a standalone plugin though, and can be attempted by anyone in the current project state. I haven't written documentation regarding plugin development yet, but there is a template provided in src/plugins/template.

Now this was quite a while ago and I can't find any further follow-up to this.

**Comment by koekeishiya** [comment]
>>    Global borders? I'm not sure if this is already possible in kwm/chunkwm, but assigning all windows on the system a border. A lot of DE's do this and I think it looks very nice. Focused borders could be differentiated by having different thickness/different colors. Just a thought.

> I have experimented a bit with this, and it seemed to work fine except for one problem.
The window borders are marked as NSFloatingWindowLevel so that they are shown above the actual window (to make the border visible).

> If two windows that both have borders, are overlapping, the border of the inactive window will in some instances display ABOVE the focused window.

^ I havent touched this since. I don't particularly care that much about this, but I can see why someone might want this. That's pretty much all I can say for now.

**Comment by koekeishiya** [comment]
I don't think this is feasible with how we are doing borders currently. Closing this.
