### ISSUE TITLE
Homebrew installed applications are not recognised

### ISSUE THREAD

**Issue by jack836** [koekeishiya/chunkwm#285]
Started using chunkwm two weeks ago and it feels awesome. I appreciate all the people involved and their efforts.

I have the following windows open
1. Terminal
2. Terminal - from where I started emacs
3. Emacs
4. Terminal - from where I started inkscape
4. Inkscape

And the way chunkwm recognises it is as follows

dhcp6169:~ jackinbj$ chunkc tiling::query --desktop windows
149, Terminal, jackinbj — -bash — 62×16
1227, Terminal, jackinbj — inkscape — 62×16
1217, Emacs, *GNU Emacs* (invalid)
1210, Terminal, jackinbj — Emacs — 62×35

When I try to cycle through the windows, emacs and inkscape are omitted. This happens only for homebrew installed applications, while others like chrome browser, MS-Office work as expected. 
What am I missing? (I believe it is not a bug in chunkwm). I am new to Mac OS X and chunkwm. Any help is highly appreciated.

**Comment by koekeishiya** [comment]
See this comment regarding Emacs: https://github.com/koekeishiya/chunkwm/issues/105#issuecomment-312716790

I believe the Inkscape issue is the same issue as described here: https://github.com/koekeishiya/chunkwm/issues/108

**Comment by jack836** [comment]
Thank you for the quick reply.
The issue with Emacs was solved right away, following instructions from #105 
chunkc tiling::rule --owner "Emacs.*" --state tile

Inkscape uses XQuartz and that may be reason for the window not to be recognized. I believe it is a Mac-thing and not a chunkwm thing.  Just curious to know if there are any possible solutions or workarounds.

**Comment by koekeishiya** [comment]
> Inkscape uses XQuartz and that may be reason for the window not to be recognized. I believe it is a Mac-thing and not a chunkwm thing. Just curious to know if there are any possible solutions or workarounds.

Right, so macOS does not provide us with an API to get notified about events related to applications that uses XQuartz.

**Comment by jack836** [comment]
I found the following comment [here](https://github.com/eczarny/spectacle/issues/226)

"I don't know if you are able to reopen this, but ShiftIt positions X11 windows without a problem. They are open source and you may be able to figure out how they do it. It may be a totally different API. This is the one big thing keeping me from switching to Spectacle."

Not sure if it could be of any use. But, glad if it helps.

**Comment by koekeishiya** [comment]
Sorry for the vague comment earlier, see https://github.com/koekeishiya/chunkwm/issues/163 for full history.

**Comment by jack836** [comment]
That explains it all! I should have looked it up by myself. Sorry!
