### ISSUE TITLE
Change dimensions of floating center window

### ISSUE THREAD

**Issue by piotryordanov** [koekeishiya/chunkwm#286]
I have this setting on: `chunkc set window_float_center           1`
When I float a window, it successfully float in the middle of the screen just like in one of the screenshots.

However, I haven't been able to figure out how to change the dimensions of this floating window. 

1. Is it possible to increase it's default dimension?
2. Is it possible to change the dimension afterwards using keyboard shortcuts?

- - - -
Thx for this great plugin! That's my first time using a tiling window manager and it makes so much more sense, especially on big screens!

**Comment by dplisek** [comment]
Hi, I have an additional suggestion. It's currently possible using the Dock extension to move the floating window using mouse drag and a keyboard modifier. Would it be possible using the same extension to resize the floating window, like it's possible on some Linux window managers? One option would be to use the right mouse button, another would be to use a different keyboard modifier. Usually this works by detecting the quadrant of the window that was clicked, and based on that, choosing the corner to extend/shrink.

**Comment by koekeishiya** [comment]
@dplisek 

I believe there was a discussion related to that here: https://github.com/koekeishiya/chunkwm/issues/212

The end result was not good, sadly.

@piotryordanov 

1. This is currently not possible.

2. There is no system for this on master. I have mixed feelings regarding how much "floating" management I want there to be. You can try to compile https://github.com/koekeishiya/chunkwm/pull/241 from source and see if that system is useful to you.

**Comment by piotryordanov** [comment]
1. Is there some kind of a roadmap for this? I'm not quite keen to compile #241 if it won't be merged because it would be hard to maintain the 'fork' with master (And I won't be able to use brew easily)
2. I don't quite need to change these dimensions afterwards to be honest. My float use case is to spin something fast and kill it right after (use cases are: Changing music on mpd, making a quick git commit, or even checking mail)

**Comment by koekeishiya** [comment]
@piotryordanov 

I think it is reasonable to be able to define the size that `window_float_center` uses, maybe by specifying percentiles of the monitor or something, that way it doesn't look terrible for people that may shift between different sized monitors often.

`chunkc set window_float_center_size 75` would use 3/4th of the monitor size. Though, depending on the monitor we need to find a useful aspect ratio as well; this can probably be determined through the monitor dimensions at runtime.

**Comment by piotryordanov** [comment]
Well, isn't it currently hardcoded at a 0.5 ratio regardless of the monitor?
How would `chunkc set window_float_center_size 75` be different from the `bsp_split_ratio` which is already hardcoded at 0.5? :)

Also, `chunkc set window_float_center_size 75` could be controlled from `skhd` making it customizable. 

(I'm new to all this, so stop me if I'm saying none sense haha )

**Comment by koekeishiya** [comment]
The `chunkc set window_float_center` option has been removed on master, in favour of a better system (#300).

To center a window upon float, you simply combine the `float` command with a `grid-layout` command, which will also allow the user to define whatever size the window should get, and it does not necessarily have to be centered.

Sample *skhd* bind that will toggle float and center a window as before:

```
# float / unfloat window and center on screen
alt - t : chunkc tiling::window --toggle float;\
          chunkc tiling::window --grid-layout 4:4:1:1:2:2
```

**Comment by piotryordanov** [comment]
Awesome! When should I expect this to be pushed to brew?

**Comment by piotryordanov** [comment]
Thank you!
