### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by michaelorr** [koekeishiya/chunkwm#287]
I just wanted to say thank you for your hard work on this project along with all your others that you contribute to open source. I have been a happy user of kwm/khd and now chunkwm for years now. 

You freely give your time and energy to build and maintain this product that I use daily and take the benefits from and I greatly appreciate your efforts. Being an open source project maintainer is often thankless and all you see from your users are complaints or problems so I just wanted to open this issue to tell you THANKS!

Feel free to close this issue.

**Comment by koekeishiya** [comment]
@michaelorr 

I very much appreciate that, thanks! Glad to see that it is quite helpful for others even in its limited state.

**Comment by crisidev** [comment]
It's a pretty awesome piece of software @koekeishiya, don't be shy :p

**Comment by CestDiego** [comment]
This is pretty great! thanks for your hard work @koekeishiya

**Comment by robertkeizer** [comment]
@koekeishiya Thanks from Winnipeg Canada! Seriously useful project.

**Comment by ossdesign** [comment]
Thanks from me as well. I have found window management to be rather poor in "stock" macOS, so having a tool like this helps out a lot.
