### ISSUE TITLE
Run or Raise - Equivalent

### ISSUE THREAD

**Issue by jack836** [koekeishiya/chunkwm#288]
StumpWM (and many other tiling window managers) allows you to 
1.  RUN an application and move focus to its window   - with an assigned keystroke 
                            OR if the application is already running 
2.  Then RAISE the application window to top (focus)   - with the same keystroke 

     StumpWM also allows you to choose the scope of 'run_or_raise' function  to be 
1. Within a group (desktop) OR 
2. Global (across all the desktops). 

This was a very useful feature that I enjoyed having in stumpWM. (Every project I was working on had a dedicated desktop with its own browser, editor, terminal, etc...)
      Is there an equivalent in chunkWM? OR Will it be possible?

**Comment by koekeishiya** [comment]
I don't think this belongs in chunkwm, however, you can use the standard macOS program `open` to achieve this. You can then create a bind in *skhd* that executes the command.

e.g: `open -a firefox` will focus an existing instance of firefox if it exists, or launch a new one.
USe `man open` to get more information as to how the `open` utility can be used.

**Comment by jack836** [comment]
I thought so too, after posting the issue. Thank you for your suggestions any way. I am now in the process of developing recipe for "run-or-raise" using 'open' and 'khd'. Once done, I will post my configuration and results here. Then we can close the issue.

**Comment by jedahan** [comment]
Would love run-or-raise-or-hide so I can use one hotkey for a quake-like terminal

**Comment by koekeishiya** [comment]
Just leaving this as a note to anyone that is interested. I think this kind of functionality should be provided by a launcher-application such as Alfred or similar.
