### ISSUE TITLE
How to make new windows float by default?

### ISSUE THREAD

**Issue by lfoster0** [koekeishiya/chunkwm#297]
Thanks for putting so much time into this amazing project!

Everything has been working great except I can't seem to find a way to get new windows to float by default.

I've tried setting `window_float_next 1` in my `.chunkwmrc` as well as commenting out the following as suggesting in [this issue](https://github.com/koekeishiya/chunkwm/issues/278) but I still can't seem to get it to work :(

```
chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5
```
Other than these settings my `.chunkwmrc` is exactly like the sample config.

**Comment by koekeishiya** [comment]
You need to edit this line in your config to be `float` instead of `bsp` https://github.com/koekeishiya/chunkwm/blob/master/examples/chunkwmrc#L21

You probably want to delete line 22 and 23 as well then.

**Comment by lfoster0** [comment]
That did it, thanks!
