### ISSUE TITLE
Multi-monitor: Switching to an already-showing desktop on another monitor doesn't focus that desktop

### ISSUE THREAD

**Issue by rattboi** [koekeishiya/chunkwm#298]
I currently have 2 monitors, configured as such:

Monitor 1: Desktop 1,2,3
Monitor 2: Desktop 4,5,6

Assume I have Monitor 1 showing Desktop 1, and Monitor 2 showing Desktop 4, focused on Desktop 1.
I would assume that pressing "cmd + alt + 4" would put the focus on Desktop 4 on monitor 2. Instead, nothing happens. If I do "cmd + alt + 5", it swaps the Desktop on monitor 2, and I get focus. 

I'm now realizing that no chunkwm command is being called for this, and this is just what OSX does with Spaces? Is there a way to fix this? I don't really know the OSX way, as I'm trying replicate my xmonad config from linux, which is what I'm used to.

**Comment by rattboi** [comment]
I was able to fix this myself, using a script I made to query, and some khd changes. I'll drop it here, in case anyone else is curious. Note that I changed cmd + # to be switch desktop.

.khdrc changes
```
cmd - 1  -> : ~/.bin/focus-monitor-on-desktop-change.sh 1
cmd - 2  -> : ~/.bin/focus-monitor-on-desktop-change.sh 2
cmd - 3  -> : ~/.bin/focus-monitor-on-desktop-change.sh 3
cmd - 4  -> : ~/.bin/focus-monitor-on-desktop-change.sh 4
cmd - 5  -> : ~/.bin/focus-monitor-on-desktop-change.sh 5
cmd - 6  -> : ~/.bin/focus-monitor-on-desktop-change.sh 6
```

~/.bin/focus-monitor-on-desktop-change.sh
```
#!/bin/bash

mon_id=$(chunkc tiling::query --monitor id) 
mon_for_desk=$(chunkc tiling::query --monitor-for-desktop $1)

if [[ "$mon_id" != "$mon_for_desk" ]]; then
  chunkc tiling::monitor -f "$mon_for_desk"
fi
```

I'll let you close this if you think this issue is solved. I'd be curious if there's another simpler way that doesn't take a script.

**Comment by dominiklohmann** [comment]
> I'd be curious if there's another simpler way that doesn't take a script.

`chunkc tiling::minitor -f <current-monitor-id>` is a no-op, so just this is enough:

```
ctrl - 1 -> : chunkc tiling::monitor -f $(chunkc tiling::query --monitor-for-desktop 1)
```

**Comment by rattboi** [comment]
Good point. I was kinda worried some race condition might happen if OSX just swapped desktops + you force a focus when one isn't necessary. I'll try your way though, as it saves me a script.

**Comment by dominiklohmann** [comment]
I've been running this for months now and haven't had it crash on me, so I think you're on the safe side with it.

**Comment by rattboi** [comment]
Yep Works. :+1:
