### ISSUE TITLE
Scaled Secondary Display Breaks Focus Follows Mouse

### ISSUE THREAD

**Issue by phantomdata** [koekeishiya/chunkwm#301]
First, thank you.  :)  `chunkwm` scratches a long-given-up-on itch I had from switching to OSX from Linux.  Huzzah!  :tada:

During my initial setup, I figured that FFM was just broken / infeasible because I could never get it to actually work and it didn't seem like many people were using it according to the googles.  I regularly stumbled on https://github.com/koekeishiya/chunkwm/issues/149 while searching for potential solutions, but FFM was definitely enabled for me according to the debug logs.  Its also enabled by default now in the homebrew formula, it actually requires an explicit `disable-ffm` flag.

I finally figured out the oddest reason for it not working for me; I had scaling enabled on my secondary display!  I just happened to find this while squirreling through some old scaling issues regarding the tiling manager last night.

**Steps to Reproduce**:
- Have a secondary MacBook Retina Display
- Have a primary external display
- Scale that MacBook Retina display to something other than default

Result: FFM *only* works on the scaled MacBook Retina display

The work-around is easy enough for me, don't scale that display.  Personally, I just use it for Slack and it has its own scaling capabilities.  I more-so wanted to make sure to document this for future searchers who may run into this.  :)

(I'm not sure if its relevant to the bug-at-hand, but my choice of wording "primary" and "secondary" above is intentional.  I have my external display set as the primary (menu-bar drug to it, dock placed, etc) and my macbook itself as my secondary)

**Comment by koekeishiya** [comment]
Sorry for the delayed response.

I've tried to reproduce this with the following setup:
External primary monitor (1080p)
Scaled secondary mbp retina display (1920x1200)
Another external display (1080p)

FFM works on all three displays for me.  Are you still able to reproduce this issue?

**Comment by phantomdata** [comment]
Thanks for the reply @koekeishiya!  I hadn't retested since I first logged that Issue.  Now that a few upgrades have been applied (chunkwm and some Apple security patches) it seems to have resolved itself.  At this point, I can use whatever scaling factor I want on the MacBook's retina display and FFM still behaves as expected.  :tada:

Closing out since this issue naturally resolved itself.  :)
