### ISSUE TITLE
Make a window takes left half of the screen

### ISSUE THREAD

**Issue by zxcvbn97** [koekeishiya/chunkwm#302]
What is the chunkwm command to make a window takes left half of the screen? 

Thanks for the great piece of software and happy holidays.

**Comment by koekeishiya** [comment]
If you are running the latest *brew* or *macports* stable version:
```
chunkc tiling::window --warp-floating left`
```

If you are running the latest from *master*, you need to use the *grid-layout* command:
```
chunkc tiling::window --grid-layout 1:2:0:0:1:1
```
