### ISSUE TITLE
Documentation for the combination chunkwm + khd

### ISSUE THREAD

**Issue by ralphholz-usyd** [koekeishiya/chunkwm#304]
Thanks for your work - I absolutely enjoy it!

I needed a bit of time to get my head around the modularisation of chunkwm + khd, and while I set it up and configured it, I wrote up my understanding in a gist. If any of the text is helpful, please feel free to take any of it.

[link](https://gist.github.com/ralphholz-usyd/342637ec2325df0f375acc1635f9bbf8)

**Comment by koekeishiya** [comment]
I believe the structure regarding chunkwm, chunkc and khd / skhd is clearly defined in the project readme, although I agree that it is *very* brief and could probably do with an improvement.

I very much want to keep the readme brief, as most people (from my experience) tend to just ignore it if it is too verbose, and open issues instead. 

Your write-up explains the concept very well, and I think it could help fill the gap for users that would like something more detailed than what is provided in the readme.

I'd be grateful if you'd take the time to add your write-up as a (new?) page in the chunkwm *wiki*.
It is open for everyone to edit without needing my approval (although I do review the changes made afterwards, to be sure).

Afterwards I could link to the wiki page from the readme, for those that would like to see a more detailed explanation. I intended to use the wiki to elaborate a bit more regarding the architectural decisions that was made etc, but have not had the time to do so yet.

**Comment by ralphholz-usyd** [comment]
Sure thing - done. I have, for the moment, left links to my basic configuration files. Feel free to replace them if you want.

Thanks for the skhd tip, I'll try it out.

**Comment by koekeishiya** [comment]
I have now added a link to the new page in the README.
Thanks again for the writeup :)
