### ISSUE TITLE
Nothing happens when I start

### ISSUE THREAD

**Issue by p3rsephone** [koekeishiya/chunkwm#310]
I start chunkwm and it appears to be running when I use `brew services list` to check. But nothing actually happens. Using High Sierra.

Already tried:
- restarting service chunkwm
- reinstalling chunkwm from homebrew

**Comment by dominiklohmann** [comment]
Starting `chunkwm` is not the same as starting the brew service named chunkwm (`brew services start chunkwm`). The former runs the binary, the latter registers it as a launchctl service that loads it on login.

**Comment by p3rsephone** [comment]
I'm sorry, I've used `brew services start chunkwm` to start it. Is it wrong?

**Comment by dominiklohmann** [comment]
In System Preferences > Security & Privacy > Privacy > Accessibility, do you have the box for chunkwm checked?

**Comment by p3rsephone** [comment]
Yup. I did that and restarted the service

**Comment by dominiklohmann** [comment]
If you stop the service and run chunkwm manually, does it tell you something about a possibly erroneous config file?

**Comment by p3rsephone** [comment]
It says 
```
Finder:<unknown> is not destructible, ignore!
/bin/bash: /Volumes/Macintosh: No such file or directory
chunkwm: finished executing config-file.
```
And then it starts with no error. But it still does nothing

**Comment by koekeishiya** [comment]
open a terminal and write `echo $HOME` whats the output?

**Comment by p3rsephone** [comment]
`/Volumes/Macintosh HD/pers`
I do have a space in the volume name. Is that an issue?

**Comment by dominiklohmann** [comment]
It seems very wrong that it isn't `/Users/<your username>`.

Assuming `/Volumes/Macintosh\ HD` is where you installed the version of macOS you booted, it should always be mounted as `/`, so `/Users/<your username` is equivalent to `/Volumes/Macintosh\ HD/Users/<your username>`.

Do you manually set `$HOME` somewhere?

**Comment by p3rsephone** [comment]
Well, I use one disk for user folders and an SSD for the actual macOS, so I have things in separate places

**Comment by koekeishiya** [comment]
I do agree with the above post, but yes in this case that whitespace is indeed the issue.
Basically, in your case, chunkwm tries to execute: `/Volumes/Macintosh HD/pers/.chunkwmrc`, but it fails to parse properly because of the whitespace.

This is simply due to how the string is concatenated in the chunkwm config code.
I have never seen anyone with a `$HOME` not be `/Users/<something>`, and I have just assumed that there would not be any whitespace here. Strictly speaking, this is a bug.

**Comment by dominiklohmann** [comment]
Regardless of that it should be `/Volumes/Macintosh\ HD/pers` instead of `/Volumes/Macintosh HD/pers`. Gotta escape that whitespace.

**Comment by koekeishiya** [comment]
Escaping the whitespace as mentioned by dominiklohmann should fix the issue of the config file not loading.

As the config is never ran, plugins are not loaded (see the `chunkc core::load <plugin>` parts of the config. 

If you are still having trouble after this, feel free to create a new issue.

**Comment by PrismaPhonic** [comment]
Where in the world would I change the config so that it escapes whitespace?  I also split up my directories - this seems like a huge oversight in the development of chunkwm
