### ISSUE TITLE
border-color lost after switching spaces

### ISSUE THREAD

**Issue by KingLoui** [koekeishiya/chunkwm#311]
When I change the border color with khd or terminal to something and then switch to another space, the border color gets reset to the default set by .chunkwmrc. 
I use the border-color to show which mode I'm in in khd so its a little irritating when I change the space and the border-color suggests I'm in another mode.

**Comment by koekeishiya** [comment]
You can do `chunkc set focused_border_color 0xaarrggbb` to make the color persist across space changes.

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/chunkwm/issues/251

**Comment by KingLoui** [comment]
Thank you!  I just want to add that I also had to `change preselect_border_color` in the on_enter statement.
