### ISSUE TITLE
Assign windows to particular monitors

### ISSUE THREAD

**Issue by stevebasford** [koekeishiya/chunkwm#316]
Looking for a way to auto send certain applications to particular monitors. Tried assigning them to monitors within macos but chunkwm seems to ignore this. I mashed together this but I'm sure something's wrong about it as still no luck:

`chunkc tiling::rule --owner Skype --send-to-monitor-2`

**Comment by koekeishiya** [comment]
Rules are limited to the following: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#window-rules

You should be able to assign using the desktop id (shown in mission-control), by using `--desktop id`. See link above.

**Comment by koekeishiya** [comment]
Assigning an application to a monitor using the Dock seems to work fine for me as well. Closing this as I don't think there is anything to do in chunkwm here.
