### ISSUE TITLE
Define floating window size

### ISSUE THREAD

**Issue by stevebasford** [koekeishiya/chunkwm#317]
I'm trying to define the size of floating windows (more specifically a bit narrower and taller). I found this is another issue or readme file but no matter what options I set for grid layout, the floating windows are still always the same size.

```
alt - t : chunkc tiling::window --toggle float;\
          chunkc tiling::window --grid-layout 4:4:2:2:3:3
```

**Comment by koekeishiya** [comment]
The `grid-layout` command is only on master still, and not in the brew release (unless you install using the brew option `--HEAD`).

I hope to do another release some time this weekend.

**Comment by koekeishiya** [comment]
these changes are now live in the latest brew release.
