### ISSUE TITLE
What does the purify plugin do?

### ISSUE THREAD

**Issue by Alok** [koekeishiya/chunkwm#328]
I see it in the brew tap, but the docs are scarce on info.

**Comment by crisidev** [comment]
It removes all shadows from windows. It needs chwm-sa to work.

**Comment by koekeishiya** [comment]
It removes window shadows as stated by crisidev. It is more just an internal thing that I use that happen to be stored in the git repository. I wasn't aware that it was available through the brew tap.

It requires chwm-sa to work, which requires disabling SIP to install, and I do not consider the purify plugin part of the "official bundle". Of course, anyone is free to use it if they want to, but this is why there is no documentation for anything other than *tiling*, *border* and *ffm*.

**Comment by imagnma** [comment]
@koekeishiya may I ask how to enable it or use it, thanks
