### ISSUE TITLE
Slow starting applications are ignored due to accessibility timeout

### ISSUE THREAD

**Issue by Daedren** [koekeishiya/chunkwm#329]
Many times when I open up a new application, the new window isn't tiled with the rest of the open ones. It doesn't show on `chunkc tiling::query --desktop windows`. I have to restart chunkwm for the window to get detected.

Unless there's some command I can do to get it detected that I just don't know about.

**Comment by blahsd** [comment]
It might be helpful if you could try to see wh exact steps cause this to happen. Since I've never heard of this, I think most users don't experience this. Is it a specific app? Does it only happen under certain conditions? For instance, when many windows are open? Etc.

**Comment by Daedren** [comment]
I'm using an iMac on 10.12.6 with a 2.7GHz i5, 16GB RAM and a terrible 5200rpm HDD. Apps do take a while to startup.
Running chunkwm 0.2.36 with About 9 tiles across 6 workspaces, split between two monitors.

For example, I just launched Excel, and it didn't tile. Constantly opening and closing Workbooks made them never tile, they just floated as normal non-chunkwm windows, but with the regular blue border around them.

That said, when I closed Excel through Cmd+Q and reopened it, everything tiled properly, and had no issues from there on out. Further Excel restarts didn't have any issues.

Same exact behavior on OneNote, Xcode but not Sublime Text or Visual Studio Code. Seems to be apps on the heavier side, but only on their first run.

**Comment by koekeishiya** [comment]
This most likely happens because the *accessibility api* hits a timeout during application startup, for applications that are slow to start.

See https://github.com/koekeishiya/chunkwm/blob/master/src/core/state.cpp#L287

If you enable logging in your config file and set the log-level to *warn*, you can see if this is indeed the issue you are having:

```
chunkc core::log_level warn
```

If you are not running chunkwm from a terminal, you can also specify the output log-file:
```
chunkc core::log_file ~/.chunkwm_log
```
You can then view the log when running chunkwm by opening a terminal: `tail -f ~/.chunkwm_log`

**Comment by Daedren** [comment]
Yeah that's exactly it.

`2018-02-08 11:13:29 WARN : 99951:Microsoft Excel could not register window notifications!!!`

**Comment by koekeishiya** [comment]
I do have this issue with one or two applications myself, and it is very annoying. I'm just not sure how to best resolve this type of problem..

**Comment by tigren** [comment]
I guess my Mac Mini is too slow so this issue occurs every time when I start Firefox / Chrome the first time after system booted.

**Comment by koekeishiya** [comment]
fixed at master.
