### ISSUE TITLE
The default configuration on "Desktop 3" is potentially confusing in the case of multiple monitors

### ISSUE THREAD

**Issue by x-ji** [koekeishiya/chunkwm#333]
`chunkwm` seems to work if I only have the internal laptop screen, but apparently it's not scaling the windows correctly if I connect external monitors with different resolutions. For example, it seems to think that the whole screen space (the space arranged after pressing `alt + f`) is just this space occupied by these two terminal windows, instead of the whole actual laptop screen space. This makes the windows extremely small and unusable.

<img width="682" alt="screenshot 2018-02-06 12 39 28" src="https://user-images.githubusercontent.com/2999209/35858154-be2753a0-0b3b-11e8-97da-e869be8d4805.png">

On the external monitor, the application does seem to be scaled normally.

![screenshot 2018-02-06 12 40 03](https://user-images.githubusercontent.com/2999209/35858190-db90aa68-0b3b-11e8-8b5a-96ca57eabb5b.png)

The following is my monitor configuration under this scenario:

<img width="765" alt="screenshot 2018-02-06 12 46 51" src="https://user-images.githubusercontent.com/2999209/35858252-120cfc7c-0b3c-11e8-9c40-adf159954c23.png">

The laptop screen is standard 13' MBP Retina (looks like 1280 x 800), while the monitor screen is 1920 x 1080.

I installed `chunkwm` just now, with the `--HEAD` option. I'm surprised that I don't seem to be able to find the same issue already reported here.

**Comment by dominiklohmann** [comment]
You can set the padding per monitor, it's probably somewhere in your `$HOME/.chunkwmrc` file.

For example, this sets a padding of 8 pt for every side:
```
chunkc set global_desktop_offset_top 8
chunkc set global_desktop_offset_bottom 8
chunkc set global_desktop_offset_left 8
chunkc set global_desktop_offset_right 8
```

However, this can be overridden per space/desktop like this, setting the padding for the space/desktop labeled "Desktop 1" to 20:
```
chunkc set 1_desktop_offset_top 20
chunkc set 1_desktop_offset_bottom 20
chunkc set 1_desktop_offset_left 20
chunkc set 1_desktop_offset_right 20
```

Note that these settings are space/desktop dependent and not depending on your monitor.

**Comment by x-ji** [comment]
Thanks. Changing the offset and restarting `chunkwm` fixed it. I was surprised to find the following in the default configuration file (I don't think I edited it after copying at installation):

```
chunkc set 3_desktop_offset_top          190
chunkc set 3_desktop_offset_bottom       190
chunkc set 3_desktop_offset_left         190
chunkc set 3_desktop_offset_right        190
```

I think this might have caused the behavior. It seems to be quite unintuitive as a default configuration.

**Comment by koekeishiya** [comment]
fixed on master.
