### ISSUE TITLE
Border disappears on link hover in Safari

### ISSUE THREAD

**Issue by audreymgu** [koekeishiya/chunkwm#334]
Hey there!

I'm running chunkwm on High Sierra 10.13.3. For some reason, the border on Safari (11.0.3) seems to disappear when hovering over any sort of link (not clicking, just hovering). Un-hovering the link brings the border back after a very short delay. It seems that disabling focused_border_skip_floating resolves the issue, so perhaps it's somehow being interpreted as a floating window on hover?

No real significant difference in my config files from the base config files aside from offsets, so I'm unsure of what exactly the cause is.

Let me know if there's any additional information I can provide.

**Comment by audreymgu** [comment]
Ah, it seems that this is a variation on issue #202. Disabling the status bar in View > Show Status Bar or using the suggested fix in the previous issue removes this odd behavior.

**Comment by koekeishiya** [comment]
The issue here is that *Safari* actually creates a new window to display the url.
Having to disable *skip_floating* for this to work properly is definitely a bug.

**Comment by koekeishiya** [comment]
This has been fixed on master. You should now be able to have View > Show Status Bar enabled, and also have *skip_floating* enabled if you so desire.

**Comment by audreymgu** [comment]
Ah, it's working exactly as expected now. Many thanks and cheers!

**Comment by audreymgu** [comment]
Hm, I just now realized that Safari's preferences are now also being tiled (it spawns as a separate tile). Is there perhaps any way to specify only the status bar?

**Comment by koekeishiya** [comment]
I don't think there is any way for us to differentiate between the Safari Preferences window, and actual brower windows. I personally use Firefox, so I can't say I've tried to look for a solution to this.
Maybe @dominiklohmann has been able to  come up with a trick that could help you out

**Comment by dominiklohmann** [comment]
Yes, actually. On mobile right now so I can't tell you the exact syntax, but I have a passthrough khd mapping for <kbd>cmd</kbd><kbd>,</kbd> (bind that opens preferences on german mac keyboard) that tells chunkwm to float the next window to be spawned.

I do not know of a workaround that works when opening the preferences window using the menu bar item.

With the way Safari creates the preferences window there is no way to distinguish it from a regular window without trying to resize every Safari window that spawns, which would look really weird.

**Comment by audreymgu** [comment]
Sounds like exactly what I'd need. How would the passthrough mapping work?

**Comment by dominiklohmann** [comment]
First, take a look at koekeishiya/khd#1 for keycode information on how to map <kbd>,</kbd>. Create the following binding, replacing the keycode with the correct one for your keyboard:

```
cmd - 0x2F [ Safari ] -> : chunkc set window_float_next 1
```

**Comment by audreymgu** [comment]
Ah, fair enough. I was aware of the chunkc command, but was not familiar with the passthrough nor specifying keycodes. 0x2B does the trick for me. Thank you for your patience in explaining and pointing me to the proper resources!

**Comment by dominiklohmann** [comment]
> Thank you for your patience in explaining and pointing me to the proper resources!

No worries. I feel like this is the least I can do to thank @koekeishiya for creating this set of applications. I myself have asked so many questions here, especially when the applications were newer, that I feel the need to pay it forward.

**Comment by karbecker** [comment]
I’m experiencing a disapperaing border when I keep the Status Bar enabled. I’m on chunkwm 0.3.3 which seems to be the newest version, installed via Homebrew. Anything I missed?

**Comment by koekeishiya** [comment]
@karbecker This fix is part of the v0.3.4, which was released a couple of days ago.
