### ISSUE TITLE
[plugin|tiling] use-insertion-point only seems to work when marked node focused

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/chunkwm#337]
This is entirely possible I have misunderstood how this is supposed to work. So if this is working as intended please feel free to close this. 

When I use `tiling::window --use-insertion-point` to mark an insertion point in one node, then focus a node in a different container and create a new window, that new window gets inserted at the currently focused node, not the marked node. 

How is this intended to work? Am I just holding it wrong?

**Comment by koekeishiya** [comment]
So this is working as intended, but I have not heard any feedback regarding this feature so far.

I would have no problem with making it work the way you mention here.
Just out of curiosity, what's the behaviour in *bspwm* here? Haven't used it for a long time now.

**Comment by chrishoage** [comment]
The windowing system broke on my VM I was running bspwm on and I never got around to fixing it, so I can't check first hand. However, looking at the docs here: https://github.com/baskerville/bspwm#manual-mode it makes me think that regardless of where the focus is, it will create a new node at the marked point. 

> The user can specify a region in the insertion point where the next new window should appear by sending a node -p|--presel-dir DIR message to bspwm.

https://github.com/baskerville/bspwm/tree/master/examples/external_rules/pseudo_automatic_mode - this makes bspwm "automatic mode" split very similar to how kwm/chunkwm split, which I vastly prefer. 

I want to say how I thought `use-insertion-point` worked here is how bspwm worked, but I can't say for certain.

**Comment by koekeishiya** [comment]
Hmm so to implement this behaviour in chunkwm, we would to make the preselect  system a global thing, and not a per-node thing.

Do you have some sample use-cases ? I often find myself just doing a preselection and immediately open a new window / application.

I suppose a use case is when you have two different applications, A and B. And you want to split B with a new window of application A, assuming B is focused.

With the current system you'd have to perform the preselection, shift focus to application A, open a new window, then do a *warp command* towards B.

With the new system you'd do the preselection, shift focus to application A and open a new window.

**Comment by chrishoage** [comment]
> I suppose a use case is when you have two different applications, A and B. And you want to split B with a new window of application A, assuming B is focused.

This is basically the case. I'll describe mine with a very specific example 


![image](https://user-images.githubusercontent.com/1056886/35941050-e684e0ea-0c05-11e8-973f-adb13efa0323.png)

The arrow pointing to the command `st -n .gitignore` opens a new sublime text window with the file `.gitignore`. I have marked the space where I would like the next window to open (seen with the red border in the screenshot) but when I hit enter it tiles in the small space my terminal is. 

It's very easy to move the window to the correct spot. However, marking that split should just create the window there (in my mind)

This example is contrived (as to not expose details from my work), but the flow is something that I try to do often in my real work.

**Comment by koekeishiya** [comment]
> It's very easy to move the window to the correct spot. However, marking that split should just create the window there (in my mind)

Agreed. I think the best solution here is to have the preselection apply for the entire desktop.
I'll probably take a look at this after I get back from work tomorrow. Thanks for the feedback on this feature btw :)

**Comment by koekeishiya** [comment]
implemented on master.

**Comment by chrishoage** [comment]
Confirmed working. Thanks a ton!
