### ISSUE TITLE
Opening new tab on Terminal.app resizes the window to half-the screen size

### ISSUE THREAD

**Issue by elefthei** [koekeishiya/chunkwm#338]
Super weird, reproduced both with the shortcut inside Terminal.app (Cmd+t) or by manually
creating a new Tab in the Terminal.app. It will move the terminal to the side and leave an empty space on the right half of the screen.

**Comment by dominiklohmann** [comment]
Duplicate of #235.

**Comment by elefthei** [comment]
Yep, closing.
