### ISSUE TITLE
Spacemacs Develop branch Doesn't Tile (Vanilla Emacs and Spacemacs Master work)

### ISSUE THREAD

**Issue by rumbletumjum** [koekeishiya/chunkwm#342]
I know this has been beaten to death, but I wanted to chime in because I've found something interesting: Emacs works fine with chunkwm (per #105), and so does the master branch of Spacemacs. The Spacemacs develop branch, however, does not; this is probably what a lot of people are running into.

@koekeishiya, my C++ foo is not as strong as it used to be, can you verify if chunkwm uses window titles to identify windows for tiling? I'm crawling through the Compare View for the two branches, but the first thing I've noticed is that when running the master branch the window title is "*spacemacs*" and when running the develop branch the window title is "Emacs@<hostname>".

I can post logs (after I set up logging) and the output of the query command. This one is weird.

(PS can someone add a "Not A Bug Informational Message" label?)

Update: this is definitely not a chunkwm issue, but I'm posting it here because I'm guessing I'm not the only person in this boat. Here's the fix (at least for me, and it's a little hacky):

In your dotspacemacs file,

`(setq dotspacemacs-frame-title-format nil)`

or something other than the default (I'm guessing), and boom.

**Comment by natsumi** [comment]
I'm running spacemacs in develop and its working fine.  You can set rules off of the owner instead.

Here's an example of one of my rules:

chunkc tiling::rule --owner Emacs --except "^$" --state tile

**Comment by rumbletumjum** [comment]
I think the “—except” bit is what I was missing

**Comment by koekeishiya** [comment]
Seems like you were able to resolve this. Closing.
