### ISSUE TITLE
bug/feature request: chunkc set window_fade_inactive

### ISSUE THREAD

**Issue by kinglouie** [koekeishiya/chunkwm#343]
I'm currently having a setup where in khd I have a `mode` called "tiling" with an `onenter` function which enables chunkwm borders to indicate that the mode is active.

I would like to replicate this behaviour with chwm-sa and the `window_fade_inactive` setting. Unfortunately when executing `chunkc set window_fade_inactive 1` it will only change the alpha of unfocused windows when focusing another window not directly upon executing said command.
Also when `window_fade_inactive` is set to `1` and I execute `chunkc set window_fade_inactive 0` all windows will stay faded, even when changing focus. This issue can only be circumvented when I execute `chunkc set window_fade_alpha 1` before I disable the window fading.

EDIT:
I wrote a small script which mimics the wanted behaviour:
```
#disable
chunkc set window_fade_alpha 1
chunkc tiling::window -f prev
chunkc tiling::window -f next
chunkc set window_fade_inactive 0

#enable
chunkc set window_fade_alpha .8
chunkc set window_fade_inactive 1
chunkc tiling::window -f prev
chunkc tiling::window -f next
```
Problem with this is that die due to prev/next the windows flicker and it only works if there are > 2 windows on the current screen.

On a sidenote:
I know that the purify plugin is not officially supported nevertheless I want to suggest a feature.
It would be nice If there was an option to enable the window shadow for the currently focused window so it can be used like in the scenario above to indicate if a mode is active. 
This would allow me to see if tiling mode is active even if there isn't another window on the monitor which is faded by `window_fade_inactive`

**Comment by koekeishiya** [comment]
Could probably make a set of commands to enbable/disable fading and restore the appropriate alpha levels.

Regarding the purify plugin, the thought was initially to make floating windows all have shadows as well. Not sure yet what I'm eventually gonna do here.

**Comment by koekeishiya** [comment]
Some improvements to window fading is now available in master.
In addition to that, there is now a new option that allows toggling of window fading, that will properly adjust the alpha as appropriate when enabled / disabled: `chunkc tiling::window --toggle fade`

No plans to add any features to the purify plugin as of now, sorry.
