### ISSUE TITLE
[Question/Feature request] Is it possible to use wildcards in .chunkwmrc ?

### ISSUE THREAD

**Issue by Thibaulltt** [koekeishiya/chunkwm#345]
I have iTerm2 behave in such a way that when I press a certain key combinaison, a dropdown terminal appears (for quick pdf compiling or program killing). Unfortunately, the window title changes, but at least one element stays the same : the profile name.

Would it be possible to have a rule in `.chunkwmrc` that would be written like one of the following options :

```
chunkc tiling::window --owner iTerm --name *\"dropdownTerminal\"* --state float
chunkc tiling::window --owner iTerm --name \"*dropdownTerminal*\" --state float
```

If this feature is already implemented, just close the issue 👍

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#window-rules and https://www.gnu.org/software/findutils/manual/html_node/find_html/posix_002dextended-regular-expression-syntax.html
