### ISSUE TITLE
Mouse does not follow focus anymore

### ISSUE THREAD

**Issue by Beulenyoshi** [koekeishiya/chunkwm#346]
I updated chunkwm **including the plugins** relatively recently and noticed that my mouse stopped following focus inbetween the versions. I am running **macOS 10.12.6**.

I run a `install make clean` to install the plugins. I also cleaned to old files manually to see if I was using an old version of the ffm plugin still.

The plugin is loaded in the chunkwm config file:

```
chunkc core::load ffm.so
chunkc set mouse_follows_focus           1
```
Any suggestions what could cause this?

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/CHANGELOG.md

See section for *version 0.3.0*:

>version 0.3.0

>cvar changes

>mouse_follows_focus has been changed to be of type string, formerly a boolean value. the new values are as follows: off, intrinsic and all.

**Comment by Beulenyoshi** [comment]
I swear I read the changelog and did not notice it... Thank you!

**Comment by koekeishiya** [comment]
No worries. The changelog isn't exactly friendly to the reader just yet, but it's a start :)
