### ISSUE TITLE
iTerm3 gets a pass though of shortcuts

### ISSUE THREAD

**Issue by brorbw** [koekeishiya/chunkwm#348]
When using chunkwm and skhd, everything have worked fine for over a month now. 
Today i messed around with my emacs configuration, and suddenly chunkwm or skhd stopped working, but only for iTerm. 
When pressing any of the shortcuts, iTerm gets a passthrough of the symbols. It works with Kitty and terminal, but iTerm is my preferred shell interpreter. 

How can i track down this issue?

**Comment by koekeishiya** [comment]
You have most likely activated *Secure keyboard entry* in iTerm. There is usually an entry to enable / disable this in the menubar.

**Comment by Beulenyoshi** [comment]
Do you see an "eye icon" in the corner of your iTerm window? This happened to me as well. It's likely you accidentally activated secure input for iTerm.

**Comment by brorbw** [comment]
That was indeed the issue. I don't use a title bar for iTerm so the eye icon does not show. The shortcut for secure input is CMD+option+S and that clashes a bit with the shortcut convention of the default skhd.
