### ISSUE TITLE
How to: horizontal triplet

### ISSUE THREAD

**Issue by torrance** [koekeishiya/chunkwm#349]
This is a support request rather than an issue: how to obtain a horizontal triplet? ie.:
```
___________________
|_______|          |
|_______|          |
|_______|__________|
```

Currently, when I send three windows to the left, half of the left pane is devoted to one window, and the other half split between two. However, I'd rather the left pane be evenly split between all three.

One of your screenshots indicates this is possible - but I can't seem to figure it out!

**Comment by koekeishiya** [comment]
You can use the command: `chunkc tiling::desktop --equalize`
This command will currently affect the root node (the entire desktop)

history: https://github.com/koekeishiya/chunkwm/issues/36

**Comment by torrance** [comment]
Excellent thank you!
