### ISSUE TITLE
Full Screen behavior....

### ISSUE THREAD

**Issue by CaninoDev** [koekeishiya/chunkwm#351]
Highly likely this is a limitation in Mac OS, but I was wondering if it is possible to modify full screen behavior of an application such that instead of taking up the screen at the window call, it would exhibit the same behavior but within a leaf of chunkwm window engine.

**Comment by koekeishiya** [comment]
This is indeed a limitation in macOS. Unfortunately there is nothing we can do to achieve this behavior.
