### ISSUE TITLE
Documentation for the parameters of .chunkwmrc

### ISSUE THREAD

**Issue by brorbw** [koekeishiya/chunkwm#356]
When i look in the configuration file it is not immediately apparent what some of the settings do. ```desktop_gap_step_size for one``` is not very easy to understand.

**Comment by dominiklohmann** [comment]
See here: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#set-desktop-offset-and-window-gap-incremental-step

**Comment by brorbw** [comment]
Thank you.
