### ISSUE TITLE
Window jump between monitors

### ISSUE THREAD

**Issue by zifeo** [koekeishiya/chunkwm#357]
I'm using a setup with two monitors with the tiling plugin only. When moving a window to the other monitor, it seems to behave correctly. However when I sometimes exchange two windows between the monitors, the second move often trigger a reset in the position of the first window (return to its previous monitor). A restart of chunkwm is often required to be able to perform such switch.

Not sure it is linked, but chunkwm seems to lose track of hidden windows after some times. It often appears at the same time as the exchange issue.

**Comment by koekeishiya** [comment]
> However when I sometimes exchange two windows between the monitors, the second move often trigger a reset in the position of the first window (return to its previous monitor).

How is this exchange performed?

> Not sure it is linked, but chunkwm seems to lose track of hidden windows after some times. It often appears at the same time as the exchange issue.

Just for clarification, do you mean hidden as in hiding applications (cmd + h) or hidden as in minimized windows (cmd + m) ?

**Comment by zifeo** [comment]
> How is this exchange performed?

Taking the first window on the other screen with the mouse. Then same in the other direction with the second window.

> Just for clarification, do you mean hidden as in hiding applications (cmd + h) or hidden as in minimized windows (cmd + m) ?

Hidden (cmd + h) ones, minimized work fine.

**Comment by zifeo** [comment]
The same behaviour seems to happen when I open (e.g.) a PDF A in a PDF reader app which already has another open PDF B, then both PDF A&B jump to one of the monitors at the same position (one over the other).

**Comment by koekeishiya** [comment]
> Taking the first window on the other screen with the mouse. Then same in the other direction with the second window.

This should be resolved in the lastest version (0.3.5). If you still experience issues with this in the new version, there is not much more that can be done, and you'd be better of using the built-in commands for moving windows around.

> Not sure it is linked, but chunkwm seems to lose track of hidden windows after some times. It often appears at the same time as the exchange issue.

I have not been able to reproduce the issue with hidden windows.

Closing this.

If you are having issues with the latest version, feel free to create a new issue report(s)

**Comment by zifeo** [comment]
Thanks!
