### ISSUE TITLE
Running chunkwm with brew or manually does nothing

### ISSUE THREAD

**Issue by Utagai** [koekeishiya/chunkwm#361]
Hello! Firstly, thanks for writing/maintaining this. Having a nice WM solution for Mac OS X, capable of being reminiscent of options like `bspwm` and `i3` is a godsend. Unfortunately, I've been experiencing some issues getting `chunkwm` to do anything.

I've installed `chunkwm` with `skhd` via:

```
$ brew install chunkwm
$ brew install skhd
```

I've gotten the Accessibility prompt, and added both `chunkwm` and `skhd` to the Accessibility list, checked.

However, when I run _any_ of the following commands, everything seems to go smoothly without error, but _nothing_ happens.

```
$ brew services restart chunkwm
$ brew services restart crisidev/chunkwm/chunkwm
$ chunkwm
```

Starting with `brew` gives a `==> Successfully started 'chunkwm' (label: homebrew.mxcl.chunkwm)`. Starting manually doesn't print out anything, but doesn't crash or provide any errors either.

Finally, `brew services list` gives:

```
Name    Status  User Plist
chunkwm started may  /Users/may/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist
skhd    started may  /Users/may/Library/LaunchAgents/homebrew.mxcl.skhd.plist
```
and, I am using the default configuration for `.chunkwmrc`, and it is located in `~/.chunkwmrc`.

Running on High Sierra 10.13.1. Let me know if any other information is needed.

**Comment by Utagai** [comment]
Embarrassingly enough, I just fixed this. The issue was that in the [sample config](https://github.com/koekeishiya/chunkwm/blob/master/examples/chunkwmrc#L23), the `plugin_dir` variable is set to `~/.chunkwm_plugins`. However, when installing with `brew`, a message stating:

```
NOTE: plugins folder has been moved to /usr/local/opt/chunkwm/share/chunkwm/plugins
```

Is printed. In other words, it seems like the sample config linked in the README is not up-to-date with the `brew` install version? I am not necessarily an expert in either `brew` or OSX in general, but this may be something to fix?

Nonetheless, the problem seems to have simple been that `chunkwm` was not finding the plugins I was expecting it to run, in particular, `tiling`.

I'll leave this open in case this is still something to fix. Otherwise, feel free to close this issue.

**Comment by dominiklohmann** [comment]
The new plugins folder is a directory created and managed by Homebrew. It may be different depending on your Homebrew installation, which is why it is not listed in the example configuration.

The Homebrew formula for chunkwm downloads the example configuration and simply changes that one line to use the path setup by Homebrew.

**Comment by Utagai** [comment]
That makes a lot of sense. I can see why the sample file differs from the Homebrew installation's directory.

In that case, I think this issue should be closed, but I do want to ask the following two questions:

1. Should there be some information about this somewhere in the documentation/README of `chunkwm`? It's possible it already does exist somewhere and I missed it. I wouldn't be surprised if a large majority of people attempting to use `chunkwm` opt for the nice and easy `brew` command, but miss this detail when using the sample file.
2. Is there a reason why I saw seemingly successful runs of `chunkwm`, both when starting it with `brew` and manually? I would expect `brew services` and a manual start of `chunkwm` to both show an error because my `.chunkwmrc` file suggests loading a plugin that doesn't exist in the directory I said it would. If anything, I'm surprised that `chunkwm` was completely quiet on this matter, I think it should be obvious to show some indication that a plugin load directive in the config file doesn't happen, so it leads me to believe that I might be doing something wrong.

Just to make sure its clear, absolutely _no_ hard feelings about this, just curious if these two things are worth considering for the project, as I believe either one would have saved a lot of time for an otherwise silly issue. 😄

**Comment by koekeishiya** [comment]
> Should there be some information about this somewhere in the documentation/README of chunkwm? It's possible it already does exist somewhere and I missed it. I wouldn't be surprised if a large majority of people attempting to use chunkwm opt for the nice and easy brew command, but miss this detail when using the sample file.

I don't maintain the homebrew distribution, but I am pretty sure this is mentioned in the caveat section after installing with Brew. Tagging @crisidev and he can do whatever he feels appropriate.

> Is there a reason why I saw seemingly successful runs of chunkwm, both when starting it with brew and manually? I would expect brew services and a manual start of chunkwm to both show an error because my .chunkwmrc file suggests loading a plugin that doesn't exist in the directory I said it would. If anything, I'm surprised that chunkwm was completely quiet on this matter, I think it should be obvious to show some indication that a plugin load directive in the config file doesn't happen, so it leads me to believe that I might be doing something wrong.

chunkwm is not dependant of the actual plugins or the configuration file in general. The application still runs properly and as intended. Thus, chunkwm actually runs properly in your case as well, however the plugins you requested to load could not be found. This is not something that I deem an error, but rather a warning. Failing to load a plugin should not interrupt otherwise already running plugins.

I agree that there should be some feedback to the users if a plugin fails to load. There are warnings logged if a plugin fails to load, however the default logging-level was set to *error*, which is why you didn't see these. I've now changed the default log-level to *warn* in the latest release.

**Comment by pyros2097** [comment]
Just ran into this issue. It would be good if this was documented somewhere because it took some time to figure this out.

**Comment by Utagai** [comment]
@pyros2097 Apparently this should be logged as a warning according to @koekeishiya's last response, so you should have seen _something_.

In either case, I've tagged him here so he might give a better answer.

**Comment by Utagai** [comment]
@pyros2097 What did the warning message say? My guess is the message is probably sufficient, but if not, then it may be worth it to revamp it. Perhaps a quick PR would be a great addition :).

It is worth noting that a successful install `!=` successful run. A successfully installed package can still fail to run for some other reason.

**Comment by pyros2097** [comment]
It just gave me a warning that tiling plugin was not loaded. I think that was good enough warning for me to find out why it was not loaded. But instead thought it should work since it was just a plugin. I should have read the configuration file first and checked the plugin_dir position from the sample config provided.
Also I couldn't find out in the code where the warning was spit out. It would be better if the warning stated that the location from the config file was incorrect.

**Comment by koekeishiya** [comment]
> But instead thought it should work since it was just a plugin. I should have read the configuration file first and checked the plugin_dir position from the sample config provided.

You don't need to set the *plugin_dir* IF you specify the absolutepath to the plugin in the load command. The plugin was not loaded warning is just saying that it could not find the file referenced.
If the load command said something like "/some/path/to/a/nonexistant/file" it would show that path in the warning message.

> It would be better if the warning stated that the location from the config file was incorrect.

The config file is just a shell-script. We don't parse the config file and don't really care what the contents of the file is, or how it is structured. . Loading the config is a simple combination of *fork -> execv* system calls that runs the shell-script.

Possible warnings and errors:

*plugin not found*
https://github.com/koekeishiya/chunkwm/blob/master/src/core/config.cpp#L172

*dlopen syscall failed*
https://github.com/koekeishiya/chunkwm/blob/master/src/core/plugin.cpp#L208

*missing export info*
https://github.com/koekeishiya/chunkwm/blob/master/src/core/plugin.cpp#L214

*invalid plugin file*
https://github.com/koekeishiya/chunkwm/blob/master/src/core/plugin.cpp#L219

*plugin ABI mismatch*
https://github.com/koekeishiya/chunkwm/blob/master/src/core/plugin.cpp#L224

**Comment by pyros2097** [comment]
Nice. Thanks @koekeishiya. Stupid me. I was searching the source code for the keyword "warning" thinking that will get me to the warning message.
