### ISSUE TITLE
Focus follows mouse and menu bar

### ISSUE THREAD

**Issue by neverfox** [koekeishiya/chunkwm#363]
This might be more of a question that an issue, but focus follows mouse and the OS X menu bar don't mix very well, because you invariably pass through other windows on you way up. I know that it's possible to use ^F2 to focus the menu bar but I was wondering if there was a chunkwm way of dealing with this elegantly (e.g. a modifier key that when held disables focus follows mouse until released).

**Comment by matthewdias** [comment]
`chunkc set mouse_modifier <mod>`
you can then hold down the modifier to temporarily disable it.

**Comment by koekeishiya** [comment]
this has been renamed to *ffm_bypass_modifier* in chunkwm release 0.3.4.

https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/ffm/CHANGELOG.md
