### ISSUE TITLE
--close has no effect on kitty

### ISSUE THREAD

**Issue by neverfox** [koekeishiya/chunkwm#364]
This might be a kitty issue but since I know it's a popular pairing with chunkwm and ultimately it's the chunkwm command that's not working as expected, I'm raising this here for now. I have `alt - w : chunkwm tiling:window --close` and that works for everything but kitty. I end up having to use kitty's own ctrl+shift+q or good old cmd+q to close the terminal.

**Comment by dominiklohmann** [comment]
The `tiling::window --close` option simply performs `kAXPressAction` on the button identified with `kAXCloseButtonAttribute`. kitty does not have such a button, which means it cannot be pressed, which in return means that the window cannot be closed using this method.

If you want to further debug this, take a look at this code:
https://github.com/koekeishiya/chunkwm/blob/f4f5dd4672a8f205e40d0bcf9d0ac47c90f66253/src/common/accessibility/element.cpp#L228-L236

**Comment by koekeishiya** [comment]
I'm fairly sure this is a limitation in *GLFW*, the windowing toolkit that *Kitty* uses. I'd suggest opening an issue in either the *Kitty* or *Glfw*. Feel free to reference this issue there.
