### ISSUE TITLE
Can't fullscreen when in float mode

### ISSUE THREAD

**Issue by lszinv** [koekeishiya/chunkwm#366]
So I tend to want to move my workspace around a lot while I'm using it. So what I want is to actually set everything in float, and then move things around the workspace accordingly. 

It seems like `chunkc tiling::window --toggle fullscreen` doesn't work on float windows. 

Similarly, I'd like to hotkey a setting to set the floating window to half the screen size, because sometimes I just need to check some stuff that's behind the float window quickly. It seems like the size change functions only allow for a generic 'increase' and 'decrease'. Is there a way to give it values?

**Comment by koekeishiya** [comment]
Check the *grid layout* command: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#grid-layout #300

**Comment by lszinv** [comment]
That's exactly what I was looking for. Thanks!

**Comment by koekeishiya** [comment]
There is no way to change focus between floating windows using *chunkc* commands for now.
