### ISSUE TITLE
Glitches on hover actions

### ISSUE THREAD

**Issue by mzgnr** [koekeishiya/chunkwm#372]
<img width="1920" alt="screen shot 2018-04-07 at 17 15 13" src="https://user-images.githubusercontent.com/6003317/38455939-637efdec-3a87-11e8-972c-181fd053bb85.png">
<img width="1920" alt="screen shot 2018-04-07 at 17 15 04" src="https://user-images.githubusercontent.com/6003317/38455940-63b0bed6-3a87-11e8-8faa-9ca3246fa95d.png">

The left one is Emacs

**Comment by dominiklohmann** [comment]
```
chunkc tiling::rule --owner Emacs --except "^$" --state tile
```

That rule should help you out. This is not a fault in chunkwm, but rather in Emacs, which appears to create tooltips as new windows of the same kind used as the main user interface.
