### ISSUE TITLE
[Question] Proper way to set desktop_tree layout from file

### ISSUE THREAD

**Issue by moxuz** [koekeishiya/chunkwm#373]
Hey,
I have a desktop set to use bsp layout and I'd like apps that are open in this specific desktop to automatically use a layout like so:
```
&---------&
| editor  |
|         |
&---------&
| terminal|
&---------&
```

Here is my layouts file (generated from `chunkc tiling::desktop --serialize ~/.chunkwm_layouts/terminal-editor-layout`
```
# ~/.chunkwm_layouts/terminal-editor-layout
root horizontal 0.750
left_leaf
right_leaf
```
And I have set my chunkwm to use the specific set command for this desktop

```
# ~/.chunkwmrc
// ...
chunkc set global_desktop_mode           bsp

chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5
chunkc set 3_desktop_tree ~/.chunkwm_layouts/terminal-editor-layout
// ...
```

But after starting chunkwm the desktop in question seems to keep using the optimal 0.5 ratio set in that excerpt, and not the layout. Nothing changes if I run `chunkc set 3_desktop_tree ~/.chunkwm_layouts/terminal-editor-layout` in my terminal either. Is there something I'm missing here?
Thank you :)

**Comment by koekeishiya** [comment]
So after adding `chunkc set 3_desktop_tree ~/.chunkwm_layouts/terminal-editor-layout` to your config-file you will have to restart chunkwm, for this change to take affect.

After doing so, the desktop in question will tile using that layout, the first time you enter that desktop OR after all windows on that desktop has been closed, and you open a new window.

You can use `chunkc tiling::desktop --deserialize ~/.chunkwm_layouts/terminal-editor-layout` to apply the layout to the active desktop on demand with the currently open windows.

**Comment by moxuz** [comment]
Thanks for the response @koekeishiya :)
I've tried closing all the windows in my desktop 3 as well as restarting chunkwm but it still opens with the windows side by side with a split half way. I've run the command but it also doesnt seem to change how the windows are tiled.
Here is a screenshot of how my desktop looks after having restarted chunkwm, and after running the command.
<img src="https://dl.dropboxusercontent.com/s/okhov2iijupq4oo/Screenshot%202018-04-09%2009.10.43.png?dl=0" height="500" width="800" alt="open windows"/>

I appreciate the help

**Comment by koekeishiya** [comment]
Well this is a weird issue. I'm not able to reproduce the problem sadly. The layout is applied as expected for me when defining a default layout in the config file, or when performing a deserialization command on demand.

**Comment by moxuz** [comment]
@koekeishiya It just magically started working! I'll close this issue now 😛

**Comment by moxuz** [comment]
@koekeishiya Hey sorry, one last question. Is it possible to tell it which app you prefer to take up how much space? I have it doing the ratio correctly, but I'd like my IDE to take up the larger portion of screen real-estate, and often times it makes my terminal occupy the space. Thanks :)
