### ISSUE TITLE
Floating window toggle not maintained after minimize/restore

### ISSUE THREAD

**Issue by neverfox** [koekeishiya/chunkwm#374]
A window toggled to float and then minimized is restored back in tiling mode. The desired behavior is that it would remain floating.

**Comment by koekeishiya** [comment]
I'm unable to reproduce this issue. Making a window floating, minimizing and deminizing works fine for me. The window stays in float mode.

**Comment by neverfox** [comment]
Turns out I forgot that I had Stay running (something I'm experimenting with to deal with windows moving around when monitor goes to sleep.). False alarm.

**Comment by neverfox** [comment]
I'm reopening because while, yes, it's staying in float mode, it's not staying where I moved it before minimization. I thought that was Stay's doing but I have it disabled now. It snaps into place in the layout instead (even though it's still floating and can be moved around). Essentially, the behavior I'm after is for something like Google Hangouts. I want a small floating window of that I can minimize a restore floating right in the middle of my screen, while the rest of the desktop it tiled.

**Comment by neverfox** [comment]
Hmm, I guess that means it's not actually staying floating because you can drag tiled windows. In fact, after it snaps back, if I toggle floating it actually goes to floating, implying it wasn't after restore from minimized.

**Comment by neverfox** [comment]
Works if you click on the icon in the Dock, but not if you cmd-tab the app to restore. In that case, it returns to tiling mode.
