### ISSUE TITLE
Wrong direction when choosing north/south focus window

### ISSUE THREAD

**Issue by NickClark** [koekeishiya/chunkwm#375]
When trying to focus a window to the north or south and, seemingly, even east/west sometimes, it doesn't seem like chunkwm logically detects what window is actually spatially in the desired direction. I'm guessing it just cycles the tree in order? Although, just now, in this config:

```
|----------|----------|----------|
|          |          |          |
|    A     |    C     |    E     |
|          |          |          |
|          |          |          |
|----------|----------|----------|
|          |          |          |
|    B     |    D     |    F     |
|          |          |          |
|          |          |          |
|----------|----------|----------|
```

... when focusing north from B, I get C. Focusing south from C, I get B. North from C I get D.

**Comment by koekeishiya** [comment]
Can you try to disable focus-wrapping and see how the behaviour works then?
add this to your config file: `chunkc set window_focus_cycle none`

The directional logic is based on window-distance. Given the focused window and a direction, we find all windows that are in that direction, and finds the one with the minimum distance using the center point of both windows.

**Comment by NickClark** [comment]
Ok... I thought I had already checked the obvious... like making sure I didn't have those keys double mapped.... whelp... I did. They were mapped to `next` and `previous`. 🤦‍♂️ Noticed after I checked the log again and noticed this:

```
2018-04-09 21:42:47 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'
2018-04-09 21:42:47 DEBUG:     command: 'f', arg: 'next'
```

DOH!
