### ISSUE TITLE
querying with chunkc is very inconsistent

### ISSUE THREAD

**Issue by apierz** [koekeishiya/chunkwm#376]
The results from querying with chunkc give very inconsistent results, even second-to-second.

For example I have the following script:

``` bash
chunkc=/usr/local/bin/chuck
active=$($chunkc tiling::query -d id)
total=$($chunkc tiling::query --desktops-for-monitor 1 | tail -c 1)

echo "$($chunkc tiling::query -d mode) $total $active"
```

Sometimes when I run it, I get the mode, occasionally the $total, and almost never the $active desktop. It never gives all three and each time I run the script it gives me a different set of the three. Running the commands individually gives similar inconsistent results where sometimes I will get the output, sometimes I will not.

**Comment by koekeishiya** [comment]
This is probably because the command are routed through the chunkwm event-system, such that we are able to prevent bad accessors due to threading issues.

Try to add a short sleep duration between each of the commands.

```
chunkc=/usr/local/bin/chuck
active=$($chunkc tiling::query -d id)
sleep 0.05
total=$($chunkc tiling::query --desktops-for-monitor 1 | tail -c 1)
sleep 0.05

echo "$($chunkc tiling::query -d mode) $total $active"
```

**Comment by apierz** [comment]
That works great, thank you!

**Comment by apierz** [comment]
I think I closed this issue too soon. While it worked initially, even 1.0 second sleeps are not sufficient to get the right output with any consistency.

**Comment by kinglouie** [comment]
as a workaround you can use a CLT of mine to query display/space information.
[kinglouie/DisplaySpaces](https://github.com/kinglouie/DisplaySpaces)
I use this to show the list of spaces for each monitor and mark the current space for each monitor in Übersicht.

**Comment by apierz** [comment]
The script I am trying to get working is here:
https://github.com/apierz/chunkbar.widget/blob/master/scripts/screens

download:
[testing_script](https://github.com/koekeishiya/chunkwm/files/1973004/testing_script.txt)

It's a bash script which is called for my ubersicht widget. I haven't had a chance to try out kinglouie's solution yet, but I might be able to this weekend.

**Comment by koekeishiya** [comment]
fixed on master. the issue was due to a problem in *chunkc*

**Comment by koekeishiya** [comment]
forgot to write this, but you no longer need those weird sleep statements either to make things work. this bug was a good catch, thanks!

**Comment by koekeishiya** [comment]
final working script:
```
#!/bin/bash

chunkc=/opt/local/bin/chunkc

active=$($chunkc tiling::query -d id)
total=$($chunkc tiling::query -D 1 | tail -c 1)
current=$($chunkc tiling::query --window name)
mode=$($chunkc tiling::query -d mode)

echo "$mode@$total@$active@$current"
```

**Comment by apierz** [comment]
I got a chance to update to the latest version tonight but for some reason chunkwm has completely stopped working post-update. I haven't seen anyone else post an issue with the problem so its probably on my end. I'll let you know if i get it working and can test the fix.

**Comment by crisidev** [comment]
Have you added an & to all calls in the .chunwmrc which are not chunkc core and chunkc set?

**Comment by apierz** [comment]
@crisidev, that was the problem, thank you. For anyone else having a similar problem if you have tiling rules in your chunkwmrc you should add an `&` as @crisidev suggests.

```
chunkc tiling::rule --owner Finder --name Copy --state float &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --owner \"Graphic\" --state float &
```
