### ISSUE TITLE
Suggestion: add chunkwm to serhii-londar/open-source-mac-os-apps

### ISSUE THREAD

**Issue by issmirnov** [koekeishiya/chunkwm#380]
Hey there,

This is a really nifty app - would be great to get word out. Might be worth adding a snippet to https://github.com/serhii-londar/open-source-mac-os-apps#window-management.

HTH!

**Comment by koekeishiya** [comment]
Feel free to submita PR there if you want to :)

**Comment by koekeishiya** [comment]
Looks like someone has submitted a PR that was accepted. Closing this.
