### ISSUE TITLE
Tabs in certain applications are treated as separate windows

### ISSUE THREAD

**Issue by kylef** [koekeishiya/chunkwm#381]
In some applications such as the system `Terminal.app`, when I create new tabs it shrinks the window size such as if another window was created. When I toggle between the tabs it jumps the window to the empty created space.

I've recorded a GIF to demonstrate this behaviour:

![untitled mov](https://user-images.githubusercontent.com/44164/38761481-eb22c4fe-3f37-11e8-961d-1877f3150678.gif)

I am experiencing this problem on more than one machine, I am also seeing similar behaviour with Xcode.app and Maps.app. Some other tabbed applications such as Safari and iTerm2 and Finder do not reproduce this problem. I believe that Xcode and Terminal are both using the same system tab API (I'm guessing Safari has some custom tab bar). I experienced the problem since I started using Chunkwm a few months ago.

My configuration: https://github.com/kylef/dotfiles/blob/ee3b8ff0f099ed1dc02ec294bae1dccac7203e60/.chunkwmrc

```
$ chunkwm --version
chunkwm 0.3.4
```

macOS High Sierra 10.13.4 (17E199/stable)

**Comment by koekeishiya** [comment]
same as #235 and #338

**Comment by kylef** [comment]
My apologies @koekeishiya, I somehow missed #235 while searching the existing issues. Thanks for the awesome work on chunkwm.
