### ISSUE TITLE
Outlook notifcations causing random window to shrink

### ISSUE THREAD

**Issue by neverfox** [koekeishiya/chunkwm#383]
I have MS Outlook running 24/7 for work and it has popup notifications for appointment reminders. When one of these pops up (lower right), it causes one of my open windows (seems random, but a bottom one), to shrink to half its "container" until the notification is dismissed.

**Comment by jhenahan** [comment]
I have the rule

```
chunkc tiling::rule --owner \"Microsoft Outlook\" --state float
```

and then I just keep Outlook fullscreen. You may also be able to use the Accessibility inspector to figure out a more nuanced rule to handle those notifications.

**Comment by neverfox** [comment]
@jhenahan Thanks. I figured it might take something like that. I'm still trying to get fluent in all the ways to examine windows for the sake of writing rules.

**Comment by neverfox** [comment]
Accessibility Inspector...that's something that's only available with full XCode? Isn't there a chunkwm command that can give some of the same information? I always forget what it is.

**Comment by Amar1729** [comment]
`chunkc tiling::query -d windows`
and
`chunkc tiling::query -w <id>` 

can give you some helpful info (you get the `id` from the `-d windows` command)

**Comment by neverfox** [comment]
`--owner \"Microsoft Outlook\" --name ".*Reminder.*" --state float` seemed to do the trick
