### ISSUE TITLE
chunkwm: failed to initialize daemon! abort..

### ISSUE THREAD

**Issue by hepan-git** [koekeishiya/chunkwm#384]
I get the following error message when I try to start chunkwm by typing "chunkwm" into the terminal.
`chunkwm: failed to initialize daemon! abort..`
Am I even supposed to type this into the terminal?

**Comment by samvv** [comment]
Got the same issue when installing using Homebrew on macOS High Sierra 10.13.4. I'm probably missing something. Any hints?

**Comment by simar7** [comment]
Same issue also on High Sierra 10.13.4 😭

**Comment by koekeishiya** [comment]
When using Brew, there is a service that starts chunkwm automatically, and thus trying to start it a second time for the terminal will fail, as the port that chunkwm uses is already taken.

If that is not the issue, then some other application happens to be using that port. You can investigate this by running the following command in a shell: `lsof -i :3920`

**Comment by hepan-git** [comment]
Thank you, that was the issue.
Chunkwm wasn’t  working though, so I just did 
`brew services restart chunkwm`
and it started working.
