### ISSUE TITLE
Sending Window To Monitor Causes It To Jump Back To Previous Monitor Occasionally

### ISSUE THREAD

**Issue by Noah-Huppert** [koekeishiya/chunkwm#385]
I have a 3 monitor setup:

<img width="682" alt="screen shot 2018-04-18 at 9 11 11 am" src="https://user-images.githubusercontent.com/3323504/38933972-767ce256-42e8-11e8-8ac1-fb5792cd6978.png">

(Bottom Center = 1, Top Right = 2, Top Left = 3)

When I plug in my laptop to these 2 monitors, and then try to send a window the third monitor, the window will go to that monitor for a second and then jump back to the monitor I just moved it from.

The exact way this usually happens is:

1. Plug laptop into monitors
2. All windows are on screen 1  
3. I send a few windows to screen 2 
4. I attempt to send a window to screen 3 
5. The window will jump to screen 3 for a second or less
6. The window will jump back to screen 3 

I am not able to reproduce this bug with 100% success yet. However I am working towards finding steps to do so. I did however find a bug where I sometimes can not move a window back from screen 3 to screen 1. Generally I would say multi monitor support isn't too robust.

Note: Apologies if you got an empty email with a weird issue title, I accidentally submitted this issue way before I was ready and had to edit most information in.

**Comment by BrianGilbert** [comment]
I'm seeing this as well

**Comment by kinglouie** [comment]
I have the same issue when dragging a window to a second monitor, but it does not happen always.

**Comment by koekeishiya** [comment]
@Noah-Huppert @BrianGilbert 

Is this when dragging the window, or when using the built-in *chunkwm* command to send the window to a different desktop / monitor?

**Comment by koekeishiya** [comment]
Added some changes to master. Dragging a tiled window to a different monitor should now properly update the state of chunkwm.

**Comment by Noah-Huppert** [comment]
For me this issue occurs when I used the CLI command via sxkd.

**Comment by koekeishiya** [comment]
I still have not been able to reproduce the issue, however, I have made some changes to how the active desktop / desktop of a window was detected, which should in theory fix the issue you have been seeing.

I would appreciate it you could try and run the latest master branch and report back. Hopefully the issue has been solved.

**Comment by Noah-Huppert** [comment]
Sure thing, I absolutely loved using Chunk WM except for this bug.

**Comment by Noah-Huppert** [comment]
Hi,

I have just installed ChunkWM from HEAD. I will report back in a few days.

**Comment by koekeishiya** [comment]
This really makes no sense to me at all. This wouldn't happen to be a specific set of applications that are having this problem? Can you reproduce this issue with something like *Terminal.app* or other well tested software?

**Comment by koekeishiya** [comment]
Well at this point I'm just curious if it happens with any "default" applications provided with macOS.
I have not been able to reproduce this problem on my end. I do have similar issues with *mpv*, but that's the only one, and that is caused some issue that mpv does not correctly respect the position it is given through the AX API (god knows why this is).

**Comment by Noah-Huppert** [comment]
I def. want to get this figured out, having i3/bspwm like functionality on OSX is an amazing feature. I don't know if I could go back to dragging stuff around.  

Are there any other things I could be doing to debug this besides getting a solid reproduction down? Logs? Debug commands?

**Comment by koekeishiya** [comment]
There isn't really any logging here that could help. There seems to be a specific state that the window has to reach, for this issue to trigger.

**Comment by Noah-Huppert** [comment]
It's been 22 days and I haven't had any problems. If I encounter this bug again I will re-open the issue.

Thank you very much for the fix.

**Comment by koekeishiya** [comment]
Not sure why your problem stopped happening. I don't recall doing any changes that would impact this during the timeframe in which your issue disappeared. Glad it is working better for you now though :)

@dominiklohmann 
> Added some changes to master. Dragging a tiled window to a different monitor should now properly update the state of chunkwm.

I had to undo this change due to #403. I will keep it in mind for the future if a better opportunity to detect window movement between monitors occur.
