### ISSUE TITLE
Google Chrome window 'bounces' when hovering a link or typing in the address bar

### ISSUE THREAD

**Issue by samvv** [koekeishiya/chunkwm#387]
I'm running High Sierra 10.13.4 with Chrome updated and I've just installed _chunkwm_ on 0e8f0fe. It looks really awesome!

Except for a warning and a short flicker at window creation, iTerm works great. However, whenever I hover a link in Chrome or start typing something in the address bar, the window is split with an empty space. If I move a bit with the mouse while hovering a link, Chrome 'bounces' from this split to full again.

I presume that _chunkwm_ detects the small tooltip at the bottom or the suggestions as a seperate window, and I'm probably doing something wrong with the configuration, but I have no clue how to fix it. Any help would greatly be appreciated!

**Comment by samvv** [comment]
For the record, this is my ridiculously simple configuration that I added to the default one:

```
chunkc tiling::rule --owner \"Google Chrome\" --name \"\" --state tile
chunkc tiling::rule --owner iTerm --state tile
```

**Comment by koekeishiya** [comment]
Chrome shouldn't need a rule to tile properly. Removing the rule for Chrome should prevent the issue you are mentioning.

**Comment by samvv** [comment]
Whoops ... seems like I misinterpreted the `tiling::rule`-clauses. Thanks for the quick response; it works now!
