### ISSUE TITLE
Chunkwm not working after a while - Mac High Sierra 10.13.4

### ISSUE THREAD

**Issue by lstrgiang** [koekeishiya/chunkwm#391]
- `Chunkwm` started to stop working after `khd` started to stop receiving hot key.
- Restart the computer cause `chunkwm` to stop working, this have happened for several times already, I tried to reinstall `chunkwm` and restart it or reset `LaunchAgents` and `LaunchDaemon` of `chunkwm`, sometimes it worked, sometimes it did not.
- I followed instruction with KeyChain certificates option described in issue #295, it worked for several weeks and stop working again, I believe the problem is about the accessibility of new update from mac

Thank you for helping me.

**Comment by koekeishiya** [comment]
This definitely sounds like an issue with the accessibility access.

Try to remove both *chunkwm* and *khd* from the list of accessibility access.
Restart the computer.
Run *chunkwm* and accept the prompt and give it accessibility access.
Restart chunkwm (*brew services restart chunkwm*)
Do the same for *khd*. 

Hopefully that works, as I don't really have any other suggestions.
I can't say I have had issues with this myself, but I do codesign the binaries myself after compiling (using method described in #295).

**Comment by zifeo** [comment]
@lstrgiang did you find out what the issue was?

**Comment by lstrgiang** [comment]
@zifeo No I did not. I created a script to reinstall and restart everything. This happen once a week. Sometimes, I switch from `khd` to `skhd` and it last for around 3 weeks. Then `skhd` stop working, and I'm back with `khd`.

**Comment by lstrgiang** [comment]
Now, I cannot get it back to work 😞

**Comment by zifeo** [comment]
@lstrgiang Thanks for the update, I've tried to reset my keychain but eventually it was the "distinct spaces" option that got unticked (see #424).

**Comment by koekeishiya** [comment]
Referenced issue should contain enough information to resolve this, closing.
