### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by pablopunk** [koekeishiya/chunkwm#392]
I like `kwm` and it has some bugs I wanna try this one but I can't get it working... I tried the example config and read the documentation but I don't how to use it.

What I want is a config file that works exactly like `kwm` (so automatic tiling) without me having to do any keyboard shortcut. Right now I can't figure out how to do that with `chunkwm`.

I installed it with `brew` and copied the example config file, but nothing happens.

Thanks

**Comment by pablopunk** [comment]
@dominiklohmann Yeah sorry about that.

* I installed it from `brew`
* I copied [example file](https://github.com/koekeishiya/chunkwm/blob/master/examples/chunkwmrc) and gave `+x` permissions
* I restarted the service `brew services restart chunkwm`
* I enabled Accessibility permissions to chunkwm
* I logged out and logged in

After all of this I can't see chunkwm working. What I want is to let it handle new windows automatically.

BTW I tried all those steps again (uninstalling with brew first) and I keep getting the following window all the time

<img width="457" alt="captura de pantalla 2018-04-26 a las 11 56 42" src="https://user-images.githubusercontent.com/4324982/39299599-688f3f24-4949-11e8-98e8-5f83e1e6ab5d.png">

And I can see two programs with the same name:

<img width="507" alt="captura de pantalla 2018-04-26 a las 12 01 07" src="https://user-images.githubusercontent.com/4324982/39299653-8a727408-4949-11e8-905e-6cc6e70ce271.png">

They are actually the same file although one is a link to the other one

* `/usr/local/bin/chunkwm -> ../Cellar/chunkwm/0.3.4/bin/chunkwm`
* `/usr/local/Cellar/chunkwm/0.3.4/bin/chunkwm`

**Comment by koekeishiya** [comment]
If you install through brew, you need to copy the sample config provided with brew, and not the one from the github repository. The reason for this is that your local brew installation will reconfigure the config file to use your brew prefix as the plugin directory.

**Comment by pablopunk** [comment]
@koekeishiya Okay, I tried that, didn't work. BUT I finally got it working, I just restarted my mac, because it seems logging out was not enough.

Thank you for your time!
