### ISSUE TITLE
Chunkwm and Skhd running, but no tiling happening, segmentation errors

### ISSUE THREAD

**Issue by halvardlange** [koekeishiya/chunkwm#393]
Hi, 
I migrated my mac to a new macbook, and had issues with chunkwm not working after the migration. I removed and re-installed both chunkwm, skhd and homebrew. After re-installation, it is still not working. Chunkwm and Skhd are both running, but the windows are not resized/tiled, nor can they be controlled. Mac osx sierra

`brew services list` yields
```
Name    Status  User    Plist
chunkwm started halvard /Users/halvard/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist
skhd    started halvard /Users/halvard/Library/LaunchAgents/homebrew.mxcl.skhd.plist
```
`chunkc tiling::window --swap east ` gives a seg error,
`7189 segmentation fault  chunkc tiling::window --swap east`

`ps aux |grep chunkwm` gives
```
halvard           5526   0.0  0.1  4384532  13924   ??  S    11:28PM   0:00.29 /usr/local/opt/chunkwm/bin/chunkwm
halvard           7198   0.0  0.0  4258468    184 s000  U+   11:52PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn chunkwm
```
Stopping the brew service, and just running `chunkwm` directly in terminal gives a long list of segmentation errors, line by line. 

Running 0.3.4 of Chunkwm, installed with homebrew using `brew install chunkwm`

Any suggestions to what I should try?

**Comment by halvardlange** [comment]
Update: Resolved. 
It turns out that my hosts file did not have localhost defined, so Chunkc was unable to resolve the localhost. Not sure if that was the migration assistant, or a freak error when the high sierra was installed. 

Adding `127.0.0.1 localhost` to the hosts file (can be found in `/etc/hosts` resolved the issue. Chunkwm is now working like a charm!

**Comment by odjhey** [comment]
took me hours before finding this. Please add it the docs/userguide alongside 'displays have separate spaces'

thank you though! 👍

**Comment by dominiklohmann** [comment]
Honestly doubt this needs to be documented. Not mapping `localhost` to `127.0.0.1` is a configuration error that is probably breaking more than just `chunkc`.

In the default `/etc/hosts` file you can find a comment at the top saying this:

```
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.

127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

**Comment by stik3nd** [comment]
Damn, I just lost a considerable amount of time trying to understand why I was getting the `Segmentation fault` errors. This was the problem for me too.
I also migrated from MacBooks, so I believe Apple's `Migration Assistant` does not copy `/etc/hosts` thus you end up with a blank file.
 
I would love to see this in the docs it would have saved tons of time, I was almost giving up :(
