### ISSUE TITLE
Is it possible to ignore some windows?

### ISSUE THREAD

**Issue by BrianGilbert** [koekeishiya/chunkwm#394]
I have some apps that I don't really want to control using chunkwm, Fantastical is a really good example, it's window is opened from the menu bar, and I only use it to enter an event and then it closes back to the menu bar, butr with Chunkwm it's taking up half the screen.

I can't find any documentation about skipping some windows?

**Comment by dominiklohmann** [comment]
You can do this using window rules: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#window-rules

**Comment by koekeishiya** [comment]
You'd have to write window rules matching the application name or window title, as mentioned by dominiklohmann.

**Comment by BrianGilbert** [comment]
thanks

**Comment by tnorthcutt** [comment]
@BrianGilbert were you able to get this working? I've added the following to my `.chunkwmrc` with no luck:
```
chunkc tiling::rule --owner Fantastical --name \"Fantastical 2\" --state float
```

**Comment by BrianGilbert** [comment]
@tnorthcutt I had the following which seemed to work initially, but has stopped doing so now.
```
chunkc tiling::rule --owner \"Fantastical 2\" --state float

**Comment by crisidev** [comment]
If you are using latest chunkwm version, all call to chunkc in your chunkwmrc which are not core or set (ie tiling rules) need to be put in background with &.

**Comment by BrianGilbert** [comment]
@crisidev can you please give a real example of how to do that?

**Comment by crisidev** [comment]
All the tiling rules in chunkwmrc should have an & at the end. Like:
```
chunkc tiling::rule --owner \"Fantastical 2\" --state float &
```

**Comment by crisidev** [comment]
I am not sure this is your problem thou, but it is easy to try :smiley:

**Comment by koekeishiya** [comment]
The & on chunkc calls is not strictly necessary anymore in 0.3.8. I felt like it was a bad move to enforce that kind of a change when I could seemingly avoid it without any sideeffects (so far at least..).

**Comment by BrianGilbert** [comment]
I still seem to need the & on mine.. unless there is a related bug with behavior when going from 1 to 2 monitors without restarting the computer..

**Comment by BrianGilbert** [comment]
confirmed working for me without the ampersand using 0.3.8.

**Comment by jonathanwall** [comment]
this is not working for me on chunks 0.4.9. I've tried with and without ampersand with no luck, and I've installed chwm-sa
