### ISSUE TITLE
Plugin interaction

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/chunkwm#4]
How are plugins supposed to interact with each other? If I wanted to create a plugin for mouse support, would I be able to stop the tiling plugin temporarily while dragging a window? Does this require a rank for each plugin so they cannot lock down each other, causing a complete lockup of the application?

These are probably things that need to be implemented in the early stages of chunkwm.

**Comment by koekeishiya** [comment]
This is more or less the problem that I'm currently trying to work out.
I have a few things in mind, but need time to evaluate pros and cons,
possible limitations and consequences.

Any suggestions are welcome.

That aside, the progress on **chunkwm** will probably be rather slow, as the goal is to avoid all the stupid issues that Kwm fundamentally has.

**Comment by dominiklohmann** [comment]
I see three options here, is there anything else you have in mind?

1) Allow plugins to expose an API that other plugins can use. This allows for plugins to be of minimal size, but requires additional programming work per plugin. Would also require heavy documentation. It would probably also require all exposed functions to be thread safe.

2) Allow plugins to be temporarily disabled by other plugins. This allows for plugins to be of minimal size and focus on their functionality, but would require some sort of hack order between plugins. Might cause deadlocks if configured improperly.

3) Do not allow plugins to interact with each other. This requires certain functionality to be built into the same plugin as other functionality, e.g. the suggested mouse support would have to be in the tiling plugin. I feel like this unnecessarily complicates the code base in the long run.

> That aside, the progress on chunkwm will probably be rather slow, as the goal is to avoid all the stupid issues that Kwm fundamentally has.

I'm all for that. I hope discussions like this come up a lot in the early development stages of chunkwm.

**Comment by koekeishiya** [comment]
Considering something like the following, with the example of your first post in mind.

At first thought, a plugin could notify **chunkwm** that it temporarily requires exclusive access from some ( all ? ) of the events it subscribes to, until the critical behaviour has been dealt with.
Thus, causing this plugin to be the only one to receive that event. Only one plugin can have "ownership" of an event at a time, some form of priority queue is likely to be maintained.

The above however, would not allow the *mouse* plugin to stop the *tiling* plugin while moving a window, as window-specific events is currently handled by the plugin itself. This behaviour could be changed by having **chunkwm** provide an API and act as MITM, tracking all observers a plugin has requested. A plugin could then signal **chunkwm** to temporarily freeze potential observers.
 
This is of course not foolproof, as there is nothing stopping the plugin developer from using the MacOS API directly. Regardless, some sort of plugin state has to be maintained at least, such that it can be "interrupted".

A "simple" solution would be to have the plugin itself expose an interface to stop / reactivate certain functionality, through sockets. Of course, this has to be kept in mind by the plugin-developer.
Anyone that wants to interact with said plugin is now probably placed under greater limits.

**Comment by koekeishiya** [comment]
I'm going to be experimenting with a variant of your first suggestion:

> Allow plugins to expose an API that other plugins can use. This allows for plugins to be of minimal size, but requires additional programming work per plugin. Would also require heavy documentation. It would probably also require all exposed functions to be thread safe.

What I envision is that the **chunkwm** exposes a `ChunkwmBroadcasst` API to all plugins.
Each plugin receives a pointer to this function as they are loaded. 

The function would take an event-name and userdata as its parameters.
When calling this function, **chunkwm** will create a copy of its context for memory ownership and add the event to its work queue. The event will be prefixed with a unique identifier for the plugin that generated said evnent. These types of events will dispatch using a different handler, that is responsible for broadcasting the event to all connected plugins. 

Every other plugin that wants to do something when receiving said event just has to implement a handler. This would work kinda similar to how **chunkwm** itself subscribes to MacOS notifications through `NSWorkspace`.

We may not want to broadcast notifications to every plugin, I see some options for this.

We could define ways for a plugin to tell **chunkwm** that it wants notifications from plugin 'x'.
The plugin that sends an event has to specify a list of target plugins.

This depends entirely if we want opt-in, opt-out or giving the responsibility to the plugin which notifies or receives.
