### ISSUE TITLE
only one window tiles on secondary montitor since 0.3.6

### ISSUE THREAD

**Issue by kinglouie** [koekeishiya/chunkwm#403]
Since updating to the latest release I sometimes have the issue that my secondary monitor (builtin macbook display) will only allow one window, if I drag a second window onto the montor, it will switch places with the window currently on that monitor. 
I uploaded a [video](https://gfycat.com/AcidicConfusedHawk) to show the bug.

**Comment by kinglouie** [comment]
that damn accessibility api -.-
Today i noticed an additional odd behaviour. Sometimes when moving a window from one screen to another it also moves other windows as well. See [this new video](https://gfycat.com/TemptingDeficientDuiker)

**Comment by koekeishiya** [comment]
Do you think you could see if this also happens in v0.3.5? That's the version that introduced the commit i mentioned above.

**Comment by kinglouie** [comment]
Actually I told garbage in the first post, the issue was on 0.3.5, I thought I had 0.3.6 installed. Now I'm on 0.3.6 and as of now the issue didn't resurface. If it happens again I will post here, but for now I think it is resolved with 0.3.6.

**Comment by kinglouie** [comment]
okay it seems that the bug wasn't gone, at the moment im experiencing the same issue as in the video with a Safari window and a textedit window. Im currently on 0.3.8

**Comment by kinglouie** [comment]
It even happens when I move some windows around with the warp command
see [this video](https://gfycat.com/HauntingHoarseDrongo) where a wanted to warp the top left window -> east

**Comment by koekeishiya** [comment]
Pretty sure it is the commit I mentioned earlier. I'll remove those changes.

**Comment by koekeishiya** [comment]
I've removed the code I mentioned, on the latest master. Hopefully this fixes the issue you've been seeing.

**Comment by koekeishiya** [comment]
Let me know if you are still having this problem and I will reopen the issue. It should be fixed though.
