### ISSUE TITLE
No command to kill chunkwm

### ISSUE THREAD

**Issue by lesseradmin** [koekeishiya/chunkwm#41]
There should be a command like `chunkwm exit` or `chunkwm stop` to kill chunkwm. Maybe also include a `chunkwm restart` or `chunkwm reset` to restart the service.

**Comment by koekeishiya** [comment]
I don't really see this as a necessity because launchd will manage the lifetime, and already have these features.

**Comment by lesseradmin** [comment]
How about creating an icon that can be placed in the menu bar to also have a small, out of the way, GUI for the software. Logs can be viewed here as well as having commands to allow for restart and exit.

**Comment by chrishoage** [comment]
👎 for anything that would create more of a dependency on XCode 

If you'd like something that sits in the menu bar I'd suggest "bitbar", you can write shell scripts that interface with chunkwm and trigger launchctl commands.

**Comment by dominiklohmann** [comment]
Honestly if you want a menubar integration why not just write it as a plugin for yourself, you might even wanna link it in the wiki or in relevant issues. As it is, I really appreciate the command line only approach of Kwm/Khd/chunkwm, since they all have a really small footprint. Definitely have to agree with @chrishoage on this.

**Comment by koekeishiya** [comment]
I don't think this is something that I will be adding to the core version of **chunkwm**.

I will open the **wiki** at some point, and people will be free to develop and post a link to their plugin, or other types of scripts, configurations and so on, there.

**Comment by lesseradmin** [comment]
I realized that `killall chunkwm && killall khd` can be used to kill these processes.
