### ISSUE TITLE
Preselect border option not working

### ISSUE THREAD

**Issue by andpalmier** [koekeishiya/chunkwm#411]
Hi, thanks for your awesome work.

I'm trying to enable the borders only when I'm choosing the window to focus on, so that they will disappear when I have chosen the window.

Currently I'm using those options, to see if I'm able to spot some differences, but it seems that preselect mode is not active, because the borders are never bigger than 1px.

```
chunkc set preselect_border_width        10
...
chunkc set focused_border_width          0
``` 

Thanks.

**Comment by koekeishiya** [comment]
The preselection border only shows if you do a *tiling::window --use-insertion-point* command, or utilize the mouse-drag system in a bsp-space.

**Comment by andpalmier** [comment]
Thank you so much for the clarification.

Is there a way to show borders only while choosing the window to focus on?

**Comment by koekeishiya** [comment]
I don't really understand what you mean by "while choosing the window to focus on".
Could you try and clarify, possibly with an example?
