### ISSUE TITLE
When switching to external monitor windows are not resized.

### ISSUE THREAD

**Issue by kylehovey** [koekeishiya/chunkwm#414]
Steps to reproduce:

1. Launch `chunkwm` (using on OS X 10.13.4, Macbook Pro Retina late 2013)
2. Plug in HDMI cable that connects to external monitor at a different resolution

Temporary fix:

`brew services restart chunkwm`

**Comment by koekeishiya** [comment]
Support for hotplugging monitors has not been implemented. See #16 #313

**Comment by koekeishiya** [comment]
I quickly looked into this and this specific functionality was actually really simple to deal with. Implemented on master.

**Comment by msarmstr** [comment]
Unfortunately, this is still an issue for me in some cases. I have a Macbook Pro 15-inch 2017, OS X 10.13.5. I connect two external displays via a thunderbolt 3 dock: 4k and 1440p.

When transitioning from laptop-only -> close laptop -> plug in dock while laptop in clamshell mode, the windows resize correctly to the external monitors.

However, when doing the reverse, unplugging dock -> opening laptop, the windows flicker and attempt to resize, but then are sized larger than the Macbook display.

Temporary fix is to restart chunkwm.
