### ISSUE TITLE
Crash continuously: chunkc. Too many corpses being created.

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/chunkwm#416]
Hi,

I am unable to run chunkwm since today.

I upgraded to latest version but stille have the issue.

I see in in the console logs the messages: 

```
par défaut	00:45:28.663061 +0200	kernel	Process[2008] crashed: chunkc. Too many corpses being created.
erreur	00:45:28.664443 +0200	ReportCrash	Failed to start process notifications for pid 2007 (16)
par défaut	00:45:28.665638 +0200	ReportCrash	Removing excessive log: <private>
par défaut	00:45:28.666790 +0200	ReportCrash	Removing excessive log: <private>
par défaut	00:45:28.667137 +0200	ReportCrash	Removing excessive log: <private>
par défaut	00:45:28.667741 +0200	ReportCrash	Removing excessive log: <private>
par défaut	00:45:28.667844 +0200	ReportCrash	Removing excessive log: <private>
par défaut	00:45:28.668151 +0200	taskgated	MacOS error: -67062
```

Any hint ?

Thanks,

**Comment by koekeishiya** [comment]
When #376 was fixed, it had a stupid sideeffect that any chunkci invocation ran from the config-file had to be backgrounded.

This has now been fixed in v0.3.8 (brew has not been updated so you need to pull from master).

**Comment by crisidev** [comment]
@koekeishiya i am without my laptop until tonight. If you want to release 3.8, you have write perms on the homebrew repo. Otherwise I can do it as soon as I am home.

**Comment by koekeishiya** [comment]
@crisidev Hmm says write permission denied. Anyway, I opened a PR atleast so you can just merge that when you get back home.

**Comment by crisidev** [comment]
Weird. I will check as soon as I am on the laptop. In the meantime I merged the PR. Thanks!!

**Comment by mickaelperrin** [comment]
Thanks a lot ! the HEAD version works !
