### ISSUE TITLE
Slack not resizing properly in tiling mode

### ISSUE THREAD

**Issue by edran** [koekeishiya/chunkwm#417]
Slack significantly breaks chunkwm when resizing, moving, or spawning the window. This gets obviously better when toggling float, since Slack then doesn't interact with any other window, however it's not really a good workaround :(

OS: High Sierra 10.13.4 (17E202)
Chunkwm: 0.3.8
Slack: 3.1.1

![output](https://user-images.githubusercontent.com/3375046/40317051-24981a10-5d18-11e8-9673-56b7b8647123.gif)

**Comment by koekeishiya** [comment]
Not something I can fix, this is an issue with Slack.

**Comment by koekeishiya** [comment]
Closing this, since it's not really an issue with chunkwm.

**Comment by Tylerc230** [comment]
Anyone come up with any work arounds? It is kind of annoying. (Slack seems to misbehave with all wms).

**Comment by rjhilgefort** [comment]
It has a min-width which is outside the control of window managers.

**Comment by Tylerc230** [comment]
But it seems to be more than just size, it doesn't seem to position itself properly. Sometimes it will be in the top left corner when it is supposed to be in the bottom right. If you drag it toward the proper position it will pop into place.

**Comment by rjhilgefort** [comment]
🤔Hmm, then I'm not sure. I've just seen slack have an aggressive min-width when trying to resize it.

**Comment by Tylerc230** [comment]
Could be an electron thing. I know Slack isn't a typical native app. Thanks!
