### ISSUE TITLE
Option to keep floating windows always on top

### ISSUE THREAD

**Issue by edran** [koekeishiya/chunkwm#418]
Would it be feasible to copy i3's behaviour and force the floating windows to always be on top of the tiled windows?

It seems like there might be some MacOS API to do this: [link](https://apple.stackexchange.com/questions/219116/any-nice-stable-ways-to-keep-a-window-always-on-top-on-the-mac)

**Comment by koekeishiya** [comment]
This is already implemented, but you need to install https://github.com/koekeishiya/chwm-sa and enable the feature: `chunkc set window_float_topmost 1` in your config-file. See https://github.com/koekeishiya/chunkwm/issues/229

**Comment by edran** [comment]
I see, thanks! Closing this issue for now then :)
