### ISSUE TITLE
Move floating windows with keyboard

### ISSUE THREAD

**Issue by njunxuan** [koekeishiya/chunkwm#419]
Sorry if I missed this somewhere, but is there any way to move floating windows with only keyboard shortcuts. 

Thank you so much for this awesome piece of work!

**Comment by koekeishiya** [comment]
Take a look at the *grid-layout* command. https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#grid-layout

If the above link isn't clear enoguh, see #300 

There is no way to do relative movement of windows using the keyboard, and this is not going to be implemented.

**Comment by njunxuan** [comment]
I see thanks for this.
