### ISSUE TITLE
Chrome incognito window seems to be ignored

### ISSUE THREAD

**Issue by alok** [koekeishiya/chunkwm#421]
- OS: 10.13.4
- chunkwm version: latest build from master

Regular chrome windows tile fine but incognito windows often just float there, until I restart chunkwm.

**Comment by koekeishiya** [comment]
Do you have any form of tiling rules, or something? Is the incognito window opened in any special way ?

I'm unable to reproduce this by simply using the *shift + cmd + n* shortcut provided by chrome.

**Comment by chrishoage** [comment]
I too am unable to repo this.

**Comment by alok** [comment]
I'll try to find some way to reproduce this then.

**Comment by koekeishiya** [comment]
I don't mind you leaving the issue open if it is a problem you have / had. It's just that I can't really do much until I can reproduce the problem :)
