### ISSUE TITLE
Start a floating terminal

### ISSUE THREAD

**Issue by bin4ryio** [koekeishiya/chunkwm#422]
Hi there, thanks for the great WM. I was wondering if there's a possibility to configure `alt + \` to start a floating terminal.

**Comment by crisidev** [comment]
You can use a combination of chunkc commands to tell chunkwm to float the next window open. Something like:

```
alt + \                : chunkc set window_float_next 1; command_to_open_a_new_terminal_window
```

**Comment by bin4ryio** [comment]
Did not know I can chain command using `;`. Much thanks @crisidev, appreciate it.
