### ISSUE TITLE
Chunkwm stopped working

### ISSUE THREAD

**Issue by zifeo** [koekeishiya/chunkwm#424]
Happened randomly to me today, I restarted the service through `brew services` and `chunkwm` stopped working. I've also tried to reset `chunkwm`, reboot, reinstall or codesign (#295) but I keep seeing nothing. This could be similar to #391.

On some restart I can see an error but nothing gets logged to the log file:
```shell
~ brew services list
Name       Status  User      Plist
chunkwm    error   redacted /Users/redacted/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist
```

Here is the output of the console with `brew services restart chunkwm`:
```
par défaut	22:05:28.696195 +0200	tccd	PID[8465] is checking access for target PID[8465]
par défaut	22:05:28.699120 +0200	trustd	cert[0]: AnchorTrusted =(leaf)[force]> 0
par défaut	22:05:28.699597 +0200	taskgated	MacOS error: -67062
par défaut	22:05:28.712047 +0200	trustd	cert[0]: AnchorTrusted =(leaf)[force]> 0
par défaut	22:05:28.714364 +0200	launchservicesd	CHECKIN:0x0-0x7c07c 8465 (null)
par défaut	22:05:28.716517 +0200	lsd	Failed to register <private>: -10811
par défaut	22:05:28.833420 +0200	trustd	cert[0]: AnchorTrusted =(leaf)[force]> 0
par défaut	22:05:28.835099 +0200	tccd	PID[337] is checking access for target PID[8465]
par défaut	22:05:28.837743 +0200	trustd	cert[0]: AnchorTrusted =(leaf)[force]> 0
par défaut	22:05:28.842676 +0200	tccd	PID[471] is checking access for target PID[8465]
par défaut	22:05:28.845283 +0200	trustd	cert[0]: AnchorTrusted =(leaf)[force]> 0
par défaut	22:05:28.848283 +0200	tccd	PID[597] is checking access for target PID[8465]
par défaut	22:05:28.851016 +0200	trustd	cert[0]: AnchorTrusted =(leaf)[force]> 0
par défaut	22:05:28.854378 +0200	tccd	PID[665] is checking access for target PID[8465]
par défaut	22:05:28.858135 +0200	trustd	cert[0]: AnchorTrusted =(leaf)[force]> 0
par défaut	22:05:28.861388 +0200	tccd	PID[1121] is checking access for target PID[8465]
par défaut	22:05:28.864040 +0200	trustd	cert[0]: AnchorTrusted =(leaf)[force]> 0
par défaut	22:05:28.873785 +0200	taskgated	MacOS error: -67062
par défaut	22:05:28.880035 +0200	taskgated	MacOS error: -67062
par défaut	22:05:28.885909 +0200	taskgated	MacOS error: -67062
...
par défaut	22:05:29.016664 +0200	taskgated	MacOS error: -67062
par défaut	22:05:29.022330 +0200	taskgated	MacOS error: -67062
par défaut	22:05:29.028272 +0200	taskgated	MacOS error: -67062
par défaut	22:05:29.034587 +0200	tccd	PID[684] is checking access for target PID[8465]
par défaut	22:05:29.034807 +0200	tccd	PID[680] is checking access for target PID[8465]
par défaut	22:05:29.034974 +0200	tccd	PID[681] is checking access for target PID[8465]
par défaut	22:05:29.037167 +0200	tccd	PID[673] is checking access for target PID[8465]
par défaut	22:05:29.037214 +0200	tccd	PID[677] is checking access for target PID[8465]
par défaut	22:05:29.037295 +0200	tccd	PID[675] is checking access for target PID[8465]
par défaut	22:05:29.037625 +0200	tccd	PID[4864] is checking access for target PID[8465]
par défaut	22:05:29.037645 +0200	tccd	PID[1118] is checking access for target PID[8465]
par défaut	22:05:29.037655 +0200	tccd	PID[683] is checking access for target PID[8465]
par défaut	22:05:29.037929 +0200	tccd	PID[682] is checking access for target PID[8465]
par défaut	22:05:29.037969 +0200	tccd	PID[679] is checking access for target PID[8465]
par défaut	22:05:29.039794 +0200	trustd	cert[0]: AnchorTrusted =(leaf)[force]> 0
...
```

Even weirder, I wanted to fallback to `kwm` and even `kwm` is not working now... What would be the next debug steps to try?

Might be also related : #420, #415

**Comment by koekeishiya** [comment]
This does seem like an issue with the accessibility setting. Try to stop the brew service, uninstall chunkwm, remove chunkwm from the accessibility pane. Then reboot your system, install chunkwm etc.

**Comment by zifeo** [comment]
I've already tried that process a few times without success. It seems to be persistent over the restart. I highly suspect something related codesign (e.g. what happens if a signed certificate is removed without unsigning?). Is that plausible?

**Comment by koekeishiya** [comment]
> I've already tried that process a few times without success. It seems to be persistent over the restart. I highly suspect something related codesign (e.g. what happens if a signed certificate is removed without unsigning?). Is that plausible?

I don't think that should matter. At least I've never had any problems related to that myself.
I don't really know what else you can try :/

**Comment by zifeo** [comment]
I just saw that the option "Screen have distinct spaces" got somehow unticked in Mission Control. After enabling it again, `chunkwm` started working again 😄 . The errors I got is still surprising, would it be worth to have a nicer check and avoid the confusion with the accessibility permissions?

**Comment by koekeishiya** [comment]
> Screen have distinct spaces

We do a check for this in the code. Should have been returning an error. See https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/plugin.mm#L1708

Did that not trigger on your side?

**Comment by koekeishiya** [comment]
Seems like some other plugins (border?) also utilized some functions that require `displays have separate spaces` to be set. I moved the check for this out of the tiling plugin and into the chunkwm-core for good measure (in 0.3.9).

**Comment by zifeo** [comment]
The log file was set but resulted in a blank file.

**Comment by JustAPerson** [comment]
I also find that chunkwm will break without the "Displays have separate spaces" checked. 

However, there's nothing that indicated this was necessary when I installed 0.4.6 from brew. The daemon will ask for the Accessibility permissions and then seems to crash shortly thereafter. It can't be seen in htop. `brew services list` shows it in yellow. The `~/.chunkwmrc` hadn't even been run yet so there was no log file.

**Comment by dominiklohmann** [comment]
> I also find that chunkwm will break without the "Displays have separate spaces" checked.
> 
> However, there's nothing that indicated this was necessary when I installed 0.4.6 from brew.

3rd line in the user guide: https://koekeishiya.github.io/chunkwm/docs/userguide.html

> chunkwm requires ['displays have separate spaces'](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/osx/separate_spaces.png) to be enabled.

**Comment by JustAPerson** [comment]
Some kind of run time notice would be appreciated rather than silently crashing.

**Comment by koekeishiya** [comment]
It doesn't crash. An error is printed to stderr, and then chunkwm exits. I'm not sure if the .plist file provided with the brew installation handles stdout/stderr.
