### ISSUE TITLE
Vim and iTerm blocking shortcuts 

### ISSUE THREAD

**Issue by yamini-krishnamurthy** [koekeishiya/chunkwm#428]
Some of the shortcuts I have programmed (alt + arrow keys, shift + cmd + arrow keys) don't work. I looked at my iTerm key bindings and "ignored" all of them because I use none, but it still doesn't work. These are the ones I'm talking about.  

 # focus window
 alt - left : chunkc tiling::window --focus west
 alt - down : chunkc tiling::window --focus south
 alt - up : chunkc tiling::window --focus north
 alt - right : chunkc tiling::window --focus east

# move window
 shift + cmd - left : chunkc tiling::window --warp west
 shift + cmd - down : chunkc tiling::window --warp south
 shift + cmd - up : chunkc tiling::window --warp north
 shift + cmd - right : chunkc tiling::window --warp east

Any help would be appreciated.

**Comment by net** [comment]
In iTerm press **⌥⌘S**, or go to **iTerm > Secure Keyboard Entry**.

**Comment by lvadla** [comment]
I had this same problem with iTerm2 and solved it by disabling **iTerm2 > Secure Keyboard Entry** (in the menu bar) as per @net's suggestion.

**Comment by koekeishiya** [comment]
the latest version of *skhd* will output during startup if secure keyboard entry is enabled, and which process enabled it. closing this.
