### ISSUE TITLE
Can't focus specific desktops

### ISSUE THREAD

**Issue by KevinSjoberg** [koekeishiya/chunkwm#429]
I've 6 virtual desktops. I'm trying to focus one of them using `chunkc tiling::desktop --focus 2`. Unfortunately, nothing happens. Am I missing something critical?

I'm using `chunkwm 0.3.9` and `skhd version 0.2.2` both installed via Homebrew and both have Accessibility enabled.

**Comment by koekeishiya** [comment]
You need to install https://github.com/koekeishiya/chwm-sa and be running High Sierra for the *desktop --focus* command to work. See #127 for history.

**Comment by KevinSjoberg** [comment]
Thank you. Thought I looked through previous issues but I guess not. 🙂
