### ISSUE TITLE
Plugin: Add nonbinary tiling mode to have vertical thirds. 

### ISSUE THREAD

**Issue by lesseradmin** [koekeishiya/chunkwm#43]
Add a plugin to allow for nonbinary tiling. Since the current tiling manager uses a binary tree to manage windows, it cannot split into thirds.

[Here](http://dotshare.it/public/images/uploads/1283.png) is an example from i3 that allows for splitting into thirds.

I attempted to recreate this in chunkwm using the increase and decrease region commands but this is the closest i could get:
![image](https://cloud.githubusercontent.com/assets/7121943/25731189/ccda0dc8-3109-11e7-9522-2e72d5b72899.png)
Here there is a noticeable difference in size, the left two terminal windows are larger than the third.

**Comment by koekeishiya** [comment]
See  `chunkc desktop ---equalize`

**Comment by koekeishiya** [comment]
This is not something that I will do, however, other users are free to implement their window management plugin if other behaviour is wanted.

This is more or less why this is plugin-based, to separate the logic of interfacing with MacOS from whatever the user might want to do.

**Comment by alok** [comment]
do you know if anyone ever ended up writing a plugin for this?

**Comment by koekeishiya** [comment]
Not that I’m aware of. You can use the command I mentioned earlier in this issue to get an equal split. It doesn’t really matter that the internal structure is a binary-tree.

Sent from my iPhone

On 24 May 2019, at 11:33, Alok Singh <notifications@github.com<mailto:notifications@github.com>> wrote:


do you know if anyone ever ended up writing a plugin for this?
