### ISSUE TITLE
[ffm] Switching from Safari with visible status bar doesn't focus next app immediatly

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#432]
Strange issue I'm experiencing, to reproduce:
1- Have safari and another app with windows open on the same space
2- Focus Safari window and hover over a link close to the border of the window (the border next to the other app window) , thus showing the status bar on the bottom
3- Move cursor away from link and safari window to the other window app

Expected result:
Other window is immediatly focused

Actual behaviour:
Need to move the cursor again while inside the other window to get the window to focus

**Comment by koekeishiya** [comment]
IIRC The statusbar actually triggers a windowcrwated + focused event, which activates standby-on-float. When the mouse is  moved out of safari, the window is then destroyed which resets the standby-on-float status.

**Comment by koekeishiya** [comment]
So I actually came up with a way to solve this. Fixed on master.

**Comment by koekeishiya** [comment]
Had to undo this as it caused a regression for other applications, see for example #455 

This is an issue we are going to have to live with..
