### ISSUE TITLE
Focusing a floating window disables ffm

### ISSUE THREAD

**Issue by blahsd** [koekeishiya/chunkwm#437]
### My system
macOS 10.13.4
chunkwm 0.3.9
ffm enabled

### Observed behaviour
With some windows tiling and one window floating;
moving the mouse over the floating window focuses said window;
moving the mouse back over the tiling windows **does not** focus the window.

**Comment by koekeishiya** [comment]
This is actually a feature. See https://github.com/koekeishiya/kwm/issues/97 for history.

**Comment by blahsd** [comment]
I see! Interesting. It doesn't look like it's possible to disable it now is it? I tried `chunks config focus standby-on-float disable` but I'm kinda in the dark

**Comment by koekeishiya** [comment]
It’s not an option that is configurable right now, as I try to minimize bloat. From what I can see, most people already find it hard enough to configure chunkwm.

On 4 Jun 2018, at 19:00, blahsd <notifications@github.com<mailto:notifications@github.com>> wrote:


I see! Interesting. It doesn't look like it's possible to disable it now is it? I tried chunks config focus standby-on-float disable but I'm kinda in the dark

**Comment by blahsd** [comment]
Oh :(

**Comment by koekeishiya** [comment]
I am open to removing this / making it configurable since I have just been able to work a fix for #229, which was the only reason I was still using this functionality.

**Comment by blahsd** [comment]
Oh :D 

I'm voting for configurable then! Can never have enough configuration

**Comment by koekeishiya** [comment]
fixed on master. `chunkc set ffm_standby_on_float 1 | 0`

**Comment by blahsd** [comment]
Jesus that was quick. Thanks!!
