### ISSUE TITLE
macOS 10.14 Mojave

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/chunkwm#439]
This is our yearly little thread that I will update with bugs as I find them. This year I'm running Mojave on my personal machine.

`chunkwm` and `chunkc` are running fine so far, carried over from my previous macOS installation.

When compiling `chunkwm` using `make` I get this error, indicating that some underlying stuff seems to be inaccessible.
```cpp
In file included from src/core/chunkwm.mm:31:
src/core/../common/accessibility/display.mm:33:25: error: use of undeclared identifier 'CGDisplayCreateUUIDFromDisplayID'
    CFUUIDRef UUIDRef = CGDisplayCreateUUIDFromDisplayID(Id);
                        ^
src/core/../common/accessibility/display.mm:355:29: error: use of undeclared identifier 'CGDisplayCreateUUIDFromDisplayID'
    CFUUIDRef DisplayUUID = CGDisplayCreateUUIDFromDisplayID(DisplayID);
                            ^
2 errors generated.
make: *** [makefile:23: bin/chunkwm] Error 1
```

I did uninstall `chwm-sa` before upgrading, just to be safe. I will try this once I get `chunkwm` to compile.

I found this [macOS 10.13 to 10.14 API diff](http://codeworkshop.net/objc-diff/sdkdiffs/macos/10.14/) which might be of interest. It says `CGDisplayCreateUUIDFromDisplayID` and `CGDisplayGetDisplayIDFromUUID` have been removed from `ColorSync`.

Feel free to ask any questions for things you want tested. I will update this thread with each developer beta if I have the time to do so.

<hr/>

### Update 1

I solved the compile issue by adding this to `src/common/accessibility/display.mm`:

```cpp
extern "C" CFUUIDRef CGDisplayCreateUUIDFromDisplayID (uint32_t displayID);
```

Everything seems to run fine so far. Still have to test `chwm-sa`, but have other things coming up first.

**Comment by koekeishiya** [comment]
I'm very curious if Mojave breaks the fsat-desktop switching that was recently added to `chwm-sa` for High Sierra. I assume it will..

**Comment by dominiklohmann** [comment]
> I'm very curious if Mojave breaks the fast-desktop switching 

I'm assuming the code signature you're searching for in `Dock.app` might be incorrect now, which would cause this to break. I am currently downloading Mojave again to create a new recovery partition, since the update broke mine, leaving me unable to disable SIP currently.

There's also a new `nvram` boot argument for completely disabling 32-bit applications, which from my understanding is supposed to be the new default starting with macOS 10.15 (luckily not in 10.14). I will test whether this breaks anything in `chunkwm` as well. Let's just hope this leaves `Carbon` intact.

**Comment by alin23** [comment]
@koekeishiya I'm testing Mojave too and luckily, the fast switching still works flawlessly 😀

**Comment by dominiklohmann** [comment]
### New issue with right-click drag

I am unable to perform any `modifier + right-click drag` action, since `right-click` seems to take priority now and always opens a context menu. Workaround is to change `chunkwm` settings. Not exactly sure what can be done about this. Example:
```
chunkc set mouse_move_window             \"fn 1\"
chunkc set mouse_resize_window           \"fn cmd 1\"
```

**Comment by koekeishiya** [comment]
@alin23 
> I'm testing Mojave too and luckily, the fast switching still works flawlessly 😀

That seems like great news! I take it that they haven't done any major changes to how the Dock works internally then, which is good.

@dominiklohmann 
> There's also a new nvram boot argument for completely disabling 32-bit applications, which from my understanding is supposed to be the new default starting with macOS 10.15 (luckily not in 10.14). I will test whether this breaks anything in chunkwm as well. Let's just hope this leaves Carbon intact.

Carbon is partially ported to x86-64, and I suspect the parts the we rely on for **chunkwm** reside in this portion of Carbon, so I don't expect this to have any effect on us at all.

> Got it working, but it crashes Dock.app for me 100% when focusing a desktop that hasn't been focused before.

This seems to be the same issue @matthewdias is having trouble with (#431). We can continue trying to figure out that problem over in the referenced issue. 

> CFUUIDRef CGDisplayCreateUUIDFromDisplayID (uint32_t displayID);

This function is not strictly necessary for us to do what we need. I'm pretty sure I have an alternative way to achieve the same functionality, if necessary. For now it just looks like they have changed the header file that contains the definition, as all you had to do was declare it extern. That means we still link against the proper framework.

> I am unable to perform any modifier + right-click drag action, since right-click seems to take priority now and always opens a context menu. Workaround is to change chunkwm settings. Not exactly sure what can be done about this. Example:

This does seem like a bug in the developer version of macOS. We use the event-tap API to detect these, and that is considered a public stable API from Apple, so I doubt they would suddenly change how this works (but we can't know for sure).

Offnote:

I don't have an Apple Developer subscription, so I will have to wait for the first public beta to be released before I can install and test things myself. With that said, I do not expect anything to break really, with the exception of the fast-desktop switching (but that seems to be fine as well).
T

**Comment by dominiklohmann** [comment]
If anyone else wants to run `chunkwm` via Homebrew on Mojave, just `brew edit chunkwm` and add this after line 7:

```ruby
  patch do
    url "https://github.com/dominiklohmann/chunkwm/commit/94750d8c0b3456840254be4f3953e7eda964d3c2.diff"
    sha256 "3a1a4de843742225c663f4d186c708b875296ef5cd0382107be4252d5c0447e4"
  end
```

**Comment by crisidev** [comment]
Interestingly, the patch you are providing is also working on my (non high) Sierra. @koekeishiya maybe the API change has been already introduced in Sierra.

**Comment by dominiklohmann** [comment]
Nah, the system header file change is new, it's just that the changed line has no effect on compilation since it doesn't violate the ODR (iirc, it's been a while since I had to work with extern linkage).

**Comment by crisidev** [comment]
Gotcha. Thanks.

**Comment by dominiklohmann** [comment]
@kinglouie see #235 for that. Not sure what can be done about that.

**Comment by dominiklohmann** [comment]
I can not get #425 (adding and removing spaces with chwm-sa) to work on beta 1. Updating to beta 2 right now, servers are a little slow, will report on changes later/tomorrow.

**Comment by koekeishiya** [comment]
@dominiklohmann 

Could you maybe zip the Dock.app from Mojave and send to me? I'd like to mess around a bit with it.
Fairly certain I can make spaces creation / removal work on Mojave with a bit of work.

**Comment by koekeishiya** [comment]
@tmaone @dominiklohmann 

Can one of you try the latest commit on *chwm-sa* branch, and let me know if *creating spaces* works on Mojave now (have not looked at removing spaces yet, so that will not work) ?

**Comment by dominiklohmann** [comment]
> @tmaone gave me access, will take a look at this soon ish.

**Comment by dominiklohmann** [comment]
Found another issue: switching between windows in split fullscreen mode is broken. The culprit quite likely is the new draggable bar in the middle.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4488655/41911175-349eb748-794c-11e8-80c6-a8144ab7d757.png">

**Comment by koekeishiya** [comment]
@dominiklohmann 

I just upated to Mojave, and the latest chunkwm-sa commit works for me to create new spaces.
(Not the one bundled with chunkwm, but the chwm-sa repository).

**Comment by koekeishiya** [comment]
Added support for destroying spaces on latest chunkwm-sa (also bundled on the latest chunkwm master). Confirmed that fast switching, creating and destroying spaces all work on Mojave.

**Comment by tinder-jonathanwilner** [comment]
Tangentially related - I wound up in a spot where post Mojave, XCode 10 and CLT, it didn't properly create the /usr/include .... directories. Anyone else experience that, or is that something that happened because of how i did the update, including having SIP off during either the OS upgrade or XCode install?

**Comment by koekeishiya** [comment]
The latest macOS Mojave beta version broke chunkwm-sa *create space* and *destroy space*. I can't be bothered fixing these until the Mojave GM is released.

**Comment by koekeishiya** [comment]
@dominiklohmann 

> Found another issue: switching between windows in split fullscreen mode is broken. The culprit quite likely is the new draggable bar in the middle.

This appears to have been fixed in the latest macOS Mojave Beta. Both *ffm* and switching with the chunkwm commands work just fine for me (as it did in High Sierra).

**Comment by dominiklohmann** [comment]
You're absolutely right, dev beta 3 seems to have fixed that. Cannot target it with the AX inspector anymore either.

**Comment by dominiklohmann** [comment]
> I am unable to perform any modifier + right-click drag action, since right-click seems to take priority now and always opens a context menu. 

This is fixed in beta 3 also.

**Comment by dominiklohmann** [comment]
Beta 4: 
- Creating a new desktop crashes sometimes (not always)
- Frontmost app still loses focus randomly from time to time (bug from beta 3, not related to chunwkm)

Other than that it seems fine so far. Best performance I've seen in a while on this laptop.

**Comment by pegak** [comment]
Hello,
I updated to Mojave and wanted to use Chunkwm. I did:

- brew tap crisidev/chunkwm
- brew install chunkwm
- brew install skhd
- brew services start chunkwm
- Copied default chunkwm config
- Put mine config for skhd from my last machine
- Allowed accessibility in settings for skhd and chunkwm.
- Restarted computer

But nothing seems to work. Even running chunkc commands in terminal doesn't work. Anybody could help me please? :)

**Comment by sirn** [comment]
With Mojave is now released, I want to report that ScriptAdditions no longer work if SIP is enabled, even on the latest commit (built with `brew install chunkwm --HEAD`). It is working fine when SIP is disabled, however.

**Comment by FydeSW** [comment]
> With Mojave is now released, I want to report that ScriptAdditions no longer work if SIP is enabled, even on the latest commit (built with `brew install chunkwm --HEAD`). It is working fine when SIP is disabled, however.

I'm having the same problem, fast-desktop switching does not work for me.

**Comment by koekeishiya** [comment]
@sirn @FydeSW 

Unfortunately there is nothing we can do against this. I'll update the documentation to reflect this soon.
For now, if you want to have these features enabled, you'll just have to keep SIP disabled.

I do not take any stance on whether you should or shouldn't do this, and would advice any individual to do their own research and see if disabling SIP could cause security risks depending on how they have configured, and use their system.

**Comment by FydeSW** [comment]
> @sirn @FydeSW
> 
> Unfortunately there is nothing we can do against this. I'll update the documentation to reflect this soon.
> For now, if you want to have these features enabled, you'll just have to keep SIP disabled.

I see, it's not a big deal anyway, I'm using the native desktop switching and it's good enough for me.
Thanks.

**Comment by dominiklohmann** [comment]
It does work and unless you also use chwm-sa, there is no need to disable SIP. Only difference really is that instead of only needing SIP disabled to inject chwm-sa, it is now required for loading it.

**Comment by pkieltyka** [comment]
so I upgraded to Mojave, and chunk/skhd are working fine.. except, I'm getting constantly asked almost every interaction to give System Preferences of Security & Privacy permission for chunkwm or skhd in my Accessibility settings, which I've done over and over, and continues to prompt me. Anyone else?

**Comment by dominiklohmann** [comment]
@pkieltyka are your binaries codesigned?

**Comment by FydeSW** [comment]
@pkieltyka I had the same problem, I solved by stopping both services, disabling the permission, rebooting, giving the permission again and starting the services.

**Comment by net** [comment]
@koekeishiya you may also want to change https://github.com/koekeishiya/chunkwm/blob/8f85ce9724779a4326a9bafa90418ad67a35edd1/src/core/chunkwm.mm#L171

**Comment by koekeishiya** [comment]
Good catch, thanks.

**Comment by ibarani** [comment]
I heavily used chunkwm on high sierra but recently did a fresh install of Mojave but I cannot find a relevant brew formula to install. Any recommendations on how to install on Mojave?

**Comment by dominiklohmann** [comment]
@ibarani 
> I heavily used chunkwm on high sierra but recently did a fresh install of Mojave but I cannot find a relevant brew formula to install. Any recommendations on how to install on Mojave?

Nothing changed about that. Follow the instructions linked in the README step by step.

**Comment by dominiklohmann** [comment]
Closing as I consider this issue resolved.
