### ISSUE TITLE
BSP Serialization

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#44]
clarification: bsp serialization as "bsp layouts" in **kwm**

I'm thinking about dropping the bsp-serialization feature due to the ease of interacting with the window layout now. It's no longer this huge time-consuming process to relayout windows, like it was in **kwm**.

A huge reason for this is the new `chunkc desktop --equalize` command, (which is probably my most used command as of late), and it gives **chunkwm** the dynamic (flexible) feeling that I'm looking for. This is also the reason why this is a bsp window manager, and not based around layouts such as **Amethyst**. 

The complexity that a proper serialization system would need (note: not the one in **kwm**) does not feel worth it for me. I know that a lot of people are probably gonna disagree with me on this, but at the end of the day, I will be driving it towards the direction I want to.

The main reason I have doubts regarding the bsp-serialization feature, is that no matter how good it is, it will still feel rather clunky, due to the simple fact that the process can never be completely automated. We can store layout and node ratios, but never which window goes where (can be "guessed" through heuristics).

I personally think it is better to focus on providing useful operations for quickly modifying the layout on a need-by-need basis. Mouse-drag feature is still planned.

Please post your thoughts, thanks

**Comment by chrishoage** [comment]
"bsp-serialization" as what "layouts" are in kwm? 

Or "bsp-serialization" as in restoring the state of a bsp tree after a shutdown or a crash? 

If its the latter I think its fine. 

If the former, that's kind of a bummer. Restoring a layout is a pretty handy feature.

**Comment by koekeishiya** [comment]
> "bsp-serialization" as what "layouts" are in kwm?

This one, yeah.

**Comment by chrishoage** [comment]
My use-case for them are to change my work layout when switching from using an external monitor to using just my laptop. 

When I have lots of screen real-estate  I like having a specific layout, when I lack the real-estate I have one that has a different configuration. 

Being able to have these layouts restored at a keystroke is quite nice. 

I completely get the difficulty serializing the layout exactly, however being able to store a layout for later use I find handy for the reasons above.

**Comment by koekeishiya** [comment]
> I completely get the difficulty serializing the layout exactly (windows in the same order, etc), however being able to store a layout (container sizes) for later use I find handy for the reasons above.

I do see how that can be useful. I'll most likely put the feature on hold while we enter alpha-stage.
I'll probably look into doing a proper serialization system closer to the first release candidate. If it turns out to be more work than I can be bothered with (think it's worth), I'll port over the system used by **kwm** and leave it at that.

**Comment by chrishoage** [comment]
When I mentioned bsp tree serialization in the goals ticket it was a really "pie in the sky" idea. 

It's not something I think is super important. 

> I'll port over the system used by kwm and leave it at that.

I honestly think this is more than adequate, the system there is functional yet simple. Resizing containers with specific ratios and splits is a non-trivial process. Swapping windows into these pre-sized nodes _is_ a trivial process. 

Preserving window and application order is a "nice to have" feature, but is no where close to a requirement.

**Comment by koekeishiya** [comment]
@chrishoage 

>>  I'll port over the system used by kwm and leave it at that.

> I honestly think this is more than adequate, the system there is functional yet simple. Resizing containers with specific ratios and splits is a non-trivial process. Swapping windows into these pre-sized nodes is a trivial process.

I am not very satisfied with the system implemented in **kwm**, however the behaviour discussed [here](https://github.com/koekeishiya/kwm/issues/157) would be rather great to have.

To summarize: 

> The behaviour I would like to have is the following:

>  1. Apply layout to space (doesn't matter how or when)
    2. There are not enough windows to fill the layout, so we optimize tiling for space
    3. Opening a new window will tile into the layout as expected, thus reorganizing the structure of
       all windows

To achieve this, I have to re-think how leaf-nodes (windows) are presented, and I have come up with one theoretical solution to how this problem can be approached.

I'm gonna deem preservation of window and / or application order out of scope.

**Comment by Michael-Jing** [comment]
I have use i3 tilling window manager for more than 1 years, it's very predictable and usable. I even install Ubuntu on my mac box only because I want to use i3. But after a forcing shutdown, I was not able to boot into the system, and Ubuntu consumes battery much faster than MacOS, So I switched back to MacOS. So maybe you can bring some ideas from i3.

**Comment by chrishoage** [comment]
> I'm gonna deem preservation of window and / or application order out of scope.

What you described above is more than adequate. Preservation of window and / or application is not at all important when it is so easy to swap windows with commands. 

Thank you!

**Comment by koekeishiya** [comment]
The tree layout can be written to file with the following command:
`chunkc desktop --serialize | -s <absolute path to file>`

The tree layout can be restored from file with the following command:
`chunkc desktop --deserialize | -d <absolute path to file>`

Behaviour as described above.

Short screencast, showing opening of windows BEFORE and AFTER deserialize has been run.
![chunkwm_serialization](https://cloud.githubusercontent.com/assets/6175959/26487615/7317987a-4200-11e7-90ab-e4a222eb6c54.gif)

**Comment by choco** [comment]
@koekeishiya This is probably the stupidest request ever, but could you keep 3 digit precision after the decimal point (instead of 2)?

**Comment by koekeishiya** [comment]
sure will do
