### ISSUE TITLE
Respect offset and gap settings for floating/grid windows

### ISSUE THREAD

**Issue by sbstnc** [koekeishiya/chunkwm#440]
I think it would be nice if the grid layout for floating windows respected the configured gaps. This is probably going to require some further thought, but I would expect it to behave somewhat like this...

Given:
```
chunkc set global_desktop_offset_top     10
chunkc set global_desktop_offset_bottom  10
chunkc set global_desktop_offset_left    10
chunkc set global_desktop_offset_right   10
chunkc set global_desktop_offset_gap     10
```

When:
`chunkc tiling::window --grid-layout 1:2:0:0:1:1`

Then:
```
window_width = (screen_width - (offset_left + offset_right)) * (n_cols_occupied/n_cols_total) - offset_gap/2
```
e.g. for a 1080p screen with given config this would be equal to 945px
```
window_height = (screen_height - (offset_top + offset_bottom)) * (n_rows_occupied/n_rows_total)
```
e.g. for a 1080p screen with given config this would be equal to 1060px

And:
When:
`chunkc tiling::window --grid-layout 2:2:0:0:1:1`

Then:
```
window_width = (screen_width - (offset_left + offset_right)) * (n_cols_occupied/n_cols_total) - offset_gap/2
```
e.g. for a 1080p screen with given config this would be equal to 945px
```
window_height = (screen_height - (offset_top + offset_bottom)) * (n_rows_occupied/n_rows_total) - offset_gap/2
```
e.g. for a 1080p screen with given config this would be equal to 525px

**Comment by koekeishiya** [comment]
Agreed, this was actually bugging me today..

**Comment by koekeishiya** [comment]
fixed on master.
