### ISSUE TITLE
Dual Monitor setup messes up offset when the dock is on the left side

### ISSUE THREAD

**Issue by gerrit-h** [koekeishiya/chunkwm#445]
This bug started seemingly randomly while using v0.4.2 (which was working perfectly fine before).

Whenever I have my second display connected, the offset on my built-in display is ignoring the dock:
![Main Display](https://user-images.githubusercontent.com/13509208/41434721-fda7b83a-701c-11e8-9fb0-5a05edb8125a.png)

On my second display is enough space for the dock, even though it will never appear there:
![Secondary Display](https://user-images.githubusercontent.com/13509208/41434720-fd848a90-701c-11e8-95f8-541831b836cd.png)

This only happens with the dock on the left side. Aligning it to the bottom or right side works as expected. Also using just the built-in display does not have this issue.

The only rules I use for the offset are global rules and custom_bar is disabled.
I'm on a MacBook Pro (Late 2013), 10.13.5

**Comment by koekeishiya** [comment]
The padding is applied to the left-most display, as that is where the Dock should(?) be.
Is the display with the padding (second screenshot) not your left-most display??
Could you show what the display arrangement looks like?

**Comment by gerrit-h** [comment]
The built-in display is on the bottom, the secondary one on top.
Because my dock is on the left side, it only appears on the built-in display and never on the other one.
But it looks like chunkwm is expecting the dock on the second display and not on the built-in one.

<img width="780" alt="screen shot 2018-06-15 at 09 18 58" src="https://user-images.githubusercontent.com/13509208/41455368-325ad480-707d-11e8-886b-994f00aa1daa.png">

**Comment by gerrit-h** [comment]
Yeah, that works. Thanks for your help!

**Comment by dominiklohmann** [comment]
Instead of comparing the outer coordinates, why not compare the display center coordinates, falling back to the main display if necessary?

**Comment by koekeishiya** [comment]
I'm still confused why it correctly assigns padding when you set the Dock to position to the right, as that is basically doing the exact same thing, just for the right-most display, which also should have resulted in the top display.

**Comment by koekeishiya** [comment]
So I did some testing, and it appears that the Dock (when positioned to the left or right) is always on the primary display, if the primary display is not "within" the y : height bounds of the other monitor.

I wonder if this is tricky to solve for 3-4 monitor setups..

**Comment by koekeishiya** [comment]
Turns out there was a multitude of situations where this was wrong. This has been corrected in the latest commit after watching how the Dock moves around in the different arrangement situations (only tested using 2 monitors though.)
