### ISSUE TITLE
Possible to change the insertion point of an existing window ?

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/chunkwm#449]
Hi,

I was wondering if I can change the insertion point of an existing window?

For example, I would like to switch from this arrangement:
![](https://i.imgur.com/kKoYtJe.jpg)
to this one:
![](https://i.imgur.com/zS0eUoj.jpg)

Thanks,

**Comment by dominiklohmann** [comment]
For your example, you could just `chunkc tiling::window --warp west` from the top right window (if that does not work, rotate your tree by 90 degree). This one is not very intuitive. 

You could also run `chunkc tiling::window --use-insertion-point east` from the top left window and then run `chunkc tiling::window --toggle float` *twice* on the window you want to insert in that spot.

**Comment by mickaelperrin** [comment]
Awesome, thanks !
