### ISSUE TITLE
Brew Services Start returns permissions denied

### ISSUE THREAD

**Issue by LEO-E-100** [koekeishiya/chunkwm#453]
After running `chunkwm` the correct behaviour is seen. However upon running `brew services start chunkwm` the following error message is returned:

`Error: Permission denied @ rb_sysopen - /Users/{USER}/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist`

I have downloaded from Homebrew as [described here](http://hde-advent-2017.hatenadiary.jp/entry/2017/12/24/000000). I also have no `chunkwm` check box in my Security and Privacy -> Accessibility menu. 

When running services start with sudo no error is returned but the service does not become active even after a restart.

**Comment by crisidev** [comment]
Hello, do you mind to send me the output of these commands:

```
brew services list
ls -l /Users/$USER/Library/LaunchAgents/
```

**Comment by koekeishiya** [comment]
I'm not gonna pretend that I know how *brew services* are implemented, but you should not try to run chunkwm with sudo. I've explicitly made chunkwm not run under root privileges. See https://github.com/koekeishiya/chunkwm/blob/master/src/core/chunkwm.mm#L230

**Comment by LEO-E-100** [comment]
`brew services list` shows:

```
chunkwm    started     root /Library/LaunchDaemons/homebrew.mxcl.chunkwm.plist
khd              started     root /Library/LaunchDaemons/homebrew.mxcl.khd.plist
skhd            stopped
```

`ls -l /Users/$USER/Library/LaunchAgents/` shows:

```
-rw-r--r--  1 root  staff  390 30 Apr 12:26 com.microsoft.OneDriveMigrationLauncher.plist
```

**Comment by crisidev** [comment]
Given you have started chunkwm via brew as root, as you can see both khd and chunkwm are started as root. You need to revert that and be sure your user have write permissions inside /Users/$USER/Library/LaunchAgents/

**Comment by Joellidin** [comment]
I have the exact same problem. ``brew services list`` shows:

**Comment by socketwiz** [comment]
I also ran into this issue but I did not use `sudo` to start my service.  I got around it by manually copying the `plist` file:

```
sudo cp /usr/local/Cellar/chunkwm/0.4.8/homebrew.mxcl.chunkwm.plist ~/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist
```

Then I ran `launchctl` directly at which point I did receive the prompt to give `chunkwm` the accessibility permission and it does seem to be working correctly now:

```
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist
```

**Comment by Joellidin** [comment]
@socketwiz Do you have any tips have one would disable `chunkwm` after doing like you said? I only getting permission denied after doing ``brew services stop chunkwm``.

The reason I want to disable it is because my programs are running much slower than I remember them doing before installing `chunkwm`. I would like to get it to work properly because it seems like an great window manager!

**Comment by socketwiz** [comment]
> @socketwiz Do you have any tips have one would disable chunkwm after doing like you said? I only getting permission denied after doing brew services stop chunkwm.

You start with the `load` command.  You stop with the `unload` command.
