### ISSUE TITLE
Possible to disable FFM per app?

### ISSUE THREAD

**Issue by bobbybroadcast** [koekeishiya/chunkwm#455]
I'm having problems with Chrome and uMatrix while in tiling mode. When selecting the uMatrix icon, a drop down appears and is given a border by chunkwm. There is a tiny amount of space between the icon and the new window, causing Chrome to take focus. Problem is solved only by either moving the mouse as fast as possible (often failing) or turning off FFM entirely. Anyway to do this per app? Or any better solution?

**Comment by koekeishiya** [comment]
Fixed on the latest master.
