### ISSUE TITLE
invalid selector

### ISSUE THREAD

**Issue by evan01** [koekeishiya/chunkwm#458]
Skhd is running, and so is chunkwm, the windows automatically resize themselves as normal. When I have 2 split windows, and I run the command `chunkc tiling::window --toggle fullscreen`. Chunkwm displays this error.

> for window flag 't'ARN :     invalid selector 'fullscreen

Any idea why? I'd love to be able to make get the tiling plugin to work.

**Comment by koekeishiya** [comment]
I honestly have no idea why you might be experiencing this issue.. Sounds like an issue with `getopt_long`.. I have not experienced this problem before

**Comment by evan01** [comment]
I managed to resolve this somehow, I think it's related to fixing either `skhd` or the `SIP` stuff. Lets close this one
