### ISSUE TITLE
command to check if window is tiled or floating

### ISSUE THREAD

**Issue by tommasolaurenzi** [koekeishiya/chunkwm#463]
Hello, I would like to know if it is possible to query a window actual state, whether it's tiled or floating. I am writing a small widget for Übersicht to report some chunkwm/khd info, like desktop and khd modes (for which I found the references) and I would like also to display the window state.

Thanks,
TL

**Comment by koekeishiya** [comment]
You can check if the focused window is floating by using. `chunkc tiling::query --window float`

**Comment by JonasSprenger** [comment]
Hello, thanks a lot for this awesome window manager, It will give me a productivity boost for sure.

I've got a question: Is it possible to retrieve the tiled / floating status just with the window ID?
So I will be able to cycle through the floating windows per desktop.

Thanks,
Jonas

**Comment by koekeishiya** [comment]
It is currently not possible to check the floating status for a given window id, only the focused window as mentioned above.

**Comment by JonasSprenger** [comment]
Ok, thanks for the quick response.

**Comment by tommasolaurenzi** [comment]
since we are here, when the desktop mode is set to float, the command `chunkc tiling::query --window float` won't reflect the floating status of the window.

Also, it would be really nice to be able to cycle between tiled and floating window when moving around. I.e., supposing some khd mappings: I enter select mode where I can focus between windows with `hjkl`, the window I want to reach is floating, so I press, say, `o`, which toggles float-select mode and the focus moves to the first floating window,  then `n` and `p` will let me cycle floating windows.

Another cool thing would be being able to resize floating windows with the same keybinding used to resize tiled windows!

Excuse me for being naive, these are just some 'hey-that'd-be-cool' thoughts of mine!

**Comment by chicocode** [comment]
I couldn't agree more with @tommasolaurenzi. I'd love to be able to cycle between floating windows. Nice tool though! Thanks for making my life so much better! ❤️
