### ISSUE TITLE
Taking screenshots results in only the blue border

### ISSUE THREAD

**Issue by angerman** [koekeishiya/chunkwm#465]
So I've tried to use the Cmd-Shift-4 combination to start the screenshot tool, and then press space to move to the window screenshot tool.

However each screenshot turns out to contain only the blue border and not the actual window. Is there a way around this behaviour?

**Comment by koekeishiya** [comment]
There is an entry in th wiki describing a workaround for this.

**Comment by angerman** [comment]
Sorry, I'm blind :(
