### ISSUE TITLE
Is there a way to focus a specific application window?

### ISSUE THREAD

**Issue by bradens** [koekeishiya/chunkwm#466]
I want to do something like 

`chunkc tiling::window --focus --owner "Google Chrome"`

but I can't seem to get something like that to work.  I noticed there are rules you can use to target application names for querying, but not for commands. Am i missing something?

Thanks

**Comment by koekeishiya** [comment]
There is no built-in way to give focus  to a specific application based on name or similar. You can utilize macOS [`open`](https://ss64.com/osx/open.html)  tool to achieve this. e.g: `open -a /Applications/Google\ Chrome.app` or `open -b <bundle identifier>`

**Comment by bradens** [comment]
Hmmm, ok I forgot I could use that command.  I'll do that, thanks.
