### ISSUE TITLE
Question: use only focus switch, not auto-layout?

### ISSUE THREAD

**Issue by ralphholz-usyd** [koekeishiya/chunkwm#469]
I've lately come into situation where I only needed to switch between windows on the same desktop, but wished that chunkwm would not try to arrange them. I agree that's probably very rare for users of this tool.

But is there a way to configure chunkwm to leave window arrangement alone and only do things like, e.g., move focus to the window east-ward?

This is not a request to add this feature if there isn't.

**Comment by koekeishiya** [comment]
This is currently not possible, no. I believe hammerspoon exposes an implementation in lua that allows you to do this, although I have not tested it: http://www.hammerspoon.org/docs/hs.window.html#focusWindowEast

**Comment by ralphholz-usyd** [comment]
Thanks for getting back to me so speedily, and for the advice. I think we can close this one! Thanks again!
