### ISSUE TITLE
Query to get windows of all spaces?

### ISSUE THREAD

**Issue by jsfr** [koekeishiya/chunkwm#477]
I know of the query command: 

```
chunkc tiling::query --desktop windows
```

To get the windows of the current space. Is there a way to query all spaces to which windows are on which spaces?

**Comment by koekeishiya** [comment]
This is not possible to do through the query system. I'm not sure what you need this information for, but it feels to me like it this belongs in the more complex category, in which I would recommend utilizing the flexibility of the plugin system that chunkwm is based around.

**Comment by tokyovigilante** [comment]
This would be ideal for intelligently switching between desktops with open windows only, would be great if this could be merged.
