### ISSUE TITLE
Cannot fullscreen a floating window

### ISSUE THREAD

**Issue by kylef** [koekeishiya/chunkwm#479]
Perhaps this is intentional behaviour but filing to check. When a window is floating and you try to fullscreen it nothing happens. This confused me a little as I didn't realise my window was floating when I was trying to fullscreen it and confused why it was not happening. I though I was in some state similar to #473.

Version: bf670fe2bcbceb9e9034228f423ce5d9d848f187

### Steps to Reproduce

- Float a window
- Try to fullscreen the window

### Expected behaviour

Window is fullscreened

### Actual Behaviour

Nothing happens expect some lines in log:

```
2018-08-03 00:48:00 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'
2018-08-03 00:48:00 DEBUG:     command: 't', arg: 'fullscreen'
```

**Comment by kylef** [comment]
I haven't fully understood the exact steps to reproduce, when I have a window minimised in the dock. When I re-activate to un-minimise, sometimes a window comes back as floating. I think this may have been how I got into the state to reproduce the above.

**Comment by koekeishiya** [comment]
I never use minimize so there may very well be some bugs there. If you figure a way to reproduce said problem could you create a separate issue for it?

The fullscreen (and similar) commands only work for tiled windows, as it specifially tells that window to temporarily expand into a different bsp-region.

If you want to fullscreen a floating window, you can use the *--grid-layout* command.

I guess we could techncally have the *--toggle fullscreen* apply the correct *--grid-layout* command internally, but then it would no longer be a *toggle*.
