### ISSUE TITLE
[0.4.5] grid-layout doesn't work in rules ?

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/chunkwm#480]
Hi,

I just tried to create a simple rule to center and float an IDE dialog window:

```
chunkc tiling::rule --owner PhpStorm --name "Commit Changes" --grid-layout 8:8:1:1:6:6 --state float
```

I noticed that as soon as I set the grid-layout command the rule doesn't seem to be applied and the window is tiled.

Am I missing something ?

**Comment by dominiklohmann** [comment]
You have to escape the quotation marks for whatever reason. 

```
chunkc tiling::rule --owner PhpStorm --name \"Commit Changes\" --grid-layout 8:8:1:1:6:6 --state float
```

**Comment by mickaelperrin** [comment]
Thanks a lot, I indeed forgot the escape, but sadly it doesn't resolve the problem.

That's interesting also to notice that the rule was working without escaping the quotes but without the grid-layout tag.

**Comment by koekeishiya** [comment]
If I'm not mistaken, this was not implemented in 0.4.5, but is only on the master branch. I probably should think of a better way to handle the reference manuals such that versions can be incorporated somehow.

**Comment by mickaelperrin** [comment]
Thanks @koekeishiya for your answer.

I did a reinstall from HEAD with
```
brew reinstall --HEAD chunkwm
```

the version displayed is still 0.4.5.

And sadly the rule still doesn't work :(

**Comment by koekeishiya** [comment]
Could you try and see if the following rule does work?

```
chunkc tiling::rule --owner Finder --grid-layout 1:1:0:0:1:1 --state float
```

It should basically fullscreen all finder windows as they are opened.

**Comment by mickaelperrin** [comment]
Sorry for busying you with that. It works. I didn't understand why it didn't work after the upgrade to HEAD branch, but currently, it works well;

Thanks.
