### ISSUE TITLE
Window does not utilize extra space left by hidden menu bar

### ISSUE THREAD

**Issue by kylehovey** [koekeishiya/chunkwm#483]
This might be hard to implement as the menu bar can come back if you mouse to the top, and that might then reduce the space and trigger a resize. Here is an image of what the behavior looks like:

![image](https://user-images.githubusercontent.com/7339800/43753973-ab96568c-99c5-11e8-88b1-3e7a599e6be2.png)

**Comment by koekeishiya** [comment]
There is no way for us to know if the menubar is visible or not depending on where the mouse location is. We do however autodetect the state state of the setting *Automatically hide and show the menubar*, and in this case we do not leave space for the menubar.

If you have changed this setting in system preferences while chunkwm is running, you can run *chunkc tiling::desktop --toggle offset* twice to force an update of the screen region.

**Comment by kylehovey** [comment]
That was it. I just needed to restart the application. Thank you!
