### ISSUE TITLE
Toggle Offset not working after follow-focus event

### ISSUE THREAD

**Issue by Beulenyoshi** [koekeishiya/chunkwm#484]
I updated chunkwm + plugins to 0.4.5 today. My last update was probably a month ago. I noticed a change in behaviour which I couldn't find a note in the changelog for:

When I send a window to a different desktop _with follow focus_  (`chunkc tiling::window --send-to-monitor 2; chunkc tiling::monitor -f 2`) and try to toggle offset immediately afterwards (`lalt - a : chunkc tiling::desktop --toggle offset`) nothing will happen until I change focus to a different window and re-focus the widow I sent to the desktop beforehand. Can someone reproduce this behaviour?

Samples taken from `.skhdrc`:

`lctrl + lcmd - w: chunkc tiling::window --send-to-monitor 2; chunkc tiling::monitor -f 2
`

`lalt - a : chunkc tiling::desktop --toggle offset
`

**Comment by koekeishiya** [comment]
Note to self:

Change how we detect active space to prioritize space of active window, if a window is actually in focus; fallback to current method.

LOC: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/controller.cpp#L1429

Should probably be done for all methods where we interact with desktops separately from windows..

**Comment by koekeishiya** [comment]
fixed on master.
