### ISSUE TITLE
Creating a new tab in the current window resizes it as if a new window had been created

### ISSUE THREAD

**Issue by rben01** [koekeishiya/chunkwm#485]
When using the `bsp` tiling mode, creating a new tab in the current window using ⌘N (which creates new tabs when `System Preferences > Dock > Prefer tabs when opening documents` is set to "Always") shrinks the current window by half even though no new window has been created. Since no new window has been created, nothing should happen when a new tab is opened.

**Comment by koekeishiya** [comment]
see #235
