### ISSUE TITLE
Print panel cannot be seen if window you are printing from is at the bottom of the screen

### ISSUE THREAD

**Issue by samerickson** [koekeishiya/chunkwm#492]
If you try to print from a window that is on the bottom of the screen, the options to cancel or print are not visible, and movie the window no longer works.

**Comment by koekeishiya** [comment]
This seems like an issue with how modal windows work on macOS. I would suggest either temporarily fullscreening the application using `--toggle fullscreen` command, or simply moving the window to the  upper part of the screen. There isn't really anything we can do to do programmatically fix  this.
