### ISSUE TITLE
Ambiguous messages

### ISSUE THREAD

**Issue by brorbw** [koekeishiya/chunkwm#494]
I installed chunkwm-sa i get an interesting message
```
2018-08-17 04:14:06.121 chunkwm[848:11167] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
chunkwm: successfully loaded sa!
```

Im running High Sierra (17E202)

[EDIT]
It's not working right now

**Comment by webframp** [comment]
I get the same message and am unable to move navigate between desktops. Installed from the brew tap and followed instructions here https://koekeishiya.github.io/chunkwm/docs/sa.html

```
$ chunkwm --version
chunkwm 0.4.7
$ chunkwm --load-sa
2019-01-19 14:25:34.368 chunkwm[85020:255728] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
chunkwm: successfully loaded sa!
```
on Mojave:
```
ProductName:    Mac OS X
ProductVersion: 10.14.2
BuildVersion:   18C54
```

**Comment by AdamWagner** [comment]
I also get this message, but *am* able to navigate between spaces - in fact all the functionality that I use seems to work correctly. I’ve been curious what it means, but haven’t had a specific problem to motivate more investigation. 

Also on most recent Mojave (responding from mobile, can’t provide precise build no.)

**Comment by webframp** [comment]
Possibly related to https://github.com/koekeishiya/chwm-sa/issues/15

**Comment by webframp** [comment]
When running with SIP disabled I still get the message as well, but am now able to control desktop movement as documented

**Comment by brorbw** [comment]
> I also get this message, but _am_ able to navigate between spaces - in fact all the functionality that I use seems to work correctly. I’ve been curious what it means, but haven’t had a specific problem to motivate more investigation.
> 
> Also on most recent Mojave (responding from mobile, can’t provide precise build no.)

The core functionality of chunkwm is also working for me. What I meant when I said that it wasn't working was the sa extension wasn't working.
It relates to the [koekeishiya/chwm-sa#15](https://github.com/koekeishiya/chwm-sa/issues/15) posted by @webframp. 

Given the information in that thread I will consider this issue closed or at least moved since I only disabled SIP during install, not during the execution of sa.

**Comment by AdamWagner** [comment]
@brorbw - Sorry, I should have specified that that desktop switching via the sa extension works for me, despite the “...may not be scriptable” message. I have SIP disabled permanently, though ... which as you noted is required.

**Comment by brorbw** [comment]
@AdamWagner Interesting, what build of macOS are you running?

**Comment by AdamWagner** [comment]
@brorbw 

```
ProductName:    Mac OS X
ProductVersion: 10.14.3
BuildVersion:   18D32a
```

I actually didn't realize I was on the beta channel. I started using Mojave just before public release, and I'm pretty sure the sa extension has worked the whole time.
