### ISSUE TITLE
suggestion: minimize window

### ISSUE THREAD

**Issue by chicocode** [koekeishiya/chunkwm#495]
Would be nice to have  a minimize feature such as close
https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#close-window

I could send them to "background" minimizing it and bring it back with spotlight search!

**Comment by dominiklohmann** [comment]
What is stopping you from just pressing <kbd>command</kbd><kbd>M</kbd> or using `skhd` to simulate that keypress for you? Unlike for the close button, there are not many applications remapping the Minimise menu action. You can also force applications to use that key binding (localisation applies here, so use Minimize for US english).

<img width="780" alt="image" src="https://user-images.githubusercontent.com/4488655/44390465-9ebb8180-a52d-11e8-88f0-62b22ec89054.png">

If you need it for GUI scripting, I suppose `s/Close/Minimize` on this should work. https://github.com/koekeishiya/chunkwm/blob/c4f349e385242975f8c1ae30b0e6b327584d5caf/src/common/accessibility/element.cpp#L228-L236

**Comment by chicocode** [comment]
Thanks! Very thoughtful answer 👍 
It helped a lot!
