### ISSUE TITLE
Setting for focus follows mouse to update focus when windows move

### ISSUE THREAD

**Issue by paulbellamy** [koekeishiya/chunkwm#496]
Steps:
- Use the mouse to focus one window on a split-screen layout
- Mirror the tree (or otherwise move windows so that a new window is below the mouse)

Expected behaviour:
- The new window under my mouse should be focused

Actual behaviour:
- The previous window retains focus until I move the mouse

chunkwm version: 0.4.5
OSX version: 10.13.6

**Comment by koekeishiya** [comment]
I disagree, I think the current behaviour is the expected behaviour. If I swap position of two windows using a keyboard shortcut, I'm not moving the mouse, thus no ffm should trigger.
