### ISSUE TITLE
chunkwm dies when querying monocle-count/monocle-index of a display with only floating windows

### ISSUE THREAD

**Issue by LnL7** [koekeishiya/chunkwm#497]
I didn't look into the failure yet, but chunkwm restarts when running these query commands.

```sh
chunkc tiling::desktop --layout monocle
chunkc tiling::window --toggle float  # for all windows
chunkc tiling::query --desktop monocle-index
chunkc tiling::query --desktop monocle-count
```

**Comment by Amar1729** [comment]
I've been running into this problem intermittently with my ubersicht bar. 

If it helps debugging, the issue for me seems to specifically be on the `monocle-index` call, and I'm temporarily working around it by first checking if the window being queried is floating or not.

**Comment by koekeishiya** [comment]
Fixed on master.
