### ISSUE TITLE
how can i set the  focus  follow mouse off

### ISSUE THREAD

**Issue by umrwifi** [koekeishiya/chunkwm#501]
thanks a lot

**Comment by koekeishiya** [comment]
You can disable this by removing the line
`chunkc core::load ffm.so` from your *.chunkwmrc* file.

**Comment by umrwifi** [comment]
oh i see it  thank you    
can i ask one more question
![image](https://user-images.githubusercontent.com/35317716/44924577-4b8fcd00-ad7e-11e8-8210-e53288e09171.png)
how can  i  hide the   close minimize maximize buttons
