### ISSUE TITLE
Expand tiling::window --grid-layout doc

### ISSUE THREAD

**Issue by JustAPerson** [koekeishiya/chunkwm#506]
Hi, I can't seem to figure out how to use the --grid-layout. I can't get it to do anything. I already have several windows open and tiled.

I'm coming from gTile for GNOME. I'd really love the ability to split the window into a 4x4 grid and then have hotkeys for moving window into a specific location in the grid. gTile only handles moving individual tiles and not rearranging all the surrounding ones, so I guess that would be achieved by having every window floating. Then just use the keybindings to move to specific spots in the grid.

I'm not certain if this is more of a feature request or a documentation request, but I'd appreciate any help.

**Comment by Amar1729** [comment]
To use --grid-layout the windows have to be floating, not tiled.  
Once floating, you can use --grid-layout to set the windows in a certain position, but there's no way builtin way to change the size of the window or move it around without re-running --grid-layout with different options.

**Comment by JustAPerson** [comment]
Okay, thank you! During different circumstances I might try to expand that functionality to resize/move floating windows within a grib, but this will suffice for now. Thank you!

**Comment by Amar1729** [comment]
Shameless plug: I actually wrote some quick 'n' dirty scripts in bash to do just that. Linked them in #382
