### ISSUE TITLE
Warp focus wrapping

### ISSUE THREAD

**Issue by zylent** [koekeishiya/chunkwm#509]
Currently there's a setting for wrapping focus across all monitors.
So, if I enable "chunkc set monitor_focus_cycle           all" , focus west on the westmost window on my center monitor will then focus the eastmost window on my west monitor.

This is great, but is there any way to use this functionality with the warp command? So warp on the westmost window would move it to the east side of the west monitor?

**Comment by koekeishiya** [comment]
I'm not really interested in the ability to warp across monitor boundaries. I think having the ability to move the window to a diff desktop/monitor is sufficient.
