### ISSUE TITLE
Idea for shell callback from tilling plugin

### ISSUE THREAD

**Issue by meck** [koekeishiya/chunkwm#513]
I've done a small bitbar plugin for showing the current tiling mode, focused display and some stuff from skhd. Right now the options for getting the current mode is polling or triggering an update from skhd.

It would be nice to be able add some shell commands to skdrc that triggers when the mode is changed and window/display focus changes, this would make it easy for people to make their own UI regardless if it is bitbar or Ubersicht...

**Comment by crisidev** [comment]
I have a PR which address somehow this issue: https://github.com/koekeishiya/chunkwm/pull/519

**Comment by koekeishiya** [comment]
Slightly related: https://github.com/koekeishiya/chunkwm/issues/354#issuecomment-370582731

**Comment by koekeishiya** [comment]
Closing this in favour of the referenced issue.
