### ISSUE TITLE
shell (zsh) completions for chunkc

### ISSUE THREAD

**Issue by Amar1729** [koekeishiya/chunkwm#515]
Sometimes I use `chunkc` from the command line when testing new keybinds, and for figuring out query commands. Remembering exact flags for each command got a little annoying, so I wrote [zsh tab completions](https://gist.github.com/Amar1729/fe960d41df55cd0357cf4adb4afc525b) for the `chunkc` command.

Obviously most people use keybindings from khd to interact with chunkwm, but if you'd like to add these to the project I could make a PR for it!

*I think they could also be added directly to the brew formula by gist link, if you don't want them in this repo.

**Comment by mdeboer** [comment]
Could you please provide them as [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) plugin? Shouldn't be too hard as the completions are already written. Makes installing and maintaining them a lot easier.

**Comment by crisidev** [comment]
I can take a look on how to deliver the shell completion through the brew formula.

**Comment by crisidev** [comment]
@Amar1729 IMHO you should make a PR to add the zsh completion file to chunkwm repository. After that is done, I can automatically install it from the brew formula.

**Comment by Amar1729** [comment]
Ok, I made a PR for adding these to the repo: #525 .

I did also create a [zsh plugin](https://github.com/Amar1729/chunkwm-zsh-completions/) for these in case anybody doesn't use the brew formula or wants to install them standalone (installation as a plugin might also be updated slightly faster when flags are added/modified in chunkwm master).

@crisidev I made a PR for your homebrew formula.
