### ISSUE TITLE
Focus to desktop <number> not working

### ISSUE THREAD

**Issue by HenryNguyen5** [koekeishiya/chunkwm#520]
I'm able to run commands such as moving a window to a separate desktop, but attempting to switch focus to desktops does not work.

These are the keybindings I'm using:
```sh
cmd + alt - 1 : chunkc tiling::desktop --focus 1
cmd + alt - 2 : chunkc tiling::desktop --focus 2
cmd + alt - 3 : chunkc tiling::desktop --focus 3
cmd + alt - 4 : chunkc tiling::desktop --focus 4
cmd + alt - 5 : chunkc tiling::desktop --focus 5
cmd + alt - 6 : chunkc tiling::desktop --focus 6
```

However, executing a command directly in terminal results in nothing happening too.

And this is what chunkwm outputs with debug enabled:
```sh
2018-10-02 23:51:30 DEBUG:     command: 'f', arg: '1'
2018-10-02 23:51:30 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'
```

I'm currently on Mojave on a MacBook Pro 2018 15in

**Comment by narze** [comment]
For focusing desktops, you have to install scripting-addition plugin (chunkwm-sa) by `chunkwm --install-sa` then `chunkwm --load-sa`. SIP is required.

**Comment by HenryNguyen5** [comment]
Didn't catch that tidbit, thanks @narze!
