### ISSUE TITLE
Can't create a new desktop

### ISSUE THREAD

**Issue by georgewitteman** [koekeishiya/chunkwm#521]
I've just installed chunkwm (and skhd) and I'm trying to get chunkwm to create new desktops so that I can move my windows around. I can't seem to get the window to be created. I'm on High Sierra and using the example config for both chunkwm and skhd. I've also tried just running `chunkc tiling::desktop --create` from a terminal window and nothing happens. Any help would be appreciated!

Also, this is the output from chunkwm when I run `chunkc tiling::desktop --create`:
```
2018-10-07 19:01:33 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'
2018-10-07 19:01:33 DEBUG:     command: 'c', arg: '(null)'
```

**Comment by dominiklohmann** [comment]
It's quite likely that you forgot to install the scripting addition.

On Mojave this requires SIP to be disabled all the time, on High Sierra you need SIP to be disabled only for installation and can re-enable it afterwards.

```
sudo chunkwm --install-sa
pkill Dock
```

**Comment by georgewitteman** [comment]
Yes that worked! Thank you! Just didn't see those docs.
