### ISSUE TITLE
Rule to set to float (or turn off) if only 1 windows on desktop?

### ISSUE THREAD

**Issue by kawtharrr** [koekeishiya/chunkwm#524]
Hi, recently started using this and it seems great, so thanks! Just wondering is it possible to do the above - leave a window untouched if it's the only window, like the first app that I launch? And then start tiling after the second window comes in...

**Comment by koekeishiya** [comment]
This is not possible without code modifications. I personally don't see the value in this as it is fairly quick to just issue a command that turns the window  into floating state.
