### ISSUE TITLE
Brew formula not working?

### ISSUE THREAD

**Issue by andpalmier** [koekeishiya/chunkwm#526]
I tried to install chunkwm using ` brew install chunkwm`, here is the result:
```
==> Installing chunkwm from crisidev/chunkwm
==> Downloading https://github.com/koekeishiya/chunkwm/archive/v0.4.6.tar.gz
==> Downloading from https://codeload.github.com/koekeishiya/chunkwm/tar.gz/v0.4
######################################################################## 100.0%
==> make install
==> make --directory src/chunkc
==> make install --directory src/plugins/tiling
==> make install --directory src/plugins/ffm
==> make install --directory src/plugins/border
Error: An exception occurred within a child process:
Errno::ENOENT: No such file or directory - src/completions/_chunkc

**Comment by fielding** [comment]
Has to do with the 0.4.6 release archive not containing the src/completions/_chunkc file while the brew formula has been updated to install completions by default.  This shouldn't be an issue after the next release. 

Until then you can install the latest stable without completions with:

`brew install chunkwm --without-completions`

Alternatively, if you want completions then simply install from the git repo with:

`brew install chunkwm --HEAD`. 

Happy Hacking!

**Comment by koekeishiya** [comment]
This is fixed now.
