### ISSUE TITLE
query windows on active desktop

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#53]
`chunkc query window list`

sample output:
```
114160, Hyper
66230, Firefox
114026, Google Chrome
```

**Comment by mickaelperrin** [comment]
Sorry for the question, but I didn't find any help on this. 

Is this still functional? The command output nothing on my system. Does the syntax has changed?

**Comment by dominiklohmann** [comment]
```
chunkc tiling::query --desktop windows
```

See this file for a list of all commands: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md

**Comment by mickaelperrin** [comment]
Awesome, thanks !
