### ISSUE TITLE
popups dragged back to their desktop

### ISSUE THREAD

**Issue by biocyberman** [koekeishiya/chunkwm#531]
I have this rule for Firefox in `.chunkwmrc`:

`chunkc tiling::rule --owner \"Firefox\" --desktop 2`

Thanks (but no thanks) to the inconsistency of desktop index assignment, I may drag Firefox on another desktop or rearrange the desktop so it gets another index (i.e not "2" anymore). This afterward causes a problem:

If I type something on the address bar (CMD + L) or try download something (a docx or PDF document), the popup window is pushed back to desktop 2. It is not fun when you are typing of search or url. The same problem also happen if I one a new Firefox window and move that window to another monitor. 

Firefox here is just an example, the problem also occur with Outlook, and any other applications that have rules for them.

To avoid this bug, I have to put the app (i.e. Firefox in this case) into its correct desktop, that has the correct index.

**Comment by biocyberman** [comment]
It helps a bit with the addressbar problem by changing the rule to this:

`chunkc tiling::rule --owner \"Firefox\"  --except "^$" --desktop 2`

But I still have problems with download and download history popups

**Comment by koekeishiya** [comment]
This is a usage limitation of desktop assignment. The behaviour of this will improve if/when I get around to doing #599
