### ISSUE TITLE
Documentation pages have viewport-relative font size, which is unviewable when the window is tiled small

### ISSUE THREAD

**Issue by cormacrelf** [koekeishiya/chunkwm#532]
A screenshot says it all:

![screen shot 2018-10-31 at 20 52 06](https://user-images.githubusercontent.com/378760/47780181-03c1fd80-dd4f-11e8-812a-511c0bc81de1.png)

Notice how the zoom in FF is set to 300%, and the text is still tiny. Basically, you cannot read the documentation when you have chunkwm enabled! This is especially frustrating when you restart chunkwm to apply some changes, and the floated documentation window gets re-tiled.

**Comment by koekeishiya** [comment]
I'm aware of this, but am not very interested in web-stuff. 
Use a separate desktop or monitor I suppose so that the window can stay in fullscreen.

PRs welcome if anyone cares enough to make the existing layout work in a non-viewport font-size fashion.
