### ISSUE TITLE
Discord (or maybe all electron apps?) are crashing when trying to bring them back from background

### ISSUE THREAD

**Issue by HoshiYamazaki** [koekeishiya/chunkwm#539]
As title says. 
Discord crashes when you minimize it and try to maximize/run it again.
Not sure if this is chunkwm problem or electron issue.

**Comment by koekeishiya** [comment]
I don't have this problem with Discord, so there seems to be something more intricate about this issue.

**Comment by HoshiYamazaki** [comment]
It works now, idk why I had this bug, anyway I close issue.
