### ISSUE TITLE
How do I map chunkwm commands to keybinds?

### ISSUE THREAD

**Issue by slifin** [koekeishiya/chunkwm#54]
with kwm I would use bettertouchtool to bind keybinds to kwm by sending them via the terminal execute functionality

I've compiled the binaries for chunkwm and the commands work on the terminal (as long as I only have one instance of chunkwm open) 

but running them through bettertouch doesn't work, do I need like a brew service running so only one instance is operating at one time and all future commands go to that, if so how do I do that?

**Comment by koekeishiya** [comment]
The chunkc binary is used to send  messages.

**Comment by slifin** [comment]
Thank you
