### ISSUE TITLE
Question/Idea: Multiple "displays" on 1 monitor

### ISSUE THREAD

**Issue by happylinks** [koekeishiya/chunkwm#541]
Hi,

I was thinking about a window setup that I'd really like to have:
![untitled diagram 2](https://user-images.githubusercontent.com/184774/48660167-850ed500-ea5d-11e8-996f-8cc4cb50e644.png)

I currently have the 2 monitors setup like in the image. This means I have 2 displays. 
But I'd rather have the middle of the right display to be kind of an extension to the "main" display, the left one.

**Example:**
App 1: Slack
App 2: Browser
App 3: Editor
1,2,3 are the most important, they can easily switch and have other things on there.
App 4: Spotify (Should always stay there, doesn't care about 1,2,3
App 5: "Bar" app with things like stats, cpu etc. (Should also just always stay there).

Would something like this be possible with chunkwm? 

I was searching if I could *really* make mac think one display is 2/3 displays, but no luck.
Currently I could make splits with chunkwm, but I'm not sure if there is a way to "lock" them so they don't accidentaly get overwritten with another app (that should only happen with Desktop 1 & 2).

Any help would be appreciated!

**Comment by koekeishiya** [comment]
> I was searching if I could really make mac think one display is 2/3 displays, but no luck.

I don't think this is possible in any way, as your conclusion also seems to be so far.

> Currently I could make splits with chunkwm, but I'm not sure if there is a way to "lock" them so they don't accidentaly get overwritten with another app (that should only happen with Desktop 1 & 2).

There is currently no way to lock a node/window in place, but that should be doable with some changes to the codebase. There might be some complications when sending a window to a monitor with locked nodes on it, and so on that might require some thinking first.

I believe it is possible to have multiple desktops visible on the same monitor (although not officially supported by Apple), and I don't know if this will break other built-in desktop support (such as Mission Control, desktop switching etc; probably will).

While I do see what you are going for here, I think a more realistic way would be to arrange App4 and App5 as floating apps, maybe with a rule or something to automatically move/resize them into their positions. Then have padding configured for desktop2 such that App3 fills the center only.
This solution would have to wait until after #534

**Comment by happylinks** [comment]
Thanks for the info, your idea about making App 4 & 5 be floating is great, I managed to get it to work.
Also I made a small applescript to reposition the windows I want to that place and mapped it to a key with skhd.

~/repositionApps.applescript
```
tell application "System Events" to tell process "Spotify"
	tell window 1
		set size to {2130, 790}
		set position to {3855, -580}
	end tell
end tell

tell application "System Events" to tell process "Slack"
	tell window 1
		set size to {2130, 800}
		set position to {3855, 2405}
	end tell
end tell
```

~/.skhdrc
```shift + alt - r : osascript ~/repositionApps.applescript```

This will absolutely work for me for now!
