### ISSUE TITLE
Saving bsp-tree state when changing layout

### ISSUE THREAD

**Issue by Sweenu** [koekeishiya/chunkwm#543]
Is there a simple way to be able to switch from bsp to monocle back to bsp while going back to the windows were at first?

I tried the following script:
```bash
desktop_id=$(chunkc tiling::query --desktop id)

if [ $(chunkc tiling::query --desktop mode) = 'bsp' ]; then
  chunkc tiling::desktop --serialize /tmp/bsp-tree$desktop_id
  chunkc tiling::desktop --layout monocle
else
  chunkc tiling::desktop --layout bsp
  chunkc tiling::desktop --deserialize /tmp/bsp-tree$desktop_id
fi
```

But realized that serializing does not keep track of where the windows were but more how the layout's like.

**Comment by koekeishiya** [comment]
Your script may work as you want if you merge this PR locally: https://github.com/koekeishiya/chunkwm/pull/390

Otherwsie there is no easy way to do what you want.
You can always just fullscreen the focused window in a bsp-layout temporarily using the `chunkc tiling::window --toggle fullscreen` command.

**Comment by Sweenu** [comment]
Thank you! I'm gonna try that then. Do you not plan to merge it into master?

`--toggle fullscreen` does not fit my needs, as the monocle layout does.
