### ISSUE TITLE
Command to temporarily disable window management

### ISSUE THREAD

**Issue by stylerw** [koekeishiya/chunkwm#546]
I'd love to see a command, along the lines of "chunkc tiling::desktop toggle tiling", which, when run, would temporarily disable chunkwm's window management altogether, either for a single desktop or for all.  Then, when run again, the same command would turn tiling back on.

This would be helpful for rare apps or dialog boxes who fight with chunkwm, or in case something goes "off the rails" with tiling and you need to reset the process. 

Thanks!

**Comment by johnallen3d** [comment]
How about switching the desktop in question to `float` temporarily? That's basically disabling management of windows. I guess that wouldn't give you the ability to toggle though...

**Comment by dominiklohmann** [comment]
It's a bit hacky and looks weird, but you can serialize the desktop state to a temporary file, toggle to floating mode and then later on toggle back and deserialize the desktop state. This might stop working if you add/remove windows while in floating mode.

Also see #190 for experimental, better serialization support that does not break as easily.

**Comment by koekeishiya** [comment]
> or in case something goes "off the rails" with tiling and you need to reset the process.

Switching the desktop to float mode, and back again will achieve this.

>  I'd love to see a command, along the lines of "chunkc tiling::desktop toggle tiling", which, when run, would temporarily disable chunkwm's window management altogether, either for a single desktop or for all. Then, when run again, the same command would turn tiling back on.

To prevent tiling on a desktop, simply switch it into floating mode.

If you want to disable tiling for all desktops you could just unload the tiling plugin and load it back in later: `chunkc core::unload tiling.so` and `chunkc core::load tiling.so`

In both cases you will lose the current state, and windows will most likely be rearranged upon reactivation of  tiling, regardless of which method was chosen, unless you got for something that was mentioned in the comment above.
