### ISSUE TITLE
move between workspaces

### ISSUE THREAD

**Issue by raheelsayeed** [koekeishiya/chunkwm#549]
Any keybindings to move between workspaces?

**Comment by acmcelwee** [comment]
This is the one you're looking for https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#focus-desktop

```
chunkc tiling::desktop --focus <option>
<option>: mission-control index | prev | next
short flag: -f
desc: requires chwm-sa (https://github.com/koekeishiya/chwm-sa) and High Sierra / Mojave
```

Make sure you check out the `chwm-sa` docs here to enable that functionality https://koekeishiya.github.io/chunkwm/docs/sa.html

**Comment by raheelsayeed** [comment]
oh man, i was hoping this wouldnt require turning of SIP.

**Comment by dominiklohmann** [comment]
In that case, live with the animations and just use the built-in keybinds?

<img width="780" alt="image" src="https://user-images.githubusercontent.com/4488655/49969956-33594d80-ff2a-11e8-8c53-c7231d233d47.png">

**Comment by raheelsayeed** [comment]
I was a long time user of totalspaces only to get rid of the bloody animations. But i guess no choice now. Have to make do with this.

Thanks for this repo!

**Comment by chipsenkbeil** [comment]
@raheelsayeed, are you against temporarily turning off SIP? To my knowledge, you only have to turn it off to install `chwm-sa` and then you can re-enable it. That's what I've done in the past, anyway.

**Comment by raheelsayeed** [comment]
@chipsenkbeil If that was the case, I would have done it. But from what I understand, on macOS Mojave, we'd have to keep it off __all__ the time for it to work.
