### ISSUE TITLE
how to set cvars

### ISSUE THREAD

**Issue by slifin** [koekeishiya/chunkwm#55]
on https://github.com/koekeishiya/chunkwm/issues/16 I can see:

> cvar / command: make floating windows topmost

which implies there's a setting to enable this (after chwm-sa is installed) what is that setting and what file does it need to go into?

**Comment by dominiklohmann** [comment]
```
chunkc config window_float_topmost 1
```

This goes where you set your other cvars as well, the config file is just a shell script executed by chunkwm on startup (defaults to `$HOME/.chunkwmrc` as defined [here](https://github.com/koekeishiya/chunkwm/blob/e0e220b8e7c932d419bb78aeb15d6885f6a85cea/src/core/constants.h#L10))

**Comment by slifin** [comment]
Thank you
