### ISSUE TITLE
Resize windows with keyboard like i3

### ISSUE THREAD

**Issue by AlbinWarmlind** [koekeishiya/chunkwm#551]
I have read what the wiki article says, but when I copy and paste the same code into my chunkwmrc it says error: cmd command not found.

**Comment by powellc** [comment]
@AlbinWarmlind The code for resizing should be added to your skhdrc dotfile, not the chunkwmrc dotfile :)

**Comment by rjhilgefort** [comment]
@AlbinWarmlind @koekeishiya Can you link to the docs? I'm having trouble figuring out how to resize windows and get the other windows to resize with it.

**Comment by rjhilgefort** [comment]
I found it, nvm. Here it is for anyone else looking:

https://github.com/koekeishiya/chunkwm/wiki/Useful-tips-and-workarounds#resize-regions-similar-to-the-behavior-known-from-the-i3-window-manager
