### ISSUE TITLE
Activate window alpha settings

### ISSUE THREAD

**Issue by limeless** [koekeishiya/chunkwm#555]
since we can set the alpha of the inactive window,
and it works very very well, very happy with it.
I'm wondering can it have an option for <del>global</del> **Activate** window alpha settings?

edit: I realize the title misleading question.

**Comment by dominiklohmann** [comment]
You can already do this, the owner parameter takes a regular expression as its parameter. 

```
chunkc tiling::rule --owner .* --alpha 0.5
```

**Comment by limeless** [comment]
Thanks for the fast reply,
actually, I tried with rule settings before posting this,
I placed the rule settings in `.chunkwmrc` file, and doesn't seem to work...

here is my [.chunkwmrc gist](https://gist.github.com/limeless/5ccdb4a650025f31083507ba9fddffd4)

**Comment by dominiklohmann** [comment]
In L15-18, you unload plugins which are not loaded yet anyways.
```
chunkc core::unload tiling.so
chunkc core::unload ffm.so
chunkc core::unload border.so
```

In L76-77, you set a rule for the tiling plugin, which has not yet been loaded at this point. This is essentially a no-op.
```
# Set Global Alpha with wildcard owner settings *
chunkc tiling::rule --owner .* --alpha 0.5
```

Then in L98-100, you load the plugins. 
```
chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so
```

To fix your issue, change L15-18 to load and delete L98-100. Then restart chunkwm.

**Comment by limeless** [comment]
after modifying the config file it's not working,
I also tried to put L76-77 below L98-100 too.

**Comment by limeless** [comment]
yes, I was able to use window_fade function no issue.
<img width="1486" alt="2019-01-18 05 41 15" src="https://user-images.githubusercontent.com/1501022/51350647-ae8ec000-1ae3-11e9-95b5-63f686b04821.png">

**Comment by lucaorio** [comment]
@dominiklohmann I have a question probably related to this: is it possible to keep a specific window always sticky, floating, and at alpha 1, no matter its active/inactive status?

 I've tried the solution below. Finder is always floating, but it gets faded out.
```
chunkc tiling::rule --owner Finder --state float --alpha 1
```

**Comment by dominiklohmann** [comment]
Have you played around with `--state sticky`? Also I assume you're trying to combine this with the other rule from earlier in this thread?

The format of the regular expressions is POSIX ERE, so I don't think there's a way to make the prior rule except anything but Finder (`^(?!^Finder$).*$` requires negative lookahead, which POSIX ERE does not support afaik). I am not exactly sure in what order existing rules are evaluated, so having multiple rules modify the alpha of the same window may cause unforeseen issues.

**Comment by dominiklohmann** [comment]
The issue in your case is that you use `window_fade_inactive`, which seems to take precedence over the window rule. 

Rules only reapply when something about the window changes (e.g. the title), but `window_fade_inactive` triggers whenever you raise a window. You would need to find some way to trigger the rule again after you raised another window.

**Comment by lucaorio** [comment]
I've tried to trigger the rule again via Karabiner, but the Finder is always faded out :(
```
# change window focus (ctrl+[/])
[:!Topen_bracket "/usr/local/bin/chunkc tiling::window --focus prev & /usr/local/bin/chunkc tiling::rule --owner Finder --alpha 1"]
[:!Tclose_bracket "/usr/local/bin/chunkc tiling::window --focus next & /usr/local/bin/chunkc tiling::rule --owner Finder --alpha 1"]
```

**Comment by dominiklohmann** [comment]
What you're doing there is redefining the rule every time—which is a particularly bad idea, because those rules don't overwrite each other, so this has quite the high cost.

I don't think you can get there without code modifications.

**Comment by lucaorio** [comment]
Thank you, @dominiklohmann!  :) 

From a UX perspective, I think it does make sense to allow a flag for persistent alpha, no matter the state of the window. cc/ @koekeishiya

**Comment by koekeishiya** [comment]
if a window alpha is set through a rule it should probably not be changed by other rules or by the window_fade system.

**Comment by koekeishiya** [comment]
I don't currently want to support explicitly setting what the alpha of the active window should be. The active window will be set to full alpha, unless that window/application explicitly has a rule that specifies the alpha it should have.
