### ISSUE TITLE
Tiled Electron apps overlap other windows

### ISSUE THREAD

**Issue by joshtwo** [koekeishiya/chunkwm#558]
After using Skype, Spotify and Mailspring in bsp mode, I'm certain that for whatever reason, Electron apps consistently display slightly bigger than you would expect them to. Here are some examples:

* [One Electron app (Mailspring)](https://imgur.com/kUSHoeu)
* [Two Electron apps (Mailspring and Spotify)](https://imgur.com/dceXz7u)
* [Three Electron apps (Mailspring, Spotify and Skype)](https://imgur.com/wDwzSCj)

Compare this behavior to a [grid of non-Electron apps](https://imgur.com/TQGZaGP).

If you don't have any of these apps, you can also use the Apple News app to reproduce the behavior. My .chunkwmrc is just the example one, in case my config could be affecting things.

**Comment by dominiklohmann** [comment]
This has nothing to do with electron, but rather the fact that all these applications set a minimum width/height for their windows.

**Comment by joshtwo** [comment]
Wow, that's some coincidence. I'm guessing there isn't much I can do about that?

**Comment by dominiklohmann** [comment]
Basically nothing. ¯\\\_(ツ)\_/¯
