### ISSUE TITLE
Activating windows hidden with cmd+h does not spawn in correct place

### ISSUE THREAD

**Issue by jumban** [koekeishiya/chunkwm#560]
When I have 2 windows on the screen, split left and right, and I re-open any application that was previously hidden with CMD+H, the re-opened window spawns in the minimum depth leaf node, regardless of focus. 

Here is an example.
This is the initial state
![image](https://user-images.githubusercontent.com/32335357/52131580-032e5100-2635-11e9-8770-05b73dd2412d.png)

I hide the activity monitor using cmd - h
![image](https://user-images.githubusercontent.com/32335357/52131627-26f19700-2635-11e9-923c-2ac621328116.png)

Now I move my focus onto the right window (iTerm), and I re-open activity monitor. The window does not spawn above iTerm, which is the expected behavior. Instead, it spawns on the minimum depth leaf node, above Google Chrome.
![image](https://user-images.githubusercontent.com/32335357/52131737-6f10b980-2635-11e9-800e-782c92996072.png)

This problem can be reproduced with any program on the computer, as long as the window was hidden using CMD+H.

I believe that this is not the intended behaviour.

**Comment by koekeishiya** [comment]
I believe this is happening because at the time when Activity Monitor becomes visible, it actually becomes the focused window BEFORE the window is shown, so when chunkwm tries to tile the newly discovered Activity Monitor window, it looks at what the focused window is, and it reports "Activity Monitor". This causes chunkwm to use the minimum depth-leaf node as the insertion point.

**Comment by jumban** [comment]
Thank you for the quick response, indeed your explanation makes sense.

Often, I want to temporarily hide a window, without closing it, and recover it sometime later. While the issue is being resolved, do you have any ideas how I can work around this issue other than having to quit the application completely? 

Thanks for your help, and thanks for the wonderful program.

**Comment by koekeishiya** [comment]
You could try  to maybe minimize the window instead, I'm not sure if that has the same problem.

**Comment by jumban** [comment]
Just wanted to add on, I just tried manually setting the insertion point for a window, and then reopening a window that was previously minimized or hidden, and it spawns in the correct place!

Hope that this piece of info somehow helps when fixing the issue. Cheers.

**Comment by koekeishiya** [comment]
Fixed on master.
