### ISSUE TITLE
Feature: Support behavior like `workspace_auto_back_and_forth` from i3wm

### ISSUE THREAD

**Issue by aengelas** [koekeishiya/chunkwm#566]
In i3wm, you can enable behavior that allows you to be on workspace 2, press `mod + 1` which will shift focus to workspace 1, and then press `mod + 1` again, which will return to the previously viewed workspace, in this case workspace 2. 

This is very handy when quickly flipping back and forth between workspaces, as you can just give a double tap. It also means you don't have to think about where you came from, if you know you just want to go back to that workspace.

I'm not sure how feasible this is, but it's one of the features I miss most from i3.

**Comment by koekeishiya** [comment]
This is not exactly what you are asking for, but it is possible to bind a key-combination, e.g: `mod + x` to focus the previously focused desktop. You can then keep hitting this key to toggle between those 2 desktops. See my comment in https://github.com/koekeishiya/skhd/issues/55

**Comment by ad1217** [comment]
I also wanted this, and ended up with this:
```
cmd - 1 : i=1; chunkc tiling::desktop --focus $(( $(chunkc tiling::query --desktop id) == $i ? $(chunkc get _last_active_desktop) : $i ))
cmd - 2 : i=2; chunkc tiling::desktop --focus $(( $(chunkc tiling::query --desktop id) == $i ? $(chunkc get _last_active_desktop) : $i ))
etc...
```
which seems to work nicely.

**Comment by koekeishiya** [comment]
Thanks for taking the extra step @ad1217 
I've added this information to the wiki: https://github.com/koekeishiya/chunkwm/wiki/Useful-tips-and-workarounds

**Comment by aengelas** [comment]
Thanks for the tip! For some reason I just hadn't realize how much scripting you could use in the config file. I think I can make this do everything I want. Many thanks for making a great tool.
