### ISSUE TITLE
Toggle border

### ISSUE THREAD

**Issue by ivomarino** [koekeishiya/chunkwm#568]
hi all, is there any way to toggle `chunkc set focused_border_width` via a `.skhdrc` key combination? Thanks in advance for feedback.

**Comment by limeless** [comment]
Yes and it's kinda easy to do with.

`chunkc border::width int`

here is some example of my `.skhdrc`
``` csharp
:: default : chunkc border::color 0xff878787 | chunkc border::width 0
:: resize  : chunkc border::color 0xffff0000 | chunkc border::width 5
:: warp    : chunkc border::color 0xff0000ff | chunkc border::width 5
:: launch  : chunkc border::color 0xffffff00 | chunkc border::width 5```

**Comment by ivomarino** [comment]
Great, thanks for the info;)
