### ISSUE TITLE
Border not drawn on plugin load (Mojave)

### ISSUE THREAD

**Issue by TJohnW** [koekeishiya/chunkwm#569]
There was a similar issue closed, #330, but I am still seeing some weird behavior around this. (I am running up to date with master).
For some context:
In my `.khdrc` I unload and load the border plugin for a specific mode
```
khd mode default on_enter chunkc core::unload border.so
khd mode tiling on_enter chunkc core::load border.so
```
When entering the mode, the border does not render on the focused window until I switch to another window and back again (or send one or sometimes two resize events etc..)

**Comment by koekeishiya** [comment]
Fixed on master.
