### ISSUE TITLE
Make CVars and Commands dispatching centralised 

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#57]
The goal of this change is to remove the need of multiple demons listening on different ports, make chunkwm the global receiver and dispatcher of commands and messages.

### Proposed CVar commands:
`chunkc set var_name var_value` Setting a new CVar
`chunkc get var_name` Return CVar value

**How:**
Cvars are store by chunkwm in a key-value structure, access to each is protected by mutex. 
Key and value are both strings. 
Helper accessors are provided to the plugins to get the var in different format CVarIntValue(var_name) etc.. 
Do we want ability to define type of a Cvar when setting it? like `chunkc set -f var_name float_value` or `chunkc set -i var_name int_value` ?
When `get` command is executed chunkwm simply looksup in cvar storage structure and return value for the cvar. Report error is var isn't defined.
When `set` commands is executed chunkwm first checks if the var is already defined:
1. If the var is already defined, then we count this as an update to the cvar, a new event is constructed `Chunkwm_CVarChanged` where the context is the cvar name and the new value. When chunkwm processes the event it sets the cvar to the new value and then sends the event to the plugins.
2. If the var isn't already defined, it is added to the cvar key value storage, an event isn't constructed. This should allow var set in the configuration file to be available after it is parsed to plugins init functions.
A plugin that uses a cvar usually checks for it is defined in its init functions and if not it defines with some default values.

**Issues:**
Effectively a cvar is changed *before* the `Chunkwm_CVarChanged` is received by the plugin, but does it really matter for how processing is done in the plugins, usually in response to events that are serialised?
Do we want plugins to be able to change cvar values?
If so how? Make an API call available to plugins that triggers a Chunkwm_CVarChanged event? How to make the plugin that made the call ignore this event? Maybe add an identifier on who generated an event to event structure in general? Probably in this case when to perform the actual cvar change becomes a bigger issue.

### Proposed Command commands:
`chunkc cmd arbitrary_command -with-options and_value` Running commands supported by plugins

**How:**
First define a command structure that is common to everyone.
Proposed one:
`command_name [ -option1 -option2 -optionN ] command_arg1 command_arg2 command_argN`
Create an API to define commands for plugins, a `command` struct with a `AddCommand` that effectively adds it to chunkwm.
Each plugin would setup its commands in the init functions.
When a command is received chunkwm parses it and sends the command to the plugins to each plugin that registered that command name.
**Example:**
- plugin 1 defines new command:
```
command_name: window
command_options: -f -v -q
```

- plugin 2 defines command:
```
command_name: window
command_options: -k
```

- chunkwm stores in its internal struct
```
command1 -> command_name: window
            command_options: [-f, -v, -q, -k]
            plugins: [plugin1, plugin2]
```

Command `chunkc cmd window -k test` is sent to chunkwm, chunkwm parses the command and check if the `command_name` and its `options` are defined if so, it add it to event queue that then sends it as a `Chunkwm_CmdExecuted` where the context is the command itself. 
In this case command would get sent to both plugin1 and plugin2 even though plugin1 doesn't have support for the -k option, personally I think this is the best option, have the plugins ignore a command if they don't support an option or an argument, instead of having a more complex struct on the chunkwm side.

**Issues:**

Do we want to make commands defined by a plugin available to other plugins? if so how?
Same ideas as a cvar change api? Basically add an api call with command structure we want to execute, or the string?

These above are just my thoughts, really open to new takes and critics to any of the issues above.

**Comment by koekeishiya** [comment]
As much as I still think the end-goal is a good thing, I still think there are a lot more subtle problems than what appear at first sight.

**CVar related**:

To clarify, the commands such as 

> chunkc set var_name var_value Setting a new CVar
chunkc get var_name Return CVar value

is meant to expose the ability for external (only) actors to be able to read the current values, and set new values.

> Cvars are store by chunkwm in a key-value structure, access to each is protected by mutex.
Key and value are both strings.

If all CVars are stored by chunkwm, there will be a lot of "back-and-forth" communication, complicating the communication-flow between chunkwm being the sole broadcaster and plugins as the receiver. Plugins now suddenly have to round-trip through chunkwm to perform a value lookup and update. If all CVars are behind a single mutex, as plugins are ran in parallell, one plugin could effectively block (slow down) some other plugin from performing a read.

> Do we want plugins to be able to change cvar values?

This is a crucial part and was the main reason for why the CVar system exists. The idea behind it was to expose a simple way of dealing with thread-safe values for internal variables. It just so happened that a lot of these variables was something that we might also want to expose to the user. 

> Effectively a cvar is changed before the Chunkwm_CVarChanged is received by the plugin, but does it really matter for how processing is done in the plugins, usually in response to events that are serialised?

This probably should not matter.

Other issues:

The above changes will result in a centralized config, which by itself, is not a bad idea.
Complications arise when a user wants to manually load a plugin. Be it a new plugin, or an update to a plugin that is already running. As the config file is simply a bash script, we would have problems
loading the config options for that plugin.

**Command related**:

> Each plugin would setup its commands in the init functions.

This sounds like a good approach.

> First define a command structure that is common to everyone.
Proposed one:
command_name [ -option1 -option2 -optionN ] command_arg1 command_arg2 command_argN

This structure will not allow for argument validation, which is the current, and preferred structure.
The approach thus far has been to associate commands -> functionality through function pointers.
Commands are simply a chain of function calls and their associated argument. Before a command is constructed, we need to verify that a valid argument was passed.

> In this case command would get sent to both plugin1 and plugin2 even though plugin1 doesn't have support for the -k option, personally I think this is the best option, have the plugins ignore a command if they don't support an option or an argument, instead of having a more complex struct on the chunkwm side.

I agree that more complex is not good. I also disagree that it should be passed on to both plugins. If plugin1 and plugin2 both for some reason have a `window -f` command, I (personally) would always want to signal only plugin1 when I press the, say, `alt - f` bind.

Another problem, related to communication-flow, is the ability to query information stored by the plugin. If the tiling-plugin wants to expose information regarding tree structure, desktop-layout and other information, the command passed to the plugin by chunkwm would either have to include the socket to which the plugin can respond, or provide some other means to achieve this without causing too much a delay between request, processing the request, and transmitting the result back up the chain.

> Do we want to make commands defined by a plugin available to other plugins? if so how?

This can be very powerful, but will essentially mean that every plugin has to introduce their own ABI that other plugins must be compatible with. A change to plugin1 could break functionality of plugin2, and this causes a huge increase in dependency complexity.

Despite the fact that a lot of the above issues can be solved. They bring with them a very messy control-flow. To try and briefly illustrate what I mean by that, the flow goes from

**chunkwm** -> **plugin** <- external interface

to

external interface -> **chunkwm** -> <- **plugin**

Notice that internal operations done by the plugin can then trigger chunkwm to do a request that requires interaction from the plugin, and the boundary becomes less clear.

My opinion on this subject as a whole is more or less; The end goal is good, but the approach presented thus far introduces more complexity, ambiguities, and concerns that I find outweigh the pros of such as system.

**Comment by choco** [comment]
I'll answer only some of the points, since for some I have to give it a good long thinking XD

First, I personally wouldn't worry about round tripping, because effectively we aren't, the plugins live in the same executable space, we're making direct calls not using any messaging mechanism.

For CVars I meant a mutex for each single CVar. We could even remove mutex for CVar.
Example CVar Struct:
```
              | chunkwm | plugin1 | plugin2 | plugin3
              ---------------------------------------
cvar_example1 |  value1 |  NULL   |  value3 | NULL
cvar_example2 |  value1 |  value2 |  NULL   | NULL
```
A `CVarGet(var_name)` call just get the var for the plugin value
a `CVarSet(var_name, value)` updates var_name for the plugin and initiates a `CvarChanged` event for the other plugins. Until a plugin doesn't request a value for a cvar this is kept empty, but when request it is updated with chunkwm value. The mutex would protect only the chunkwm copy, that should only be using during updates. This should allow us to send the cvar changed only to the plugins that are actually using it for something.

> The above changes will result in a centralized config, which by itself, is not a bad idea.
Complications arise when a user wants to manually load a plugin. Be it a new plugin, or an update to a plugin that is already running. As the config file is simply a bash script, we would have problems
loading the config options for that plugin.

The only limitation here would be that the user would need to set the cvars before loading the plugin
```
chunkc set some_var_used_by_plugin1 value
chunkc load plugin1
```
But ideally doing the opposite:
```
chunkc load plugin1
chunkc set some_var_used_by_plugin1 value
```
would be the same:
- plugin loads
- init function checks for Cars, sets default value, finishes initalization
- `cvar set` is executed, plugin1 that listens for cvar changes reconfigures appropriately for the cvar change

I have to give more though to the commands part.

**Comment by koekeishiya** [comment]
> First, I personally wouldn't worry about round tripping, because effectively we aren't, the plugins live in the same executable space, we're making direct calls not using any messaging mechanism.

I suppose we make these calls through function pointers and so it shouldn't have any performance impact, but it does blur the lines of interaction quite a bit with respect to plugins now calling "through" chunkwm. My point is simply that it complicates the "design" of the system from a developer perspective. 

This very well might be a correct tradeoff to make, but I really emphasize on having an intuitive understanding of how the code flows and which parts call eachother, in chunkwm. 

> For CVars I meant a mutex for each single CVar. We could even remove mutex for CVar.

I'm not a huge fan of every CVar requiring its own mutex. Removing mutexex completely in favour of a different structure might be doable, but not sure how much that would impact the memory footprint (probably insignificant, but unsure at this point). 

A different solution could be to have one mutex per plugins cvars. If some other plugin is interested in a specific CVar, they track that manually using the ChunkWM_CVarChanged notification or something.

> The only limitation here would be that the user would need to set the cvars before loading the plugin

The problem here is not the loaded plugin in particular, but because that plugin has settings stored in the same file as all the other plugins, when we load plugin1, we will also effectively revert any runtime setting changes made to plugin2 and plugin3, despite only plugin1 being relevant at the time of config execution. 

Now this problem could be solved by not having the config be a bash script, we could have a custom parser that would allow for definition of sections and we could then execute only the relevant section. This is again quite a bit of work to accomplish properly.

I realize that I might seem overly critical and bring about a lot of criticism that might seem vague or not important, but I simply want to avoid going into the same direction that kwm did at some point, where everything became hard to reason about. 

The codebase is a lot cleaner and more organized in chunkwm due to the simple fact that I've taken great care regarding where to put responsibilities and try to have clear boundaries between different parts of the code and how it all comes together. 

There is no "'x' -> call -> 'y' -> request info -> 'x' -> return to -> 'y' -> perform operation" type of relationships.

**Comment by choco** [comment]
> A different solution could be to have one mutex per plugins cvars. If some other plugin is interested in a specific CVar, they track that manually using the ChunkWM_CVarChanged notification or something.

This sound like a really cool approach.

> The problem here is not the loaded plugin in particular, but because that plugin has settings stored in the same file as all the other plugins, when we load plugin1, we will also effectively revert any runtime setting changes made to plugin2 and plugin3, despite only plugin1 being relevant at the time of config execution.

I'm sorry could you provide an example, I'm not sure I completely get it :(


> Now this problem could be solved by not having the config be a bash script, we could have a custom parser that would allow for definition of sections and we could then execute only the relevant section. This is again quite a bit of work to accomplish properly.

Personally I'm not a fan of the bash script as configuration, simply because this also opens us up to security issues, chunkwm has accessibility access (which is a really privileged api on macOS) and anything executed when parsing the config has the same rights unfortunately.

> I realize that I might seem overly critical and bring about a lot of criticism that might seem vague or not important, but I simply want to avoid going into the same direction that kwm did at some point, where everything became hard to reason about. The codebase is a lot cleaner and more organized in chunkwm due to the simple fact that I've taken great care regarding where to put responsibilities and try to have clear boundaries between different parts of the code and how it all comes together.

I completely understand! And all the issue you're talking about my suggestions are real and should be addressed in a proper way, coming up with a decent design is probably the best feeling for a programmer so I don't mind discussion :D I'm not answering but I've actually been thinking quite a lot about the problems above ahahah

**Comment by koekeishiya** [comment]
> I'm sorry could you provide an example, I'm not sure I completely get it :(

The first time i start chunkwm, it will execute the bash script `.chunkwmrc`.
In here, we specify which plugins to load, and all their settings.

Now during runtime, I figure that I want plugin1 to behave differently,
so I issue `chunkc <change some setting of plugin1>`

If I at some later point decide to do `chunkc load <new plugin>`, it will also have to run `.chunkwmrc`, which causes all the commands listed to be executed again, causing my previously custom setting to be restored back to default.

Hopefully this made some sense, can't really think of a better example.

Again, the solution to this isn't hard, but would require us to write a config parser etc, instead of relying on a bash script as the config file. 

> Personally I'm not a fan of the bash script as configuration, simply because this also opens us up to security issues, chunkwm has accessibility access (which is a really privileged api on macOS) and anything executed when parsing the config has the same rights unfortunately.

This is true, but I guess the same goes for **khd** (which is why I prefer to run applications using `open -a` as this does not propagate the accessibility access further. I have not yet investigated why that is the case).

**Comment by koekeishiya** [comment]
Currently testing a more centralized version of commands through use of a prefix.

With this approach, *chunkc* always connects to *chunkwm (3920)*.

The *.chunkwmrc* file then looks like the following:
```
chunkc core::plugin_dir ~/.chunkwm_plugins
chunkc core::hotload 1
chunkc load tiling.so
..
```

*.khdrc* for the tiling plugin looks like the following:
```
alt - h   : chunkc  tiling::window --focus west
alt - j    : chunkc  tiling::window --focus south
alt - k   : chunkc  tiling::window --focus north
alt - l    : chunkc  tiling::window --focus east
..
```

By doing this, we can let the tiling plugin deal with its own command logic, without having to pass any of this to *chunkwm*. *chunkwm* uses the the prefix specified to figure out which plugin the command is meant for. This will solve the  problem regarding queries, as the socket is passed a long to the plugin, so it can write a response if necessary.

This causes issues with the current logic of the *cvar* system, which still needs to be changed to support this new model.
