### ISSUE TITLE
Need help in creating a setup with chunkwm

### ISSUE THREAD

**Issue by jbharat** [koekeishiya/chunkwm#570]
I started using chunkwm recently. Moved from amethyst. I have installed the script addon as well so I do get multiple desktop. I am currently using the sample config from the repo. 

I want to create a desktop as below.
```
|------|------|
|      |  2   |
|      |------|
|   1  |  3   |
|      |------|
|      |  4   |
|------|------|
```

Here there will be always be 1 primary window and others as secondary.  I am not sure how to do it. I will swap the primary with the secondary window when required but the structure remains same. Any new window will become the primary window automatically by pushing the current primary window to secondary windows.

Current relevant  config is below
```
chunkc set global_desktop_mode           bsp
chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5
```

Is it possible to set it up as above? Thank You.

**Comment by limeless** [comment]
you can set `chunkc set bsp_spawn_left` to `0`, so new window will always place on the right.
on the forth window spawned the placement will be like this 
```
|-------|-------|
|       |   2   |
|   1   |-------|
|       | 3 | 4 |
|-------|-------|
```

**Comment by koekeishiya** [comment]
When you have the first placement mentioned by @limeless simply perform focus window 3 or 4, and perform the command `chunkc tiling::window --toggle` followed by `chunkc tiling::desktop --equalize` and you will have the placement and sizes mentioned in the first comment @jbharat

**Comment by jbharat** [comment]
I will give it a try today.

**Comment by jbharat** [comment]
Awesome that worked. Thanks @koekeishiya and @limeless
