### ISSUE TITLE
Unable to switch desktops/workspaces despite chwm-sa being installed

### ISSUE THREAD

**Issue by lowercasename** [koekeishiya/chunkwm#571]
Hi! I love chunkwm, thank you so much for all your work.

I've diabled SIP, successfully installed and enabled chwm-sa, but nothing happens when I try to switch desktops, either via skhd or the command line. chunkc gives me no output when I run `chunkc tiling::desktop --focus 4`, `chunkwm --load-sa` outputs:

```
2019-03-01 12:43:37.617 chunkwm[6259:29811] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
chunkwm: successfully loaded sa!
```

Any pointers?

**Comment by koekeishiya** [comment]
Which version of macOS are you running (e.g: Mojave 10.14.3) ?

**Comment by lowercasename** [comment]
I’m running Mojave (10.14.3 Beta).

**Comment by koekeishiya** [comment]
So the Dock process seems to work different in Beta versions of macOS, so the code we inject is not able to properly locate the functions necessary to perform these operations. If you upgrade to the stable Mojave 10.14.3 version, and reinstall the scripting-addition it should work fine.

**Comment by lowercasename** [comment]
Ah, how strange! Thanks for the help, I’ll do that (no idea why I’m 
on the beta anyway to be honest).

**Comment by rjhilgefort** [comment]
I'm on `10.14.4` and I can't seem to get desktop focusing to work despite having SIP disabled and the scripting addition loaded. I'm seeing the same output as @lowercasename.

**Comment by capaldo** [comment]
> I'm on `10.14.4` and I can't seem to get desktop focusing to work despite having SIP disabled and the scripting addition loaded. I'm seeing the same output as @lowercasename.

What helped me with this was restarting. You then get a pop-up asking permission for chunkwm to control the dock. Hope this helps.

**Comment by rjhilgefort** [comment]
I tried restarting since enabling and still no luck. I didn't see any pop up asking for chunk to control the dock.

**Comment by joshtwo** [comment]
I'm having the same issue. I upgraded to 10.14.4, saw chunkwm was no longer working, tried `chunkwm --load-sa`, tried (un)installing the sa, restarted the computer, gave it permission to control the dock, and it still doesn't work.

**Comment by capaldo** [comment]
> I tried restarting since enabling and still no luck. I didn't see any pop up asking for chunk to control the dock.

Just stopped working for me

**Comment by koekeishiya** [comment]
When a new version of macOS is released, sometime there are changes to the Dock.app that we have to adjust to. I have not yet updated to 10.14.4. If you rely on this functionality I would advice you to either wait with updating til I have made the necessary changes to the scripting addition, or you would have to make the necessary changes on your own.

**Comment by alin23** [comment]
Damn OS updated over night. For me, macOS is quite unusable without this desktop focus functionality. 
@koekeishiya I'm eagerly waiting for an update to chwm-sa. Let me know if I can help with reverse engineering the latest changes.

**Comment by rjhilgefort** [comment]
No worries @koekeishiya, I appreciate the update. I'm looking forward to the `10.14.4` support whenever there is time.

Regardless, I can't thank  you enough for `chunkwm` and related projects!

**Comment by koekeishiya** [comment]
Updated with support for 10.14.4 on master. No ETA for the next release is going to be though.

**Comment by rjhilgefort** [comment]
🎉 Thanks @koekeishiya!!

Do you know if I just reinstall against `--HEAD` will pick up the changes? I can test things out and report back.

```shell
brew reinstall --HEAD chunkwm
```

**Comment by koekeishiya** [comment]
The following steps should pretty much do it, I think:

```
brew reinstall --HEAD chunkwm
sudo chunkwm --uninstall-sa
pkill Dock
sudo chunkwm --install-sa
brew services start chunkwm
```

**Comment by eugeneware** [comment]
I had to modify the steps above, but it definitely works again. Thanks so much for the quick fix @koekeishiya !

``` sh
brew unlink chunkwm
brew install --HEAD chunkwm
sudo chunkwm --uninstall-sa
pkill Dock
sudo chunkwm --install-sa
brew services start chunkwm
```

**Comment by rjhilgefort** [comment]
Can confirm that it works again off of `master` after reinstalling. Thanks again @koekeishiya !!

**Comment by joshtwo** [comment]
It works now. Excellent, thank you!

**Comment by harkylton** [comment]
Thanks for the quick turnaround on this @koekeishiya

**Comment by EvanCarroll** [comment]
What's the command using `port` to install HEAD?

**Comment by EvanCarroll** [comment]
> ```
> brew reinstall --HEAD chunkwm
> ```

There is no `reinstall --HEAD` (there is an install --HEAD) . I think we need @eugeneware's instructions,

https://github.com/koekeishiya/chunkwm/issues/571#issuecomment-477379681

**Comment by dominiklohmann** [comment]
Homebrew changed that not so long ago, reinstall now uses the same flags as your previous installation. Just omit the `--HEAD`.

**Comment by alextes** [comment]
Thanks so much. The instant switching between spaces is a big comfort.
I will remember to not update immediately 🙈 , create an issue here first to see if it works, and patiently wait if it doesn't.

Thanks again! 🙏

**Comment by koekeishiya** [comment]
Did a new release containing this update (if you built from master you are already fine). Closing this.

**Comment by C1tas** [comment]
@koekeishiya Dear sir, i'm in 10.13.4 chunkwm can't install the script

`brew install chunkwm` or `with --HEAD` both not work

when i do install and start chunkwm, my screen is still flash and print a log

```
2019-04-21 17:28:35.054 chunkwm[11497:123928] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
```

and `lsof -u 5050` not such port

my config 
```
#!/bin/bash

#
# NOTE: any 'chunkc' command that is run from this config file
#       that is NOT 'chunkc core::<..>' or 'chunkc set ..'
#       MUST be put in the background using &
#
#       e.g:
#       chunkc tiling::rule --owner Finder --name Copy --state float &
#

#
# NOTE: specify the absolutepath of the file to use for logging.
#       'stdout' or 'stderr' can be used instead of an actual filepath.
#

chunkc core::log_file /tmp/chunkwm/log.log

#
# NOTE: specify the desired level of logging.
#
#       - none, debug, profile, warn, error
#

chunkc core::log_level warn

#
# NOTE: specify the absolutepath to the directory to use when loading a plugin.
#

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 0

#
# NOTE: the following are config variables for the chunkwm-tiling plugin.
#

chunkc set custom_bar_enabled            0
chunkc set custom_bar_all_monitors       0
chunkc set custom_bar_offset_top         22
chunkc set custom_bar_offset_bottom      0
chunkc set custom_bar_offset_left        0
chunkc set custom_bar_offset_right       0

chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     20
chunkc set global_desktop_offset_bottom  20
chunkc set global_desktop_offset_left    20
chunkc set global_desktop_offset_right   20
chunkc set global_desktop_offset_gap     15

#
# NOTE: syntax for desktop-specific settings
#
# chunkc set 2_desktop_mode                monocle
# chunkc set 5_desktop_mode                float
# chunkc set 3_desktop_offset_top          190
# chunkc set 3_desktop_offset_bottom       190
# chunkc set 3_desktop_offset_left         190
# chunkc set 3_desktop_offset_right        190
# chunkc set 3_desktop_offset_gap          30
#

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set mouse_move_window             \"fn 1\"
chunkc set mouse_resize_window           \"fn 2\"
chunkc set mouse_motion_interval         35

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        5
chunkc set preselect_border_radius       0
chunkc set preselect_border_outline      0

#
# NOTE: these settings require chwm-sa.
#       (https://github.com/koekeishiya/chwm-sa)
#

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           0

#
# NOTE: the following are config variables for the chunkwm-border plugin.
#
# NOTE: syntax for `focused_border_outline` setting
#       0 = false, inline border
#       1 = true, outline border
#

chunkc set focused_border_color          0xff0f6288
chunkc set focused_border_width          5
chunkc set focused_border_radius         0
chunkc set focused_border_outline        0
chunkc set focused_border_skip_floating  0
chunkc set focused_border_skip_monocle   0

#
# NOTE: the following are config variables for the chunkwm-ffm plugin.
#

chunkc set ffm_bypass_modifier           fn
chunkc set ffm_standby_on_float          1

#
# NOTE: specify plugins to load when chunkwm starts.
#

chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so

#
# NOTE: sample rules for the tiling plugin
#

chunkc tiling::rule --owner Finder --name Copy --state float &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --owner Emacs --except "^$" --state tile &

```

**Comment by webframp** [comment]
@C1tas I'm on 10.14.4 and it's working for me using latest `HEAD`

Following https://koekeishiya.github.io/chunkwm/docs/sa.html you'll need to have SIP disabled, and leave it disabled in order for it to work.

**Comment by Catbodi** [comment]
@C1tas This is the same issue I'm having, did you find fix?

**Comment by koekeishiya** [comment]
@Catbodi This was an issue on High Sierra, reported in https://github.com/koekeishiya/chunkwm/issues/611 and fixed on master. It looks like the person who reported also closed the issue after confirming the fix.

**Comment by Catbodi** [comment]
> @Catbodi This was an issue on High Sierra, reported in #611 and fixed on master. It looks like the person who reported also closed the issue after confirming the fix.

Thank you so much koekeishiya. Quick question.

Will chunkwm-sa ever be able to be installed on Mojave and then SIP re-enabled? Or is this not a possibility? One of the reasons I downgraded to High Sierra was because of chunkwm-sa working after SIP being enabled and some of my other applications having issues on Mojave.

**Comment by koekeishiya** [comment]
> Will chunkwm-sa ever be able to be installed on Mojave and then SIP re-enabled? Or is this not a possibility?

I don't think this is very likely to happen, unfortunately.
