### ISSUE TITLE
Website usability improvements

### ISSUE THREAD

**Issue by localhostdotdev** [koekeishiya/chunkwm#576]
- [x] Not using `vmin` to be able to resize the text
- [x] Linking images to their full size equivalent (in https://koekeishiya.github.io/chunkwm/screens.html)
- [x] Have a border on the top of the footer to indicate that there is still content, or better, disable position: fixed on the footer
- [x] Have install instructions on the homepage
- [x] Specify if it can be easily uninstalled without any consequences on the system (as it's quite intrusive)

Thanks, awesome project

**Comment by koekeishiya** [comment]
See my comment in https://github.com/koekeishiya/chunkwm/issues/532

**Comment by koekeishiya** [comment]
> Have install instructions on the homepage
Specify if it can be easily uninstalled without any consequences on the system (as it's quite intrusive)

Will address these when I have time, thanks for the input.

**Comment by koekeishiya** [comment]
Made images clickable for full size version.
Added some text on the main page that links to installation instructions.
Added short info mentioning that it is fairly trivial to remove chunkwm, depending on the method of installation.

Did some other quick changes to improve looks after changes to font-size from PR #577, and that's pretty much all I can be bothered with.

**Comment by koekeishiya** [comment]
PRs welcome if people are severely annoyed by this.

**Comment by localhostdotdev** [comment]
Thanks a lot, I think you and jamesa handled everything, so I'm closing this.
