### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [koekeishiya/chunkwm#579]
I would like to point out that an identifier like “[`_FindCVar`](https://github.com/koekeishiya/chunkwm/blob/84e081674cdd20a36ed8ba9d0769b368813d117a/src/core/cvar.cpp#L15 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by koekeishiya** [comment]
No.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
