### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [koekeishiya/chunkwm#580]
Would you like to add more error handling for return values from functions like the following?
- [ftell](https://pubs.opengroup.org/onlinepubs/9699919799/functions/ftell.html "Return a file offset.") ⇒ [ReadFile](https://github.com/koekeishiya/chunkwm/blob/6078c63a50c6fd3d5101b82223ed6caccfa61e77/src/plugins/tiling/misc.h#L24)
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [CreateAndInitVirtualSpace](https://github.com/koekeishiya/chunkwm/blob/6078c63a50c6fd3d5101b82223ed6caccfa61e77/src/plugins/tiling/vspace.cpp#L68)

**Comment by koekeishiya** [comment]
No.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
