### ISSUE TITLE
Chunkwm won't find $HOME if it has whitespace in it, even if escaped

### ISSUE THREAD

**Issue by PrismaPhonic** [koekeishiya/chunkwm#585]
I commented on another closed thread where a different user was having the same issue.  Chunkwm cannot find it's config file if there's whitespace in $HOME.  I've even tried re-exporting $HOME while escaping all white spaces and running chunkwm and it still encounters the exact same bug.

**Comment by koekeishiya** [comment]
I still stand by what I said the previous time this was brought up. If your home includes a non-escaped whitespace, that is a misconfiguration on your part, and a lot of applications may exhibit abnormal behaviour as a result of that. **chunkwm** simply uses the `getenv` function to return the value of the $HOME env. variable.

Env. variables have to be escaped for the same reason that you can't do `cd /Library/Application Support` in a terminal, but have to write `cd /Library/Application\ Support`

**Comment by PrismaPhonic** [comment]
It's absolutely not a misconfiguration.  There are plenty of people that separate out their data across multiple hard drives.  I write plenty of terminal applications in Rust that don't have these kinds of issues, and I also access global environment variables.

**Comment by dominiklohmann** [comment]
@PrismaPhonic Can you give an example of a path with escaped whitespaces that does not work for you? Because—if I remember correctly—that other closed thread you mentioned resulted in the user fixing their issue by escaping whitespaces in their paths.

**Comment by koekeishiya** [comment]
Whatever causes this to not work on your system - I don't consider this a bug in **chunkwm**.
We do a fairly trivial step to build the config path, simply read the value of $HOME and concatenate the name of our config:
```
const char *HomeEnv = getenv("HOME");
if (!HomeEnv) {
    Fail("chunkwm: 'env HOME' not set! abort..\n");
}
snprintf(ConfigFile, Size, "%s/%s", HomeEnv, CHUNKWM_CONFIG);
```

We then make sure the filepath references a valid file on the users system before trying to execute it:
```
struct stat Buffer;
if (stat(ConfigFile, &Buffer) != 0) {
    Fail("chunkwm: config '%s' not found!\n", ConfigFile);
}
```

A solution would be to parse the result of `getenv("HOME")` to decide whether the value we got back was considered a valid path, and if it was not, escape whitespaces in it. This is in my opinion not something the application accessing defined env. variables should have to deal with.
