### ISSUE TITLE
Focus desktop is not working for me 

### ISSUE THREAD

**Issue by EvanCarroll** [koekeishiya/chunkwm#587]
None of these are working for me,

```
cmd + alt - 1 : chunkc tiling::desktop --focus 1                                                                                                                                                        
cmd + alt - 2 : chunkc tiling::desktop --focus 2                                                                                                                                                        
cmd + alt - 3 : chunkc tiling::desktop --focus 3                                                                                                                                                        
cmd + alt - 4 : chunkc tiling::desktop --focus 4                                                                                                                                                        
cmd + alt - 5 : chunkc tiling::desktop --focus 5                                                                                                                                                        
cmd + alt - 6 : chunkc tiling::desktop --focus 6   
```

They don't work if manually call `chunkc` either. Not sure what to add, they just silently fail.

**Comment by rjhilgefort** [comment]
You need to have the scripting addition `chunkwm-sa` installed. 

https://koekeishiya.github.io/chunkwm/docs/sa.html

You can follow this thread in case some it applies to you after installing the `sa`: https://github.com/koekeishiya/chunkwm/issues/571

**Comment by rockosov** [comment]
> You need to have the scripting addition `chunkwm-sa` installed.
> 
> https://koekeishiya.github.io/chunkwm/docs/sa.html
> 
> You can follow this thread in case some it applies to you after installing the `sa`: #571

Hello! If I don't have ability to switch off SIP, is it possible to enable Desktop Focus using some another way? Thank you!

**Comment by koekeishiya** [comment]
> Hello! If I don't have ability to switch off SIP, is it possible to enable Desktop Focus using some another way?

The only other way would be to use the built-in shortcuts for Mission Control.

> I tried to use Mission Control, but look like "Switch Desktop" is working so strange... It doesn't take a focus when desktop are shown on the real display...

That's sadly just how the built-in desktop switching works as far as I know. You may be able to work around the issue by creating a script that simulates your shortcut for activating a desktop, and then retrieves the active application for that desktop and gives it focus.
