### ISSUE TITLE
Can not unfloat

### ISSUE THREAD

**Issue by EvanCarroll** [koekeishiya/chunkwm#589]
when i do <kbd>Alt</kbd> - <kbd>t</kbd> I can get my window float, but I can't get it to unfloat. skhd has this,

```
# float / unfloat window and center on screen
alt - t : chunkc tiling::window --toggle float;\
          chunkc tiling::window --grid-layout 4:4:1:1:2:2
```

Are there any known issues with windows unfloating (`--toggle float`)

**Comment by dominiklohmann** [comment]
https://imgur.com/91ui8ap Not exactly sure what your issue is with this. Working on 10.14.4 for me.
