### ISSUE TITLE
Connection failed when trying to load tiling.so

### ISSUE THREAD

**Issue by Michael-Jing** [koekeishiya/chunkwm#59]
When I was trying to start chunkwm, it was unable to start correctly and the following are related info.

Processes runing:
michael           1229   0.0  0.0  2434832    716   ??  S     9:33AM   0:00.00 /Users/michael/apps/chunkwm/bin/chunkc config 1_desktop_offset_left 190
michael           1210   0.0  0.0  2444660   1028   ??  S     9:33AM   0:00.01 /bin/sh /Users/michael//.chunkwmtilingrc
michael           1119   0.0  0.1  2507396   6700   ??  S     9:30AM   0:00.08 /Users/michael/apps/chunkwm/bin/chunkwm

message in chunkwm.err:
chunkc: connection failed!
chunkc: connection failed!
chunkc: connection failed!
chunkc: connection failed!
chunkc: connection failed!

output of netstat -atn: 
tcp4       0      0  127.0.0.1.50111        127.0.0.1.3920         SYN_SENT
tcp4      35      0  127.0.0.1.3920         127.0.0.1.50088        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50088        127.0.0.1.3920         FIN_WAIT_2
tcp4      32      0  127.0.0.1.3920         127.0.0.1.50087        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50087        127.0.0.1.3920         FIN_WAIT_2
tcp4      36      0  127.0.0.1.3920         127.0.0.1.50086        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50086        127.0.0.1.3920         FIN_WAIT_2
tcp4      38      0  127.0.0.1.3920         127.0.0.1.50085        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50085        127.0.0.1.3920         FIN_WAIT_2
tcp4      37      0  127.0.0.1.3920         127.0.0.1.50084        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50084        127.0.0.1.3920         FIN_WAIT_2
tcp4      39      0  127.0.0.1.3920         127.0.0.1.50083        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50083        127.0.0.1.3920         FIN_WAIT_2
tcp4      36      0  127.0.0.1.3920         127.0.0.1.50082        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50082        127.0.0.1.3920         FIN_WAIT_2
tcp4      28      0  127.0.0.1.3920         127.0.0.1.50081        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50081        127.0.0.1.3920         FIN_WAIT_2
tcp4      30      0  127.0.0.1.3920         127.0.0.1.50080        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50080        127.0.0.1.3920         FIN_WAIT_2
tcp4      31      0  127.0.0.1.3920         127.0.0.1.50079        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50079        127.0.0.1.3920         FIN_WAIT_2
tcp4       0      0  127.0.0.1.3920         127.0.0.1.50078        CLOSE_WAIT
tcp4       0      0  127.0.0.1.50078        127.0.0.1.3920         FIN_WAIT_2
tcp4       0      0  127.0.0.1.3920         *.*                    LISTEN
udp4       0      0  *.3920                 *.*

my kwmtilingrc:
export CHUNKC_SOCKET=3920
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config global_desktop_mode           bsp
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 2_desktop_mode            monocle
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 5_desktop_mode              float
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config global_desktop_offset_top      20
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config global_desktop_offset_bottom   20
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config global_desktop_offset_left     20
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config global_desktop_offset_right    20
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config global_desktop_offset_gap      15
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 1_desktop_offset_top          190
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 1_desktop_offset_bottom       190
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 1_desktop_offset_left         190
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 1_desktop_offset_right        190
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 1_desktop_offset_gap           15
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 3_desktop_offset_top          190
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 3_desktop_offset_bottom       190
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 3_desktop_offset_left         190
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config 3_desktop_offset_right        190
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config desktop_padding_step_size    10.0
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config desktop_gap_step_size         5.0
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config bsp_spawn_left                  1
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config bsp_optimal_ratio           1.618
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config bsp_split_mode            optimal
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config bsp_split_ratio               0.5
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config window_focus_cycle            all
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config mouse_follows_focus             1
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config window_float_next               0
CHUNKC_SOCKET=3920 /Users/michael/apps/chunkwm/bin/chunkc config window_float_center             0

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/chunkwm/issues/26

**Comment by Michael-Jing** [comment]
I noticed that CHUNKC_SOCKET in different configuration sample files are different, ie 3920 in chunkwmrc and 4131 chunkwmtilingrc, is this correct?

**Comment by Michael-Jing** [comment]
After I changed the port in chunkwmtilingrc to 4131, the connection failed error is gone. However the port in chunwmrc is still 3920, it is a little bit confusing.

**Comment by koekeishiya** [comment]
The tiling plugin is listennig on port 4131.

chunkwm itself listens on port 3920, this is only for loading / unloading plugins as seen in the config file.
