### ISSUE TITLE
Mouse Functionality Not Working

### ISSUE THREAD

**Issue by rjhilgefort** [koekeishiya/chunkwm#593]
I can't seem to get mouse functionality to work despite numerous attempts. I've read through [the documentation](https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#set-binding-to-use-for-moving-windows-with-the-mouse) and a few of the issues (#146 #159) and can't seem to figure it out. I'm trying things on a bsp layout, I have `chunk-sa` installed... Any thing to try to get this to work? I'm on MacOS `10.14.4`, which may be a problem?

I apologize if this is user error and if this is another duplicate, but I've tried everything I can think. Here's my configuration:

```shell
# Mouse settings
chunkc set mouse_follows_focus           1
chunkc set mouse_modifier                alt
chunkc set mouse_move_window             1
chunkc set mouse_resize_window           1
# chunkc set mouse_motion_interval         1000
```

Here's what happens when I try to resize:

![2019-03-31 15 27 15](https://user-images.githubusercontent.com/2034823/55295370-836cfa80-53c9-11e9-8b7d-28569465e171.gif)

**Comment by peppy** [comment]
Have you tried dragging from in the middle of the window, rather than the resize border?

**Comment by koekeishiya** [comment]
You have to drag by actually clicking in the window, as explained by peppy. The resize border is directly connected to the applications integration with the macOS windowing framework and we do not  integrate our mouse functionality with that system for various reasons.

**Comment by pcr910303** [comment]
@koekeishiya Is there no plans to integrate with the window system?̊̈ I really would appreciate if chunkwm can integrate functionality with the mouse... as I feel that superior mouse functionality is one of macOS’s greatest features.

**Comment by rjhilgefort** [comment]
@koekeishiya works now that I understand it and with the config from @peppy- Thanks! This functionality is 🔥  btw, well done 👏 .
