### ISSUE TITLE
Window Tiling Rules Not Working

### ISSUE THREAD

**Issue by rjhilgefort** [koekeishiya/chunkwm#594]
I'm trying to setup rules for specific apps to launch to specific desktops but not having any luck. I've read over [the documentation](https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#window-rules) but the application doesn't get launched and/or moved to the desired desktop. I have a rule like this for Spotify to launch to Desktop 4 and it doesn't go there when I restart chunk whether it's open or not when chunk is loaded.

```shell
# .chunkwmrc
chunkc tiling::rule --owner Spotify --desktop 4
```

I'm on MacOS `10.14.4`, have `chunk-sa` installed and working for other things.

**Comment by dominiklohmann** [comment]
That exact command works for me on 10.14.4 with `chunkwm --version` being 0.4.8 (2f84) which is the current HEAD as of writing this. My Spotify version is 1.1.3.

Just off the top of my head, here's how some questions for DIY troubleshooting:
- Does desktop 4 exist? Is it on the same or another monitor?
- Can you reproduce this with other applications?
- Do you have other rules interfering with this?
- Does moving a window to another space with `chunkc tiling::window --send-to-desktop 4` work?

**Comment by rjhilgefort** [comment]
Thanks for the comment! I tried out the things you said to check, see below.

> That exact command works for me on 10.14.4 with chunkwm --version being 0.4.8 (2f84) which is the current HEAD as of writing this. My Spotify version is 1.1.3.
```shell
➜ chunkwm --version
chunkwm 0.4.8 (2f84)
```
> Does desktop 4 exist? Is it on the same or another monitor?
Yeah, I  was sending to a desktop that other things were on already. I only have 1 monitor.

> Can you reproduce this with other applications?
Yeah, I've tried with a few apps and nothing happens with them as well.

> Do you have other rules interfering with this?
I don't know?

> Does moving a window to another space with chunkc tiling::window --send-to-desktop 4 work?
Yep!

**Comment by dominiklohmann** [comment]
https://github.com/rjhilgefort/.chunkwm/blob/1abb39de757370d7bcc5bd83bd1e9c22cc224ecf/.chunkwmrc#L77-L88

Swap the order. The rules are commands and not variables, so they need to be used after loading the tiling plugin.

**Comment by rjhilgefort** [comment]
🙌wow, thanks you for finding my config and making the suggestion. That makes a lot of sense and I'm sorry I didn't figure that out myself.
