### ISSUE TITLE
Can't install scripting addition

### ISSUE THREAD

**Issue by pietdevries94** [koekeishiya/chunkwm#595]
I finally updated to 10.14.4 and now I can't install the scripting additions
```
~
» sudo chunkwm --install-sa
Password:
chunkwm: successfully installed sa!

~ took 3s
» sudo chunkwm --load-sa
2019-04-01 19:24:20.423 chunkwm[1188:7559] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
chunkwm: successfully loaded sa!
```

**Comment by rjhilgefort** [comment]
This was recently fixed. You'll need to reinstall `chunkwm` from `--HEAD`. See the following thread where @koekeishiya commented about fixing it.

https://github.com/koekeishiya/chunkwm/issues/571#issuecomment-477357784

**Comment by pietdevries94** [comment]
Ah yes that indeed fixed it! Thanks!
