### ISSUE TITLE
error: The specified item could not be found in the keychain.

### ISSUE THREAD

**Issue by EvanCarroll** [koekeishiya/chunkwm#597]
```
$ codesign -fs "chunkwm-cert" /usr/local/opt/chunkwm/bin/chunkwm
error: The specified item could not be found in the keychain.
```

That code to run (the `codesign` line) was right from the docs presented after `brew install`

**Comment by dominiklohmann** [comment]
The caveats in the formula instruct you to create said codesigning certificate yourself before that and the error message is quite clear on this—the certificate you are trying to codesign with does not exist.
