### ISSUE TITLE
About disabling SIP.

### ISSUE THREAD

**Issue by EvanCarroll** [koekeishiya/chunkwm#598]
My workplace wants to prevent me from disabling SIP (with their jamf stuff). The update to OSX to get to 14.4.4 broke ChunkWM. In order to fix it, we have to [reinstall the scripting-addition](https://github.com/koekeishiya/chunkwm/issues/571#issuecomment-477379681) with the patch for OSX 14.4.4 which are required for productive use of ChunkWM.

Is there anyway to maintain the upgradability of the Scripting-Additions with SIP enabled? Ideally, I would be able to disable them, and install something from ChunkWM that could update the ChunkWM scripting additions *without* having to disable and re-enable SIP (because I'm not sure if I'll have that ability moving forward).

**Comment by capaldo** [comment]
This has been [covered](https://github.com/koekeishiya/chwm-sa/issues/11#issuecomment-424670435) [multiple times](https://github.com/koekeishiya/chwm-sa/issues/11#issuecomment-427568476): The answer is no per the maintainer unless someone else wants to offer up a solution.I don't think theres a long term solution as far as I can tell.

I'm not the master authority on this though so [I might be wrong that its not feasible](https://totalspaces.binaryage.com/elcapitan-with-sip). The linked instructions for TotalSpaces might be applicable to chunkwm but it requires booting into the Recovery OS.

**Comment by dominiklohmann** [comment]
> I don't think theres a long term solution as far as I can tell. It might be possible this way. The instructions for TotalSpaces might be applicable to chunkwm but it requires booting into the Recovery OS.

Just to expand on this: This is impossible since 10.14. 

Before 10.14 you only needed SIP disabled to install the scripting addition. Since 10.14 you also need SIP disabled to load the scripting addition, which needs to be done whenever Dock.app launches.
