### ISSUE TITLE
inject code into Dock to expose functionality

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#6]
Some time ago in version 3.x.x of Kwm, I experimented with killing the dock to gain access as the universal window connection owner. Branch [here](https://github.com/koekeishiya/kwm/tree/hijack-universal-owner).

By doing this I was able to utilize all the `CGWindow` related functions to manipulate a window solely based on its CGWindowID (we can bypass the accessibility API). I suspect it would be a boost in response time / performance. This will also allow us to manipulate window alpha and window layers, among other things.

Of course, the reality is that the MacOS Dock application is responsible for a lot of the functionality in the system, and not only the visible Dock that we see. The following is a short list of functionality I've noticed will be lost upon doing this:

```
dock-bar (obviously)
launchpad
drawing of wallpaper (??)
mission control (this is potentially huge, and needs to be replicated / improved upon)
cmd + tab / cmd + ´
touchpad gestures (swipe to switch spaces, and so on)
```
Some of the functionality from the above list can easily be recreated.

I am going to be experimenting with something like this, instead of the accessibility approach that Kwm has. It may turn out to be a worse experience than simply going with the previous approach, but I think this is worth a try.

**Comment by choco** [comment]
I can't say I'm a fan of this. I use so many of the following features personally :( It would cool being able to act as a proxy for the Dock, not sure if it's possible though...

**Comment by choco** [comment]
I was just checking around and saw that there's also `_CGSSetOtherUniversalConnection`, but multiple people said that it isn't implemented. Looking and the SkyLight private framework it is surely implemented, just haven't been able yet to track down what function deals with the specific mach message under which condition, but maybe we can make use of it with something like this?
```
/* Hijack universal owner */

/* new connection that will become our default one */
CGSConnectionID conn;
CGSNewConnection(NULL , &conn);
CGSSetOtherUniversalConnection(hijacked_conn, conn);

/* let dock take back main universal owner connection */

**Comment by choco** [comment]
Hate to be the bearer of bad news, but I was actually getting quite fascinated investigating how CoreGraphics worked in general and while looking how the various CGS functions worked found out that on Sierra the WindowServer checks if the executable calling `CGSSetUniversalOwner` has the `com.apple.private.skylight.universal-owner` entitlement, so we can't hijack it :(

**Comment by koekeishiya** [comment]
Hm, so I guess injecting into the Dock is the only option then.
Do you know / can you test if `https://github.com/rentzsch/mach_inject` works on Sierra?

**Comment by choco** [comment]
I mean it is possible to get it working by disabling SIP, but if you want to keep SIP enabled then the solutions in this comment https://github.com/koekeishiya/kwm/issues/304#issuecomment-210072132 are still the only one working.

**Comment by choco** [comment]
Just leaving it here for future reference, Bartender is able to install its osax without disabling SIP. I only took a quick look but it seems to add an helper in `/Library/PrivilegedHelperTools` that has the sole purpose to install the OSX in `ScriptingAdditions` (it also temporarily disables entitlements?!? not sure), if you want to go down that road it surely is a better experience for the user.

**Comment by koekeishiya** [comment]
Notes for future reference:

So we would need some kind of an `installer` which uses `SMJobBless` to install an elevated `helper` that we can control (through `xpc` or `sockets`), to install our `scripting addition`. By doing this, `SIP` does not have to be disabled.

**Comment by koekeishiya** [comment]
So I've successfully created a `scripting addition` that does nothing but log that it has been loaded inside the target application, and a simple injector to have it load.

Trying to inject into `Dock`, I get the following:
```
warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
```
and so the code is never loaded.

Injecting into, say, `iTerm2` works just fine.

This was tested with `SIP` enabled.

**Comment by choco** [comment]
I actually though Bartender installed its scripting addition in `/System/Library/ScriptingAdditions` but it just puts it in `/Library/ScriptingAdditions`; to load a scripting addition in system processes and other apple code signed programs we need to drop the `osax` in the directory above.
So in the end user needs to temporarily disable SIP so we can put the osax there, and then we can enable it again. The good news is that as of macOS Sierra 10.12.2 once disabled we can enable it again, the user has to enter recovery only once (http://blog.eriknicolasgomez.com/2016/12/13/system-integrity-protection-sip-changes-in-macos-sierra-10-12-2/)

**Comment by choco** [comment]
I also want to add that I'm not really trilled by the idea of making the above a service for everyone to use, since this this would be a pretty big security hole that any malicious program can take advantage of. In my opinion we should allow access to it only to trusted clients by reusing Apple code signing mechanism (there's api to check the signature of an app, if it matchess specific developers)

**Comment by koekeishiya** [comment]
> I also want to add that I'm not really thrilled by the idea of making the above a service for everyone to use, since this this would be a pretty big security hole that any malicious program can take advantage of.

I was thinking that the scripting addition injects our bundle that starts a thread listening for incoming connections. We define the API for what it will be allowed to do, and the outside applications can request any of the supported actions to be performed, by connecting to the socket.

A plugin in **chunkwm** or whatever could then send something like the following to set the alpha value of an arbitrary window: 

"window_alpha wid value"

**Comment by koekeishiya** [comment]
I consider this more or less solved for my own usages. Will take a closer look at user-friendliness before release.
