### ISSUE TITLE
Unable to create desktop automatically when trying to move a window to another desktop.

### ISSUE THREAD

**Issue by Michael-Jing** [koekeishiya/chunkwm#61]
I was trying to move a window from desktop 1 to another desktop, say desktop 2, however the window is not moved, and I see the following error message in chunkwm.err:

invalid destination desktop specified, desktop '2' does not exist!

**Comment by koekeishiya** [comment]
I just tested this and it worked fine. 

Started chunkwm while on space one, opened notes, issued command to move notes to desktop 3.
Window was moved. Switched to desktop 3 using macOS shortcut, windows tiled properly.

**Comment by Michael-Jing** [comment]
I have pulled code and rebuild everything. But the issue remains, start from only one desktop, trying to move window to desktop 2 is not working. However, If I maximize(mac osx native fullscreen) one window by clicking on the maximizing icon on the top left corner of the window, then the window goes to desktop 2 by osx nature. Switch back to desktop 1, now I can move another window to desktop 2. So I guess, by maximizing a window using osx native fullscreen mode, I have created desktop 2. So the error message and the above behavior indicates that somehow chunkwm is not able to create desktop space by its own, if desktop has been created, chunkwm works fine on moving windows from one desktop to another.

**Comment by dominiklohmann** [comment]
Could this be related to the issue where chunkwm thinks Desktop `n` is actually Desktop `n+1` if there's a native fullscreen space inbetween? Here's a screenshot showing the issue:

<img width="1680" alt="screen shot 2017-05-21 at 14 58 07" src="https://cloud.githubusercontent.com/assets/4488655/26284216/67280040-3e36-11e7-8505-0c6247876e2c.png">

**Comment by koekeishiya** [comment]
> I have pulled code and rebuild everything. But the issue remains, start from only one desktop, trying to move window to desktop 2 is not working. However, If I maximize(mac osx native fullscreen) one window by clicking on the maximizing icon on the top left corner of the window, then the window goes to desktop 2 by osx nature.

Right, so chunkwm cannot create the desktop for your. MacOS does not expose an API that allows us to do this. You must first create the desktop manually.

> Could this be related to the issue where chunkwm thinks Desktop n is actually Desktop n+1 if there's a native fullscreen space inbetween? Here's a screenshot showing the issue:

This does not seem to be the problem in this topic, but yes, this will actually be a problem. I don't use OSX fullscreen too often (and when I do, they are always placed after all my "normal" desktops, as I always have 6-7 available).

I'll take a closer look at this specific behaviour. Feel free to create a new issue to track this specifially, if you'd like.

**Comment by koekeishiya** [comment]
> MacOS does not expose an API that allows us to do this. You must first create the desktop manually.

So, this is not actually correct. There are private functions `CGSSpaceCreate()` and `CGSSpaceDestroy()`, but there are some required steps (unknown to me), that must also be performed to update the state of the system (mission control). I do not know what these steps are, and there is no information about this to be found.

**Comment by Michael-Jing** [comment]
How did you manage to create those Desktops (2, 3 etc) in your screenshot @dominiklohmann ?

**Comment by dominiklohmann** [comment]
You open `Mission Control.app` by either three finger swiping upwards or pressing ctrl-up and click on the plus icon in the top right corner.
