### ISSUE TITLE
chwm-sa install make Dock flash continuously

### ISSUE THREAD

**Issue by realfirst** [koekeishiya/chunkwm#611]
i use macos as blow:
⇒  sw_vers 
ProductName:    Mac OS XProductVersion: 10.13
BuildVersion:   17A405

i have installed chunkwm & chunkwm-sa use following command
brew install --HEAD chunkwm
sudo chunkwm --install-sa
chunkwm --load-sa

then Dock app begin flash continuously
[https://imgur.com/ga8syMv](https://imgur.com/ga8syMv)
and 
lsof -i :5050 
return no result

**Comment by koekeishiya** [comment]
Fixed on master.

**Comment by realfirst** [comment]
i have reinstall chunkwm from master via following command

brew install --HEAD chunkwm

it works. thank you @koekeishiya
