### ISSUE TITLE
Allow focusing desktop without chwm-sa

### ISSUE THREAD

**Issue by BlueDrink9** [koekeishiya/chunkwm#614]
[This program](http://www.irradiatedsoftware.com/sizeup/) can move windows to and focus the next/previous space or monitor only using accessibility. Needing `chwm-sa` is a big extra installation step, especially on multi-user machines.

If you can, please consider looking into that functionality for skhd/chunkwm.

**Comment by dominiklohmann** [comment]
Meh, all SizeUp does is press buttons and move your mouse for you. Not really a robust solution since there is no requirement for an application to have a draggable bar at the top.

**Comment by BlueDrink9** [comment]
Ooh, is that how is does it? How sad, I thought it might have discovered another workaround.

If that's the case, this can be closed. The motivation still stands, but if the mechanism is still out of sight…

**Comment by koekeishiya** [comment]
chunkwm can already move windows to spaces without the user having chunkwm-sa installed.
As for focusing spaces, there is no real way to do that without code-injection, becaue the Dock is managing the system state. See #127 for information regarding macOS spaces.

**Comment by BlueDrink9** [comment]
How did you synthesise the keyboard shortcut? I'd be interested in replicating that.

**Comment by koekeishiya** [comment]
```
shift + cmd - 1 : chunkc tiling::window --send-to-desktop 1; skhd -k "cmd + alt - 1"
shift + cmd - z : chunkc tiling::window --send-to-desktop prev; skhd -k "cmd + alt - z"
shift + cmd - c : chunkc tiling::window --send-to-desktop next; skhd -k "cmd + alt - c"
```

cmd + alt - z was my mission control shortcut for "focus previous desktop" 
cmd + alt - c was my mission control shortcut for "focus next desktop"
