### ISSUE TITLE
chunkwm & skhd stuck in Privacy settings after uninstalling

### ISSUE THREAD

**Issue by strafe** [koekeishiya/chunkwm#617]
I've uninstalled chunkwm and skhd but they both still appears in the Security and Privacy settings. How can I remove these?
<br>

![image](https://user-images.githubusercontent.com/15663890/57178823-631fd800-6e6e-11e9-843e-45c06e3de514.png)

**Comment by dominiklohmann** [comment]
If you look at the whole settings window (and not just your zoomed in screenshot), you'll see a big minus button for removing entries from that list. Select the entry you wish to remove and then remove it by pressing said button. This design language using plus and minus labelled buttons for adding and removing entries from list is spread all throughout macOS.

**Comment by strafe** [comment]
@dominiklohmann thanks! Other uninstalled applications disappeared when toggling the checkbox and these didn't.
