### ISSUE TITLE
`chunkc tiling::monitor -f 2` goes to 3rd monitor

### ISSUE THREAD

**Issue by aiya000** [koekeishiya/chunkwm#623]
Hi 😄

I have 3 monitors.
And I always put only a window onto a monitor.

Now I put

- iTerm2 window onto 1st monitor
- Vivaldi window onto 2nd monitor
- Vivaldi window onto 3rd monitor

also I do `chunkc tiling::monitor -f 2`,
then it goes to the 3rd monitor 😭
I want to go to 2nd monitor.

But if I arranged to

- iTerm2 window onto 1st monitor
- Vivaldi window onto 2nd monitor
- non Vivaldi window onto 3rd monitor

and I do `chunkc tiling::monitor -f 2`, it works finely.

Please help me :joy:

**Comment by koekeishiya** [comment]
This is a limitation of the macOS API that is used. There is a way around this if you install the scripting addition (chunkwm-sa), but then you need to disable SIP on your system.

Sent from my iPhone

On 14 May 2019, at 06:24, aiya000 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi 😄

I have 3 monitors.
And I always put only a window onto a monitor.

Now I put

  *   iTerm2 window onto 1st monitor
  *   Vivaldi window onto 2nd monitor
  *   Vivaldi window onto 3rd monitor

also I do chunkc tiling::monitor -f 2,
then it goes to the 3rd monitor 😭
I want to go to 2nd monitor.

But if I arranged to

  *   iTerm2 window onto 1st monitor
  *   Vivaldi window onto 2nd monitor
  *   non Vivaldi window onto 3rd monitor

and I do chunkc tiling::monitor -f 2, it works finely.

Please help me 😂

**Comment by dominiklohmann** [comment]
See the first comment in issue #511 for more information.

**Comment by aiya000** [comment]
After install chunkwm-sa, it works finely.

I like chunkwm!
Thanks so much!

https://koekeishiya.github.io/chunkwm/docs/sa.html
