### ISSUE TITLE
Is there a way for me to know if 10.14.4 -> 10.14.5 will break script additions?

### ISSUE THREAD

**Issue by alextes** [koekeishiya/chunkwm#627]
If script additions generally only break between minor versions I'm happy to take the gamble. If they're known to break between patch versions I'd be happy to wait for someone to confirm it's working.

**Comment by Amar1729** [comment]
Only one data point, but scripting additions still work for me on 10.14.5. I have SIP disabled.

**Comment by koekeishiya** [comment]
The parts of the scripting addition that chunkwm uses works fine on 10.14.5 yeah.

**Comment by capaldo** [comment]
> Only one data point, but scripting additions still work for me on 10.14.5. I have SIP disabled.

Haven't noticed any issues as well with SIP disabled.

**Comment by alextes** [comment]
Thank you all 🙏 .
