### ISSUE TITLE
how to disable mouse_follows_focus?

### ISSUE THREAD

**Issue by mrjayviper** [koekeishiya/chunkwm#630]
steps I used:

1. I installed chunkwm via brew
2. I copied the sample chunkwmrc to my home folder
3. I an chunkwm for the first time using "brew services start chunkwm". After enabling the Accessibility setting, chunkwm started to do its thing.
4. I changed the setting for "chunkc set mouse_follows_focus". I was initially set to "intrinsic". I change that to "off".
5. I restarted chunkwm via "brew services stop chunkwm" and then "brew services start chunkwm".

The window focus still follows the mouse pointer.

Any ideas what I could be doing wrong? Thank you.

**Comment by joshvasquez** [comment]
You can disable the follow focus mode by commenting out or deleting `chunkc core::load ffm.so`

**Comment by mrjayviper** [comment]
> You can disable the follow focus mode by commenting out or deleting `chunkc core::load ffm.so`

Thanks for the suggestion. It worked!

**Comment by pvinis** [comment]
@mrjayviper you should close the issue. @joshvasquez thanks, i needed that too!
