### ISSUE TITLE
what values to use for color?

### ISSUE THREAD

**Issue by mrjayviper** [koekeishiya/chunkwm#631]
I am looking at the sample config that came with the installation (installed via brew) and I do not think this is  HTML-based which is normally 6 characters long.

I searched the net and the documentation and I cannot see what color format is used on the config.

Thanks!

**Comment by joshvasquez** [comment]
[border plugin docs](https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/border/README.md#set-border-color)

`chunkc set focused_border_color 0xAARRGGBB`

A is alpha, R red, G green, and B blue.

**Comment by mrjayviper** [comment]
> [border plugin docs](https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/border/README.md#set-border-color)
> 
> `chunkc set focused_border_color 0xAARRGGBB`
> 
> A is alpha, R red, G green, and B blue.

I saw that page but the AARRGGBB didn't click as RGB and even then. I wouldn't have know AA is for the alpha.

Thanks! :)
