### ISSUE TITLE
move desktop / change position of desktop

### ISSUE THREAD

**Issue by theonlygusti** [koekeishiya/chunkwm#633]
How do I move a Space rightwards/leftwards?

**Comment by BlueDrink9** [comment]
Unless you are using `chunkwm-sa`, the script addition you have to install manually, you will have to use the OS shortcut, which you can change to whatever you like.

However, you can add this to your `skhdrc`:

`alt - z  : skhd -k "ctrl - left"`

which will cause `alt + z` to send the OSX default shortcut for switching desktop.

Or are you meaning move spaces relative to oneanother?

**Comment by theonlygusti** [comment]
@BlueDrink9 move spaces relative to one another. I have sa installed

**Comment by dominiklohmann** [comment]
That’s not possible right now. 

Best you can do is to save the layout, move all windows to the target space and follow, move all other windows on there back to the original space, then restore the layout. There’s this one PR that’s never gotten merged (iirc) that improves layout restoration.

Using Mission Control for this is probably a lot smoother.

**Comment by koekeishiya** [comment]
The scripting addition does actually support this, and this was how it worked when I was experimenting. I didn’t really find it useful with my workflow so chunkwm was limited to moving between displays on purpose.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by theonlygusti** [comment]
@koekeishiya does/will yabai support it?

**Comment by koekeishiya** [comment]
It currently does not, undecided if it will.

**Comment by koekeishiya** [comment]
*yabai* has simple support for this, simply moving the active desktop one to the left, or one to the right.
