### ISSUE TITLE
Switching desktop doesn't switch on monitor with focus

### ISSUE THREAD

**Issue by natsumi** [koekeishiya/chunkwm#636]
I have a multiple monitor setup with each monitor having multiple desktops.  If I use a chunkwm to switch monitor focus, then hit the shortcut to switch desktop spaces, it'll switch on the monitor that my mouse cursor is over and not the monitor with active focus.

This causes me to have to take my hand off the kb to move my mouse over.

Is there any way to have the desktop switch work on the currently active monitor?

**Comment by nikolaJosifovic** [comment]
Try to find answer here https://github.com/koekeishiya/chunkwm/issues/571

**Comment by natsumi** [comment]
Turning on mouse follow focus worked.  Thanks.
