### ISSUE TITLE
[plugin/tiling] ToogleWindow function don't check for floating window

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#64]
Edit: Second time I open an issue without typing a word XD

But basically the ToggleWindow function don't check if the window passed is floating, this can lead to crashes when calling one of the function on one of these. Obviously one shouldn't call these function floating windows but it can happen by pressing the wrong binding etc.. and we should probably not crash. Specifically in many places it check for `(!Node && !Node->Parent)` leading to a crash

**Comment by koekeishiya** [comment]
Uh, do you have a line of code or steps to reproduce a crash? I don't see a particular problem in the ToggleWindow function. Probably just something I'm overlooking.

**Comment by choco** [comment]
```
chunkc window --toggle float
chunkc window --toggle split 
```
on the same window produces one reliably.

**Comment by koekeishiya** [comment]
Well that is a major fuckup, wonder how late it was when I wrote that line of code.

It's supposed to be `if(!Node || !Node->Parent)` so we can short-circuit.

**Comment by koekeishiya** [comment]
I have tested this and it should now be fixed.

**Comment by koekeishiya** [comment]
Marking this as a bug even tho it is fixed, for future references.
