### ISSUE TITLE
Clicking notifications changes space order

### ISSUE THREAD

**Issue by xiamaz** [koekeishiya/chunkwm#640]
When using apps having notifications, which should raise the app on clicking, the order of spaces gets mixed up.

## Example

[1], [2], [3] with Telegram on [3].

Focusing [1]

Clicking Telegram notification

Telegram gets raised, but now Telegram is on [2] Any applications in the same space as telegram are also in 2 now.

**Comment by koekeishiya** [comment]
There is no code in chunkwm to change the order of spaces. You have likely enabled the mission control setting «Automatically rearrange spaces by recent use» or whatever the name is.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xiamaz** [comment]
Thanks for the quick answer! Never realized there is this kind of option in mac os
