### ISSUE TITLE
[plugins|tiling] App quitting native fullscreen not always retiled

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#68]
It would be nice to investigate why the window isn't always retiled like it should.

**Comment by choco** [comment]
Just by looking at the logs the operations order when a window goes to native fullscreen seem to be:
1. window1 focused
2. another window created (i'll call this window 2)
3. window2 focused -> can be after the event below
4. window1 resized -> can be before the event above
5. space changed -> window listed on new space: window1
6. window2 destroyed
7. window1 focused

and the operation when a window exits fullscreen

1. window1 focused
2. another window created (i'll call this window 2)
3. window1 resized -> can be after the event below
4. window2 focused  -> can be before the event above
5. space changed -> window listed on new space:
   1. when tiling works: window1 is listed, as a valid window
   2. when tiling doesn't work: window2 is listed as invalid
6. window2 destroyed
7. window1 focused

**Comment by koekeishiya** [comment]
Is this when using the provided `chunkc window --toggle native-fullscreen` or when toggling externally?

**Comment by choco** [comment]
Both!

**Comment by koekeishiya** [comment]
Because this also happens when issuing the chunkc command which explicitly handles both untile and retile of the window, it seems like the cases where a problem occurs, the window is actually destroyed and created with a new identifier, and we somehow are not properly picking up on the window_created event.

**Comment by choco** [comment]
I think we pick up all the events.
Here's the log, I also added to the print the windowID to know which does which.
We start in a desktop with a Safari window and an iTerm one
```
Entering fullscreen:

 msg: 'window --toggle native-fullscreen'
1 arg '--toggle'
2 arg 'native-fullscreen'
    command: 't', arg: 'native-fullscreen'
Safari:[plugins|tiling] App quitting native fullscreen not always retiled · Issue #68 · koekeishiya/chunkwm:9538 window moved
Safari:[plugins|tiling] App quitting native fullscreen not always retiled · Issue #68 · koekeishiya/chunkwm:9538 window resized
iTerm2::9711 window created
iTerm2:1. prezto:2:zsh - "swordfish-II"  (tmux):8545 window resized
iTerm2::9711 window focused
Finder:<unknown> is not destructible, ignore!
0:desktop   9711:0:invalid window:iTerm2:
iTerm2::9711 window destroyed

Quitting fullscreen:

iTerm2:1. prezto:2:zsh - "swordfish-II"  (tmux) window title changed
 msg: 'window --toggle native-fullscreen'
1 arg '--toggle'
2 arg 'native-fullscreen'
    command: 't', arg: 'native-fullscreen'
iTerm2::9711 window created
iTerm2:1. prezto:2:zsh - "swordfish-II"  (tmux):8545 window resized
iTerm2::9711 window focused
Finder:<unknown> is not destructible, ignore!
2:desktop   9711:0:invalid window:iTerm2:
2:desktop   9538:0:Safari:[plugins|tiling] App quitting native fullscreen not always retiled · Issue #68 · koekeishiya/chunkwm
iTerm2::9711 window destroyed
```

**Comment by koekeishiya** [comment]
Do the existing window and the new temporary window have the same windowid??

If so we have a potential fundamental problem. Windows are stored using the windowid as the unique key..

**Comment by choco** [comment]
Nope, different ID, you can see in the log that the "real" window has 8545 id, the "fake" one 9711. Strangely the fake window ID seems to be the same when entering and then quitting fullscreen.
To clarify it isn't always the same, but in a enter-quit cycle seems to stay the same.

**Comment by koekeishiya** [comment]
```
 msg: 'window --toggle native-fullscreen'
1 arg '--toggle'
2 arg 'native-fullscreen'
    command: 't', arg: 'native-fullscreen'
Finder:programming:40932 window moved
Finder:programming:40932 window resized
Activity Monitor:44519 window created
Activity Monitor:Activity Monitor (All Processes):42714 window resized
Activity Monitor:Activity Monitor (All Processes):42714 window resized
Activity Monitor::44519 window focused
Finder:<unknown> is not destructible, ignore!
0:desktop   42714:0:Activity Monitor:Activity Monitor (All Processes)
Activity Monitor::44519 window destroyed
 msg: 'window --toggle native-fullscreen'
1 arg '--toggle'
2 arg 'native-fullscreen'
    command: 't', arg: 'native-fullscreen'
Activity Monitor:44519 window created
Activity Monitor:Activity Monitor (All Processes):42714 window resized
Activity Monitor:Activity Monitor (All Processes):42714 window resized
Activity Monitor:Activity Monitor (All Processes):42714 window resized
Activity Monitor::44519 window focused
Finder:<unknown> is not destructible, ignore!

FULlSCREEN TO NORMAL SPACE

4:desktop   44519:0:invalid window:Activity Monitor:
details: id: 44519
level: 0
name: 
owner: Activity Monitor
role: AXWindow
subrole: AXUnknown
movable: 1
resizable: 0

4:desktop   40868:0:Safari:Untitled
4:desktop   41323:0:kitty:Koe@Asmunds-MacBook-Pro: ~
4:desktop   40932:0:Finder:programming
Activity Monitor::44519 window destroyed
```

The `original` window `42714`, is never destroyed or touched in any noticable way, by MacOS.
However, as you can see from the above log, the `original` window is no longer returned to us by the MacOS API, after returning from fullscreen desktop -> normal desktop (added code to detect this type of transition).

We do see that some transparent window `44519` is `created` when we tell the `original` window to enter fullscreen and after the transition has finished, it is `destroyed`.

The same exact behaviour happens when we exit fullscreen. The same transparent window `44519` is again created, and after the transition has finished, it is `destroyed`.

If we manually switch away from the desktop where the window failed to tile after exiting fullscreen, and then go back to that same desktop again, we can see that `RebalanceWindowTree()` properly does retile the window.

This issue seems to be due to how the internal MacOS API manages windows.

**Comment by choco** [comment]
I'd really love to know why on earth they need to create a random window when doing those operations ahahah
In kwm to fix this I added a `RebalanceWindowTree` to WindowDestroyed handler (https://github.com/koekeishiya/kwm/pull/504/files#diff-26635c43a92b5d7a3c6efd5eb9b309e1R381), and this seems to fix the issue on chunkwm as well but it's more of an hack then anything and a proper way would be better, like maybe still have a call to `RebalanceWindowTree` into WindowDestroyed but only on this kinds of windows, if we're able to identify them.

**Comment by koekeishiya** [comment]
> if we're able to identify them.

Well, we know so far that these windows are amongst the invalid windows category, which will limit how often this function will be called from Window_Destroyed. There will be times when a non-related invalid window will be destroyed and trigger such an event, but I have no other ideas as to how this problem can be solved. This is pretty much the only solution that I can think of.

**Comment by choco** [comment]
10/10 commit message 👌
