### ISSUE TITLE
[plugins|tiling] Safari window when terminated isn't removed for window tree

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#69]
I'm able to only reproduce this reliably with Safari, not sure if it's specific to that only.
1. be in a bsp desktop
2. start Safari, window should take all space available (single node)
3. quit Safari
4. launch Safari again, window takes only half of the desktop space

**Comment by koekeishiya** [comment]
This doesnt seem to be specific to Safari.

I can reproduce for a lot of applications by doing the following:

1. be in a bsp desktop
2. start Safari, Notes (applications that behave similar)
3. quit application WITHOUT closing the window
4. launch any application or window
