### ISSUE TITLE
[plugin|tiling] Window rules

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#73]
Wondering what people would use this for, except for setting float and different accepted AXRoles.
What kind of filters would you like to see and why.

This feature was originally (and currently just a way to get some applications to work alongside kwm), but some potential ideas can't hurt.

**Comment by dominiklohmann** [comment]
I mostly use it for floating windows depending on their window title.

Some examples from my Kwm rules:
```
kwmc rule owner="QuickTime Player" name="Screen Recording" properties={float="true"}
kwmc rule owner="Tweetbot" properties={float="true"} except="Main Window"
kwmc rule owner="Trash" properties={float="true"}
kwmc rule owner="Finder" name="Copy" properties={float="true"}
```

> What kind of filters would you like to see and why.

- The same as above to make some applications work with chunkwm, most importantly the `name` and `except` filters in combination with `float`.
- I would like to see smooth solution for floating every window of an application except for the first one (per space). It's just hard to do if the main window doesn't have a fixed title.
- That's it! But I would like to see the system be less prone to errors. With rules in Kwm, having a syntax error often silently breaks everything. That shouldn't be happening.

**Comment by TheEmpty** [comment]
I have a few games set to float because they have to maintain a certain aspect ratio. Then what happens is KWM would resize them, then the game would resize, ∞

**Comment by crisidev** [comment]
I use it mostly to specify which monitor / space the window is forced to and to set float on some applications which needs to maintain the aspect ration.

**Comment by koekeishiya** [comment]
```
# section - window rules

# regex filters (pattern is case sensitive):
#  --owner | -o
#  --name  | -n

# properties:
#  --state | -s
#   values:
#    float
#    tile

chunkc rule --owner "System Preferences" --state tile
chunkc rule --owner Finder --name Copy --state float
```

Currently, the only thing you can do with rules is force a window to tile regardless of the accessibility role or whatever, and make a window float by default. Windows that have been affected by these rules can still be unfloated / floated manually afterwards.

> The same as above to make some applications work with chunkwm, most importantly the name and except filters in combination with float.

The **except** filter has been removed, but you should be able to get the old behaviour by using a regex pattern for the **name** filter.

> I would like to see smooth solution for floating every window of an application except for the first one (per space). It's just hard to do if the main window doesn't have a fixed title.

I have not yet looked into this, but could be a potential addition in the future.

> That's it! But I would like to see the system be less prone to errors. With rules in Kwm, having a syntax error often silently breaks everything. That shouldn't be happening.

There are two errors that we currently check for, missing filters and missing state.
These are done at parsetime, and will print to *stdout*

> I use it mostly to specify which monitor / space the window is forced to

There is no support for this for now, but will probably take a look at adding this in the future.

**Comment by choco** [comment]
I someone figures out how to match a title that doesn't contain a string let me know, no idea how to do it with posix regex

**Comment by koekeishiya** [comment]
https://www.gnu.org/software/findutils/manual/html_node/find_html/posix_002dextended-regular-expression-syntax.html

**Comment by koekeishiya** [comment]
> I someone figures out how to match a title that doesn't contain a string let me know, no idea how to do it with posix regex

This seems to be particularly hard in POSIX regex, so I'll probably have to add a separate **except** filter.

**Comment by koekeishiya** [comment]
@choco 
> I someone figures out how to match a title that doesn't contain a string let me know, no idea how to do it with posix regex

>> This seems to be particularly hard in POSIX regex, so I'll probably have to add a separate except filter.

Added except for this. It performs a regex match on the pattern, and simply asserts that no matches was found (pretty sure this is how it worked in kwm).

**Comment by choco** [comment]
> Added except filter because of this. It performs a regex match on the pattern, and simply asserts that no matches was found (pretty sure this is how it worked in kwm).

Works well for my use case 👍

**Comment by crisidev** [comment]
Looks like the window rules patterns you implemented works fine for my usecase too. Thanks! 👍
