### ISSUE TITLE
[plugins | tiling] focused_window_float event not always sent

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#74]
EDIT: Omg, I keep pressing enter when creating issues.

`focused_window_float` event is sent inside the `Focused` and `Activated` handler. But for some window this event isn't sent. The check `IsWindowValid` also checks for windows are Resizable or Movable, but this is probably too strict in this situation, since we also make non resizable window float. The event isn't basically sent for the windows that need it the most.

**Comment by koekeishiya** [comment]
Should be fixed on master. May have caused other issues regarding bsp-insertion-point.

**Comment by choco** [comment]
One issue I found is that when a window comes back from native fullscreen, ffm doesn't focus other window in the spaces, like the window is floating.
