### ISSUE TITLE
[plugin|tiling] Ignore spurious focused notification

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#75]
I'm sorry for issues spam, but any time I encounter one I prefer to write it down, so I can get back to it later and investigate.

Basically applications with a focused window will sometimes emit a focused event even though the focus hasn't changed, and the focus event is still referring to the same window. This wouldn't be a problem, but with the addition of cursor centring on focusing or activation this can be a problem, since the cursor jump back to the centre even if the focus never changed. So we just need to ignore these, or at least don't perform the centring again.
Checking that the cursor is inside the window rect isn't enough to prevent this because the cursor may on the desktop or the menu bar.

**Comment by koekeishiya** [comment]
> I'm sorry for issues spam, but any time I encounter one I prefer to write it down, so I can get back to it later and investigate.

No worries, this is a good thing :)

I added the following logic, hoping it will fix it:

When we receive focused changed / app activated, we get our already focused window id,
if this window id is not equal to the window passed as argument for the event, we perform the mouse move.
