### ISSUE TITLE
[plugins|tiling] leaving native fullscreen ffm sync

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#77]
@choco 

> One issue I found is that when a window comes back from native fullscreen, ffm doesn't focus other window in the spaces, like the window is floating.

**Comment by choco** [comment]
The fix doesn't doesn't correctly handle the case where I have a floating window focused, switch to another space, then switch back and standby_on_float fails.

**Comment by koekeishiya** [comment]
This is because our call to `AXLibGetVisibleWindowsForSpace()` in `SpaceAndDisplayChangedHandler()` does not include floating windows.

This is due to prerequisite of `Create/RebalanceWindowTree()` functions.
The issue isn't hard to fix, but will require some rethinking to keep everything the way I want.

**Comment by koekeishiya** [comment]
Created new issue for the bug you mentioned.
