### ISSUE TITLE
padding and gaps

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#8]
Just wanted to hear opinions of having the screen padding be separate from window gaps.

In Kwm, padding could be set for all screen directions separately, they did not have to be equal.
Vertical and horizontal window gaps were also independent of any screen padding.

Is that a behaviour that people like, and should it stay that way?

Currently thinking about doing one of the below:
 - Keep the behaviour that Kwm has.
 - Keep screen padding and window gaps separate, but uniform.
    Thus, there is only `window_gaps = 'num'` and `screen_padding = 'num'`.
 - Merge all types of gaps, `window_gaps = 'num'`, but these also apply outwards 
    toward edges of the screen, regardless of the window having adjacent windows.

**Comment by matthewdias** [comment]
I personally would like it to stay the same way as Kwm. I use padding that is larger than the gaps, and different larger vertical than horizontal padding, to account for top and bottom bars. That said, I can't think of a reasonable use case for having non-uniform window gaps.

**Comment by net** [comment]
Agreed with @matthewdias. Merge x and y padding, keep gaps and edges separate.

**Comment by koekeishiya** [comment]
So I've decided padding will remain individual, and gaps will be uniform.
