### ISSUE TITLE
macOS High Sierra

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#80]
Need to investigate if there are breaking changes regarding private APIs.

**Comment by dominiklohmann** [comment]
I ran Kwm, Khd and chunkwm in a beta (clone of my usual setup upgraded in a VM for testing purposes) and experienced no issues so far. Do you want me to test anything specific?

**Comment by koekeishiya** [comment]
Nothing in particular for now, but figured it might be worth opening an issue in case something comes up.

**Comment by dominiklohmann** [comment]
For what it's worth, you don't need an Apple Developer account to install the beta. You only need to install the profile they list in the download portal behind that 99$ paywall, so if you want to test it yourself you could easily download that file from a third party. Just make sure to verify the code signature to avoid downloading malware (saw some fake ones around last year).

You shouldn't upgrade your main partition though, not all applications are working yet (some only without APFS) and there seem to be some weird issues with Sleep and all window title bar related code. On the plus side, all the desktop animations are buttery smooth even in a VM with very limited resources. Mission Control lag seems to be gone completely.

**Comment by dominiklohmann** [comment]
http://codeworkshop.net/objc-diff/sdkdiffs/macos/10.13/ Found this on the internet if you want to see API diffs. Can't find anything that has changed that chunkwm is using.

**Comment by koekeishiya** [comment]
This is potential bad news, as if monitor stuff was not already hard enough to deal with..

The following function has been removed (not deprecated, removed..):

**CGDisplayCreateUUIDFromDisplayID(CGDirectDisplayId ..)**

This function is pretty much the core of how we currently uniquely identify monitors.

**Comment by choco** [comment]
If I understand @dominiklohmann correctly compiled chunkwm, if they really removed usually compiling would simply fail. Also the Dock has to have a way to generate similar information, so maybe they moved declaration in another framework, made the call private or simply built an alternative?

**Comment by dominiklohmann** [comment]
Nope, I did not recompile. My VM was a copy of my main setup upgraded to High Sierra. Also I was unable to test any multiple monitor stuff due to VM constraints.

I will test the compilation later today when I've got some free time and report back.

**Comment by dominiklohmann** [comment]
Mhm, what I was currently doing wasn't very interesting anyways, so here goes. 

```sh
chunkwm/src/plugins/tiling git/remotes/origin/HEAD 
❯ make
```
```
clang++ plugin.cpp node.cpp region.cpp vspace.cpp controller.cpp config.cpp ../../common/accessibility/display.mm ../../common/accessibility/application.cpp ../../common/accessibility/window.cpp ../../common/accessibility/element.cpp ../../common/accessibility/observer.cpp ../../common/ipc/daemon.cpp ../../common/config/cvar.cpp ../../common/config/tokenize.cpp ../../common/misc/carbon.cpp ../../common/misc/workspace.mm -O0 -g -DCHUNKWM_DEBUG -std=c++11 -Wall -Wno-deprecated -o ../../../plugins/tiling.so -shared -fPIC -framework Carbon -framework Cocoa -framework ApplicationServices
plugin.cpp:1438:41: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    CreateCVar(CVAR_WINDOW_FOCUS_CYCLE, "none");
                                        ^
1 warning generated.
region.cpp:38:16: warning: enumeration value 'Dock_Orientation_Top' not handled in switch [-Wswitch]
        switch(Orientation)
               ^
region.cpp:38:16: note: add missing switch cases
        switch(Orientation)
               ^
1 warning generated.
controller.cpp:139:12: warning: enumeration value 'Dir_Unknown' not handled in switch [-Wswitch]
    switch(Direction)
           ^
controller.cpp:139:12: note: add missing switch cases
    switch(Direction)
           ^
controller.cpp:181:16: warning: enumeration value 'Dir_Unknown' not handled in switch [-Wswitch]
        switch(Direction)
               ^
controller.cpp:181:16: note: add missing switch cases
        switch(Direction)
               ^
controller.cpp:273:30: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
                FocusMonitor("next");
                             ^
controller.cpp:277:30: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
                FocusMonitor("prev");
                             ^
controller.cpp:303:98: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
                else if(StringEquals(FocusCycleMode, Window_Focus_Cycle_All))       FocusMonitor("prev");
                                                                                                 ^
controller.cpp:309:98: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
                else if(StringEquals(FocusCycleMode, Window_Focus_Cycle_All))       FocusMonitor("next");
                                                                                                 ^
6 warnings generated.
```

**Comment by dominiklohmann** [comment]
False alarm: `CGDisplayCreateUUIDFromDisplayID`and `CGDisplayGetDisplayIDFromUUID` have simply been moved from `ApplicationServices` to `ColorSync`.

**Comment by choco** [comment]
Funny thing, it was always there, `ApplicationServices` only had a reference to it, *Apple things™*

**Comment by koekeishiya** [comment]
I'm more worried about the private APIs we use, as these are not listed in the docs / changelog.
Although if everything seemed to work so far, then I think we're safe to assume that we should be fine.

I do not have enough free space to run High Sierra in a VM, and I only have one MBP, so I won't be able to test until later into the public beta cycle.

**Comment by dominiklohmann** [comment]
Found an issue: Opening tabs in applications that use native cocoa tab handling (Terminal.app, Maps.app and many more / weirdly enough not Safari) makes chunkwm think a new window has been spawned. Demonstration gif (too big for direct upload here): https://gfycat.com/UnhealthyBountifulIndianpangolin

Temporary fix is a cmd-t passthrough bind in Khd for rebalancing the window tree. Same issue exists with Kwm for what it's worth.

Additionally, using the new feature "Show All Tabs" for apps using native tabs seems to spawn a new window and hide the original window (using it somehow rebalances the window tree?). Screenshot: 
<img width="1754" alt="screen shot 2017-06-18 at 10 05 13" src="https://user-images.githubusercontent.com/4488655/27259216-ddeace96-540d-11e7-942d-bfd7e51523ac.png">

I think the real WTF here is that Safari does tab handling differently from all other cocoa apps?

**Comment by koekeishiya** [comment]
If you close a tab again. Is the window resized back?? If you run a debug build of chunkwm / plugins all events will be logged to stdout

**Comment by dominiklohmann** [comment]
So I can't get it to print event logs, but yes, closing a tab resizes it back to normal, as does switching to another space and back. Here's a gif: https://gfycat.com/AncientPessimisticGuppy

**Comment by dominiklohmann** [comment]
Just updated my VM to beta 2. Small things I noticed in the first 10 minutes:
- window title bars are no longer broken
- iterm2 works again
- Bartender can no longer hide system menubar icons, its osax functionality seems to be broken (?)
- chwm-sa still works
- chunkwm and plugins compile and work just fine
- khd still works
- window server animations seem even smoother than in beta 1
- chunkwm tries to tile search results in in System Preferences.app (looks really weird)

Will add more things as I find them. If you want to know anything specific, feel free to ask.

**Comment by dominiklohmann** [comment]
Nothing relevant changed for beta 3. 

Native tabs are still bugged.

**Comment by choco** [comment]
@dominiklohmann Would you mind opening a bug report about it? Because we'll have a really high probability of getting it fixed if we report it now. I would do it, but unfortunately I don't have time to install new beta versions to try. Basically just need to say that new tabs are sending new window creation notification through the accessibility api

**Comment by dominiklohmann** [comment]
Isn't it the Carbon API though and not Accessibility (the former is deprecated)? The notification is kAXWindowCreatedNotification if I recall correctly.

**Comment by koekeishiya** [comment]
Its the acceswibility API. The carbon only notifies about process launch and termination.

**Comment by dominiklohmann** [comment]
Alright, gonna open a bug report then.

**Comment by koekeishiya** [comment]
> chunkwm tries to tile search results in in System Preferences.app (looks really weird) This only happens if you force tile the application with a rule. Seems to be a bug with the rule system rather than High Sierra.

Fixed in latest release, if explicit role is used as a filter in the rule (optional, but necessary in some cases), see #176

**Comment by dominiklohmann** [comment]
Ah, forgot to update this for beta 4. No reply on my bug report yet. 

The only issue I have experienced still is the tabs issue, other than that chunkwm and mission control seem to be running smoother than they ever did on 10.12.

**Comment by koekeishiya** [comment]
@dominiklohmann 

Would you be able to paste the output of `chunkw tiling::query --desktop windows` after reproducing the *gif* with tabbed Maps.app from above?

Im curious to see if we could somehow use this to filter these windows if the ticket @ Apple does not get any response before release.

**Comment by dominiklohmann** [comment]
It only shows the active tab/window. Also if you `ctrl-tab` through the windows it shows the tab where it would've been as a window if it actually tiled every tab as a window.

**Comment by dominiklohmann** [comment]
Double deminimize and focused events

![bug](https://user-images.githubusercontent.com/4488655/29241466-ddfda500-7f7a-11e7-82c7-88a3de6e06b3.gif)

**Comment by dominiklohmann** [comment]
Native tabs still not fixed in beta 6 ¯\\\_(ツ)\_/¯

**Comment by koekeishiya** [comment]
Does beta 6 otherwise seem stable enough to run as a primary OS for daily use?

**Comment by dominiklohmann** [comment]
If you don't rely on Bartender, Airfoil, Duet Display want to compile gcc via Homebrew or run an NVIDIA GPU (from what I've head) I'd say it's more reliable than macOS Sierra already. 

Little Snitch 3 is dead, gotta pay for the upgrade to Little Snitch 4 if you want to use it.

Window Server is definitely much better in High Sierra, despite the few AX notification issues.

Safari has some weird cursor lag while the search/location bar is open.

If you wanna install it for daily use, definitely back everything up just to be sure.

**Comment by dominiklohmann** [comment]
Nothing relevant changed in the GM.

@koekeishiya I suggest closing this issue and opening a superseding one for the native tabs issue on High Sierra.

**Comment by chrishoage** [comment]
The GM is out for High Sierra (it releases tomorrow)

**Comment by dominiklohmann** [comment]
Looks like we'll have to live with window created notifications for created native tabs.

**Comment by koekeishiya** [comment]
Will install High Sierra asap. It is not yet available for me in the app store for whatever reason.

I have some things that I'm going to try regarding how to handle the tabbed issue. I'm not sure if they will work, but it is worth a try.

@dominiklohmann Would you mind creating the issue regarding the tabbed windows ?

Thanks.

Closing this.
