### ISSUE TITLE
Focus previous/next window

### ISSUE THREAD

**Issue by joshuap** [koekeishiya/chunkwm#81]
Is there an equivalent to `kwmc window -f prev` and `kwmc window -f next` yet? If not, is that on the roadmap? (I don't see it mentioned in #16.)

I'm currently using the direction (north/south/east/west) values, but I'm also accustomed to cycling prev/next windows quickly and haven't found a way to implement that in chunkwm yet.

**Comment by dominiklohmann** [comment]
I asked about it here: https://github.com/koekeishiya/chunkwm/issues/15#issuecomment-302711335
@koekeishiya replied right below that he's not sure if he's going to implement that feature. 👎

**Comment by joshuap** [comment]
@dominiklohmann ah, I missed that, thanks! It sounds like we have  similar workflows. On spaces with just a few windows I find it easier to cycle forward/back rather than thinking about direction. In kwm and xmonad I have prev/next window bound to mod+j and mod+k respectively.

I'd be interested to hear why @koekeishiya feels this is out of place in chunkwm and if there is an alternative.

**Comment by dominiklohmann** [comment]
@koekeishiya has your opinion on this changed by chance? Still missing this one bind, and even after a few weeks of using chunkwm over Kwm I have not been able to get used to it.

**Comment by koekeishiya** [comment]
I guess it makes sense to have this ability. No ETA for when this is going to happen though, as it requires quite some changes. The current logic is based on selecting window soleley by distance.

**Comment by koekeishiya** [comment]
Was easier to adapt the necessary code than expected.

window --focus, --swap, --warp, --use-insertion-point, --adjust-window-edge now all support prev | next as well.

The chunkwm-tiling readme has been updated to reflect these changes.

prev / next performs west / east respectively for desktops in monocle mode.
