### ISSUE TITLE
[plugins|ffm] slow performance/high CPU usage?

### ISSUE THREAD

**Issue by joshuap** [koekeishiya/chunkwm#82]
I just noticed that with the ffm plugin enabled I get some noticeable drag when moving the mouse rapidly and CPU utilization for the `chunkwm` process in `htop` spikes as high as 30%. After disabling the `ffm` plugin, the `chunkwm` process barely registers at all no matter what I do. This is my system:

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
```

**Comment by koekeishiya** [comment]
The ffm plugin is still in the "make it working" phase. I have an optimization in mind for when I feel like programming, which should improve this quite a lot.

**Comment by joshuap** [comment]
@koekeishiya thanks for the quick commit! Memory utilization with the new ffm plugin is much lower. I'll keep it enabled and let you know it goes.

**Comment by koekeishiya** [comment]
The ffm plugin was more or less completely re-written in the latest release (v0.2.14).

From my testing, it has a low cpu-usage and memory footprint, and should feel pretty responsive.

**Comment by marcjoha** [comment]
I started using chunkwm just yesterday (and loving it btw!) so I have nothing to compare with, but I've noticed that general performance is noticeably worse with ffm enabled. This is particularly obvious in Chrome. Hovering a link can take a few seconds before the underline shows up. Disabling ffm and everything is fast again. Anything I can do to help debug?

**Comment by garymm** [comment]
I'm seeing really sluggish performance in Chrome with FFM enabled just like @marcjoha. It seems like it started around the time I upgraded to MacOS Mojave.
I'm currently using MacOS 10.14.3.
    
    ➜  brew info chunkwm
    koekeishiya/formulae/chunkwm: stable 0.4.7, HEAD

It's much worse when I'm using a large external monitor, but I also notice it even using just the built-in display.

Should I file another bug about this?
