### ISSUE TITLE
[plugin|tiling] alt - rightmouse to resize window in bsp mode

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#83]

**Comment by dominiklohmann** [comment]
I think this would feel more natural if it dragged relative to the border instead of making the border jump to the cursor.

Also feels way smoother than in Kwm 👍

**Comment by koekeishiya** [comment]
> I think this would feel more natural if it dragged relative to the border instead of making the border jump to the cursor.

Agreed, will look into this next session.

> Also feels way smoother than in Kwm

I noticed this as well. Quite satisfied with the performance so far.

Will see if optimization is needed later on, as I think it can be made even better (from a code perspective)

**Comment by koekeishiya** [comment]
@dominiklohmann 

> I think this would feel more natural if it dragged relative to the border instead of making the border jump to the cursor.

Implemented on master. Feels way better this way, nice suggestion!
