### ISSUE TITLE
[plugin|tiling] alt - leftmouse to swap window in bsp mode

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/chunkwm#84]

**Comment by dominiklohmann** [comment]
This breaks native macOS functionality, alt+leftclick shows extended menus on both dock and menubar items. (Examples: Finder in dock lets you restart Finder.app, Wi-Fi in menubar shows debug data)

**Comment by koekeishiya** [comment]
Right, forgot about these things, thanks for letting me know.

Will figure out some way to deal with this.

**Comment by dominiklohmann** [comment]
I think simply changing the key for ignoring ffm and the drag-binds is enough. Why not use fn instead of alt?

**Comment by koekeishiya** [comment]
fn had some weird instances last time I used it in **khd**.

I don't have fn on my mechanical keyboard  though, which is why I didn't think about it.

**Comment by dominiklohmann** [comment]
I think fn is the only modifier key that has no issues whatsoever with mouse clock binds. Or you'll have to use some combination, like cmd+ctrl. Just can't use alt.

fn to me seems to be the smoothest option for people using Apple keyboards.

**Comment by koekeishiya** [comment]
Does cmd+alt seem like an ok combination for this? I'd prefer to also support keyboards without the fn-key. Worst-case scenario I'll default to fn, but make it configurable.

**Comment by dominiklohmann** [comment]
> Worst-case scenario I'll default to fn, but make it configurable.

I'd prefer this. Pressing cmd+alt is feels breaking fingers using the built-in MacBook keyboard, but that's probably just me.

**Comment by koekeishiya** [comment]
> I'd prefer this. Pressing cmd+alt feels like breaking fingers using the built-in MacBook keyboard, but that's probably just me.

I think that is the correct choice to make as well.

**Comment by dominiklohmann** [comment]
Just tested it, seems to work just fine. Thanks for the quick fix 👍

**Comment by net** [comment]
(cont. from https://github.com/koekeishiya/khd/issues/11) I've been using `fn` as a modifier in khd since January with no issues thus far.

**Comment by choco** [comment]
Would it be possible to add support three fingers touchpad drag? Pretty sure it worked with kwm, just stalls probably waiting for a keyrelease that doesn't come in chunkwm

**Comment by koekeishiya** [comment]
I've never tried three finger drag (no idea how it works), however I have made a slight difference between the behaviour in kwm and the implementation in chunkwm.

In kwm, you'd initiate mouse-drag, move mouse above some window, release mouse-drag.
This would swap the focused window and the window that was selected.

In chunkwm, you mouse-over the window you want to swap, initiate mouse-drag, move mouse above some other window, release mouse-drag. The two selected windows will now swap.

The only difference I can think of is that in kwm, the mouse-drag modifier could be released before the mousebutton.

In chunkwm (currently), you need to hold the fn modifier while releasing the mouse button.
e.g: mouseover window, fn + left mouse (three finger can substitute this??), select destination, release mouse button -> release fn.

**Comment by koekeishiya** [comment]
@choco 

> Would it be possible to add support three fingers touchpad drag? Pretty sure it worked with kwm, just stalls probably waiting for a keyrelease that doesn't come in chunkwm

I removed the requirement to hold FN upon drag and release. The FN modifier is only required to be down upon right / left mouse down now.

**Comment by net** [comment]
Will this be configurable? I'd like to use `fn + shift + left click` instead of `fn + right click`. Two finger click and drag is a little clumsy on a trackpad.

**Comment by dominiklohmann** [comment]
Wouldn't it make sense to just always offer `fn + ctrl + left click` as an alternative to `fn + right click` since `ctrl + left click` is the same as `right click` anyways?

**Comment by net** [comment]
@dominiklohmann `shift` is easier to hit than `ctrl` if your pinky is on `fn`.

**Comment by koekeishiya** [comment]
Ideally, I'd like these to be abstracted away completely, as commands.

You could then map these using any external programs, as any other command.

e.g: If i wanted to, I could initiate mouse-resize (currently fn - right mouse), by using khd:
`shift + cmd - button3 : chunkc mouse --resize` or something.

The reason why interchanging left / right-button or making this customizable in general, becomes an issue, is because there are three different kinds of mouse-moved events from the MacOS API side of things that we need to manage. These are `mousemoved`, `leftmousedragged`, `rightmousedragged`.

It surely is possible to achieve customization here, but not sure yet how clean that system would become. I'll leave this the way it is for now, until I (or someone else) can come up with a good solution for this.

**Comment by koekeishiya** [comment]
@net added support for arbitrary modifier, #150

**Comment by koekeishiya** [comment]
See #220
