### ISSUE TITLE
[plugin|border] Border isn't shown when switching from a native fullscreen space

### ISSUE THREAD

**Issue by choco** [koekeishiya/chunkwm#85]
Issue was still before the last refactoring.

**Comment by choco** [comment]
To add more info, this happens because `UpdateWindow` is behind a `DrawBorder` check. This is set when switching to a fullscreen space, but since `ApplicationActivated` notification is received before the `space changed` one, we try to draw the border before setting the correct `DrawBorder` value. 
Either we need to update border again when we receive the space changed notification, or move the space changed logic inside the activation handler

**Comment by koekeishiya** [comment]
I don't remember why DrawBorder check was necessary in UpdateWindow. The updateborder call done in the SpaceChangedHandler for non-user-spaces should in theory be enough.

**Comment by choco** [comment]
Agreed 👍

**Comment by koekeishiya** [comment]
So the DrawBorder check was done because when we entered a fullscreen space, the space border was not cleared in cases where a new window was created for that space or something.

Anyway this is all just stupid anywya, as we can just call `AXLibIsWindowFullscreen()`.

**Comment by sunjon** [comment]
Windows aren't getting retitled when leaving native full screen, after this change.
There's also a border drawn whilst in native full screen, that I don't recall being the previously.

**Comment by koekeishiya** [comment]
> Windows aren't getting retitled when leaving native full screen, after this change.

This change does not touch the tiling plugin and could not have caused this behaviour.

> There's also a border drawn whilst in native full screen, that I don't recall being the previously.

Unable to reproduce this with the applications I have tested with. Any more specific information you could share?

**Comment by choco** [comment]
@koekeishiya I can reproduce a bug with safari . Basically open a video (a youtube video maybe) and make the video fullscreen, and you'll see that the border is shown and not resized. This is because in this case the window doesn't have the correct role (it's just a AXWindow)

**Comment by koekeishiya** [comment]
@choco 

Regardless of the AXWindow role though, it is still placed in a fullscreen space.
Thus, from my pov, the window should report as a fullscreen window through the accessiblity API...
Get Apple'd again I suppose.

Readding the code to clear border upon fullscreen space activation fixes the issue you mentioned with safari. I suppose we need both fixes in place.

**Comment by choco** [comment]
The window is reported as a fullscreen one but the code in `UpdateWindow` is never reached, the check is in `WindowFocusedHandler` before calling `UpdateWindow`

**Comment by koekeishiya** [comment]
Right, can't really change that either or we will add border to random dialogs,tooltips,contextmenus

**Comment by choco** [comment]
Actually it isn't reported as fullscreen either ahahaha got Apple'd indeed :)
