### ISSUE TITLE
[plugin|border] Option to skip border for floating windows?

### ISSUE THREAD

**Issue by joshuap** [koekeishiya/chunkwm#89]
It would be nice to disable the border on floating windows in some  setups, or even via per-app rules. For instance, Steam doesn't look great with the border applied (and has some issues with its drop-down menus) and full-screen game overlays seem to have the border as well.

**Comment by koekeishiya** [comment]
this can now be configured in *.chunkwmrc*.
`chunkc set focused_border_skip_floating 1 | 0`

**Comment by Famis** [comment]
Is it possible to do the same for _ffm_ in float mode? Could that be done on a per desktop basis as easily as per window? I would like to have a desktop in float mode but without ffm while having the rest in tiling with ffm.
