### ISSUE TITLE
How to start and stop chunkwm

### ISSUE THREAD

**Issue by mamelara** [koekeishiya/chunkwm#90]
It would be nice if the documentation told you how to start and stop kwm for those who are not familair with launchctl. If it is already posted then could you refer me to it? I wanted to try out but it doesn't seem to be tiling well on my 15" macbook pro.

**Comment by taylorthurlow** [comment]
Yeah, really agree on this one.

**Comment by kmcnellis** [comment]
For me, it was
`launchctl load -w ~/Library/LaunchAgents/com.koekeishiya.chunkwm.plist`
`chunkwm`

**Comment by jhenahan** [comment]
The above works, but I'm also missing `kwmc quit` for a quick refresh when things just get out of whack.

**Comment by koekeishiya** [comment]
>  If it is already posted then could you refer me to it?

It's listed in the install section under **Source**.

If you installed using MacPorts, it is printed to the terminal as part of the ports notes section, for things the user needs to do after installing.

> The above works, but I'm also missing kwmc quit for a quick refresh when things just get out of whack.

You can just unload and load the tiling plugin again, or whatever other plugin this refers to, just as the *.chunwmrc* bash script does it.

**Comment by mamelara** [comment]
Hi @koekeishiya thanks for the response. This was not at all obvious to me especially since again I'm not too familiar with launchctl (now I am since I had to look up how to turn off chunkwm). I still think it would be useful to be explicit about this and also how to turn it off.

**Comment by henry-stripe** [comment]
For posterity (and because this issue has good SEO): I was running into an issue getting chunkwm to start after a brew install. It turned out that the [official example .chunkwmrc](https://github.com/koekeishiya/chunkwm/blob/master/examples/chunkwmrc) was assuming that plugins existed in `~/.chunkwm_plugins`, but brew does not set this up. To get things running, I symlinked the plugins and restarted:

```
$ ln -s /usr/local/opt/chunkwm/share/chunkwm/plugins/* ~/.chunkwm_plugins/
$ brew services restart chunkwm
```

**Comment by dominiklohmann** [comment]
@henry-stripe The caveats for the brew formula include this:

```
==> Caveats
Copy the example configuration into your home directory:
  cp /usr/local/opt/chunkwm/share/chunkwm/examples/chunkwmrc ~/.chunkwmrc
```

Installing chunkwm via Homebrew modifies the example chunkwmrc to always use the correct path. This is necessary because this path might be different from the one I quoted above when using non-default Homebrew settings.

**Comment by ipstone** [comment]
Sorry everyone, I still could not exit chunkwm, trying `aunchctl unload -w ~/Library/LaunchAgents/com.koekeishiya.chunkwm.plist` It says 'no such file or list'.

**Comment by jhenahan** [comment]
@ipstone If you installed through Homebrew, the plist is at `~/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist`. In general, `launchctl dumpstate | grep chunkwm`, will tell you a bunch of info, including the absolute path to the plist.

**Comment by 4lt3r3d5t4t35** [comment]
> @ipstone If you installed through Homebrew, the plist is at `~/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist`. In general, `launchctl dumpstate | grep chunkwm`, will tell you a bunch of info, including the absolute path to the plist.

this helped tons! thanks!
