### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by TacoVox** [koekeishiya/chunkwm#91]
Hi koekeishiya!

First of all thanks for your nice wm's. 

Tried to move on from kwm to your new project. But I am stuck. Installed via macports copied over the configs, gave the correct permissions.

When I run chunkc, I get the following output:

> chunkc: connection failed!

Checking the /tmp/chunkwm.err file, I get the following output:

> sh: /Users/jonas/.chunkwmrc: Permission denied

Pretty sure the permussions are sufficient (set to 644)...

Thanks, Jonas

**Comment by koekeishiya** [comment]
You need the bash scripts to be executable. Mine is set to 755.

This goes for both the .chunkwmrc and .chunkwmtilingrc

**Comment by oxyc** [comment]
This might need clarification in the README, it tripped me up as well. Unusual for dotfiles to be executable.

Also the example `.chunkwmtilingrc` in the repo is actually named `.chwmtilingrc`

**Comment by koekeishiya** [comment]
> Also the example .chunkwmtilingrc is actually named .chwmtilingrc in the repo

I'm aware of this, but the install instructions states the name it needs upon execution.

> Unusual for dotfiles to be executable.

I figured this would be self-explanatory given that 

>> the config file is also a bash script

**Comment by TacoVox** [comment]
Well that worked. How could I miss that point -.- But maybe really mention that these are scripts rather than config files :)

**Comment by koekeishiya** [comment]
I personally think that it should be pretty clear already. It is mentioned twice in the *configuration* part of the readme, and the first line of both config files is `#!/bin/bash`

**Comment by oxyc** [comment]
I was expecting that would be sourced not executed.
