### ISSUE TITLE
Building tiling plugin fails

### ISSUE THREAD

**Issue by OliverHofkens** [koekeishiya/chunkwm#93]
Hi,

I'm trying to switch from kwm to chunkwm, but the `make install` of the tiling plugin fails with error:
```
../../common/border/border.mm:76:51: error: use of undeclared identifier 'NSWindowStyleMaskFullSizeContentView'
                                       styleMask: NSWindowStyleMaskFullSizeContentView
```

I'm on OS X 10.11.6 and have the XCode 8 command line tools installed. 
Am I missing a dependency?

Thanks!

**Comment by koekeishiya** [comment]
There seems to have been some changes regarding the NSWindowStyleMask. It seems that some of these defines was changed between El Capitan and Sierra. I have changed it (on master) to the one that was used in Kwm, *NSWindowStyleMaskBorderless*.

If it does not build still, you simply have to find what the constant is named, to build on El Capitan.
I only have a build environment for Sierra (10.12.5).

**Comment by OliverHofkens** [comment]
I see, thanks!

**Comment by pakelley** [comment]
`NSWindowStyleMaskBorderless` didn't work for me, but changing `NSWindowStyleMaskBorderless` to `NSBorderlessWindowMask` worked for me on 10.11.6.

Not sure if this is a good solution, but I hope it helps :)

**Comment by koekeishiya** [comment]
@pakelley Thanks. I've added compilation support for El Capitan directly to master, no manual steps should be necessary. It would be great if you could just confirm that you can indeed build from master and that everything (seemingly) works properly, as I do not have an actual El Capitan system running.

**Comment by pakelley** [comment]
Yep, everything seems to work for me on master. Thanks for the update!! Also, thanks for the awesome window manager :)

**Comment by willus10245** [comment]
I'm getting this error on OS X 10.12.6 when installing with Homebrew.

**Comment by willus10245** [comment]
Figured it out. Needed to upgrade Xcode and Command Line Tools
