### ISSUE TITLE
Customise configuration path

### ISSUE THREAD

**Issue by peel** [koekeishiya/chunkwm#96]
With KWM we used to have (much like in KHD) a `-c` switch for customising config path. For now it's a hardcoded location at `$HOME`. 
For us nix users the switch proves to be really helpful so we can use nix-managed config from `/etc/{chunkwmrc,chunktilingrc}`

Thank you for the fantastic effort. I really love the project.

**Comment by koekeishiya** [comment]
I can add a switch to *chunkwm*, but the *chunkwm-tiling* plugin is loaded using dlopen, and so it cannot be done the same way. Not sure if only being able to do this for *chunkwm* would help all that much. I do want to change how the system works eventually, see #57

**Comment by peel** [comment]
Well, we'd need to use the workaround anyways, hence it's better to keep it the way it is until the end goal is reached.
