### ISSUE TITLE
screenshot on windows not working

### ISSUE THREAD

**Issue by wxmtech** [koekeishiya/chunkwm#98]
When using chunkwm, I take a screenshot and then it is just a "transparent" png file, any ideas guys? Both save to file and copy to clipboard are not working.

**Comment by choco** [comment]
I assume you're taking the screenshot in "app mode" (takes screenshot of entire window, you're not selecting the screenshot area yourself) and have borders enabled. In that case this is a known issue, you're actually screenshotting the transparent window that we use to create the border. Possible solutions:
1- take screenshot by selecting area
2- disable border temporary (right now the only way is unloading the border plugin), you can automate this with a bind in khd

**Comment by wxmtech** [comment]
Thanks a lot, that really makes a lot of sense, I’ll do a little bit work on solution 2 then.

**Comment by koekeishiya** [comment]
after updating to the latest version, you can now use `chunkc border::clear` instead of unloading it completely.

**Comment by koekeishiya** [comment]
Doubt there is anything we can do to fix this, due to how window layering works in macOS.
However, it can be solved with the following bind in *khd*:
```cmd + shift - 4 -> : chunkc border::clear```

**Comment by koekeishiya** [comment]
Moved response from choco, as well as the suggested (s)khd bind into the wiki: https://github.com/koekeishiya/chunkwm/wiki/Useful-tips-and-workarounds#macos-grab-native-screenshot-application-is-blocked-by-chunkwm-border
