### ISSUE TITLE
[plugin|border] Command to clear/undraw border

### ISSUE THREAD

**Issue by darvelo** [koekeishiya/chunkwm#99]
I'm noticing a border on fullscreen videos running within Firefox. It'd be nice to be able to bind a khd hotkey to remove the border in this case, until some other window focus event happens (such as returning from fullscreen) that can redraw it automatically.

**Comment by koekeishiya** [comment]
I have a prototype up and going for centralizing commands, which should allow for customization and commands to interact with the border plugin soon.

**Comment by koekeishiya** [comment]
added command `chunkc border::clear` on master
